- testing_ci.txt
Reverts openvinotoolkit/nncf_pytorch#1
> Revert "Testing CI Please Ignore"

- testing_ci.txt
Reverts openvinotoolkit/nncf_pytorch#2
> Revert "Revert "Testing CI Please Ignore""

- testing_ci.txt
Reverts openvinotoolkit/nncf_pytorch#3
> Revert "Revert "Revert "Testing CI Please Ignore"""

- nncf/dynamic_graph/patterns.py
- tools/debug/common.py
> Add conv1d to default quantizable patterns

- docs/Usage.md
- examples/classification/main.py
- examples/classification/staged_quantization_worker.py
- examples/object_detection/main.py
- examples/semantic_segmentation/main.py
- examples/semantic_segmentation/utils/checkpoint.py
- nncf/binarization/algo.py
- nncf/composite_compression.py
- nncf/compression_method_api.py
- nncf/pruning/filter_pruning/algo.py
- nncf/quantization/algo.py
- nncf/quantization/schedulers.py
- nncf/sparsity/base_algo.py
- nncf/sparsity/const/algo.py
- nncf/sparsity/magnitude/algo.py
- nncf/sparsity/rb/algo.py
- nncf/sparsity/schedulers.py
- tests/test_algo_common.py
- tests/test_compressed_graph.py
- tests/test_sanity_sample.py
Compression level is considered on choosing best accuracy and saving checkpoint.
If current accuracy less then the best one, checkpoint still can be best if current compression level is bigger then best one. Compression levels in ascending: NONE, PARTIAL, FULL.
> Introduced a compression level to properly save best checkpoints

- setup.py
- tests/test_install.py
> Fix setup.py install mode

- nncf/quantization/init_range.py
- tests/quantization/test_range_init.py
> Fix percentile per-channel init

- nncf/hw_config.py
- nncf/quantization/algo.py
- nncf/quantization/quantizer_propagation.py
- tests/quantization/test_hw_config.py
These get associated with a "wildcard" propagating quantizer, which
will either get merged with any other quantizer during propagation,
or get assigned a default quantization config.
> Properly handle ops in HW config without quantization configs associated

- examples/classification/configs/pruning/googlenet_imagenet.json
- examples/classification/configs/pruning/googlenet_pruning_geometric_median.json
- tests/sota_checkpoints_eval.json
@vshampor Please, take a look.
> Googlenet with pruning configs

- examples/classification/configs/pruning/googlenet_pruning_geometric_median.json
> Fix googlenet config

- nncf/composite_compression.py
- nncf/compression_method_api.py
- nncf/pruning/filter_pruning/algo.py
Give more functionality for pytorch model export to ONNX:
* add **strip_model()** for compression controllers with implementation for _FilterPruningController_
* change **export_model()** for _FilterPruningController_ and _CompositeCompressionAlgorithmController_
> Add new functionality for ComressionAlgorithmController

- setup.py
> Refactor imports in setup.py

- README.md
- docker/cpu/Dockerfile
- setup.py
- Update cpu_only part dockerfile; 
- Fix issue with setup.py install with --cpy-only opt; 
- Fix README.md against Ubuntu 18 requirements
> To fix cpu_only part

- nncf/quantization/algo.py
> Allow quantizing modules that share their weights for multiple ops

- docs/Usage.md
- examples/classification/main.py
- examples/classification/staged_quantization_worker.py
- examples/object_detection/main.py
- examples/semantic_segmentation/main.py
- nncf/initialization.py
- nncf/quantization/algo.py
- nncf/quantization/hessian_trace.py
- nncf/quantization/precision_init/hawq_init.py
- nncf/structures.py
- tests/data/configs/hawq/icnet_camvid_mixed_int.json
- tests/data/configs/hawq/inception_v3_cifar10_mixed_int.json
- tests/data/configs/hawq/inception_v3_cifar10_mixed_int_staged.json
- tests/data/configs/hawq/resnet18_cifar10_mixed_int.json
- tests/data/configs/hawq/resnet18_cifar10_mixed_int_staged.json
- tests/data/configs/hawq/ssd300_vgg_voc_mixed_int.json
- tests/data/configs/hawq/unet_camvid_mixed_int.json
- tests/quantization/test_precision_init.py
- tests/test_compressed_graph.py
- tests/test_sanity_sample.py
should be merged after #222, #191 and #232
> Criterion generalization for HAWQ algorithm

- nncf/hw_config.py
- nncf/hw_configs/cpu.json
- nncf/hw_configs/gpu.json
- nncf/hw_configs/template.json
- nncf/quantization/layers.py
- nncf/quantization/quantize_functions.py
- tests/quantization/test_functions.py
Quantization levels are changed for weights only as activations are already use full range of 8 bits
> Change quantization levels for SymmetricQuantizer from 255 to 256

- docs/compression_algorithms/Quantization.md
- nncf/config_schema.py
> More clarification about `bits` parameter in docs

- nncf/model_creation.py
If we start with graph dumping for a randomly initialized model it might lead to unexpected model output. E.g. for some models in mmdetection (retinanet) in post-processing part all bboxes will pass the filter stage (there are many of them ~500k) followed by memory allocation error saying that there is no enough memory to store this data.
Due to this issue, I suggest to change the order of operation and initially load model's state and then dump a model's graph
> Change an operation order in create_compressed_model

- tests/test_sota_checkpoints.py
It's need to separated eval test, now it can be run with -k "test_name" option of PyTest
> Fixed collecting metrics.json for incomplete eval test

- tests/data/ac_configs/unet_mapillary_int8.yml
- tests/data/ac_configs/unet_mapillary_magnitude_sparsity_int8.yml
Adeed Unet Mapillary AC configs: 
unet_mapillary.yml
unet_mapillary_int8.yml
unet_mapillary_magnitude_sparsity_int8.yml
> Added Unet Mapillary AC configs

- nncf/initialization.py
- nncf/utils.py
> Proper BN momentum parameter and train mode setting in BN adaptation

- examples/classification/main.py
- examples/common/utils.py
Required to avoid mlflow.exceptions.MlflowException: Could not create run under non-active experiment with ID 0.
> Don't call MLFlow if it's not enabled

- examples/classification/main.py
- examples/classification/staged_quantization_worker.py
- examples/common/argparser.py
- examples/object_detection/main.py
- examples/semantic_segmentation/main.py
- nncf/initialization.py
- nncf/quantization/hessian_trace.py
- nncf/quantization/precision_init/hawq_init.py
- tests/test_sanity_sample.py
Separate data_loader is registered for initialization via `register_default_init_args`
resolves #170 
@vuiseng9
> Introduced a separate batch size for initialization

- tests/test_sanity_sample.py
> Increase number of epochs in sanity test runs

- tests/data/ac_configs/ssd300_vgg_voc.yml
- tests/data/ac_configs/ssd300_vgg_voc_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc_magnitude_sparsity_int8.yml
- tests/data/ac_configs/ssd512_vgg_voc.yml
- tests/data/ac_configs/ssd512_vgg_voc_int8.yml
- tests/data/ac_configs/ssd512_vgg_voc_magnitude_sparsity_int8.yml
Added max labels for AC metrics. Now the AC accuracy is comparable with Torch.
> Changed AC configs for SSD models

- docker/cpu/Dockerfile
- setup.py
This reverts commit 8c17e0cd0b71dfddc2c33374804eec1f0434af56.
> Revert "Fk/update packages versions (#338)"

- tests/test_sota_checkpoints.py
Support paralleling start OpenVino part of End-2-End test
> OV separated exec

- tests/test_sanity_third_party.py
- third_party_integration/mmdetection/0001-Modifications-for-NNCF-usage.patch
Add export to onnx for NNCF models (retinanet)
> Update mmdet patch

- tests/test_sota_checkpoints.py
Added Q-DQ ONNX converting parameter
> Added ONNX Q-DQ converting parameters

- tests/test_sota_checkpoints.py
Reverts openvinotoolkit/nncf#362
> Revert "Added ONNX Q-DQ converting parameters"

- beta/examples/tensorflow/common/argparser.py
Model export doesn't work due to missing default value
> Fix missing default value

- beta/examples/tensorflow/common/argparser.py
- beta/nncf/tensorflow/quantization/quantizers.py
- beta/tests/tensorflow/quantization/test_algorithm_quantization.py
Test for pre-post processing functionality
> Add pre post processing test 

- beta/examples/tensorflow/common/argparser.py
- beta/examples/tensorflow/common/object_detection/datasets/builder.py
The issue with the tfds coco dataset preprocessing for the retinanet was fixed.
> include_mask flag for tfds decoder was added

- examples/classification/common.py
- examples/classification/main.py
- examples/classification/staged_quantization_worker.py
- examples/common/utils.py
- examples/object_detection/main.py
- examples/semantic_segmentation/main.py
> Configure device by common function for all samples

- nncf/initialization.py
- nncf/progress_bar.py
- tests/test_progress_bar.py
> Basic progress bar to avoid multiprocessing issue with tqdm(DataLoader)

- licensing/third-party-programs.txt
- nncf/automl/agent/ddpg/ddpg.py
- nncf/automl/agent/ddpg/memory.py
> Added proper license for DDPG-related code

- docs/compression_algorithms/Sparsity.md
I believe this makes docs little bit clearer
> Add some explanations to make doc clearer

- nncf/pruning/base_algo.py
- nncf/pruning/filter_pruning/algo.py
- nncf/pruning/schedulers.py
- tests/pruning/filter_pruning/test_algo.py
- tests/pruning/test_onnx_export.py
https://github.com/openvinotoolkit/nncf/pull/365 with fixed tests
> Small scheduler fixes

- beta/examples/tensorflow/common/object_detection/evaluation/coco_evaluator.py
- beta/examples/tensorflow/object_detection/main.py
- beta/examples/tensorflow/segmentation/evaluation.py
Changes:
- Refactoring and minor fixes to make code more clear
> [TF] Minor fixes

- beta/tests/tensorflow/test_sanity_sample.py
Turns on skipped sanity tests for samples.
> fixed sanity tests for samples

- tests/sota_checkpoints_eval.json
diff_fp32_min from -1.2 to -4.8
> Change thresholds for ssd300_vgg_voc_pruning_geometric_median 

- nncf/config/schema.py
> Use one of the registered JSON meta-schemae

- nncf/nncf_network.py
- nncf/quantization/quantizer_propagation.py
- tests/quantization/test_quantizer_propagation_graph.py
Python does not handle deep recursion stacks well.
> Use non-recursive BFS for graph traversal

- examples/common/utils.py
Changed writing method for .json metrics in examples.
> Changed working logic with json metrics

- nncf/composite_compression.py
https://github.com/openvinotoolkit/nncf/issues/406
> Add exception when try to export a pruned-quantized model

- tests/test_sota_checkpoints.py
Now, if reference FP32 model not executed, will be collect "target" metric from JSON file.
> Changed collecting reference fp32 metric

- tests/conftest.py
- tests/test_sota_checkpoints.py
https://github.com/openvinotoolkit/nncf/issues/427
> Clean previous metrics dump before sota test launch

- nncf/composite_compression.py
- nncf/compression_method_api.py
- nncf/model_creation.py
- nncf/pruning/base_algo.py
- nncf/pruning/pruning_node_selector.py
- nncf/quantization/algo.py
- nncf/quantization/precision_init/manual_init.py
- nncf/sparsity/const/algo.py
- tests/conftest.py
- tests/helpers.py
- tests/pruning/test_model_pruning_analysis.py
- tests/quantization/test_algo_quantization.py
- tests/test_compressed_graph.py
- tests/test_frozen_layers.py
- tests/test_progress_bar.py
resolves comments from #382 and issue #201
> Handling Frozen Layers

- tests/conftest.py
- tests/test_sota_checkpoints.py
It's separate convertation to ONNX and execution eval to different tests.
Please do not merge before CI modification
> Separate convertation to ONNX and OpenVino eval

- tests/conftest.py
- tests/test_frozen_layers.py
- tests/test_progress_bar.py
> Removed nncf import in conftest.py to not fail installation tests

- tests/data/ac_configs/icnet_camvid.yml
- tests/data/ac_configs/icnet_camvid_int8.yml
- tests/data/ac_configs/icnet_camvid_magnitude_sparsity_int8.yml
Modified AC configs for ICNet models
> Modified AC configs for ICNet models

- nncf/automl/environment/quantization_env.py
- nncf/hw_configs/cpu.json
- nncf/hw_configs/gpu.json
- nncf/hw_configs/vpu.json
Updated HW config: added pertensor quantization of activations for schemes compatibility
> Updated HW config: added pertensor quantization of activations

- beta/nncf/tensorflow/graph/model_transformer.py
- beta/nncf/tensorflow/graph/transformations/__init__.py
- beta/nncf/tensorflow/graph/transformations/commands.py
- beta/nncf/tensorflow/graph/transformations/layout.py
- beta/nncf/tensorflow/quantization/algorithm.py
- beta/nncf/tensorflow/sparsity/magnitude/algorithm.py
- beta/tests/tensorflow/test_transformations.py
- beta/tests/test_sota_checkpoints.py
- nncf/common/graph/transformations/commands.py
- nncf/common/graph/transformations/layout.py
Introduces the common API for transformation commands and transformation layout and implementation in the TF-backend.
> Common API for transformation commands and transformation layout

- README.md
- examples/classification/README.md
- examples/object_detection/README.md
- examples/requirements.txt
- examples/semantic_segmentation/README.md
- setup.py
Reverts openvinotoolkit/nncf#504
> Revert "Remove torchvision from dependency list"

- beta/nncf/__init__.py
> [TF] Disabled keras tensors to bypass issue with TFOpLambda layers

- nncf/dynamic_graph/patch_pytorch.py
> Fix bug with parsing pytorch version

- tests/quantization/test_quantization_metric.py
Added new tests cases for `MemoryCostMetric` and `ShareEdgesQuantizedDataPath` metrics. Please merge before #544 .
> Add test cases for test quantization metrics.

- nncf/automl/environment/quantization_env.py
- nncf/quantization/precision_constraints.py
- nncf/quantization/precision_init/base_init.py
- nncf/quantization/precision_init/compression_ratio.py
- nncf/quantization/precision_init/hawq_debug.py
- nncf/quantization/precision_init/hawq_init.py
- nncf/quantization/precision_init/traces_order.py
- nncf/quantization/quantizer_propagation.py
- nncf/quantization/structs.py
- tests/quantization/test_hawq_precision_init.py
- tests/test_sanity_sample.py
Aligned names in HAWQ
- replaced the ambiguous word "configuration" -> qconfig_sequence, bitwidth_sequence 
- bits, num_bits -> bitwidth
- flops_ops -> bits_complexity
Removed QuantizersBetweenQuantizableLayers
> Refactored and cleaned up HAWQ-related code

- beta/examples/tensorflow/common/scheduler.py
Hope it'll improve users handiness
> [TF] Handle unsupported lr scheduler exception

- nncf/compression_method_api.py
- nncf/dynamic_graph/context.py
- nncf/dynamic_graph/patch_pytorch.py
- nncf/dynamic_graph/wrappers.py
- nncf/model_creation.py
- nncf/nncf_network.py
- nncf/quantization/layers.py
- nncf/utils.py
- tests/test_graph_building.py
> Fix repeated forwards

- nncf/pruning/filter_pruning/functions.py
> Faster calculation of geometric median importance scores in filter pruning

- tests/test_extensions_build.py
> CUDA extension fix

- examples/classification/main.py
> Make training settings sensible for CIFAR10/100 in classification sample

- nncf/algo_selector.py
- nncf/binarization/algo.py
- nncf/pruning/base_algo.py
- nncf/quantization/algo.py
- nncf/sparsity/base_algo.py
- nncf/sparsity/rb/loss.py
- tests/test_algo_common.py
> Compression loss device bug

- nncf/pruning/base_algo.py
- nncf/pruning/filter_pruning/algo.py
- nncf/quantization/algo.py
- nncf/sparsity/base_algo.py
- nncf/sparsity/magnitude/algo.py
- nncf/sparsity/rb/algo.py
> Code cleanup

- examples/object_detection/dataset.py
- examples/object_detection/datasets/voc0712.py
- examples/object_detection/eval.py
- tests/data/ac_configs/ssd300_mobilenet_voc.yml
- tests/data/ac_configs/ssd300_mobilenet_voc_magnitude_sparsity_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc.yml
- tests/data/ac_configs/ssd300_vgg_voc_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc_magnitude_sparsity_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc_pruning_geometric_median.yml
- tests/data/ac_configs/ssd512_vgg_voc.yml
- tests/data/ac_configs/ssd512_vgg_voc_int8.yml
- tests/data/ac_configs/ssd512_vgg_voc_magnitude_sparsity_int8.yml
- tests/sota_checkpoints_eval.json
- tests/test_sanity_sample.py
Changed AC configs, and targets according VOC2007 dataset
Please see Build 252 of E2E test
> Switched to VOC2007 in validation

- beta/examples/tensorflow/common/dataset_builder.py
- beta/examples/tensorflow/object_detection/models/yolo_v4_model.py
- beta/examples/tensorflow/object_detection/preprocessing/yolo_v4_preprocessing.py
Compression loss added for YOLOv4.
TFRrecords data type proper handling.
> Compression loss added

- examples/classification/staged_quantization_worker.py
> Load optimizer state from the checkpoint only when the training mode is enabled

- tests/test_algo_common.py
> Comp loss device compatibility CPU env test fix

- tests/quantization/test_saturation_issue_export.py
I made several experiments and collected statistics, according to it I increased a threshold value of a test. 
Also, experiments demonstrate that non quantized models have the same order of difference as quantized models. Therefore, our export of FQ nodes dones't influence on ONNX model output much, which is good.
> Update threshold values of test

- tests/data/ac_configs/ssd300_mobilenet_voc.yml
- tests/data/ac_configs/ssd300_mobilenet_voc_magnitude_sparsity_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc.yml
- tests/data/ac_configs/ssd300_vgg_voc_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc_magnitude_sparsity_int8.yml
- tests/data/ac_configs/ssd300_vgg_voc_pruning_geometric_median.yml
- tests/data/ac_configs/ssd512_vgg_voc.yml
- tests/data/ac_configs/ssd512_vgg_voc_int8.yml
- tests/data/ac_configs/ssd512_vgg_voc_magnitude_sparsity_int8.yml
- tests/sota_checkpoints_eval.json
Changed metrics representation for SSD models.
> Changed configs for SSD models

- nncf/compression_method_api.py
> Update the signature of the export_model method

- docs/styleguide/PyGuide.md
> Fix abstract method styleguide

- beta/nncf/tensorflow/pruning/export_helpers.py
- nncf/common/graph/graph.py
- nncf/pruning/export_helpers.py
- tests/pruning/filter_pruning/test_algo.py
- reimplement get_input_edges to return dictionary of edges with description.
- remove get_previous_nodes_sorted_by_in_port
> Reimplement get_input_edges

- beta/tests/test_sota_checkpoints.py
Deleted new lines in error message written in csv file
Before:  build 1959
After: build 1960
> Deleted new lines in error message

- beta/examples/requirements.txt
- beta/requirements.txt
- beta/tests/requirements.txt
`nncf/beta/requirements.txt` is getting split into three lists of requirements: NNCF TF, TF tests, and TF examples. 
The installation works in any order.
> Adjust requirements.txt

- third_party_integration/huggingface_transformers/0001-Modifications-for-NNCF-usage.patch
- third_party_integration/mmdetection/0001-Modifications-for-NNCF-usage.patch
Fixed number of lines in patches after #688
Build 328
> Fixed third_party patches

- examples/object_detection/eval.py
BN statistics were calculated batch-wise during evaluation in the OD sample, which technically gives incorrect metric values.
> Put BN layers into evaluation mode during AutoQ search in OD sample

- tests/torch/install_checks.py
- tests/torch/test_install.py
> Fixed test install for pip

- README.md
- nncf/tensorflow/README.md
- setup.py
The major dependencies require Python>=3.6.2:
https://pypi.org/project/torch/
https://pypi.org/project/tensorflow/
https://pypi.org/project/openvino/
> Python >=3.6.2

- nncf/tensorflow/sparsity/rb/algorithm.py
- nncf/tensorflow/sparsity/utils.py
Move sparsity utils to new way collecting wrapped layers and operations
> Refactor sparsity utils.py

- nncf/torch/__init__.py
- nncf/version.py
- tests/torch/test_sanity_third_party.py
> Fix third party integration tests

- tests/tensorflow/test_sota_checkpoints.py
Now Model Optimizer will be installed in separate venv
> Added execution model converting in venv

- examples/tensorflow/segmentation/train.py
Have checked all tf samples import order
> Fix import order

- examples/tensorflow/segmentation/README.md
- examples/tensorflow/segmentation/configs/quantization/mask_rcnn_coco_int8.json
- tests/tensorflow/sota_checkpoints_eval.json
> Add MaskRCNN with saturation issue

- examples/tensorflow/common/prepare_checkpoint.py
- tests/tensorflow/test_sanity_sample.py
* Add param `--model-type` to make it possible to choose between object detection and segmentation models
* Add sanity test (running time~12 sec on local machine) which check compressed model creates without errors
> Unify prepare_checkpoint.py

- nncf/tensorflow/quantization/utils.py
`tf.quantization.fake_quant_with_min_max_vars` sometimes returns small values on zero valued inputs due to arithmetic error. Updated export save exact zero value indexes and after saturation issue fix applied restore exact zeros on saved indexes
> Fix quantized values miss exact zero

- setup.py
setuptools<43.0.0 could not find suitable distribution for 'tensorflow==2.4.0'
> Added requirements for setuptools

- nncf/tensorflow/helpers/model_creation.py
The `create_compression_algorithm_builder()` method never returns `None` because the `extract_compression_algorithm_configs()` contains this check:
https://github.com/openvinotoolkit/nncf/blob/138a7dc4c87e8436b62509abfd14050f3d94f559/nncf/config/extractors.py#L47-L48
> Refactoring

- tests/common/helpers.py
- tests/tensorflow/conftest.py
- tests/tensorflow/install_checks.py
- tests/tensorflow/test_install.py
- tests/torch/conftest.py
- tests/torch/test_install.py
test_install
* Torch
* cpu job: 38
* gpu job: 40
> Added TF test install

- .github/labeler.yml
- .github/workflows/labeler.yml
- CODEOWNERS
> add dependency label to PR

- nncf/tensorflow/quantization/algorithm.py
> Fixed statistic collection for the algo-mixing scenario

- tests/tensorflow/test_sota_checkpoints.py
After Monday discussion, added condition to skip unsupported models
> Added condition to skip unsupported mask_rcnn models

- examples/torch/object_detection/README.md
> Fix object detection README for torch

- tests/torch/sota_checkpoints_eval.json
Now we have green sota_eval_pytorch. See build 479
> Slightly increased the thresholds for several models

- docs/compression_algorithms/Sparsity.md
- nncf/config/schema.py
> Fix multistep_sparsity_levels description

- nncf/tensorflow/helpers/model_creation.py
I change mode from "test" to "export"
> Correct command

- nncf/torch/dynamic_graph/graph.py
Reverts openvinotoolkit/nncf#932
> Revert "Fix view with size"

- tests/tensorflow/test_sota_checkpoints.py
- tests/torch/test_sota_checkpoints.py
The last commit created an issue with subprocess in test_sota_checkpoints. This is an attempt to fix this issue.
> fixed issue with subprocess in test_sota_checkpoints

- examples/torch/classification/main.py
- examples/torch/classification/staged_quantization_worker.py
- examples/torch/object_detection/main.py
- examples/torch/semantic_segmentation/main.py
- tests/torch/test_sanity_sample.py
> Corrected handling of --to-onnx option and export mode in sample

- examples/tensorflow/classification/main.py
- examples/tensorflow/object_detection/main.py
- nncf/common/accuracy_aware_training/training_loop.py
- nncf/tensorflow/accuracy_aware_training/keras_model_utils.py
- nncf/tensorflow/accuracy_aware_training/runner.py
- tests/tensorflow/accuracy_aware_training/test_keras_api.py
- Missed callbacks are added
- Proper logging into TB
> Fix for AA tensor board logging

- examples/torch/object_detection/main.py
Fix bugs with TB dumping and checkpoint loading
-
-
-
> Fix bugs in object detection samples

- nncf/torch/pruning/operations.py
Add LeakyRelu to PTIdentityMaskForwardPruningOp list
https://github.com/openvinotoolkit/nncf/issues/1001
None
None
> Add Leaky Relu Metatype to Pruning Operations

- README.md
> Add HF ref to front page results table

- README.md
Added link to the TensorFlow notebook.
To make NNCF TF usage examples more visible.
n/a
n/a
> Added link to the TensorFlow notebook

- tests/torch/test_custom_modules.py
As stated in the PR title.
The scenario has not yet been covered by existing tests.
N/A
Added a test case in tests/torch/test_custom_modules.py
> Add a test for custom module handling

- tests/torch/pruning/test_model_pruning_analysis.py
Add test for model with GroupNorm modules
> Add test GroupNorm in model_pruning_analysis

- examples/tensorflow/classification/README.md
Update the metrics  for TF model by recently obtained ones
Incorrect value
No
No
> Update AA result for TF

- README.md
> Add a link to the new notebook

- setup.py
> Fix issues

- .github/labeler.yml
Now the labeler will actually do something helpful automatically - set up the labels for PR that are consistent with the changes that are being made.
Will improve the visual perception of the PR list.
N/A
Might even get tested by this PR itself!
> Improve PR labeling based on change location

- tests/torch/test_sanity_sample.py
Change tmp_path location for each test
Fix bug
No
> Fix bug in test_sanity_AA

- examples/tensorflow/common/distributed.py
- examples/tensorflow/common/utils.py
Added the workaround for https://github.com/tensorflow/tensorflow/issues/33916
Customer request
N/A
N/A
> Set memory growth = True

- tests/tensorflow/test_weekly.py
Expand the weekly test
N/A
#ref74624
N/A
> Expand the weekly test

- examples/torch/classification/README.md
- examples/torch/object_detection/README.md
> Samples readme typo fix

- README.md
Metric update after https://github.com/openvinotoolkit/nncf/pull/1083
> Metric update

- nncf/torch/exporter.py
When export ONNX every epoch, we need to restore it's device.
resolves https://github.com/openvinotoolkit/nncf/issues/1099
> Restore model device after ONNX export

- nncf/torch/graph/patterns.py
- nncf/torch/hardware/fused_patterns.py
- tests/torch/data/reference_graphs/quantized/synthetic_model/FC_ConstMul.dot
- tests/torch/test_compressed_graph.py
- tests/torch/test_models/synthetic.py
Add pattern Linear + const mul.
Fix bug with incorrect FQ configuration.
78186
`tests/torch/test_compressed_graph.py`
> Add FC+const_mul pattern.

- examples/tensorflow/classification/main.py
Strategy thread pool fix for classification
> Strategy threadpool fix for classification

- examples/tensorflow/segmentation/configs/quantization/mask_rcnn_coco_int8.json
The extra comma was removed.
Broken quantization config.
N/A
N/A
> Config was fixed

- examples/tensorflow/segmentation/configs/quantization/mask_rcnn_coco_int8.json
Changed TF configs
To run TF weekly tests
> Fixes to add TF weekly test

- nncf/experimental/tensorflow/graph/argprovider.py
- nncf/experimental/tensorflow/patch_tf.py
Support operations by experimental algo
> ArgProvider update

- examples/torch/object_detection/configs/ssd300_mobilenet_voc_magnitude_int8.json
- examples/torch/object_detection/main.py
Set `test-interval` param 1 by default.
Set `test-interval` param in config for ssd300.
77586
Please see weekly NNCF_PT job 79
> Fix for ssd300 weekly test 

- tests/torch/data/ac_configs/resnet34_imagenet_filter_pruning_geomean_kd.yml
> Fix path to AC config for resnet34.

- nncf/common/accuracy_aware_training/training_loop.py
Use original compression controller to dump best checkpoints
Adaptive compression controller updates target pruning rate at each iteration, thus compression stage is always `PARTIALLY_COMPRESSED` (best checkpoint are saved only if compression stage == `FULLY_COMPRESSED`) 
-
-
> Adaptive compression loop: use original compression controller to dump best checkpoints

- ReleaseNotes.md
- setup.py
Pillow version update for Snyk scanning
Remove critical and high severity issues
None
None
> Pillow version upgrade

- ReleaseNotes.md
> update release note for v220

- nncf/config/experimental_schema.py
- setup.py
Added Pymoo to setup script and improved the descriptions in experimental schema. 
Add missing library Pymoo.
Tested building a wheel with new setup.
> Add Pymoo to setup. Desc. experimental schema

- nncf/torch/quantization/quantize_functions.py
> add type casting to symmetric_quantize

- ReleaseNotes.md
- nncf/version.py
> Version update

- nncf/torch/extensions/src/quantization/cuda/functions_cuda_impl.cu
line 36 of file functions_cuda_impl.cu should be:
else if (scale_dim >= 2 && input_range.size(1) > 1)
Compile error.
None
None
> Fix a bug with functions_cuda_impl.cu

- setup.py
> modify networkx for CI testing

- examples/experimental/onnx/README.md
- examples/experimental/onnx/accuracy_checker.py
- examples/experimental/onnx/det_and_seg/onnx_models_configs/fcn-resnet50-12.yml
- examples/experimental/onnx/det_and_seg/onnx_models_configs/tiny-yolov3-11.yml
- examples/experimental/onnx/det_and_seg/onnx_models_configs/tinyyolov2-8.yml
- examples/experimental/onnx/run_ptq_onnx_models.sh
- tests/torch/pytest.ini
- Add custom accuracy check pipeline for FCN-ResNet50 model
- Update tiny yolo models' accuracy checker configs
- Update README.md
PTQ for ONNX model zoo - object detection and segmentation models
[CVS-85504](https://jira.devtools.intel.com/browse/CVS-85504)
> [CVS-85504] Update ONNX det and seg model accuracy check pipelines

- .pylintrc
- CONTRIBUTING.md
- Makefile
- README.md
- examples/experimental/onnx/performance_checker.py
- examples/experimental/onnx/requirements.txt
- examples/experimental/onnx/run_ptq_onnx_models.sh
- nncf/experimental/onnx/algorithms/quantization/utils.py
- nncf/experimental/onnx/model_normalizer.py
- nncf/experimental/onnx/requirements.txt
- setup.py
- Revert README.md installation guide for users 
- Remove `openvino` dependency from onnx experimantal part
- Fix ONNX pylint errors
[Remove add_input_from_initializer](https://github.com/openvinotoolkit/nncf/commit/f3cce02bce4e406cc31d2faa6d8aeba10d97b246) 
- It seems solved after onnx=1.11.0. Please refer to comments in https://github.com/onnx/onnx/issues/4102
> Update onnx installation

- ReleaseNotes.md
- nncf/version.py
Update ReleaseNote and NNCF version
Publish new release
None
> Update ReleaseNote and NNCF version

- examples/experimental/onnx/README.md
- examples/experimental/onnx/det_and_seg/onnx_models_configs/fcn-resnet50-12.yml
- examples/experimental/onnx/performance_checker.py
- examples/experimental/onnx/run_ptq.py
- examples/experimental/onnx/run_ptq_onnx_models.sh
- tests/onnx/README.md
- tests/onnx/conftest.py
- tests/onnx/pytest.ini
- tests/onnx/requirements.txt
- tests/onnx/test_e2e_ptq.py
- Add ONNX e2e test for ONNX Model ZOO models
- [Fix examples/experimental/onnx/README.md](https://github.com/openvinotoolkit/nncf/commit/04e88eef614c9bee0b803830ab53af4229f40421) to correct hyper links and miscs.
- To add nightly job tests for ONNX framework
76195
> Add onnx e2e test

- examples/experimental/onnx/README.md
Remove ONNX PTQ API performance results from README.md
Please see the related ticket
87917
> Remove ONNX PTQ API performance results from README.md

- examples/experimental/onnx/README.md
- examples/experimental/onnx/yolov5/0001-Add-NNCF-ONNX-PTQ-example-notebook.patch
- nncf/experimental/post_training/algorithms/quantization/algorithm.py
87917
Because there is no code change and it is an emergency, I merge it now.
> Remove perf number of yolov5

- nncf/experimental/torch/fracbits/__init__.py
- nncf/experimental/torch/fracbits/quantizer.py
- nncf/experimental/torch/fracbits/structs.py
- tests/torch/experimental/fracbits/test_quantizer.py
- Implement FracBitsSymmetricQuantizer and FracBitsAsymmetricQuantizer
- Implement relevant unit test
To extend mixed-precision QAT algorithm choices.
87363
Related unit tests added
> Implement FracBitsQuantizers

- examples/experimental/torch/classification/README.md
- examples/experimental/torch/classification/configs/inception_v3_imagenet_int8.json
- examples/experimental/torch/classification/configs/inception_v3_imagenet_mixed_int_fracbits_msize.json
- examples/experimental/torch/classification/configs/mobilenet_v2_cifar100_asym_int8.json
- examples/experimental/torch/classification/configs/mobilenet_v2_cifar100_mixed_int_fracbits_msize.json
- examples/experimental/torch/classification/configs/mobilenet_v2_imagenet_int8.json
- examples/experimental/torch/classification/configs/mobilenet_v2_imagenet_mixed_int_fracbits_msize.json
- examples/experimental/torch/classification/configs/resnet50_imagenet_int8.json
- examples/experimental/torch/classification/configs/resnet50_imagenet_mixed_int_fracbits_msize.json
- examples/experimental/torch/classification/fracbits.py
- examples/torch/common/argparser.py
- examples/torch/common/execution.py
- examples/torch/requirements.txt
- nncf/config/experimental_schema.py
- nncf/experimental/torch/fracbits/controller.py
- nncf/experimental/torch/fracbits/loss.py
- nncf/experimental/torch/fracbits/params.py
- nncf/experimental/torch/fracbits/quantizer.py
- nncf/experimental/torch/fracbits/scheduler.py
- tests/torch/experimental/fracbits/conftest.py
- tests/torch/experimental/fracbits/test_builder.py
- tests/torch/requirements.txt
- Add some FracBits experiment configurations and report results to README.md (inceptionv3, resnet50,  and mobilenetv2).
- Refactor and fix some code for FracBits experiment.
To provide FracBits usecases for users.
88254
> Add some FracBits experiment results

- examples/tensorflow/common/object_detection/architecture/factory.py
- nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_width.py
- nncf/experimental/torch/nas/bootstrapNAS/search/search.py
- nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_controller.py
- nncf/experimental/torch/nas/bootstrapNAS/training/scheduler.py
- tests/experimental/post_training/test_api.py
- tests/torch/accuracy_aware_training/test_training_loop.py
Fix pylint for files where pylint check was missing in the meantime
Same as above
89149
> Fix pylint

- examples/experimental/torch/classification/Quickstart.md
- examples/experimental/torch/classification/bootstrapnas_examples/config.json
- nncf/experimental/torch/nas/bootstrapNAS/BootstrapNAS.md
Update BootstrapNAS document and add a quickstart. 
Update documentation 
N/A
N/A
> Update BootstrapNAS document and add a quickstart

- examples/experimental/onnx/semantic_segmentation/onnx_ptq_segmentation.py
"filename": "examples/experimental/onnx/semantic_segmentation/onnx_ptq_segmentation.py"
"warning_type": "Incompatible variable type [9]",
"warning_message": " ignored_scopes is declared to have type `List[str]` but is used as type `None`.",
"warning_line": 28
"fix": None to []
> ignored_scopes has type `List[str]` but is used as type `None`.

- examples/experimental/onnx/semantic_segmentation/onnx_ptq_segmentation.py
> Fix missing import

- nncf/torch/pruning/operations.py
Reopened [PR 982](https://github.com/openvinotoolkit/nncf/pull/982)
> Support interpolate op in filter pruning

- README.md
- docs/Usage.md
Fixes: #1283
The users should be explicitly made aware of this peculiarity, otherwise hard-to-debug compression errors might occur.
N/A
N/A
> Explicitly mention import order in README

- .github/workflows/build_schema_page.yml
- nncf/config/schema.py
> Test branch for pr

- .github/workflows/build_schema_page.yml
This reverts commit 6b54fb03557d7d9d80f9cfa67a7cac7b6f7f8b21.
> Revert "Make schema build trigger on closed PR (#1292)"

- .github/workflows/build_schema_page.yml
- nncf/config/schema.py
> Test branch for pr - final?

- .github/workflows/build_schema_page.yml
- nncf/config/schema.py
> Test branch for pr - really final

- nncf/config/schema.py
> Another test

- nncf/config/schemata/algo/binarization.py
Testing the Github Action trigger.
> Add missing full stop in the config schema

- tools/benchmark.py
- tools/benchmark_quantize_layers.py
Quantizers performance benchmark was updated, now FP16 kernels are checking by the benchmark
To enable FP16 quantizers benchmarking
> [Torch] Quantizers fp16 benchmark

- setup.py
Custom request
93312
Available graph tests
> Bump lower allowed networkx version

- nncf/torch/quantization/layers.py
- tests/torch/quantization/test_onnx_export.py
Fixed the issue with using torch.onnx.export() to export a quantized model.
The export with using orch.onnx.export() fails with the following error message:
```
>               return ExportQuantizeToFakeQuantize.apply(x, levels,
input_low,
input_high,
input_low,
input_high)
E                                                         RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
E                                                         Tensor:
E                                                          0
E                                                         [ torch.FloatTensor{1} ]
```
N/A
test_torch_onnx_export
> Fixed the issue with using torch.onnx.export()

- .github/labeler.yml
Automatic addition of NNCF ONNX and NNCF OpenVINO labels in PR
Improve developing
N/A
N/A
> Automatic addition of NNCF ONNX and NNCF OpenVINO labels

- examples/experimental/openvino/mobilenet_v2/main.py
- examples/experimental/openvino/mobilenet_v2/utils.py
- examples/experimental/openvino/yolo_v5/main.py
- nncf/openvino/engine.py
- nncf/parameters.py
Fixed pylint issues for the following command:
```
pylint nncf/openvino examples/experimental/openvino
```
Required for the pylint job for the OpenVINO backend
N/A
N/A
> [OpenVINO] pylint

- nncf/__init__.py
- nncf/experimental/post_training/algorithms/quantization/fast_bias_correction/__init__.py
- nncf/experimental/post_training/algorithms/quantization/min_max/__init__.py
- nncf/experimental/post_training/graph/__init__.py
- nncf/experimental/post_training/samplers.py
- setup.py
- tests/common/helpers.py
- tests/openvino/conftest.py
- tests/openvino/install_checks.py
- tests/openvino/requirements.txt
- tests/openvino/test_install.py
```
python setup.py install --openvino
```
adding openvino backend
N/A
[test_install.py](https://github.com/openvinotoolkit/nncf/compare/develop...alexsu52:as/dependencies?expand=1#diff-53910d318d1940f81165dcb97a5800355f0c0e7ed56b73f247be55171a9dc3f0)
> openvino extra to setup.py

- examples/tensorflow/requirements.txt
- tests/torch/requirements.txt
> Update protobuf version

- nncf/experimental/onnx/graph/metatypes/onnx_metatypes.py
- nncf/experimental/onnx/graph/model_transformer.py
- nncf/experimental/onnx/graph/nncf_graph_builder.py
- nncf/experimental/onnx/graph/onnx_graph.py
- nncf/experimental/onnx/graph/transformations/commands.py
- nncf/experimental/onnx/quantization/default_quantization.py
- nncf/experimental/onnx/statistics/aggregator.py
- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/backend.py
- nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
- nncf/quantization/algorithms/min_max/algorithm.py
- nncf/quantization/algorithms/min_max/backend.py
- nncf/quantization/algorithms/min_max/onnx_backend.py
- tests/onnx/quantization/test_graphs.py
- tests/onnx/test_model_transformer.py
Improve the methods structure of MinMax and FBC
Contiguous code improvement
No
No
> Add some improvements in the code structure of post-training

- tests/openvino/pot/test_engine.py
- tests/openvino/pot/utils.py
- Tests for `OVEngine` was added. The instance of this class is used inside the `NMSEBasedAccuracyAware` class.
- `nncf.quantize_with_accuracy_control()` method.
N/A
N/A
> Tests for AA algorithm

- nncf/openvino/engine.py
- tests/openvino/pot/test_engine.py
The AA algorithm takes a lot of time when we use a dataset with the `__iter__()` method.
Reduce execution time.
N/A
The `test_calc_per_sample` test was added.
> Fix for accuracy control

- nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_width.py
Follow-up for a couple of unresolved comments in #1418 
N/A
test_nas
> Adjust logging in elastic width code

- docs/accuracy_aware_model_training/AdaptiveCompressionLevelTraining.md
- docs/accuracy_aware_model_training/actl_progress_plot.png
- Tweaked parameters description according to recent changes to ACTL
- Added an example plot reflecting model compression progress by ACTL
> Adaptive Compression Training Loop documentation tweaks and improvement

- examples/tensorflow/segmentation/configs/quantization/mask_rcnn_coco_int8.json
- tests/tensorflow/data/ac_configs/retinanet.yml
- tests/tensorflow/data/ac_configs/yolo_v4.yml
- tests/tensorflow/data/ac_configs/yolo_v4_int8_w_sym_ch_a_asym_t.yml
Updated output nodes for RetinaNet and YOLOv4
Make e2e green again
N/A
Build 194
> Make e2e green again

- examples/torch/README.md
address comment
https://github.com/openvinotoolkit/nncf/pull/1446#discussion_r1055582971
n/a
n/a
> Added link to compatible torchvision and torch versions

- tests/cross_fw/install/test_install.py
- tests/shared/helpers.py
Fixed path to TensorFlow test requirements.txt
The test requirements install command failed with the following error:
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/jenkins/agent/workspace/NNCF/nightly/ubuntu20_install_tf/src/tests/tf/requirements.txt'
```
N/A
install_tf 144
> Fixed again the install test for TensorFlow

- Makefile
- tests/cross_fw/__init__.py
- tests/cross_fw/install/install_checks_onnx.py
Add nncf.experimental.openvino pattern to excluded dirs in test
Fix test
99921
No
> Fix ONNX test_install

- README.md
Added nncf badges, aligned with OpenVINO repo
Improve Readme
none
na
> Added nncf badges

- nncf/openvino/engine.py
Data item format fix
Fix for the [228-clip-zero-shot-image-classification](https://github.com/eaidova/openvino_notebooks/tree/ea/clip_quantization_dict/notebooks/228-clip-zero-shot-image-classification)
N/A
N/A
> Data item format fix

- .github/workflows/labeler.yml
* Update GitHub action labeler
* Resolving GitHub labeler error
> Update labeler version

- .github/workflows/labeler.yml
Add permissions to labeler GitHub actions
Access error
> Labeler permissions

- setup.py
- tests/openvino/native/models.py
- tests/openvino/native/test_model_transformer.py
- tests/openvino/pot/test_engine.py
- Update OV version, fix OV (POT) tests
- This change will allow us to use the latest OV version in the tests
- 99840
> Update the ov.Model creation & ov version

- tests/openvino/requirements.txt
- tests/openvino/tools/README.md
- tests/openvino/tools/__init__.py
- tests/openvino/tools/calibrate.py
Added the calibrate tool for OpenVINO backend
To wide test scope
ref:98129
N/A
> Calibrate tool for OpenVINO backend

- nncf/experimental/openvino_native/quantization/__init__.py
- nncf/experimental/openvino_native/quantization/algorithms/__init__.py
- nncf/experimental/openvino_native/quantization/algorithms/min_max/__init__.py
- Missing `__init__.py` files were added.
N/A
N/A
> Missing __init__.py files were added

- nncf/quantization/algorithms/bias_correction/backend.py
- nncf/quantization/algorithms/fast_bias_correction/backend.py
- Signature for FBCAlgoBackend.bias_correction_command() was changed.
- Signature was wrong.
N/A
N/A
> Signature for FBCAlgoBackend.bias_correction_command() was changed

- nncf/torch/quantization/layers.py
Use correct type to compare `scale_shape` 
`scale_shape` is tuple (typehit and [code](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/algo.py#L784)), but comparing with list, as result `per_channel` always `True`.
> Fix comparing tuple with list in PTQuantizerSpec

- examples/post_training_quantization/onnx/mobilenet_v2/main.py
Fix incorrect comment in sample
Fix bug
No
No
> Fix incorrect comment in ONNX sample

- nncf/quantization/algorithms/bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
- nncf/quantization/algorithms/min_max/algorithm.py
- tests/post_training/conftest.py
- tests/post_training/model_scope.py
- tests/post_training/test_quantize_conformance.py
Added OpenVINO Native implementation to the post training conformance test
Test OpenVINO Native implementation
N/A
test_ptq_timm()
build: post_training_quantization/9
> MinMax algorithm has been added to the post training conformance test

- nncf/onnx/hardware/patterns.py
Fix incorrect marking of Model Input in HW patterns.
Bug fix
101560
No
> Change incorrect NNCFGraphNodeType to INPUT_NOOP_METATYPES in patterns

- .github/labeler.yml
> Fix typo in labeler

- nncf/openvino/quantization/quantize.py
Using the offline transformation compress_quantize_weights_transformation instead of pot.compress_model_weights()
Migration on NGraph implementation
Customer request
N/A
> Using the offline transformation compress_quantize_weights_transformation

- nncf/quantization/quantize.py
- Type hint was fixed for the `nncf.quantize_with_accuracy_control()` method.
Bug.
N/A
N/A
> Fix type hint

- tests/post_training/model_scope.py
- tests/post_training/test_quantize_conformance.py
- test_quantize_conformance.py was updated with the PostTraninigQuantization algorithm instead of MinMaxQuantization
- Wider algorithms test scope
> Change conformance test algorithms

- examples/post_training_quantization/openvino/yolov8/README.md
- examples/post_training_quantization/openvino/yolov8/main.py
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- Added YOLOv8n PTQ example
- Demonstrate new PTQ API
> Added YOLOv8 example

- examples/post_training_quantization/openvino/quantize_with_accuracy_control/README.md
> Fixed README of quantization with accuracy control for OpenVINO backend

- examples/post_training_quantization/openvino/quantize_with_accuracy_control/main.py
Updated hash of the openvino mdoel in the quantization with accuracy control example.
Updated archive with the openvino model
Tests
TBD
> Updated hash of the openvino mdoel in the quantization with accuracy control example.

- nncf/experimental/openvino_native/graph/model_transformer.py
- nncf/quantization/algorithms/min_max/algorithm.py
- tests/onnx/quantization/test_ptq_params.py
- tests/openvino/native/models.py
- tests/openvino/native/quantization/test_ptq_params.py
- Fixed ignored scope for weights
- Fixed OpenVINO outputs creation in case of ignored scope
- Features alignment
- 102187
> Fix ignored scope for weights & OV

- tests/openvino/tools/calibrate.py
Added support for the OpenVINO native quantization implementation in calibrate.py
Testing
N/A
N/A
> Support for the OpenVINO native quantization implementation in calibrate.py

- nncf/experimental/openvino_native/graph/model_transformer.py
- nncf/experimental/openvino_native/quantization/algorithms/bias_correction/__init__.py
- nncf/experimental/openvino_native/quantization/algorithms/bias_correction/openvino_backend.py
- nncf/experimental/openvino_native/quantization/algorithms/fast_bias_correction/openvino_backend.py
- nncf/experimental/openvino_native/statistics/collectors.py
- nncf/experimental/openvino_native/statistics/statistics.py
- nncf/onnx/graph/model_transformer.py
- nncf/onnx/graph/nncf_graph_builder.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
- nncf/quantization/algorithms/bias_correction/backend.py
- nncf/quantization/algorithms/bias_correction/onnx_backend.py
- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/backend.py
- nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
- Added OpenVINO backend support for the BiasCorrection algorithm
- Extension of the set of algorithms for the backend
- 98621
> Full BiasCorrection for OpenVINO backend

- tests/post_training/model_scope.py
- tests/post_training/test_quantize_conformance.py
- Updated conformance test with Process while validation to avoid main process failure
- More robust conformance test
> Conformance test with Process

- nncf/experimental/openvino_native/graph/nncf_graph_builder.py
- tests/openvino/native/data/reference_graphs/original_nncf_graph/ComparisonBinaryModel.dot
- tests/openvino/native/data/reference_graphs/quantized/ComparisonBinaryModel.dot
- tests/openvino/native/models.py
> [OV] OV dtypes extended with boolean

- tests/torch/nas/models/synthetic.py
- tests/torch/nas/test_elastic_depth.py
- tests/torch/nas/test_state.py
A test was adjusted to correctly work with original model copies.
Incorrect tested behaviour discovered while working on another PR.
N/A
tests.torch.nas.test_state.test_can_load_handler_state
> Fix NAS test

- nncf/openvino/engine.py
- nncf/openvino/quantization/accuracy_aware.py
Problem was fixed.
nncf.quantize_with_accuracy_control() run validation during computing statistics
Ref: 102885
How to test:
https://github.com/openvinotoolkit/nncf/pull/1421
> nncf.quantize_with_accuracy_control() run validation during computing statistics

- nncf/experimental/openvino_native/graph/model_transformer.py
- nncf/experimental/openvino_native/graph/node_utils.py
- nncf/experimental/openvino_native/statistics/aggregator.py
- nncf/onnx/graph/model_transformer.py
- nncf/onnx/graph/nncf_graph_builder.py
- nncf/onnx/graph/onnx_graph.py
- nncf/onnx/statistics/aggregator.py
- tests/onnx/quantization/test_graphs.py
- tests/onnx/test_model_transformer.py
- tests/onnx/test_statistics_aggregator.py
Introduce the way to register weight quantizers statistics the same for weight and for activations.
To vanish the problems with finding the weight tensor.
102594
Updated
> [PTQ] Register statistics for weights the same as for activations

- docs/compression_algorithms/Quantization.md
Fixed typo in Quantization.md
Unescaped special character in math expression
-
-
> Fix typo in Quantization.md

- examples/post_training_quantization/onnx/mobilenet_v2/main.py
- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
Change validation function and requirements
Performance speed up measured on OV ~ 3x
Accuracy drop: 0.3%
102713
Manually tested
> ONNX sample update validation to OV

- tests/post_training/__init__.py
- tests/post_training/test_quantize_conformance.py
* Added `__init__.py` to `tests/post_training` dir
* Removed whitespaces in backend-specific dirs with error logs
> Added __init__.py to post training tests

- nncf/experimental/openvino_native/hardware/fused_patterns.py
- Fixed OV patterns that affects performance
- Performance degradation
Here is the example of the changes:
> [PTQ] Fix OV patterns

- tests/openvino/tools/calibrate.py
- tools/get_ir_ignored_scope_by_model_id.py
- tools/get_ir_is_by_model_id.py
[PTQ][OV] Remove IS calculation from `calibrate.py`, move it to separate tool
To make calibration clearer
> [PTQ][OV] Remove IS calculation from `calibrate.py`, move it to separate tool

- nncf/onnx/graph/model_transformer.py
- nncf/onnx/graph/node_utils.py
- nncf/onnx/graph/transformations/commands.py
- nncf/onnx/statistics/aggregator.py
- nncf/quantization/algorithms/min_max/algorithm.py
- nncf/quantization/algorithms/min_max/onnx_backend.py
- tests/onnx/data/reference_graphs/original_nncf_graph/synthetic/double_input_output_model.dot
- tests/onnx/data/reference_graphs/quantization/synthetic/double_input_output_model.dot
- tests/onnx/data/reference_graphs/quantization/synthetic/multi_input_output_model.dot
- tests/onnx/models.py
- tests/onnx/quantization/common.py
- tests/onnx/quantization/test_classification_models_graph.py
- tests/onnx/quantization/test_detection_models_graph.py
- tests/onnx/quantization/test_graphs.py
- tests/onnx/quantization/test_opset_versions.py
- tests/onnx/quantization/test_segmentation_models_graph.py
- tests/onnx/test_model_transformer.py
Fix a bug with using incorrect port while quantizing Input
104908
104908
> [ONNX] Add port to nncf_input_node_next_onnx_nodes

- tests/post_training/model_scope.py
- tests/post_training/test_quantize_conformance.py
Fix conformance test
Fix bug with rewriting the results for the mode with different quantization configurations
No
No
> [PTQ] Fix rewriting results for models with the same name

- nncf/common/graph/patterns/patterns.py
- nncf/experimental/openvino_native/hardware/fused_patterns.py
- tests/onnx/test_pattern_manager.py
- tests/torch/test_pattern_manager.py
* Added `Input -> Subtract -> Multiply` pattern
* Added `MVN -> Multiply -> Add -> Activation` pattern
* To improve performance of quantized models (fast-neural-style-mosaic, vfnet)
* 105079
> [OV] Extend fused patterns

- licensing/third-party-programs.txt
- Added Keras third-party license
> Keras third-party license

- nncf/common/graph/patterns/patterns.py
- nncf/experimental/openvino_native/hardware/fused_patterns.py
- nncf/onnx/hardware/fused_patterns.py
- tests/torch/test_pattern_manager.py
The linear squeeze activation pattern was added
Align with the OpenVINO runtime
https://github.com/openvinotoolkit/nncf/issues/1631
N/A
> Add the linear squeeze activation pattern

- nncf/experimental/openvino_native/graph/model_transformer.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
- Fixed the ModelTransformer behavior for BiasCorrection algorithms
- Fixed (Full)BiasCorrection algorithm
- Detection models support
- 103935
> [PTQ] Update F-/BC with the dynamism

- tests/openvino/native/quantization/test_fq_params_calculation.py
- tests/openvino/native/quantization/test_graphs.py
- tests/openvino/native/quantization/test_sanity.py
- tests/openvino/native/test_nncf_graph_builder.py
- tests/openvino/omz_helpers.py
- tests/openvino/pot/quantization/test_sanity.py
> [OV] Fixed path to OMZ converted model

- tests/torch/ptq/test_calculation_quantizer_params.py
Added a test for the Torch PTQ backend that verifies that common FQ params match to the FQ params in exported Torch model.
To improve code coverage
100805
test_quantizer_parameters_export
> [PTQ][PT] Added test to check export of FQ params

- nncf/common/quantization/quantizer_propagation/solver.py
- Hotfix solver bug "filtered_ip_graph is not defined"
- Hotfix
> Solver hotfix

- nncf/experimental/openvino_native/engine.py
- nncf/experimental/openvino_native/graph/model_transformer.py
- nncf/experimental/openvino_native/quantization/algorithms/bias_correction/openvino_backend.py
- nncf/experimental/openvino_native/quantization/algorithms/fast_bias_correction/openvino_backend.py
- tests/openvino/native/common.py
- tests/openvino/native/models.py
- tests/openvino/native/test_engine.py
- tests/openvino/tools/calibrate.py
- tests/post_training/test_quantize_conformance.py
- Updated calibrate.py to use only tensor names
- Updated OVNativeEngine to check only tensor names
- nGraph don't guarantee that friendly name == tensor name
- 104835
> [PTQ] Update friendly names usage

- tests/common/test_logging.py
Close the file handler in the set_log_file_test before leaving the `TemporaryDirectory` context manager.
Fails on windows otherwise because we are trying to remove the directory where the log file is still open by NNCF. Strange that this did not fail on Linux.
N/A
tests.common.test_logging.test_set_log_file
> Fix set_log_file_test

- nncf/experimental/openvino_native/graph/metatypes/openvino_metatypes.py
- nncf/experimental/openvino_native/hardware/fused_patterns.py
- tests/openvino/native/test_pattern_manager.py
Add a check of dynamic shape to determine depthwise convolution.
Add pattern for OV
**Before:**
**After:**
Fix bug for rvm_mobilenet_v3
107759
TBD
> [OV] Fix dynamic shape for depthwise conv

- tests/cross_fw/install/test_install.py
- tests/shared/helpers.py
- tests/torch/test_extensions_build.py
Shared function to return correct python/pip executable depending on platform
Fix and beautify code to run precommit tests on Windows and Linux platforms 
107218
> deduplicate python/pip executable function

- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
- examples/torch/common/model_loader.py
- nncf/experimental/common/graph/netron.py
> Fixed issues

- tests/post_training/test_quantize_conformance.py
Import fixed
Runtime error during quantize conformance
> [Torch] Fix torch quantize import

- examples/post_training_quantization/openvino/yolov8/README.md
Typo in Yolov8 description
Typo in Yolov8 description
na
na
> Yolo example title correction

- nncf/common/tensor_statistics/aggregator.py
- nncf/quantization/algorithms/post_training/algorithm.py
- tests/common/test_statistics_aggregator.py
- tests/openvino/native/quantization/test_fq_params_calculation.py
- tests/torch/ptq/test_calculation_quantizer_params.py
> Fixed typo

- nncf/__init__.py
- nncf/experimental/openvino/quantization/quantize_model.py
- nncf/openvino/pot/quantization/quantize_model.py
- nncf/openvino/quantization/quantize_model.py
- nncf/parameters.py
- nncf/quantization/algorithms/accuracy_control/algorithm.py
- nncf/quantization/quantize_model.py
- tests/openvino/tools/calibrate.py
Added the drop_type parameter to the quantize_with_accuracy_control function
ref:109717
ref:109717
TBD
> Introduced the drop_type parameter to the quantize_with_accuracy_control function

- nncf/__init__.py
- nncf/experimental/openvino/quantization/quantize_model.py
- nncf/openvino/pot/quantization/quantize_model.py
- nncf/openvino/quantization/quantize_model.py
- nncf/parameters.py
- nncf/quantization/algorithms/accuracy_control/algorithm.py
- nncf/quantization/quantize_model.py
- tests/openvino/tools/calibrate.py
https://github.com/openvinotoolkit/nncf/pull/1758
> [ReleaseV250] Introduced the drop_type parameter to the quantize_with_accuracy_control function

- tests/shared/paths.py
- tests/tensorflow/test_sanity_sample.py
- tests/torch/test_extensions_build.py
- tests/torch/test_sanity_sample.py
> Fix final windows tests (#1752)

- README.md
Same as #1721 but to release branch.
> [Release 2.5.0] Usage docs improvement

- Security.md
> Add security.md file

- README.md
https://github.com/openvinotoolkit/nncf/pull/1794#issuecomment-1543374288
> [Release v2.5.0] Mentioned JPQD and Intel Optimum in the main readme #1801

- tests/torch/test_sota_checkpoints.py
> Fix E2E PT

- nncf/common/tensor_statistics/aggregator.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
Add `tqdm` status bars.
Improve UX
...
> [Release v2.5.0][PTQ] Add status bar for FBC, BC and statistics collection 

- nncf/common/tensor_statistics/aggregator.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
Add `tqdm` status bars.
Improve UX
...
> [PTQ] Add status bar for FBC, BC and statistics collection

- nncf/openvino/pot/quantization/quantize_model.py
- nncf/tensorflow/quantization/quantize_model.py
- nncf/torch/quantization/quantize_model.py
Fixed bug relative to the ignored scope
PR #1620
N/A
N/A
> Fix ignored scope for PR #1620

- nncf/openvino/pot/quantization/quantize_model.py
- nncf/tensorflow/quantization/quantize_model.py
- nncf/torch/quantization/quantize_model.py
> Fix ignored scope

- tests/openvino/tools/calibrate.py
AA `transform_fn` aligned with standard quantize `tranform_fn` 
To align AA and standard quantize in `calibrate.py`
> [Test][PTQ] Fix `transform_fn` for AA in calibrate.py

- tests/onnx/quantization/test_transform_fn.py
- tests/openvino/test_transform_fn.py
- tests/tensorflow/quantization/test_transform_fn.py
- tests/torch/test_transform_fn.py
- Tests were added for transformation function (single input, multiple inputs)
Ref: 96928
Ref: 96928
- tests/openvino/test_transform_fn.py
> Tests for transformation function

- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/backend.py
- nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
- nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
- Temporary remove inserting null biases from FBC
- Null biases do not affect accuracy for now due to the magnitude formula
> [PTQ][OV] Drop null biases for FBC

- nncf/onnx/graph/metatypes/onnx_metatypes.py
- nncf/openvino/graph/metatypes/openvino_metatypes.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
> [Release_v250][PTQ] Fix BC subset_size usage & operations with bias list

- nncf/torch/quantization/algo.py
- tests/torch/quantization/test_range_init.py
Copy of #1828 to release branch
> [Release] Force range initialization to be applied in eval mode (#1828)

- nncf/torch/dynamic_graph/patch_pytorch.py
- nncf/torch/nncf_network.py
- tests/torch/ptq/test_calculation_quantizer_params.py
- tests/torch/test_nncf_network.py
- tests/torch/test_onnx_export.py
> Fix NNCFNetwork forward hooks

- nncf/common/graph/operator_metatypes.py
- nncf/common/quantization/quantizer_propagation/solver.py
- nncf/torch/graph/operator_metatypes.py
- tests/torch/data/reference_graphs/quantized/synthetic_model/Baddbmm.dot
> Ignore 0-th port of baddbmm in quantization (#1852)

- examples/post_training_quantization/openvino/quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
> Fix PTQ example versions (#1854)

- tests/tensorflow/sota_checkpoints_eval.json
> [Release_v250] Updated reference metric for MobileNetV3Small Quantization + Sparsity

- tests/post_training/requirements.txt
Copy of https://github.com/openvinotoolkit/nncf/pull/1832 into release250
> [Release_v250] Fixed version of timm (#1832)

- ReleaseNotes.md
> [Release_v250] Update ReleaseNotes.md

- nncf/torch/nncf_network.py
- tests/torch/test_nncf_network.py
Copy of https://github.com/openvinotoolkit/nncf/pull/1863 into release250
> [Release_v250] Return copy of scope from get_nncf_modules (#1863)

- examples/torch/classification/main.py
- examples/torch/common/example_logger.py
- nncf/common/hardware/config.py
- nncf/common/quantization/quantizers.py
- nncf/quantization/fake_quantize.py
- nncf/torch/quantization/layers.py
- nncf/torch/quantization/strip.py
- tests/torch/quantization/test_strip.py
- tests/torch/test_compression_training.py
> Fix compression training tests (#1823)

- ReleaseNotes.md
- Added known issues section for PTQ into ReleaseNotes.md
- Known issues
> Known issues update

- README.md
This PR updates the Readme file with the Contents, more examples, corrections for PTQ, slight re-structure, etc.
More changes will come in further PRs for other NNCF documents. I decided to split it to reduce the number of potential comments and review time. 
Docs improvements
na
na
> More updates of Readme

- nncf/torch/graph/transformations/commands.py
- nncf/torch/model_transformer.py
- nncf/torch/nncf_network.py
- tests/torch/test_model_transformer.py
- Rebuild after insert FQ nodes in the models.
111575
test_rebuild_graph_after_insert_transformation
> Rebuild graph after insert FQ nodes 

- README.md
> [Release_v250] Mapping of 1836

- Makefile
- setup.py
- tests/onnx/benchmarking/requirements.txt
- tests/onnx/requirements.txt
- tests/openvino/requirements.txt
- tests/post_training/requirements.txt
- tests/torch/requirements.txt
Fixed OpenVINO version `openvino==2022.3.0`
Make pre-commits green 
N/A
pre-commits
> Fix openvino version

- ReleaseNotes.md
- examples/torch/object_detection/README.md
- examples/torch/semantic_segmentation/README.md
- Updated docs from release (#1879 + #1876)
- Docs actual status
> Update docs from release

- nncf/quantization/advanced_parameters.py
> [Release_v250] Fixed type hints

- examples/tensorflow/object_detection/main.py
Follow up https://github.com/openvinotoolkit/nncf/pull/1799
> Fixed pylint issue in the object detection example

- nncf/experimental/torch/nas/bootstrapNAS/search/search.py
- setup.py
Update pymoo to 0.6. This package is used in BootstrapNAS search. Currently BootstrapNAS uses pymoo 0.5, which was released two years ago. 
N/A
N/A
> Update pymoo to 0.6

- README.md
Actual information about system requirements and test environment 
- Python <3.11 - https://github.com/openvinotoolkit/nncf/pull/1739
- Supported version of `PyTorch >=1.13.0, <2.1` - https://github.com/openvinotoolkit/nncf/pull/1783
- Tests run with `PyTorch* 2.0.1 (NVidia CUDA\* Toolkit 11.7)`
Readme contains not actual information
> Update system requirements and test environment

- nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_builder.py
- nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_controller.py
- tests/torch/nas/test_ps_controller.py
- tests/torch/nas/test_scheduler.py
Enables KD loss in BootstrapNAS.
Using KD loss improves the training efficiency and produces better search results. Tested on MobileNetV3-ImageNet and BERT-SQuAD v1.1. 
N/A
test_knowledge_distillation_training_process.
> BNAS KD Loss

- nncf/quantization/algorithms/algorithm.py
- nncf/quantization/algorithms/min_max/algorithm.py
2x speedup for PTQ
Optimization post-training quantization algorithm
ref: 113245
N/A
> Speedup of PTQ

- tests/torch/data/search_building_block/wave2vec_2.0.json
- tests/torch/requirements.txt
- tests/torch/sparsity/movement/training_scripts/run_glue.py
Fixing https://github.com/openvinotoolkit/nncf/security/dependabot/37
113101
tests/torch/experimental/search_building_blocks
> Update transformers version for tests

- tests/post_training/test_templates/test_ptq_params.py
Add inference_graph in `_get_ignored_names`
Fix pre-commit after merge https://github.com/openvinotoolkit/nncf/pull/1905
No
No
> Fix incorrect arg in test after #1905

- nncf/onnx/graph/onnx_graph.py
Removed outdated methods in ONNXGraph
> [ONNX] Remove useless methods

- examples/tensorflow/common/object_detection/utils/yolo_v4_utils.py
Update pillow api.
Old api was removed.
> Support pillow>=10.0.0

- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- nncf/openvino/quantization/quantize_model.py
- nncf/quantization/algorithms/accuracy_control/evaluator.py
- tests/cross_fw/examples/example_scope.json
Additional check was added
nightly tests failed
N/A
Nightly jobs/test examples
> Fix samples

- README.md
Follow up https://github.com/openvinotoolkit/nncf/pull/1950
> Added the transformation in all code snippets in the usage guide

- tests/post_training/reference_data.yaml
Update reference metrics of PTQ according weekly test 145. 
- https://github.com/openvinotoolkit/nncf/pull/1945
> Update reference metrics of PTQ

- nncf/quantization/advanced_parameters.py
- nncf/quantization/algorithms/smooth_quant/algorithm.py
- tests/post_training/model_scope.py
- tests/post_training/reference_data.yaml
- Rollback #1945 
- Update conformance test parameters & golds
- Need to have enabled SQ
> Enable SQ & update conformance

- nncf/onnx/graph/metatypes/onnx_metatypes.py
- nncf/onnx/quantization/default_quantization.py
- nncf/quantization/algorithms/min_max/onnx_backend.py
- nncf/quantization/algorithms/min_max/openvino_backend.py
- nncf/quantization/algorithms/min_max/torch_backend.py
Add Maximum operator into ignored when model_type = ModelType.Transformer
N/A
113823
> [PTQ] Add Maximum op to ignored_scope for ModelType.Transformer

- README.md
> Add link to CLIP notebook in README

- nncf/torch/extensions/include/common_cpu_funcs.h
- nncf/torch/extensions/include/common_cuda_defs.cuh
- nncf/torch/extensions/include/common_cuda_funcs.cuh
- nncf/torch/extensions/include/common_defs.h
- nncf/torch/extensions/include/dispatch.h
- nncf/torch/extensions/src/binarization/cpu/functions_cpu.cpp
- nncf/torch/extensions/src/binarization/cuda/functions_cuda_impl.cu
- nncf/torch/extensions/src/quantization/cpu/functions_cpu.cpp
- nncf/torch/extensions/src/quantization/cuda/functions_cuda_impl.cu
- tests/torch/quantization/test_algo_quantization.py
- tools/benchmark.py
- tools/benchmark_quantize_layers.py
Otherwise the autocast to BF16 does not work with quantization.
N/A
test_external_autocast on CPU-only hosts
> Dispatch bfloat along with the rest of the types for the kernels

- README.md
Add link to ImageBind notebook
112981
> Add link to ImageBind notebook in README

- tests/post_training/requirements.txt
Update transformers version from `4.29.2` to `4.30.0`
113101
> Update transformers to 4.30.0 in ptq tests

- tests/post_training/reference_data.yaml
Update ref metrics for ONNX conformance test after #1917
N/A
N/A
N/A
> [ONNX] Update Reference metrics for ONNX after #1917

- nncf/openvino/pot/quantization/quantize_model.py
- Disabled MMAP
- Failures on Windows
> [PTQ] Disable MMAP

- nncf/openvino/pot/quantization/quantize_model.py
- Added warning message for POT backend
- Better UX
> [PTQ] Added warning logger for pot backend

- nncf/common/graph/patterns/patterns.py
- nncf/onnx/hardware/fused_patterns.py
- nncf/openvino/graph/metatypes/openvino_metatypes.py
- nncf/openvino/hardware/fused_patterns.py
- nncf/openvino/hardware/pattern_operations.py
- tests/torch/test_pattern_manager.py
Added hswish metatype and LINEAR_ARITHMETIC_ACTIVATIONS_ARITHMETIC pattern
Support for OpenVINO HSwish operation.
https://github.com/openvinotoolkit/nncf/issues/1936
N/A
> [PTQ] Added hswish metatype and LINEAR_ARITHMETIC_ACTIVATIONS_ARITHMETIC pattern

- examples/tensorflow/requirements.txt
> update pycocotools==2.0.6 for tf examples

- nncf/common/utils/os.py
- nncf/quantization/algorithms/accuracy_control/algorithm.py
Add option to get logical or physicals cores
> Use psutils for get_available_cpu_count

- tests/cross_fw/install/test_install.py
Disabled until NNCF is exposed in a release
failed install tests in the nightly build
N/A
install tests
> Fix for install tests

- nncf/quantization/algorithms/accuracy_control/algorithm.py
- nncf/quantization/algorithms/accuracy_control/ranker.py
- nncf/quantization/algorithms/accuracy_control/subset_selection.py
- tests/common/accuracy_control/test_ranking.py
Move worst subset selection from Ranker to the QuantizationAccuracyRestorer
This subset is required for tuning of hyperparameters
N/A
N/A
> Move worst subset selection from Ranker to the QuantizationAccuracyRestorer

- docs/ModelZoo.md
- Sort tables by module name
- Remove duplicated rows
- Replace unicodes with the appropriate characters
> [DOC] Sort tables by model name in ModelZoo.md

- tests/openvino/tools/calibrate.py
- Added support of different POT-style algorithms into `calibrate.py`
- Extended usage of the `calibrate.py` tool
- 108993
> [PTQ] Update calibrate.py with the other algorithms support

- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- tests/cross_fw/examples/example_scope.json
Updated the model used in the anomaly_stfpm_quantize_with_accuracy_control example to a more accurate model.
Demonstrate quantize with accuracy control flow
ref: 106970
test_examples.py
> Updated model for the anomaly_stfpm_quantize_with_accuracy_control example

- CODEOWNERS
- docs/ModelZoo.md
- Fix names of teams in CODEOWNERS
- But openvino-admins and openvino-configuration-mgmt looks like private groups as result 
```
Unknown owner on line 3: make sure the team @openvinotoolkit/openvino-admins exists, is publicly visible, and has write access to the repository
```
- Little improves of modelzoo.md
> [DOCS] Update CODEOWNERS, Some improves of modelzoo.md

- nncf/common/graph/patterns/patterns.py
- nncf/openvino/hardware/fused_patterns.py
- nncf/openvino/quantization/ignored_patterns.py
- tests/onnx/test_pattern_manager.py
- tests/torch/test_pattern_manager.py
Make EQUAL_LOGICALNOT ignored for quantization
Algin with POT; Fix bad metrics in the model.
109507
Manually tested
> [OV] Place EQUAL_LOGICALNOT from fused to ignored

- tests/openvino/tools/calibrate.py
Models are reshaped back after quantization
To return quantized models with the same shapes as it was before the quantization
115226
> [PTQ] Reshape models to original shapes after quantization in calibrate.py

- nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_width.py
- nncf/quantization/algorithms/accuracy_control/algorithm.py
Rename `data` to `attributes`
It was not renamed here https://github.com/openvinotoolkit/nncf/pull/2030
N/A
N/A
> Rename data to attributes

- .github/workflows/pre-commit-linters.yml
- .github/workflows/precommit.yml
- .github/workflows/precommit_onnx.yml
Pretty much as stated in the title. This adds a simple GH action workflow file to run the ONNX precommit via the makefile.
> Run ONNX precommit as a Github action

- .github/workflows/precommit.yml
- Makefile
- codecov.yml
- tests/common/requirements.txt
- tests/cross_fw/examples/requirements.txt
- tests/cross_fw/install/requirements.txt
- tests/onnx/requirements.txt
- tests/openvino/requirements.txt
- tests/post_training/requirements.txt
- tests/tensorflow/requirements.txt
- tests/torch/requirements.txt
Makefiles and actions adjust to generate coverage reports along with the precommit tests.
Going to track coverage on a per-PR basis, to ensure good test coverage of new and existing code.
N/A
precommit
> Run coverage with pytest

- .github/workflows/api_changes_check.yml
- .github/workflows/build_and_publish_doc.yml
- .github/workflows/build_html_doc.yml
- .github/workflows/build_schema_page.yml
- .github/workflows/labeler.yml
- .github/workflows/python-publish.yml
Introducing consistency with local CI.
N/A
N/A
> Use Ubuntu 20 in workflows

- Makefile
- tests/torch/sparsity/movement/test_model_saving.py
> Revert "Run coverage with pytest (#2038)" 

- nncf/__init__.py
> Use find_spec instead of try-import-except to detect backends

- .github/workflows/api_changes_check.yml
> Add release labeler

- nncf/common/quantization/quantizer_propagation/graph.py
- nncf/common/quantization/quantizer_propagation/solver.py
- tests/common/quantization/test_ignore_post_processing.py
> [Release_v260] Fix PostprocessingNodeLocator

- examples/torch/common/export.py
- nncf/experimental/torch/sparsity/movement/structured_mask_handler.py
- nncf/torch/nncf_network.py
- tests/torch/pruning/experimental/test_nodes_grouping.py
- tests/torch/test_nncf_network.py
Copy of #2083 to release branch.
> [Release] Deprecate some methods for NNCF 2.6 release

- nncf/quantization/algorithms/accuracy_control/algorithm.py
PR: https://github.com/openvinotoolkit/nncf/pull/2095
> [Release_v260] Use num_ranking_processes = 1 for Windows

- nncf/quantization/algorithms/post_training/algorithm.py
- nncf/quantization/algorithms/smooth_quant/algorithm.py
Copy of  #2090 to release branch
> [Release] Skip SmoothQuant creation if alpha is negative

- README.md
Added Whisper notebook to the list of quantization samples
> Added Whisper notebook to the list of quantization samples

- nncf/torch/quantization/weights_compression.py
- tests/torch/ptq/test_weights_compression.py
Fixed problem with shared weights in compression.
Problem with some LLMs with shared weights.
> Fixed problem with shared weights in compression.

- ReleaseNotes.md
https://github.com/openvinotoolkit/nncf/pull/2111
> [Release_v260] Update ReleaseNotes with 2.6.0

- nncf/version.py
> [Release_v260] Fixed release version

- nncf/torch/quantization/weights_compression.py
- tests/torch/ptq/test_weights_compression.py
Copy of [#2110](https://github.com/openvinotoolkit/nncf/pull/2110)
> Fixed problem with shared weights in compression. (#2110)

- examples/post_training_quantization/openvino/yolov8/main.py
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
Copy of #2133 to release branch.
> [Release] Upgrade ultralytics to 8.0.170 (#2133)

- README.md
Copy of #2123 to release branch
> [Release] Added Whisper notebook to the list of quantization samples (#2123)

- nncf/experimental/torch/nas/bootstrapNAS/search/search.py
- setup.py
> [Release_v260] Update pymoo version

- nncf/version.py
> Fixed release version (#2131)

- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- setup.py
- tests/onnx/benchmarking/requirements.txt
- tests/onnx/requirements.txt
- tests/torch/requirements.txt
- Updated OpenVINO version to 23.1
> Update OpenVINO version

- tests/openvino/requirements.txt
Fix incorrect version of OV
N/A
N/A
> Update OV Version for tests

- tests/openvino/tools/calibrate.py
- Add support for models that don't have per-sample metrics.
Some models don't have per-sample metrics. An error occurred with these models.
N/A
> Update calibrate tool

- README.md
Added links to `OneFormer` and `InstructPix2Pix` OpenVINO notebooks
> Add links to OneFormer and InstructPix2Pix notebooks

- tests/openvino/conftest.py
- tests/openvino/native/quantization/test_fq_params_calculation.py
- tests/openvino/native/quantization/test_graphs.py
- tests/openvino/native/quantization/test_sanity.py
- tests/openvino/native/test_nncf_graph_builder.py
- tests/openvino/omz_helpers.py
- tests/openvino/pot/quantization/test_sanity.py
Added cache_dir for OMZ models
* Сhanges made according to the requirements of the validation team
> [OV] Add caching of OMZ models

- tests/openvino/native/data/2023.2/reference_scales/yolo-v4-tiny-tf_mixed.json
- tests/openvino/native/data/2023.2/reference_scales/yolo-v4-tiny-tf_performance.json
> Updated reference for 2023.2.0-12979-04c766e9f17

- examples/post_training_quantization/onnx/mobilenet_v2/main.py
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/openvino/mobilenet_v2/main.py
- examples/post_training_quantization/openvino/yolov8/main.py
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/torch/mobilenet_v2/main.py
- examples/post_training_quantization/torch/ssd300_vgg16/main.py
Using ov.save_model(...) in PTQ examples
ov.save_model(...) is introduced in OpenVINO==2023.1.0
N/A
examples
> Using ov.save_model(...) in PTQ examples

- nncf/quantization/algorithms/hyperparameter_tuner/param_grid.py
- nncf/quantization/algorithms/pipeline.py
Fix index out of range
File "nncf/nncf/quantization/algorithms/pipeline.py", line 119, in run_step
current_model = pipeline_step[-1].apply(current_model, current_graph, step_statistics)
IndexError: list index out of range
N/A
N/A
> Fix index out of range

- nncf/experimental/tensor/functions.py
- nncf/experimental/tensor/numpy_functions.py
- nncf/experimental/tensor/tensor.py
- nncf/experimental/tensor/torch_functions.py
- tests/shared/test_templates/template_test_nncf_tensor.py
Follow-up from comment https://github.com/openvinotoolkit/nncf/pull/2218#discussion_r1372651109
n/a
test_fn_max
test_fn_min
test_max
test_min
> Added `keepdims` argument for min,max functions

- .github/workflows/post_pr_merge.yml
- .github/workflows/precommit.yml
- .github/workflows/upload_coverage_for_develop.yml
> Github actions codecov add ONNX flag

- tests/torch/ptq/test_reducers_and_aggregators.py
Skip cuda test if cuda is not available
To fix CPU pre-commit
> [Release 270][Torch] Skip cuda test if cuda is not available

- examples/torch/common/export.py
- nncf/torch/dynamic_graph/graph_tracer.py
- nncf/torch/dynamic_graph/io_handling.py
- nncf/torch/exporter.py
- nncf/torch/model_creation.py
- nncf/torch/model_transformer.py
- nncf/torch/nncf_module_replacement.py
- nncf/torch/nncf_network.py
- nncf/torch/utils.py
- tests/torch/test_graph_building.py
- tests/torch/test_nncf_network.py
- tests/torch/test_transform_fn.py
Supports multi-device model inference and wrapped forward functions
Support tracing "bigscience/bloomz-560m" model from HF
N/A
test_no_self_forward,  test_multidevice_model
> Supports multi-device model inference and wrapped forward functions

- tests/torch/nas/test_elastic_width.py
Use built-in `tmp_path` for temporary files to fix NAS tests on Windows
The PR (https://github.com/openvinotoolkit/nncf/pull/2234) introduced a new test which fails on Windows with error:
`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\SYS_K8~1\\AppData\\Local\\Temp\\tmpmf1i25nd'`
124904
NAS tests on Windows
> Fixed NAS test on Windows

- examples/torch/requirements.txt
> Fix torchvision version in the examples

- examples/post_training_quantization/onnx/mobilenet_v2/main.py
Fixed output text in the ptq onnx example
Incorrect output text in the ptq onnx example
N/A
test_examples
> Fixed output text in the ptq onnx example

- ReleaseNotes.md
- As stated in the title
- Minor changes for the links in the ReleaseNotes.
> [Release_v270] Add known issue to ReleaseNotes

- Makefile
- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- setup.py
- tests/onnx/benchmarking/requirements.txt
- tests/onnx/requirements.txt
- tests/openvino/requirements.txt
- tests/post_training/requirements.txt
- tests/torch/requirements.txt
- As stated in the title
- Updated TensorFlow installation position for `install-openvino-test` make action
- Release benchmark
> [Release_v270] Update OV version

- Makefile
- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- setup.py
- tests/onnx/benchmarking/requirements.txt
- tests/onnx/requirements.txt
- tests/openvino/requirements.txt
- tests/post_training/requirements.txt
- tests/torch/requirements.txt
cherry picked from commit c2529611887fb38a40be26d10be92c16598c5a50
> Update OV version

- nncf/openvino/graph/model_transformer.py
Remove workaround for OV backend as the ticket was closed.
Code cleaning
121115
The current test validates this issue.
`test_if_model_fq_placement` in `tests/openvino/native/quantization/test_graphs.py`
> [OV] remove workaround

- docs/compression_algorithms/CompressWeights.md
- nncf/parameters.py
- nncf/quantization/algorithms/weight_compression/algorithm.py
- nncf/quantization/algorithms/weight_compression/backend.py
- nncf/quantization/algorithms/weight_compression/openvino_backend.py
- nncf/quantization/quantize_model.py
- nncf/torch/quantization/quantize_model.py
> mentioned all embeddings in weight compression docs

- examples/torch/requirements.txt
- As stated in the title.
- 125654
> Update MLFlow version

- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
- examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/main.py
- examples/post_training_quantization/torch/ssd300_vgg16/main.py
- tests/cross_fw/examples/example_scope.json
- Migrated to openvino.convert_model(...)
- Upgraded OpenVINO version to 2023.2 in PTQ TensorFlow example 
Aligned examples with the OpenVINO 2023.2
125257
test_examples 157
> Updating examples

- tests/post_training/reference_data.yaml
Update reference of metrics according last weekly tests
> Update reference for test_quantize_conformance

- nncf/torch/dynamic_graph/context.py
- nncf/torch/graph/graph_builder.py
- nncf/torch/nncf_network.py
- nncf/torch/quantization/algo.py
- nncf/torch/tensor.py
- tests/common/experimental/test_statistic_collector.py
- tests/common/test_statistics_aggregator.py
- tests/onnx/test_statistics_aggregator.py
- tests/openvino/native/test_statistic_collector.py
- tests/openvino/native/test_statistics_aggregator.py
- tests/torch/helpers.py
- tests/torch/ptq/test_statistic_collector.py
- tests/torch/test_model_transformer.py
- tests/torch/test_statistics_aggregator.py
Part 2/4 of SQ support https://github.com/openvinotoolkit/nncf/pull/2279
* Nested and successive hooks are supported
* To make it possible to insert nested and successive hooks to the torch models
124563
* tests/torch/test_model_transformer.py checks sequential and nested hooks are inserted correctly / checks temporary hooks are applied correctly
> [PTSQ 2/4][Torch] Nested and successive hooks

- examples/post_training_quantization/torch/ssd300_vgg16/main.py
Disable tracing for anchor generator
127935
> Disable tracing for DefaultBoxGenerator

- .github/workflows/python-publish.yml
- Updated `python-publish.yml` with a fix.
- - Updated `python-publish.yml` with actions version.
- Small fixes after release
> Small fix & update action version

- nncf/openvino/graph/model_transformer.py
- Added creation of a constant as an operation.
- To make constant names unique.
- 125404
> [PTQ][OV] Named constant nodes

- nncf/telemetry/wrapper.py
Getting too many events that look suspiciuous - will estimate if this change helps after this is merged based on the event time series graph
N/A
Effect only visible past-merge
> Set disable_in_ci=True in OV telemetry object

- tests/torch/sota_checkpoints_eval.json
Increase thresholds for test_sota_checkpoints.py
Metrics for OV does not change.
Unstable results with CUDA
tests/torch/test_sota_checkpoints.py
> Increase thresholds for pt e2e tests

- setup.py
> Bump pandas version

- setup.py
- tests/tensorflow/requirements.txt
- tests/torch/requirements.txt
These are the leftovers from #2241.
69520
torch/TF precommit
> Remove pyparsing limitation from tests

- tests/tensorflow/requirements.txt
- tests/torch/requirements.txt
> Remove pyparsing limitation from tests 

- docker/onnx/openvinoep/Dockerfile
- docker/onnx/openvinoep/build.sh
- docker/tensorflow/gpu/Dockerfile
- docker/torch/cpu/Dockerfile
- docker/torch/gpu/Dockerfile
> Make dockerfiles conform to hadolint 

- tests/openvino/tools/calibrate.py
> [CI] Calibration stopped - fix import - CVS-128463

- nncf/common/graph/layer_attributes.py
- nncf/common/tensor_statistics/collectors.py
- nncf/onnx/statistics/collectors.py
- nncf/openvino/statistics/collectors.py
- nncf/tensorflow/tensor_statistics/collectors.py
- nncf/torch/tensor_statistics/collectors.py
- tests/common/experimental/test_reducers_and_aggregators.py
- tests/openvino/native/quantization/test_reducers_and_aggregators.py
- tests/torch/ptq/test_reducers_and_aggregators.py
Cast float16 and float32 to float64 for mean and median.
Error on calculation parameters of FQ for large scale.
test_reducers_and_aggregators.py::test_overflow
> Fix overflow in collectors

- nncf/common/graph/layer_attributes.py
- nncf/common/tensor_statistics/collectors.py
- nncf/onnx/statistics/collectors.py
- nncf/openvino/statistics/collectors.py
- nncf/tensorflow/tensor_statistics/collectors.py
- nncf/torch/tensor_statistics/collectors.py
- tests/common/experimental/test_reducers_and_aggregators.py
- tests/openvino/native/quantization/test_reducers_and_aggregators.py
- tests/torch/ptq/test_reducers_and_aggregators.py
Reverts openvinotoolkit/nncf#2337
> Revert "Fix overflow in collectors"

- tests/torch/sota_checkpoints_eval.json
Update metrics for pt e2e tests
> Update metrics for pt e2e tests

- examples/torch/common/export.py
- tests/openvino/native/test_bias_correction.py
- tests/openvino/native/test_fast_bias_correction.py
- tests/openvino/native/test_smooth_quant.py
- tests/post_training/pipelines/base.py
- tests/post_training/pipelines/image_classification_timm.py
- tests/post_training/pipelines/masked_language_modeling.py
Use `openvino.convert_model` instead of `openvino.tools.mo.convert_model`
> Use ov.convert_model

- examples/llm_compression/openvino/README.md
> Grammar / typo fixes

- tests/tensorflow/requirements.txt
- Update Tensorflow requirements with the actual OpenVINO version;
- More accurate tests;
> Update Tensorflow requirements with OV

- nncf/onnx/graph/transformations/commands.py
- nncf/quantization/algorithms/bias_correction/onnx_backend.py
- nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
Remove unused ONNXNullBiasInsertionCommand command
Unused code
N/A
N/A
> Remove unused ONNXNullBiasInsertionCommand command

- docs/compression_algorithms/CompressWeights.md
- nncf/quantization/algorithms/weight_compression/mixed_precision.py
> Added a note about execution time of data-based mixed precision weight compression

- nncf/experimental/common/tensor_statistics/collectors.py
- nncf/onnx/statistics/collectors.py
- nncf/openvino/graph/model_transformer.py
- nncf/openvino/graph/node_utils.py
- nncf/openvino/graph/transformations/commands.py
- nncf/openvino/statistics/aggregator.py
- nncf/openvino/statistics/collectors.py
- tests/openvino/native/test_model_transformer.py
InplaceReducers interface was extracted from the base implementation of reducer
To make it easier to implement reducers for backends
> [Experimental][Collectors] Decouple inplace reducers from base reducers

- ReleaseNotes.md
> Updated release notes

- ReleaseNotes.md
> Add release notes for release v2.8.0

- docs/FAQ.md
> fix code example error on torch part

- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/run_example.py
Fix test_examples[llm_compression] 
Job: 217
> Fix TinyLLama test

- tests/common/requirements.txt
- tests/cross_fw/examples/requirements.txt
- tests/cross_fw/install/requirements.txt
- tests/openvino/requirements.txt
- tests/post_training/requirements.txt
- tests/tensorflow/requirements.txt
- tests/torch/models_hub_test/requirements.txt
> Use pytest 7.4.4

- nncf/quantization/algorithms/smooth_quant/algorithm.py
- nncf/quantization/algorithms/weight_compression/algorithm.py
Duplicating copyrights are removed
> Duplicating copyrights are removed

- nncf/openvino/engine.py
reset_state before model inference
Support statefull model inference in `OVCompiledModelEngine`
131141
TBD
> Proposal for stateful models.

- tests/openvino/native/models.py
- tests/openvino/native/test_engine.py
Changes
test for PR #2440
Reason for changes
test for PR #2440
Related tickets
131141
Tests
It is test
> Added test for stateful model.

- nncf/__init__.py
nncf.AdvancedAccuracyRestorerParameters
Make it easier to create AdvancedAccuracyRestorerParameters
N/A
N/A
> nncf.AdvancedAccuracyRestorerParameters

- nncf/common/factory.py
- nncf/openvino/engine.py
- nncf/openvino/graph/model_utils.py
- nncf/quantization/algorithms/accuracy_control/backend.py
- nncf/quantization/algorithms/accuracy_control/evaluator.py
- nncf/quantization/algorithms/accuracy_control/openvino_backend.py
- nncf/quantization/algorithms/accuracy_control/ranker.py
- tests/common/accuracy_control/test_evaluator.py
Restoring state after inference only for stateful models
Inference optimization
131141
test_examples 230
> Restoring state after inference only for stateful models

- nncf/quantization/algorithms/weight_compression/algorithm.py
- nncf/quantization/quantize_model.py
- tests/openvino/native/quantization/test_weights_compression.py
Introduced `subset_size` parameter for weight compression API.
Customers may need to increase or decrease a default value = 128
Also, it can accelerate validation with lower number of samples.
n/a
test_valid_subset_size
test_default_subset_value
test_invalid_subset_size
> Introduced `subset_size` parameter for data-aware weight compression

- tests/post_training/model_scope.py
> Fix name of params

- nncf/quantization/algorithms/accuracy_control/ranker.py
- Add progress bar for calculating ranking scores
Calculating ranking score for groups of quantizers takes a long time for SD models.
Ref: 124131
Manually
> Add progress bar for calculating ranking scores

- tests/post_training/data/wc_reference_data.yaml
- tests/post_training/data/wwb_ref_answers/tinyllama__tinyllama-1.1b-step-50k-105b/ref_qa.csv
- tests/post_training/model_scope.py
- tests/post_training/pipelines/base.py
- tests/post_training/pipelines/lm_weight_compression.py
- tests/post_training/requirements.txt
- tests/post_training/test_quantize_conformance.py
Cache ref data to accelerate conformance tests for weight compression
faster validation
n/a
Before
After
> Cache ref data to accelerate conformance tests for weight compression

- examples/llm_compression/openvino/tiny_llama_find_hyperparams/main.py
Print info about `all_layers` param more clearly
CI examples build: 242
> Improve logging in LLM tune hyperparams example

- nncf/parameters.py
> Fixed API Enums serialization/deserialization issue

- tests/torch/sota_checkpoints_eval.json
> [PT] Update reference for dorefa

- tests/torch/sota_checkpoints_eval.json
> [PT] Update reference for dorefa (#2471)

- tests/onnx/benchmarking/accuracy_checker.py
- tests/onnx/benchmarking/run_ptq.py
- tests/openvino/datasets_helpers.py
- tests/openvino/tools/calibrate.py
- tests/openvino/tools/config.py
- Added try-catch for OMZ imports;
- [OV PR #22683](https://github.com/openvinotoolkit/openvino/pull/22683)
- 132634
- Locally tested with 24.0 OV
- Test run with OV nightly - ubuntu20_precommit_openvino/48 (upd. useless run due to the latest drop a week ago)
(cherry picked from commit 86cee4b3870045297b17d095b741767fd55a60ff)
> [PTQ] Added try-catch for the OMZ imports (#2478)

- tests/common/sdl/test_schema.py
- tests/common/test_monkey_patching.py
- tests/common/utils/__init__.py
- tests/common/utils/test_decorators.py
- tests/common/utils/test_os.py
- tests/common/utils/test_timer.py
- Added unit tests for the first 5 files (listed in the issue) to reach at least 80% coverage
- Addresses https://github.com/openvinotoolkit/openvino/issues/22194
- Tests for remaining files in progress
> Add unit tests for NNCF utils

- docs/compression_algorithms/CompressWeights.md
Added perplexity for AWQ algorithm to documentation.
125383
> [docs] Added perplexity for AWQ.

- nncf/torch/dynamic_graph/context.py
- nncf/torch/model_transformer.py
- nncf/torch/nncf_network.py
- tests/torch/test_model_transformer.py
Add option to insert point for models that wrapped with replace_modules=False
> [PT] Insert point for not replaced modules

- nncf/quantization/algorithms/min_max/torch_backend.py
- tests/torch/ptq/test_fq_params_calculation.py
Eps is subtracted from quantizer parameters instead of zeroing.
To have non zero eps parameters inside quantizer modules. That allows to do the quantization aware training.
129584
TODO:
> [Torch] Subtract eps from quantizer parameters instead of zeroing it

- nncf/torch/binarization/algo.py
- Added the simple deprecation warning for the **binarization** algorithm;
- Binarization deprecation;
- 133129
- N/A
> Added deprecation warning

- nncf/torch/binarization/algo.py
- Added the simple deprecation warning for the **binarization** algorithm;
- Binarization deprecation;
- 133129
- N/A
(cherry picked from commit c8000caa4203a17a18b2c8beb6f934941c4818e0)
> [v2.9.0] Added deprecation warning (#2490)

- .github/workflows/precommit.yml
> Skip precommit tests for docs (*.md) files

- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/deploy.py
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/run_example.py
- Add quantize_with_accuracy_control example for ONNX
TODO:
> Add quantize_with_accuracy_control example for ONNX

- Makefile
Add parameters `--sota-data-dir` and `--sota-checkpoints-dir` for weekly tests 
#2404
134104
> Sota parameters for weekly pytorch job

- tests/torch/sparsity/movement/test_model_saving.py
Corrected deprecated path to mo
> Corrected deprecated path to mo

- examples/quantization_aware_training/torch/resnet18/README.md
- examples/quantization_aware_training/torch/resnet18/main.py
- examples/quantization_aware_training/torch/resnet18/requirements.txt
- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/run_example.py
- tests/cross_fw/examples/test_examples.py
Resnet18 example of QAT after PTQ is presented
To show usage of PTQ in quantization pipelines
129584
Test examples are updated
TODO:
> [Torch] QAT after PTQ resnet18 example

- docs/compression_algorithms/CompressWeights.md
> Fix broken links

- Makefile
- README.md
- tests/cross_fw/install/test_install.py
- tests/torch/quantization/test_hawq_precision_init.py
Removed --index-url to run test with cuda12.1
> [PT] CUDA 12.1

- .github/workflows/nightly.yml
- .github/workflows/pre-commit-linters.yml
- In pull requests will check external links only for modified markdown files 
- Add nightly job to check all links
> Update link checker

- examples/post_training_quantization/onnx/mobilenet_v2/main.py
- examples/post_training_quantization/openvino/mobilenet_v2/main.py
- examples/post_training_quantization/torch/mobilenet_v2/main.py
- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/test_examples.py
- tests/shared/command.py
Fixes of examples for Windows
Support for running examples on Windows
N/A
Linux: test_examples 309
Windows: test_examples 10
> Fixes of examples for Windows

- nncf/onnx/graph/metatypes/groups.py
- nncf/onnx/graph/metatypes/onnx_metatypes.py
- nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
- tests/onnx/test_metatypes.py
Update metatypes list for FBC/BC
Fix bug with determing depthwise conv.
Red PTQ conformance
N/A
Extend test_metatypes by quantized models
> [ONNX] ONNX FBC/BC metatypes groups

- nncf/torch/dynamic_graph/layer_attributes_handlers.py
- tests/torch/test_layer_attributes.py
Fix `IndexError: tuple index out of range` in function `apply_args_defaults`, 
136784
test_apply_args_defaults
test_apply_args_defaults_errors
> [PT] Fix apply_args_defaults

- docs/styleguide/PyGuide.md
Updated reference of copyright header, to don't update it each year.
> Update reference of copyright header in PyGuide.md

- README.md
- docs/compression_algorithms/Quantization.md
- docs/compression_algorithms/post_training/Quantization.md
On top of #2515
PTQ quantization aware training documentation
To improve docs coverage
129584
> PTQ quantization aware training documentation

- tests/tensorflow/sota_checkpoints_eval.json
- tests/torch/sota_checkpoints_eval.json
Update expected metrics values and thresholds according last several builds. 
Not deterministic results on cuda.
136319
> Update thresholds for e2e

- .github/workflows/nightly.yml
- .github/workflows/pre-commit-linters.yml
Update md-dead-link-check action to v0.8
https://github.com/openvinotoolkit/nncf/actions/runs/8608236002
https://github.com/AlexanderDokuchaev/nncf/actions/runs/8622656712/job/23634251845
> Update md-dead-link-check action to v0.8

- nncf/common/quantization/structs.py
Copy of #2629 to release branch
> [Release] Revert quantization scheme StrEnum release

- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/main.py
- examples/post_training_quantization/openvino/yolov8/main.py
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
Change ingored_scope utilizing node names to subgraph.
New ignored_scope is independent on export to OpenVINO format (dynamic, static)
136835
Manually tested
> Update Yolov8 ignored scope utilizing subgraphs approach 

- ReleaseNotes.md
(cherry picked from commit d3a3fe96190721c778156b14001e92de7dc594c2)
> [Release] Release notes 2.10 (#2640)

- nncf/experimental/tensor/functions/numeric.py
- nncf/experimental/tensor/functions/numpy_numeric.py
- nncf/experimental/tensor/functions/torch_numeric.py
- tests/shared/test_templates/template_test_nncf_tensor.py
Fix implementation of `argsort` function
Align PyTorch and Numpy implementation
ref: 2588
tests/common/test_tensor.py
> Fix argsort function

- nncf/quantization/advanced_parameters.py
- nncf/quantization/quantize_model.py
- Removed copy-paste from the AdvancedSmoothQuantParameters
- Updated docsting of compress_weights function
Fix typo
N/A
N/A
> Updated docstrings for AdvancedAWQParameters and AdvancedScaleEstimationParameters

- nncf/quantization/algorithms/weight_compression/algorithm.py
- tests/openvino/native/quantization/test_weights_compression.py
Fix bug in `_get_ratio_defining_params` method
test_shared_gather_all_layers
> [WC] Fix ratio_defining_params

- .pre-commit-config.yaml
- nncf/common/quantization/quantizer_propagation/graph.py
- nncf/common/quantization/quantizer_propagation/solver.py
- nncf/common/tensor_statistics/statistic_point.py
- nncf/openvino/graph/node_utils.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
- nncf/quantization/algorithms/min_max/algorithm.py
- nncf/tensorflow/utils/node.py
- nncf/torch/quantization/init_range.py
- tests/tensorflow/test_sanity_sample.py
- tests/torch/qat/helpers.py
- tests/torch/qat/test_qat_object_detection.py
- tests/torch/test_statistics_aggregator.py
Bump version of black to 24.4.2
Improve formatting
> Bump version of black to 24.4.2

- nncf/quantization/algorithms/weight_compression/algorithm.py
Small fix: added scale_estimation flag to IR metadata.
Small fix: added scale_estimation flag to IR metadata.
> Added scale_estimation flag to IR metadata.

- nncf/common/quantization/structs.py
> [quantization] Fix config compatible check

- examples/quantization_aware_training/torch/resnet18/main.py
- tests/cross_fw/examples/example_scope.json
Resnet18 examples updated to showcase NNCF Torch save/load capabilities
To showcase NNCF Torch save/load capabilities
129586
test_examples/382/
> [Torch][PTQ] Resnet18 example updated to showcase comrpession save/load

- nncf/experimental/tensor/functions/__init__.py
- nncf/experimental/tensor/functions/numeric.py
- nncf/experimental/tensor/functions/numpy_numeric.py
- nncf/experimental/tensor/functions/torch_numeric.py
- tests/shared/test_templates/template_test_nncf_tensor.py
Add function for experimental tensor 
- concatenate
- logical_or
- masked_mean
- masked_median
- median
- percentile
> Add more functions for experimental tensor

- nncf/quantization/algorithms/weight_compression/awq.py
Add log message for when no matches were found for AWQ algorithm
Not obvious enough when AWQ was actually applied.
> Add log message for when no matches were found for AWQ algorithm

- tests/torch/sota_checkpoints_eval.json
- ssd512_vgg_voc_magnitude_sparsity_int8
Unstable result on CUDA
> [PT] Increase threshold for e2e reference

- nncf/quantization/algorithms/weight_compression/awq.py
- nncf/quantization/algorithms/weight_compression/awq_patterns.py
- nncf/quantization/algorithms/weight_compression/openvino_backend.py
- tests/openvino/native/models.py
- tests/openvino/native/quantization/test_weights_compression.py
This reverts commit ce29e75bed3a04655b19164a5977a55ff1e6062f.
failed nightly job on this line: 
https://github.com/openvinotoolkit/nncf/pull/2676/files#diff-4a7f9b3bb3ddee6bd4454ed1fed4d1f0ad01557b206c1e09959392fef58222fdR16
> Revert "Andreyan/awq extention (#2676)"

- README.md
- examples/torch/README.md
- nncf/common/utils/decorators.py
- requirements-dev.txt
- setup.py
- tests/cross_fw/examples/test_examples.py
- tests/cross_fw/install/test_install.py
- tests/shared/helpers.py
- tests/shared/install_fixtures.py
- tests/torch/test_extensions_build.py
Remove extra dependencies to install backends from setup.py
Add [plots] extra dependencies to install optional packages to visualize plots.  
134503
> Removal of installation extras in setup.py

- examples/quantization_aware_training/torch/anomalib/main.py
`# nosec` is added because `urlretrieve` function is used with the hard code url
Suppress bandit issue
ref: 143381
build 862
> bandit happy

- tests/post_training/data/wc_reference_data.yaml
Update metric for tinyllama_data_aware_gptq_backend_OV
Wrong metric.
N/A
tinyllama_data_aware_gptq_backend_OV
> Update metric for tinyllama_data_aware_gptq_backend_OV

- nncf/common/plotting.py
Fix for import matplotlib
Runtime error during import nncf
Request from OpenVINO notebooks
N/A
> Fix for import matplotlib

- .github/workflows/api_changes_check.yml
- .github/workflows/build_and_publish_doc.yml
- .github/workflows/post_pr_merge.yml
- .github/workflows/precommit.yml
- use correct hash for 
- remove unused permissions: attestations: write
> [CI] fix GA workflows

- nncf/parameters.py
> Update doc links

- .github/workflows/post_pr_merge.yml
- .github/workflows/precommit.yml
Add coverage for PT and TF jobs
> [CI] Add coverage for pt and tf jobs

- nncf/experimental/tensor/tensor.py
- tests/shared/test_templates/template_test_nncf_tensor.py
Implement  __rpow__ for Tensor
143943
TemplateTestNNCFTensorOperators :: test_operators_int_rev
> Implement  __rpow__ for Tensor

- ReleaseNotes.md
(cherry picked from commit 9200a22fad8c79f68919f40a21c54179d7354504)
> [Release] Release notes v2.11 (#2710)

- docs/usage/post_training_compression/weights_compression/Usage.md
Added GPTQ documentation
126887
N/A
> GPTQ documentation

- tests/openvino/native/quantization/test_graphs.py
- tests/openvino/native/quantization/test_weights_compression.py
- tests/openvino/native/test_model_transformer.py
- tests/openvino/native/test_smooth_quant.py
- tests/openvino/native/test_statistic_collector.py
- tests/post_training/test_templates/test_smooth_quant.py
- tests/torch/ptq/test_statistic_collector.py
- tests/torch/sparsity/movement/test_model_saving.py
- Revised `xfailed` tests.
- Absence of the revision for tests at all.
- N/A
- N/A
> Tests revision

- tests/post_training/data/wc_reference_data.yaml
> Update WC metric values

- tests/onnx/requirements.txt
- tests/post_training/requirements.txt
- tests/torch/models_hub_test/requirements.txt
Bump version of scikit-learn
144479
> Bump version of scikit-learn

- nncf/quantization/algorithms/weight_compression/weight_lowering.py
Speed ​​up `decompressed_weight` calculations in the `do_dequantization` function
> Fix do_dequantization func

- nncf/quantization/algorithms/min_max/torch_backend.py
- nncf/torch/graph/operator_metatypes.py
- tests/post_training/test_templates/helpers.py
- tests/torch/data/reference_graphs/quantized/ptq/symmetric/scaled_dot_product_attention_model.dot
- tests/torch/ptq/test_graphs.py
Add PTScaledDotProductAttentionMetatype
130925
> [PT] Support scaled_dot_product_attention 

- nncf/parameters.py
- nncf/quantization/algorithms/weight_compression/algorithm.py
- nncf/quantization/algorithms/weight_compression/config.py
- nncf/quantization/algorithms/weight_compression/mixed_precision.py
- nncf/quantization/algorithms/weight_compression/openvino_backend.py
- nncf/quantization/algorithms/weight_compression/weight_lowering.py
- nncf/quantization/quantize_model.py
- tests/openvino/native/quantization/test_weights_compression.py
Support e2m1 as type for weight compression.
e2m1 compression.
CVS-140944
> E2M1 compression.

- nncf/onnx/graph/node_utils.py
- nncf/openvino/graph/layout.py
- nncf/openvino/graph/node_utils.py
- nncf/quantization/algorithms/bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/algorithm.py
- nncf/quantization/algorithms/fast_bias_correction/backend.py
- nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
- nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
- nncf/quantization/algorithms/fast_bias_correction/torch_backend.py
- tests/onnx/test_layer_attributes.py
- tests/onnx/test_node_utils.py
- tests/openvino/native/data/2024.1/reference_scales/MatMul2DModel_mixed.json
- tests/openvino/native/data/2024.1/reference_scales/MatMul2DModel_performance.json
- tests/openvino/native/models.py
- tests/openvino/native/test_layer_attributes.py
This reverts commit beb9c0447a7c86b5aa427cad6744ca0f0dc373ae.
post_training_quantization/415 - running
> Revert "Update Fast-/BC algorithms (#2747)"

- .github/workflows/nightly.yml
- .github/workflows/pre-commit-linters.yml
- md_dead_link_check.toml
- Bump to 0.9
- Add config file for link checker
> Ignore ReleaseNotes.md by link checker

- docs/Algorithms.md
- docs/usage/post_training_compression/weights_compression/Usage.md
Added short MXFP4 (e2m1, e8m0) description to docs.
> Updated docs with MXFP4 (e2m1, e8m0) information.

- nncf/openvino/graph/metatypes/openvino_metatypes.py
- tests/openvino/native/models.py
- tests/openvino/native/test_metatypes.py
PReLU -> PRelu
Bad performance due to not matching HW patterns.
Before and after 
144218
Mannualy
> [OpenVINO] Fix PRelu type name

- tests/post_training/pipelines/lm_weight_compression.py
Disable dynamic quantization in the lm_weight_compression
Alignment with openvino-nightly
ref: 144846
N/A
> [TEST] Turn off dynamic quantization in the lm_weight_compression

- tests/post_training/data/wc_reference_data_2024.4.yaml
build 17 has another metrics for 2024.4
n/a
build 20
> added references for 2024.4 nightly

- setup.py
- tests/common/data/reference_graphs/dot_rw_reference.dot
Set upper limit for pydot version 3.0.0
Pydot 3.0.0 broke saving and loading with special characters
> Set upper limit for pydot version 3.0.0

- examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
- tests/cross_fw/examples/run_example.py
Follow-up #2800
Enable progress bar in the example for users
N/A
test examples - 458
> Reduce test_examples logs

- nncf/openvino/graph/model_transformer.py
- Fixed shared memory warnings issue.
- Reverted cast for data type while creating constant.
- Leftover from #2307.
- Bugfix.
- 147255
- N/A
> Fix shared_memory issue with cast

- nncf/openvino/graph/model_transformer.py
- tests/post_training/test_templates/helpers.py
- Fixed `model_extraction_command` issue introduced in #2307.
- Bugfix.
- 147065
- Updated
> Fix for model transformer command

- nncf/version.py
- Bumped NNCF version due to release.
- Release activities.
- 146856
- N/A
> Bump NNCF version

- ReleaseNotes.md
(cherry picked from commit c62c3ab2fccb6e40219e0b5fbfe85312fd642970)
> Update ReleaseNotes.md (#2837)

- tests/post_training/data/wc_reference_data.yaml
- tests/post_training/data/wc_reference_data_2024.3.yaml
Updated weight compression metrics regarding to OpenVINO 2024.3
Bump up OpenVINO version
N/A
post_training_weight_compression/134/
> Updated weight compression metrics regarding to OpenVINO 2024.3

- nncf/quantization/algorithms/weight_compression/weight_lowering.py
- tests/openvino/native/quantization/test_gptq.py
Follow-up #2790
1. 2.8x speed up of `calculate_signed_scale`
2. Simplification of test_gptq code.
N/A
post_training_weight_compression/135/
> Optimization of the "calculate_signed_scale" function

- tests/cross_fw/examples/example_scope.json
Updated metrics for llm example tests regarding to OpenVINO 2024.3
Bump up OpenVINO version
ref: 148833
test_examples/475/
> Updated metrics for llm example tests regarding to OpenVINO 2024.3

- .github/workflows/api_changes_check.yml
- .github/workflows/labeler.yml
- .github/workflows/post_pr_merge.yml
> [GA] pull_request

- .github/workflows/labeler.yml
revert to pull_request_target for labeler
Permission issue
> [GA] Fix labeler action

- nncf/quantization/algorithms/min_max/algorithm.py
- Remove the exception that was added in https://github.com/openvinotoolkit/nncf/pull/2802
- Regression
-148270
-149401
Current scope
> Replace the exception with a warning

- nncf/openvino/graph/metatypes/groups.py
- Reverts adding Slice as agnostic.
- Performance degradations.
- Lack of the support on the LPT side (https://github.com/openvinotoolkit/openvino/pull/26182).
- 149909
- 149011
- N/A
> Revert Slice as agnostic

- .github/workflows/api_changes_check.yml
- .github/workflows/api_set_label.yml
Add pr number to artifact from api check 
`github.event.workflow_run.pull_requests[0].number` is not available for PR from fork
> [GA] Fix set api label action

- .github/workflows/api_set_label.yml
> [GA] Fix path

- tests/tools/test_memory_monitor.py
Raise relative error threshold for memory monitor tool test
https://github.com/openvinotoolkit/nncf/actions/runs/10577143863/job/29304453353?pr=2903
> Raise error threshold

- docs/ModelZoo.md
Added link to HF compressed models
> Added link to HF compressed models

- tests/openvino/tools/calibrate.py
Extend NNCF logging by the device information where quantization was done
Ref: 150780
> Extend NNCF logging by the device information where quantization was done

- nncf/quantization/algorithms/layerwise/scheduler.py
- nncf/quantization/algorithms/weight_compression/activation_stats.py
- nncf/quantization/algorithms/weight_compression/algorithm.py
- nncf/quantization/algorithms/weight_compression/gptq.py
- nncf/quantization/algorithms/weight_compression/scale_estimation.py
- nncf/quantization/quantize_model.py
- tests/openvino/native/quantization/test_gptq.py
- tests/openvino/native/quantization/test_weights_compression.py
> Support the scale estimation inside GPTQ

- docs/usage/post_training_compression/weights_compression/Usage.md
> Accuracy/Footprint trade-off with different int4 compression algorithms.

- docs/usage/post_training_compression/weights_compression/Usage.md
PR #2941 to release branch
150857
> Accuracy/Footprint trade-off with different int4 compression algorithm

- tests/post_training/data/ptq_reference_data.yaml
- tests/post_training/model_scope.py
Add ignored scope mobielenet_v3 torchvision
Ignore SE block
150204
150952
> [TESTS] add ignored scope for mobielenet_v3 torchvision

- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
Set num_workers = 0
Segmentation fault
Ref: 151081
> Fix segmentation fault

- tests/post_training/data/wc_reference_data_2024.4.yaml
- tests/post_training/data/wc_reference_data_2024.5.yaml
same as in https://github.com/openvinotoolkit/nncf/pull/2954
> Added similarity for weight compression with 2024.4

- tests/post_training/data/wc_reference_data_2024.4.yaml
- tests/post_training/data/wc_reference_data_2024.5.yaml
same as in https://github.com/openvinotoolkit/nncf/pull/2954
> Added similarity for weight compression with 2024.4 (#2958)

- tests/tools/test_memory_monitor.py
Update threshold
https://github.com/openvinotoolkit/nncf/actions/runs/10793346745/job/29935059876
> Increase threshold for test_memory_values_isolated

- nncf/quantization/advanced_parameters.py
- tests/cross_fw/examples/conftest.py
- tests/cross_fw/examples/run_example.py
- tests/cross_fw/examples/test_examples.py
added --data option for test examples
Request from the CI
ref: 151116
> data option for test examples

- docs/usage/post_training_compression/weights_compression/Usage.md
Updated Usage.md for GPTQ and Scale Estimation
Updating documentation
ref: 143637
N/A
> Updated Usage.md for GPTQ and Scale Estimation

- ReleaseNotes.md
(cherry picked from commit 01e2cb484a8907ef8f817be49a319ae3e7974a7e)
> Update ReleaseNotes.md (#2940)

- nncf/common/quantization/quantizer_propagation/solver.py
- nncf/common/quantization/quantizer_propagation/structs.py
- nncf/quantization/advanced_parameters.py
- nncf/quantization/algorithms/hyperparameter_tuner/param_grid.py
- nncf/quantization/algorithms/min_max/algorithm.py
- nncf/quantization/algorithms/post_training/pipeline.py
- tests/common/hyperparameter_tuner/test_hyperparameter_tuner.py
- tests/common/quantization/test_quantizer_propagation_solver.py
- tests/torch/quantization/test_adjust_padding.py
Add propagation_strategy in AdvancedQuantizationParameters
To be able to control merging behavior in PTQ
153028
> [PTQ] Add option for merging quantizers strategy in advanced parameters

- nncf/experimental/common/tensor_statistics/collectors.py
- nncf/onnx/statistics/collectors.py
- nncf/quantization/algorithms/smooth_quant/torch_backend.py
- nncf/quantization/algorithms/smooth_quant/torch_fx_backend.py
- nncf/torch/tensor_statistics/collectors.py
- tests/common/experimental/test_statistic_collector.py
- tests/onnx/quantization/test_reducers_and_aggregators.py
- tests/torch/ptq/test_reducers_and_aggregators.py
* `get_inplace_fn` is not abstract method anymore
* Redundant code is removed
* To remove redundant code
> [experimental][collectors] Redundant code is removed

- nncf/quantization/algorithms/weight_compression/gptq.py
- nncf/quantization/algorithms/weight_compression/scale_estimation.py
> Move `activations_to_wc_statistics` to SE class

- docs/api/source/conf.py
- examples/tensorflow/classification/main.py
- examples/tensorflow/common/optimizer.py
- examples/tensorflow/requirements.txt
- nncf/tensor/README.md
- nncf/tensorflow/accuracy_aware_training/runner.py
- tests/tensorflow/requirements.txt
- tests/tensorflow/sparsity/rb/test_integration.py
Remove tensorflow_addons dependency.
tensorflow_addons  was deprecated
- Ref: 155320
Current scope
> Remove tensorflow_addons

- tests/tensorflow/test_sota_checkpoints.py
Set pythonpath in tests/tensorflow/test_sota_checkpoints.py
> Fix e2e_tf 

- nncf/quantization/algorithms/weight_compression/mixed_precision.py
- nncf/quantization/quantize_model.py
- tests/post_training/data/wc_reference_data_2024.5.yaml
- tests/post_training/model_scope.py
- tests/post_training/test_quantize_conformance.py
- tests/torch/fx/test_compress_weights.py
- tests/torch/ptq/test_weights_compression.py
Data-free mixed precision algorithm for Torch and Torch FX backends
For more accurate weight compression
ref: 153918
NNCF/job/manual/job/post_training_weight_compression/228
> Data-free mixed precision algorithm for Torch and Torch FX backends

- tests/post_training/data/wc_reference_data_2024.5.yaml
Remove `tinyllama_data_aware_gptq_backend_OV` reference metrics 
The test was removed.
N/A
N/A
> [left over] Update weight compression metrics

- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- tests/cross_fw/examples/run_example.py
- Check dataset before extract
- Use `setuptools<72.1` to avoid issue on build torch extension
> Fix windows test example

- nncf/experimental/common/tensor_statistics/collectors.py
- nncf/openvino/statistics/collectors.py
- nncf/quantization/algorithms/weight_compression/mixed_precision.py
- nncf/quantization/algorithms/weight_compression/openvino_backend.py
- tests/cross_fw/test_templates/test_weights_compression_backends.py
- tests/openvino/native/quantization/test_weights_compression.py
- tests/openvino/native/quantization/test_weights_compression_backends.py
Fix bug with passing subset_size
Add a test for backend methods
> Fix hessian criteria statistics collector

- tests/tensorflow/sota_checkpoints_eval.json
Update thresholds for yolo_v4_coco
Different values for NNCF/weekly/e2e_tf_2.12.1 and  NNCF/nightly/tf_full (see NNCF/nightly/tf_full: Build # 808,  NNCF/weekly/e2e_tf_2.12.1: Build # 37)
> Update thresholds for yolo_v4_coco

- tests/tensorflow/sota_checkpoints_eval.json
https://github.com/openvinotoolkit/nncf/pull/3070
> [release_v2140] Update thresholds for yolo_v4_coco

- tests/openvino/native/quantization/test_gptq.py
Added modification note
Legal requirements
N/A
N/A
> Added modification note

- tests/openvino/native/quantization/test_gptq.py
[pr 3089](https://github.com/openvinotoolkit/nncf/pull/3089)
> [Release] Added modification note

- docs/usage/post_training_compression/weights_compression/Usage.md
Added new note for statistics caching
157343
NA
> Added a note for statistics caching

- docs/usage/post_training_compression/weights_compression/Usage.md
> [Release] Added a note for statistics caching

- nncf/common/tensor_statistics/statistics_serializer.py
- As stated in the title.
- Fix after #3017.
- 157068
- Manual
> [Release] Update to use safe_open

- ReleaseNotes.md
- (cherry picked from commit 5279634b43bdf11054f4ddd6ff67c48b9b80a6cc)
-  Updated incorrect links (examples, notebooks)
> Update ReleaseNotes.md (#3071)

- tests/torch/sota_checkpoints_eval.json
(cherry picked from commit d637ce7612cae975e964001a35a660c16cff7f94)
> [PT] update metrics for openvino 2024.5.0 (#3084)

- tests/cross_fw/test_templates/test_quantizer_config.py
Redundant code is removed from `tests/cross_fw/test_templates/test_quantizer_config.py`
To decrease amount of code in tests
> [Tests] A redundant code is removed

- nncf/tensor/__init__.py
- nncf/tensor/definitions.py
Removed TensorBackendType.
Got TensorBackendType and TensorBackend with the same definition
> remove unused class

- examples/llm_compression/openvino/smollm2_360m_fp8/main.py
- examples/llm_compression/openvino/smollm2_360m_fp8/requirements.txt
Workaround for issue https://github.com/huggingface/optimum-intel/issues/993
> Fix imports in FP8 example

- README.md
- docs/Installation.md
Update readme.md and installation.md
> Update readme and installation

- tests/cross_fw/examples/requirements.txt
Fix missed numpy for tests/cross_fw/examples
https://github.com/openvinotoolkit/nncf/actions/runs/12157799068
> Fix missed numpy requirements for cross_fw

- pyproject.toml
added datasets to the known third party for isort
Improve DevEx
https://github.com/openvinotoolkit/nncf/pull/3091
N/A
> [DevEx] Fix for make pre-commit

- .github/workflows/macos.yml
- .github/workflows/precommit.yml
- nncf/common/utils/os.py
- tests/openvino/native/quantization/test_reducers_and_aggregators.py
- tests/openvino/native/test_fast_bias_correction.py
Introduce tests on MacOS in weakly scope
- precommit / common
- precommit / openvino
> [GHA] macos

- .github/workflows/examples.yml
Add windows for test examples
153650
> [GHA] examples on windows

- docs/PyPiPublishing.md
https://github.com/openvinotoolkit/nncf/pull/3133
> Fix badge link in PyPiPublishing.md

- .github/workflows/examples.yml
`!github.event.inputs.skip_windows` always false
> [GHA] fix condition for example 

- nncf/common/quantization/quantizer_removal.py
- Fixed AAQ algo propagation for quantizable types.
- Bugfix.
- https://github.com/openvinotoolkit/nncf/issues/3118
- TBD
> Fix AAQ propagation

- nncf/torch/dynamic_graph/patch_pytorch.py
Cherry-pick https://github.com/openvinotoolkit/nncf/pull/3139
> changed the signature of the torch compile wrarpper function (#3139)

- docs/api/source/conf.py
- nncf/common/utils/api_marker.py
https://github.com/openvinotoolkit/nncf/pull/3099
> Fix annotation for api marker (#3099)

- docs/usage/post_training_compression/weights_compression/Usage.md
Upd docs after https://github.com/openvinotoolkit/nncf/pull/3122
> [DOCS] Update note statistics caching

- ReleaseNotes.md
(cherry picked from commit bd61081e8d6b3fb88ebd0947a52c916b8e7b2ed6)
> Release notes update (#3145)

- docs/Installation.md
- docs/PyPiPublishing.md
- Cherry-picked #3133.
- Partially cherry-picked #3111.
- Fix tests
- Release
- 159303
- N/A
> [Release] Fix docs

- .github/workflows/examples.yml
add for step create summary
pip install defusedxml==0.7.1
https://github.com/openvinotoolkit/nncf/actions/runs/12383825698/job/34567280129
> [GHA] fix test examples action

- pyproject.toml
- tests/onnx/requirements.txt
Remove tqdm from dependencies
https://github.com/openvinotoolkit/nncf/pull/2162
Not used in nncf, rich used instead
> Remove tqdm from dependencies

- nncf/common/accuracy_aware_training/training_loop.py
- nncf/config/config.py
- nncf/config/extractors.py
- nncf/config/schema.py
- nncf/config/schemata/algo/quantization.py
- nncf/config/schemata/basic.py
- nncf/config/schemata/experimental_schema.py
- nncf/config/structures.py
- pyproject.toml
Enable mypy check for `nncf/config`
> [mypy] nncf/config

- nncf/errors.py
- nncf/parameters.py
- nncf/scopes.py
- pyproject.toml
Enable mypy check for `nncf/*py`
> [mypy] nncf/*py

- .git-blame-ignore-revs
Ignore commits with updating copyright by blame
https://github.com/openvinotoolkit/nncf/pull/3174
> Ignore commits with updating copyright in blame

- .github/workflows/api_changes_check.yml
- .github/workflows/build_html_doc.yml
- .github/workflows/examples.yml
- .github/workflows/install.yml
- .github/workflows/macos.yml
- .github/workflows/nightly.yml
- .github/workflows/weekly.yml
- Call scheduled jobs from nightly and weekly actions
- Set timeout for some jobs
- Disable scheduled jobs for forks
155528
nightly - https://github.com/openvinotoolkit/nncf/actions/runs/12522007368
weekly - https://github.com/openvinotoolkit/nncf/actions/runs/12522007372
> [GHA] trigger for scheduled jobs

- nncf/common/quantization/initialization/range.py
- nncf/common/quantization/quantizer_propagation/graph.py
- nncf/common/quantization/quantizer_propagation/grouping.py
- nncf/common/quantization/quantizer_propagation/solver.py
- nncf/common/quantization/quantizer_setup.py
- nncf/common/quantization/structs.py
- nncf/common/scopes.py
- nncf/common/utils/dot_file_rw.py
- pyproject.toml
Enable mypy for part of files in nncf/common/quantization
> [mypy] nncf/common/quantization (part 2)

- tests/post_training/README.md
- tests/post_training/data/wc_reference_data_2025.0.yaml
- tests/post_training/experimental/sparsify_activations/pipelines.py
- tests/post_training/pipelines/base.py
- tests/post_training/pipelines/causal_language_model.py
- tests/post_training/pipelines/gpt.py
- tests/post_training/pipelines/image_classification_base.py
- tests/post_training/pipelines/lm_weight_compression.py
- tests/post_training/pipelines/masked_language_modeling.py
Mark as xfail PTWC torch tests counting number of int4/int8 ops. 
starting from OV 2025 ZP is represented as f16 in some cases (bug: 160006)
159993
160006
> xfail for bug with f16 zp

- tests/post_training/README.md
- tests/post_training/data/wc_reference_data_2025.0.yaml
- tests/post_training/experimental/sparsify_activations/pipelines.py
- tests/post_training/pipelines/base.py
- tests/post_training/pipelines/causal_language_model.py
- tests/post_training/pipelines/gpt.py
- tests/post_training/pipelines/image_classification_base.py
- tests/post_training/pipelines/lm_weight_compression.py
- tests/post_training/pipelines/masked_language_modeling.py
#3220 to release branch.
Mark as xfail PTWC torch tests counting number of int4/int8 ops. 
starting from OV 2025 ZP is represented as f16 in some cases (bug: 160006)
159993
160006
> xfail for bug with f16 zp (#3220)

- nncf/experimental/torch2/function_hook/nncf_graph/__init__.py
Add __init__.py for `nncf/experimental/torch2/function_hook/nncf_graph/` to ensure installtion of this directory when using pip
> [Common] Add init file to ensure installation

- tests/post_training/pipelines/base.py
Fix microbug in an if statement
PTQ/job/ptq_single_model/14500/
> [Conformance] Microfix

- nncf/common/utils/backend.py
Follow-up to #3233 . Fix an issue arising during documentation building. 
Caught here: https://github.com/openvinotoolkit/nncf/actions/runs/13131916886/job/36638718655 . This test is run on PRs to develop only. That's why it was not caught during merging to release branch.
https://github.com/openvinotoolkit/nncf/actions/runs/13132576726/job/36640708447?pr=3246
> [Release] Parse OV version on demand

- nncf/common/utils/backend.py
- nncf/common/utils/cpu_info.py
- nncf/common/utils/helpers.py
- nncf/openvino/optimized_functions/models.py
- pyproject.toml
- tests/common/utils/test_helpers.py
Copy of #3233 and #3247 to develop branch
> Set environment variable on LNL CPUs before compression model compilation

- tests/post_training/data/wc_reference_data_2025.0.yaml
The same bug as in https://github.com/openvinotoolkit/nncf/pull/3220
159993
> [TORCH] Add xfail for conformance

- README.md
- docs/usage/training_time_compression/quantization_aware_training/Usage.md
- examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
- examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
- nncf/tensorflow/__init__.py
- nncf/tensorflow/helpers/model_creation.py
- nncf/tensorflow/quantization/algorithm.py
- nncf/tensorflow/quantization/quantize_model.py
- nncf/tensorflow/utils/state.py
- nncf/torch/model_creation.py
> Update TF QAT docs. Deprecate TF create_compressed_model method (#3217)

- nncf/tensor/functions/__init__.py
> Fix openvino numeric import

- docs/PyPiPublishing.md
Add TorchFX backend in the PyPiPublishing.md
Alignment with README.md
> Add TorchFX backend in the PyPiPublishing.md

- .github/dependabot.yml
Enable dependabot for github actions
> [GHA] dependabot for github-actions

- .pre-commit-config.yaml
- docs/styleguide/PyGuide.md
- examples/post_training_quantization/torch/ssd300_vgg16/main.py
- nncf/experimental/torch/nas/bootstrapNAS/elasticity/multi_elasticity_handler.py
- pyproject.toml
- tests/cross_fw/sdl/fuzz/quantize_api.py
- tests/torch2/function_hook/quantization/test_quantized_graphs.py
Use ruff isort instead of direct isort
> [ruff] isort

- pyproject.toml
- tools/requirements.txt
Remove upper bound for matplotlib
> Remove upper bound for matplotlib

- .github/dependabot.yml
> Enable dependabot for python

- tests/post_training/data/wc_reference_data.yaml
- tests/post_training/data/wc_reference_data_2025.0.yaml
manual/job/post_training_weight_compression/328
> [TESTS] Remove tinyllama_scale_estimation_group_size_64 from reference

- .github/dependabot.yml
set open-pull-requests-limit 10
> [gha] set open-pull-requests-limit 10

- nncf/experimental/torch2/function_hook/serialization.py
- tests/torch2/function_hook/helpers.py
- tests/torch2/function_hook/test_serialization.py
Implement `get_config` and `load_from_config` function for new tracing
Analog https://github.com/openvinotoolkit/nncf/pull/2531
152996
tests/torch2/function_hook/test_serialization.py
> [PT2]  Serialize and load transformations

- tests/cross_fw/examples/test_examples.py
Retry run example on connection errors
https://github.com/openvinotoolkit/nncf/actions/runs/13585977596
> [ci] retry examples tests on connection errors

- .github/workflows/examples.yml
> Fix typo in github/workflows/examples

- nncf/experimental/torch2/function_hook/hook_executor_mode.py
- nncf/torch/dynamic_graph/context.py
- nncf/torch/dynamic_graph/patch_pytorch.py
- tests/torch2/data/function_hook/disable_tracing/graph.dot
- tests/torch2/function_hook/test_disable_tracing.py
- tests/torch2/function_hook/test_train.py
Add context manager to disable tracing for some part of code in a model
> [PT2] Context manager to disable tracing

- constraints.txt
- examples/llm_compression/openvino/smollm2_360m_fp8/requirements.txt
- examples/llm_compression/openvino/tiny_llama/requirements.txt
- examples/llm_compression/openvino/tiny_llama_find_hyperparams/requirements.txt
- examples/llm_compression/openvino/tiny_llama_synthetic_data/requirements.txt
- examples/llm_compression/torch/qat_with_lora/requirements.txt
- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- examples/post_training_quantization/torch_fx/resnet18/requirements.txt
- examples/quantization_aware_training/tensorflow/mobilenet_v2/requirements.txt
- examples/quantization_aware_training/torch/resnet18/requirements.txt
- tests/cross_fw/examples/test_examples.py
- tests/post_training/requirements.txt
- As stated in the title
- Upcoming release
- 164968
- https://github.com/openvinotoolkit/nncf/actions/runs/14108886939 - passed
> [Release_v2160] Updated OpenVINO & WWB versions

- nncf/common/strip.py
- nncf/experimental/torch2/function_hook/hook_executor_mode.py
- nncf/experimental/torch2/function_hook/hook_storage.py
- nncf/experimental/torch2/function_hook/nncf_graph/nncf_graph_builder.py
- nncf/experimental/torch2/function_hook/serialization.py
- nncf/experimental/torch2/function_hook/strip.py
- nncf/torch/strip.py
- tests/torch2/function_hook/nncf_graph/test_nncf_graph.py
- tests/torch2/function_hook/quantization/test_quantized_graphs.py
- tests/torch2/function_hook/quantization/test_strip.py
- tests/torch2/function_hook/test_hook_storage.py
Implement replace_quantizer_to_torch_native_module for new tracing
Add method named_hooks to HookStorage
Change nncf.strip signature, added example_input that required to build graph.
152996
> [PT2] strip

- tests/post_training/data/ptq_reference_data.yaml
[Release260][TorchFX] Xfails are removed from the conformance test
Issue 162009 is fixed
NNCF/job/manual/job/post_training_quantization/640/ - in progress
> [Release2160][TorchFX] Xfails are removed from the conformance test

- nncf/torch/quantization/strip.py
- tests/torch/quantization/test_strip.py
Co-authored-by: Lyalyushkin Nikolay <nikolay.lyalyushkin@intel.com>
(cherry picked from commit 4c45b5727a6a75c9ddb592b1e67fbb7ab2d361e9)
> [Release_v2160] Minor strip updates (#3402)

- .github/workflows/examples.yml
- examples/llm_compression/torch/qat_with_lora/main.py
- examples/llm_compression/torch/qat_with_lora/requirements.txt
- nncf/quantization/advanced_parameters.py
- nncf/torch/quantization/layers.py
- tests/cross_fw/examples/.test_durations
- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/run_example.py
- tests/cross_fw/examples/test_examples.py
Added sample with QAT + absorbable LoRA to test example on CUDA.
new job was introduced, since previous tests were launched on CPU only.
validation of the tuning sample
164755
https://github.com/openvinotoolkit/nncf/actions/runs/14261388047/attempts/1#summary-39973579272
> Added qat lora sample to test_examples

- .github/workflows/examples.yml
- examples/llm_compression/torch/qat_with_lora/main.py
- examples/llm_compression/torch/qat_with_lora/requirements.txt
- nncf/quantization/advanced_parameters.py
- nncf/torch/quantization/layers.py
- tests/cross_fw/examples/.test_durations
- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/run_example.py
- tests/cross_fw/examples/test_examples.py
Added sample with QAT + absorbable LoRA to test example on CUDA. new job was introduced, since previous tests were launched on CPU only.
validation of the tuning sample
164755
https://github.com/openvinotoolkit/nncf/actions/runs/14261388047/attempts/1#summary-39973579272
> Added qat lora sample to test_examples (#3386)

- examples/llm_compression/openvino/smollm2_360m_fp8/main.py
- Simply changed the question to reach answer stability.
- Test robustness.
- 164968
- Release runs
- https://github.com/openvinotoolkit/nncf/actions/runs/14333587332
> [Release_v2160] FP8 example minor changes

- nncf/experimental/torch2/function_hook/strip.py
- nncf/quantization/algorithms/weight_compression/torch_backend.py
- nncf/torch/quantization/quantize_functions.py
- nncf/torch/quantization/strip.py
- tests/torch/quantization/test_strip.py
- tests/torch2/data/reference_graphs/compress_weights/fq_lora/shared_weights_all_layers_False.dot
- tests/torch2/data/reference_graphs/compress_weights/fq_lora/shared_weights_all_layers_True.dot
- tests/torch2/function_hook/quantization/strip/test_strip_dequantize.py
- tests/torch2/function_hook/quantization/strip/test_strip_native.py
- tests/torch2/function_hook/quantization/test_fq_lora.py
- tests/torch2/requirements.txt
Support strip for dequantize format on new tracing
152996
> [PT2] strip for dequantize format

- examples/llm_compression/openvino/smollm2_360m_fp8/main.py
(cherry picked from commit 816ad85760d18b5863c95d330b111999cdf0f263)
https://github.com/openvinotoolkit/nncf/actions/runs/14337818742 - passed
> FP8 example minor changes (#3414)

- constraints.txt
- examples/llm_compression/openvino/smollm2_360m_fp8/requirements.txt
- examples/llm_compression/openvino/tiny_llama/requirements.txt
- examples/llm_compression/openvino/tiny_llama_find_hyperparams/requirements.txt
- examples/llm_compression/openvino/tiny_llama_synthetic_data/requirements.txt
- examples/llm_compression/torch/qat_with_lora/requirements.txt
- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- examples/post_training_quantization/torch_fx/resnet18/requirements.txt
- examples/quantization_aware_training/tensorflow/mobilenet_v2/requirements.txt
- examples/quantization_aware_training/torch/resnet18/requirements.txt
- tests/cross_fw/examples/test_examples.py
- tests/post_training/requirements.txt
- As stated in the title
- Release
- 164968
- Release runs
> [Release_v2160] Bump OV version

- .github/workflows/call_precommit.yml
- tests/torch2/function_hook/quantization/test_fq_lora.py
- tests/torch2/requirements.txt
Add precommit job for pytorch2 on cuda
> [gha] add precommit job for pytorch2 on cuda

- pyproject.toml
Updated email in pyproject.toml
> Minor update pyproject.toml

- tests/torch/ptq/test_fq_lora.py
- tests/torch2/function_hook/quantization/test_fq_lora.py
replaced a model from HF with a synthetic one in tests
to avoid sporadic errors in pre-commit with download
n/a
precommit
> no download from hf in test for checkpoint load

- tools/README.md
- tools/memory_monitor.py
> Add quotes to memory monitor command example

- .ci/cspell_dict.txt
- examples/llm_compression/torch/qat_with_lora/README.md
> Added results on wikitext for QAT + LoRA

- .github/workflows/precommit.yml
Add .ci to paths-ignore for precommit workflow
> Add .ci to paths-ignore for precommit workflow

- .github/workflows/precommit.yml
Stop running jobs on push new commits in PR
> [gha] cancel-in-progress for precommit

- tests/post_training/experimental/sparsify_activations/pipelines.py
As in the description.
NNCF/job/weekly/job/sparsify_activations_conformance/50
> Fix activation sparsity conformance test fp32 model saving

- nncf/onnx/graph/metatypes/groups.py
- nncf/onnx/graph/metatypes/onnx_metatypes.py
- nncf/openvino/graph/metatypes/groups.py
- nncf/openvino/graph/metatypes/openvino_metatypes.py
- nncf/torch/graph/operator_metatypes.py
- nncf/torch/graph/pattern_operations.py
> Add SELU activation metatype

- .github/workflows/sdl.yml
> [sdl] set severity all for trivy

- docs/Installation.md
Alignments with constraints.txt
> Fix version of torch and tf in doc

- .github/workflows/call_precommit.yml
- .github/workflows/nightly.yml
Move TF tests to nightly scope
> Move TF tests to nightly scope

- tests/onnx/test_external_data.py
- Disable test_not_accessible for Windows
> Disable test_not_accessible for Windows

- tests/torch/quantization/test_hawq_precision_init.py
Change atol 
After moving tests to nightly scope. changed device
> Fix pt nightly

- nncf/tensor/functions/tf_numeric.py
NNCF tensor atleast_1d implementation in TensorFlow backend
https://github.com/openvinotoolkit/nncf/actions/runs/14918548607/job/41919358385
> [TF] NNCF tensor atleast_1d implementation

- examples/llm_compression/torch/qat_with_lora/custom_eval_tasks/preprocess_wikitext.py
- examples/llm_compression/torch/qat_with_lora/custom_eval_tasks/wikitext_validation.yaml
- examples/llm_compression/torch/qat_with_lora/main.py
- examples/llm_compression/torch/qat_with_lora/requirements.txt
- nncf/parameters.py
- nncf/torch/function_hook/hook_storage.py
- nncf/torch/function_hook/strip.py
- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/run_example.py
- tests/cross_fw/examples/test_examples.py
- tests/torch2/function_hook/quantization/strip/test_strip_in_place.py
- tests/torch2/function_hook/test_hook_storage.py
Changed evaluation and selection of the best checkpoint in QAT + absorbable LoRA.
Now it selects the best checkpoint on validation split of wikitext and make a final validation in OpenVINO on test split of wikitext.
One step towards integration to Optimum and faster evaluation on GPU.
165735
test_examples - https://github.com/openvinotoolkit/nncf/actions/runs/14997415198
> QAT + LoRA sample on wikitext

- nncf/common/hardware/configs/gpu.json
- nncf/quantization/algorithms/min_max/algorithm.py
- tests/common/quantization/test_minmax.py
- tests/common/test_hardware_config.py
Mapping GPU target device to CPU for a8w8
Alignment between GPU and CPU for a8w8
N/A
test_target_device
test_device_configuration_alignment
> Explicit mapping GPU target device to CPU for a8w8

- examples/llm_compression/torch/qat_with_lora/custom_eval_tasks/preprocess_wikitext.py
> Added note about copy-pasted code with MIT license

- .ci/cspell_dict.txt
- CONTRIBUTING.md
- examples/llm_compression/torch/qat_with_lora/custom_eval_tasks/preprocess_wikitext.py
- licensing/third-party-programs.txt
- nncf/torch/automl/agent/ddpg/memory.py
- tests/openvino/native/quantization/test_gptq.py
- tests/torch/automl/test_memory.py
- tests/torch/automl/test_ring_buffer.py
- tests/torch/nas/models/tcn.py
- tests/torch/test_models/swin.py
Legal requirements
https://github.com/openvinotoolkit/nncf/pull/3502
https://github.com/openvinotoolkit/nncf/pull/3089
> added license for autogptq and lm_eval

- examples/llm_compression/torch/qat_with_nls_downstream/main.py
removed dependency from another sample
can run sample without setting PYTHONPATH
n/a
test_examples - https://github.com/openvinotoolkit/nncf/actions/runs/15190626862
CC: @jpablomch
> Made NLS sample self-contained

- tests/torch/data/search_building_block/vit.json
- tests/torch/sparsity/movement/helpers/trainer.py
- tests/torch/sparsity/movement/test_training.py
> Fix tests for transformers==4.51.3

- .ci/cspell_dict.txt
- README.md
Used by section is extended with Ultralytics, ExecuTorch and torch.compile integrations
> [README] Used by section is extended

- tests/onnx/quantization/test_weights_compression.py
Follow up for https://github.com/openvinotoolkit/nncf/pull/3525
> Follow up # 3525

- .github/scripts/pytest_md_summary.py
Remove coloring by latex in summary
No supporting now
> [gha] Remove coloring by latex in summary

- constraints.txt
- examples/llm_compression/onnx/tiny_llama/requirements.txt
- examples/llm_compression/openvino/smollm2_360m_fp8/requirements.txt
- examples/llm_compression/openvino/tiny_llama/requirements.txt
- examples/llm_compression/openvino/tiny_llama_find_hyperparams/requirements.txt
- examples/llm_compression/openvino/tiny_llama_synthetic_data/requirements.txt
- examples/llm_compression/torch/distillation_qat_with_lora/requirements.txt
- examples/llm_compression/torch/downstream_qat_with_nls/requirements.txt
- examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/openvino/mobilenet_v2/requirements.txt
- examples/post_training_quantization/openvino/yolov8/requirements.txt
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
- examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
- examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
- examples/post_training_quantization/torch_fx/resnet18/requirements.txt
- examples/quantization_aware_training/tensorflow/mobilenet_v2/requirements.txt
- examples/quantization_aware_training/torch/resnet18/requirements.txt
- tests/cross_fw/examples/test_examples.py
- tests/post_training/requirements.txt
> [release_v2170] Updated OV 

- tests/post_training/pipelines/fx_modelling.py
- tests/post_training/pipelines/lm_weight_compression.py
Correct initilize of  `FXAutoModelForCausalLM)` that requared 3 arguments
Rework if conditions 
https://github.com/openvinotoolkit/nncf/actions/runs/15469026916
> [fx] Fix conformance test

- tests/onnx/quantization/test_weights_compression.py
- tests/openvino/optimized_functions/test_compression_functions.py
Cherry-pick commits with fix tests
> [Release 2.17.0] Cherry-pick commits with fix tests

- .github/workflows/call_precommit.yml
- .github/workflows/call_precommit_windows.yml
- .github/workflows/examples.yml
- .github/workflows/install.yml
Use windows-2025 runner
Remove `nvcc --version ` that raise error in summary
Disabled windows-2019
> [ci] windows-2025 

- examples/llm_compression/onnx/tiny_llama/requirements.txt
Add missing onnxruntime requirement
https://github.com/openvinotoolkit/nncf/issues/3563
https://github.com/openvinotoolkit/nncf/issues/3563
> Add missing onnxruntime requirement

- examples/llm_compression/onnx/tiny_llama/README.md
- examples/llm_compression/openvino/smollm2_360m_codebook/README.md
- examples/llm_compression/openvino/smollm2_360m_fp8/README.md
- examples/llm_compression/openvino/tiny_llama/README.md
- examples/llm_compression/openvino/tiny_llama_find_hyperparams/README.md
- examples/llm_compression/openvino/tiny_llama_synthetic_data/README.md
- examples/llm_compression/torch/distillation_qat_with_lora/README.md
- examples/llm_compression/torch/downstream_qat_with_nls/README.md
- examples/post_training_quantization/onnx/mobilenet_v2/README.md
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/openvino/mobilenet_v2/README.md
- examples/post_training_quantization/openvino/yolov8/README.md
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/tensorflow/mobilenet_v2/README.md
- examples/post_training_quantization/torch/mobilenet_v2/README.md
- examples/post_training_quantization/torch/ssd300_vgg16/README.md
- examples/post_training_quantization/torch_fx/resnet18/README.md
- examples/quantization_aware_training/tensorflow/mobilenet_v2/README.md
- examples/quantization_aware_training/torch/anomalib/README.md
- examples/quantization_aware_training/torch/resnet18/README.md
updated readme to suggest a one-line installation of all required dependencies at once
minor UX improvement
n/a
test examples - https://github.com/openvinotoolkit/nncf/actions/runs/16442257929
> Single line installation step in samples

- tests/torch2/function_hook/quantization/test_fq_lora.py
simplified unit test for tuning after compression with FQ_LORA mode.
Removed dependency from hugging-face and optimum.
Test relies on outputs for external model, which might change with new versions of torch, transformers and etc.
171197
test_fq_lora_tuning
> Simplified test for FQLoRA

- .github/workflows/conformance_weight_compression.yml
- .github/workflows/mypy.yml
- .github/workflows/nightly.yml
Remove using `-e` for install nncf
> [gha] no use edit mode

- examples/llm_compression/torch_fx/tiny_llama/modelling.py
- examples/llm_compression/torch_fx/tiny_llama/requirements.txt
Update Example to use transformers==4.52.2
To match with the NNCF dependencies
171250
test pass: https://github.com/openvinotoolkit/nncf/actions/runs/16590851872
> [TorchFX][Example] Upgrade Transformers for Torch FX TinyLlama Example

- README.md
- docs/PyPiPublishing.md
- Provide an example command for export with optimum-cli.
- Move OTX to the last position.
> Update "Used by" readme section

- tests/cross_fw/examples/example_scope.json
- tests/cross_fw/examples/test_examples.py
set CUDA_VISIBLE_DEVICES="0"  for llm_compression_distillation_qat_with_lora example
Differ result with multi gpu
/weekly/job/openvino-nightly/job/test_examples/151
> [ci] set CUDA_VISIBLE_DEVICES for llm_compression_distillation_qat_with_lora example

- src/nncf/torch/function_hook/hook_executor_mode.py
- tests/torch2/function_hook/test_wrapper.py
Filter signature of forward function to exclude self argument before binding arguments.
For python < 3.10 in case of combination of decorated forward method and overriding by partial `inspect.signature` got differ behavior:
```
signature=<Signature (self, x: int) -> int>
#python3.10
signature=<Signature (x: int) -> int>
#python3.13
signature=<Signature (x: int) -> int>
```
171692
tests/torch2/function_hook/test_wrapper.py::test_wrapper
> [pt] Fix process_model_inputs for python3.9

- .github/workflows/precommit.yml
- tests/tensorflow/requirements.txt
Fixed version of tf packages in tests/tensorflow/requirements.txt
https://github.com/openvinotoolkit/nncf/actions/runs/17186508564/job/48756299266
Version of package differ from develop, in result of enabled `--pre` option
> [release_v2180] Fix version of TF packages 

- .github/workflows/precommit.yml
- src/nncf/openvino/cpu_info.py
* Added a new function `_get_cpu_architecture()` to retrieve the CPU's architecture using `ov.properties.device.architecture`.
* Updated the `is_arm_cpu()` function to use `_get_cpu_architecture()` instead of `_get_cpu_name()` for determining if the CPU is ARM-based, resulting in a more reliable check.
https://github.com/openvinotoolkit/nncf/actions/runs/17186509415/job/48756301432
Changed output of full_name property for macos https://github.com/openvinotoolkit/openvino/pull/31649/files
https://github.com/openvinotoolkit/nncf/actions/runs/17190083004/job/48764498315
https://github.com/openvinotoolkit/nncf/actions/runs/17190234113/job/48764865081
> [release_v2180] Update is_arm_cpu 

- src/nncf/torch/nncf_network.py
Revert change from https://github.com/openvinotoolkit/nncf/pull/3675
nightly/job/torch_nightly/664/
nightly/job/torch_nightly/665/
> [pt] fix nightly job

- src/nncf/quantization/range_estimator.py
RAW reducer/ HISTOGRAM aggregator and HISTOGRAM range estimator parameters set docstrings are introduced
To fill missed parameters in docstrings
> Range estimator: Histogram aggregator docstrings

- .github/workflows/weekly.yml
- README.md
- constraints.txt
- examples/llm_compression/onnx/tiny_llama/README.md
- examples/llm_compression/onnx/tiny_llama_scale_estimation/README.md
- examples/llm_compression/openvino/smollm2_360m_codebook/README.md
- examples/llm_compression/openvino/smollm2_360m_fp8/README.md
- examples/llm_compression/openvino/tiny_llama/README.md
- examples/llm_compression/openvino/tiny_llama_find_hyperparams/README.md
- examples/llm_compression/openvino/tiny_llama_synthetic_data/README.md
- examples/llm_compression/torch/distillation_qat_with_lora/README.md
- examples/llm_compression/torch/downstream_qat_with_nls/README.md
- examples/post_training_quantization/onnx/mobilenet_v2/README.md
- examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/openvino/mobilenet_v2/README.md
- examples/post_training_quantization/openvino/yolov8/README.md
- examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/README.md
- examples/post_training_quantization/tensorflow/mobilenet_v2/README.md
- examples/post_training_quantization/torch/mobilenet_v2/README.md
- examples/post_training_quantization/torch/ssd300_vgg16/README.md
- examples/post_training_quantization/torch_fx/resnet18/README.md
- examples/pruning/torch/resnet18/README.md
- examples/quantization_aware_training/tensorflow/mobilenet_v2/README.md
- examples/quantization_aware_training/tensorflow/mobilenet_v2/requirements.txt
- examples/quantization_aware_training/torch/anomalib/README.md
- examples/quantization_aware_training/torch/resnet18/README.md
- pyproject.toml
- src/nncf/torch/function_hook/hook_executor_mode.py
Set `requires-python = ">=3.10"` 
Python 3.9 reached end of life
> Disable support of python 3.9
