openvinotoolkit/nncf

testing_ci.txt

Reverts openvinotoolkit/nncf_pytorch#4

Revert "Revert "Revert "Revert "Testing CI Please Ignore""""

---

nncf/quantization/cuda/functions_cuda_kernel.cu
tests/quantization/test_functions.py

An error was made during simultaneous work on the CUDA kernels way
back in time, and the per activation channel quantization kernel
ended up calculating gradients for lower bound of quantization
incorrectly when the currently quantized value was lower than this
lower bound. This slipped through the tests because they themselves
were too lax and had epsilon values set incommensurably high compared
to the quantized values. Fixed this - also removed the negative range
tests because they will actually always fail with the fixed test setup
due to TuneRange function that is built into AsymmetricQuantize automatically
resetting the negative input_range to positive values.

Fix gradient calculation for quantization lower bound

---

tests/test_compression_training.py

Previous thresholds incorrectly tracked global best accuracy
instead of the best accuracy with full compression (i.e. sparsity)
applied.

Adjust compression training thresholds for sparsity

---

examples/classification/configs/quantization/mobilenet_v2_imagenet_int8.json
nncf/quantization/layers.py

Should fix per-channel MobileNetV2 starting at 0 accuracy

Fix symmetric quantizer per-channel init for max values close to 0

---

nncf/hw_config.py
nncf/quantization/algo.py
nncf/quantization/quantizer_propagation.py
tests/quantization/test_hw_config.py
tests/quantization/test_quantizer_propagation_solver.py

(except for the "any supported quantization for the ops in config
without specified quantizations", because they need config wildcarding,
to be implemented as a follow-up)

Make HW config parsing conform to the implicit rules

---

examples/classification/main.py
examples/object_detection/main.py
examples/semantic_segmentation/main.py

Hopefully this will make nightly compression training "eval" tests
more stable.

Use sequential sampling for evaluation across example scripts

---

nncf/quantization/quantizer_propagation.py
tests/helpers.py
tests/quantization/test_quantization_helpers.py
tests/quantization/test_scheduler.py
tests/test_backward_compat.py
tests/test_compression_training.py
tests/test_sanity_sample.py

Could fix the consequences of https://github.com/pytorch/pytorch/issues/39570

Set data loading workers to 0 across tests to force single process

---

nncf/dynamic_graph/graph_builder.py

Should reduce memory usage during create_compressed_model

Build graphs within the torch.no_grad() context

---

nncf/quantization/algo.py
nncf/quantization/layers.py
tests/helpers.py
tests/quantization/test_precision_init.py
tools/add_new_quantization_parameters.py

This is required to correctly export to ONNX a checkpoint from the staged quantization regardless of the specified config and scheduler.

Introduced `enabled` parameter to Quantizers

---

nncf/quantization/layers.py
nncf/quantization/quantize_functions.py
tests/quantization/test_onnx_export.py

Add hack of export processing for our old checkpoints
Add Exception raising for exporting per-channel Q/DQ layers, as PyTorch ONNX exporting supports only per-tensor.

Fix bug with export to Q/DQ

---

nncf/dynamic_graph/input_wrapping.py

Right now a lot of messaged outputs that something wrong with parameter 'param_name'. it is better to output real parameter name.

make customer happy to see param name that is wrong

---

nncf/pruning/base_algo.py
tests/pruning/filter_pruning/test_algo.py

Fixes for gradients and BatchNorms zeroing (now all batch norms are masked with the previous convolution by default).
cc @AlexKoff88  @vanyalzr @AlexanderDokuchaev

Pruning fixes

---

examples/object_detection/configs/ssd300_vgg_voc_int8.json
examples/object_detection/eval.py
examples/object_detection/layers/modules/ssd_head.py
examples/object_detection/main.py

Backward compatible changes. Introduce a config key "loss_inference" to specify test with loss evaluation or the default mAP evaluation. It is disabled by default. This patch support issue #131

Introduce evaluation option of loss function to SSD application

---

examples/common/sample_config.py

Newer `addict` version uses custom private attributes for internal
working and __getattr__ disrupted it. It was quite useless anyway.

Remove __getattr__ from SampleConfig

---

tests/sota_checkpoints_eval.json

Updated sota_checkpoints_eval json with new paths after https://github.com/openvinotoolkit/nncf/pull/300

Fixed paths to mixed-precision configs

---

tests/sota_checkpoints_eval.json

After #300 *_hawq.json configs are propagation-based, but checkpoints are still for pattern-based quantization settings.
That's why nightly eval tests may fail for mixed-precision models. Switched to "manual" configs, as they still have original pattern-based configuration.
@pfinashx @vshampor

Correct configs for mixed precision models

---

nncf/quantization/layers.py
tests/quantization/test_range_init.py

The initialization using the controller method may occur *after*
the optimizer received the list of model's parameters, so replacing
the parameter as a whole during such initialization will break the
gradient updates.

Do not replace  parameter during symmetric range init

---

tests/test_sota_checkpoints.py

Fixed error: ModuleNotFoundError: No module named 'google.protobuf' in parallel cpu jobs

Fixed protobuf error

---

examples/classification/main.py
examples/semantic_segmentation/main.py
tests/helpers.py
tests/quantization/test_logarithm_scale.py
tests/quantization/test_precision_init.py
tests/quantization/test_quantization_helpers.py
tests/quantization/test_range_init.py

There is a little chance that last data point may have a batch size equal to 1, which leads to an error:
```
ValueError: Expected more than 1 value per channel when training
```
We caught this error in sanity tests with CIFAR10. The dataset has 1000 data points.
There're 333 data points with batch_size=3 and the last one with batch_size=1. Training may fail in the end of epoch, which is not accepted for bigger datasets.
@vuiseng9

Dropped last data point in all DataLoaders to prevent issue with BN

---

nncf/pruning/base_algo.py
nncf/pruning/filter_pruning/algo.py
nncf/utils.py
tests/pruning/filter_pruning/test_algo.py
tests/quantization/test_precision_init.py

Example of output:
```
pruning_rate: 0.09999999999999998
FLOPS pruning level: 0.1128178144173182
FLOPS current / full: 533683152 / 601548544
```
Additions fixes:
- Missed transpose convolution for 'prunable_types'
- Fix incorrect computation FLOPS of linear module

Print flops pruning level in statistic

---

docker/cpu/Dockerfile
docker/gpu/Dockerfile

Changes;
both CPU and GPU Docker files:
-  using ubuntu 20.04 
-  python 3.8
only gpu Docker file:
- entry point changed to /home/nncf/
- image used nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

00.0:Updating NNCF github dockerfiles against last changes

---

nncf/model_creation.py
nncf/quantization/precision_init/hawq_init.py

- Set debug log directory for collecting hawq-related data not only in debug mode, but via option `dump_precision_init_data`
- Corrected printing of chosen bitwidth configuration

Minor fixes for HAWQ

---

beta/tests/tensorflow/data/configs/retinanet_coco2017_magnitude_sparsity_int8.json

The sanity test duration for the object detection sample is ~**19:30** minutes at the moment.
After these changes, the duration was reduced to ~**02:45** minutes.
Changes: `"use_batched_nms": false` ---> `"use_batched_nms": true`
Time reduction: 19:30 min ---> 09:27 min
Changes: `"num_convs": 4` ---> `"num_convs": 1`
Time reduction: 09:27 min ---> 06:51 min
Changes: `"max_level": 7` ---> `"max_level": 3`
Time reduction: 06:51 min ---> 02:45 min

[TF] Reduction of the sanity test time for object detection sample

---

beta/tests/tensorflow/data/configs/mask_rcnn_coco2017_magnitude_sparsity_int8.json

The sanity test duration for the segmentation sample is ~**05:10** minutes at the moment.
After these changes, the duration was reduced to ~**02:35** minutes.

[TF] Reduction of the sanity test time for segmentation sample

---

beta/nncf/tensorflow/sparsity/schedulers.py
nncf/compression_method_api.py
nncf/sparsity/schedulers.py

* Unused attributes were removed from `MultiStepSparsityScheduler` class.
* Method `load_state_dict()` was removed from `PolynomialSparseScheduler` because it is already defined in the super class.
* Method `initialize()` was removed from `CompressionScheduler` and `SparsityScheduler` because it is unused now.

Schedulers refactoring

---

nncf/sparsity/schedulers.py
tests/sparsity/test_common.py

Let's consider test cases from NNCF tests
https://github.com/openvinotoolkit/nncf/blob/452ff2d7714a4e3da4b5da6484a8a13e27cbb2cc/tests/sparsity/test_common.py#L150-L156
and draw these dependencies, namely
```python
epochs = [0, 1, 2, 3, 4]
concave = [0.1, 13 / 90, 25 / 90, 0.5, 0.5]  # "concave": true
convex = [0.1, 29 / 90, 41 / 90, 0.5, 0.5]  # "concave": false
plt.plot(epochs, concave, '-bo', label='Concave')
plt.legend()
plt.ylabel('Sparsity level')
plt.grid(True)
plt.xlabel('Epochs')
plt.savefig('concave.png')
```
I got the following charts:
**"concave": true**
**"concave": false"**
From these charts, we can see when we set the `"concave"` parameter to `true` we get the [convex function](https://en.wikipedia.org/wiki/Convex_function) and the [concave …

The "concave" parameter is misleading

---

nncf/automl/agent/ddpg/ddpg.py

Issue message: [E1130(invalid-unary-operand-type), DDPG.update_policy] bad operand type for unary -: tuple
@vuiseng9 @alexsu52 @aleksei-kashapov @andrey-churkin

Fixed pylint issue in DDPG

---

tests/test_compression_training.py

Should fix internal error during nncf_cuda nightly run
CVS-49053
@pfinashx @aleksei-kashapov

Proper usage of pytest-dependency plugin: name should hashable

---

tests/test_install.py

Since in docker was added python3.7-venv, all install tests passed, except of bdist_wheel setup.
While creating venv virtual environment wheel does not install automatically, like in virtualenv virtual environment, so it need install manually.

Added wheel install in venv

---

nncf/extensions/src/quantization/cuda/functions_cuda_impl.cu

If input tensor has only 1 channel incorrect shape of scale tensor is chosen;

Fix bug with cuda kernel

---

nncf/dynamic_graph/graph.py
nncf/dynamic_graph/operator_metatypes.py
nncf/nncf_network.py
nncf/pruning/model_analysis.py
nncf/pruning/pruning_node_selector.py
tests/pruning/filter_pruning/test_algo.py
tests/pruning/helpers.py
tests/test_nncf_network.py

Nncf_network:
-  use `find_node_in_nx_graph_by_input_agnostic` instead of `find_node_in_nx_graph_by_scope` to set `ConvolutionModuleAttributes` for nodes
- Add `GroupNormMetatype`
Pruning:
- Merge nodes that forwards several times into cluster 
- Check nodes that already added to one of clusters

Support pruning models with FCOS detection head

---

nncf/checkpoint_loading.py
nncf/quantization/layers.py
tests/test_load_model.py

Also refactored load_data functionality
This feature is needed for #518 to not update all checkpoints when new parameter is introduced.
Instead, if old checkpoint doesn't have this new optional attribute, it can be successfully loaded even in a resume mode. The new attribute will be initialized by default (e.g. padding_value=0)

Optional parameters support on loading PT checkpoint

---

nncf/sparsity/rb/algo.py

I found method which has no uses in code and calling not existing methods of RB loss. Please correct me if I am wrong

Remove useless method from RB sparsity algo

---

nncf/sparsity/schedulers.py

When we use the polynomial scheduler with `"sparsity_target_epoch": 0` and `"update_per_optimizer_step": true` we get that `sparsity_target` value is reached at step 0 of the 1st epoch.
This behavior does not correspond to the `sparsity_target_epoch` parameter description:
https://github.com/openvinotoolkit/nncf/blob/4189d090b730f712c35aa8147a4b80f99294f347/nncf/config/schema.py#L513-L515
Also, this behavior is different from other schedulers. This PR fixes it.

Align polynomial scheduler with other schedulers

---

beta/requirements.txt

Fixed absl-py version to avoid the following error during installation:
`ERROR: tensorflow-metadata 0.28.0 has requirement absl-py<0.11,>=0.9, but you'll have absl-py 0.11.0 which is incompatible.`

[TF] update requirements

---

examples/common/utils.py

Sometime when writing metrics in json file, there is a failure - extra bracket is appears in json file ( {"Accuracy": 78.2}} ), and when collecting common table, script return error, for example - 165 build. This PR trying to fix it. (See 166 build)

Fixed re-write metrics in json

---

docs/compression_algorithms/Pruning.md
nncf/pruning/base_algo.py
nncf/pruning/export_helpers.py
nncf/pruning/export_utils.py
nncf/pruning/filter_pruning/algo.py
tests/helpers.py
tests/pruning/filter_pruning/test_algo.py
tests/pruning/helpers.py

REF: 50604
In some case (like DenseNet) when batch_norm layer is after not convolution layer we should propagate masks to apply actual mask for this batch_norm layer
```
conv1 conv2 
\    / 
concat
| 
batch_norm 
```

Propagate masks before apply masks

---

nncf/common/pruning/schedulers.py
tests/pruning/test_schedulers.py

Looks like that current implementation does not work properly.
Consider the following example:
```python
a, b, k = _init_exp(10, 0.1, 0.7)
x = a * np.exp(-k * 10) + b
print(x)
```
I expected that `x` is equal to `0.7` but I got `0.666666666666667`.

Fix exponential scheduler with bias

---

tests/quantization/test_quantizer_propagation_solver.py

The random_index mechanism in networkx looks sketchy as it only
inspects args for a seed value (aka "random_state"), and not kwargs.
This is a workaround for "random_state_index is incorrect" errors.

Switch gnc_graph calls in test to using positional args

---

beta/tests/sota_checkpoints_eval.json
beta/tests/test_sota_checkpoints.py

What's new:
`batch` key in `beta/tests/sota_checkpoints_eval.json`  renamed to `batch_per_gpu`. 
If `batch_per_gpu` is provided - `global_batch` is getting calculated at `beta/tests/test_sota_checkpoints.py` using the `BATCH_COEFF`.
If `batch_per_gpu` is NOT provided in `beta/tests/sota_checkpoints_eval.json` - the `global_batch` is getting from main model config.

Test sota checkpoint, batch size fix

---

beta/tests/test_sota_checkpoints.py

Compressed model yolo_v4_int8_w_sym_c_a_asym_t has it own AC config, this PR fix condition to make compression configs from base model - now it's check, AC config already present in configs folder or not.

[TF] Fixed condition to make compression model AC config

---

beta/tests/tensorflow/data/ac_configs/yolo_v4_int8_w_sym_ch_a_asym_t.yml

E2E test takes model name from AC config, so name must be unique.

Changed model name in AC config

---

beta/tests/sota_checkpoints_eval.json

Last validation disclosed fluctuation in the value of target value of  yolo_v4_int8_w_sym_ch_a_asym_t checkpoint. Mean growth is 0.1, thus I suggest to increase diff target to 0.15

Update threshold for yolov4 int8

---

tests/test_ddp.py
tests/test_distributed_data_parallel_mode.py

I add a test that checks out whether the processes in multiprocessing mode are frozen during wrapping by DistributedDataParallel mode. This test reproduces this issue that occurred in integration NNCF to mmdetection (when the in model's training method updates the requires_grad fields of parameters)

Add DistributedDataParallel test reproducing processes hanging in mmdet

---

nncf/checkpoint_loading.py
tests/data/configs/squeezenet1_1_cifar10_rb_sparsity_int8.json
tests/test_backward_compat.py
tests/test_load_model.py

- Checkpoint without |OUTPUT and |INPUT suffixes wasn't loadable
- No way to load separate compression parameters to the model with unified ones.
- Updated squeezenet1_1_custom_cifar10_rb_sparsity_int8_ddp.pth to avoid issue with duplicated FQ and with per-tensor input quantization instead of per-channel.
- fixed backward-compatibility test:
registered data_loader for range init and set proper tolerance for accuracy comparison
- refactored KeyMatcher class
resolves 53579

Fixed backward compatibility issues

---

beta/examples/tensorflow/common/prepare_checkpoint.py
beta/nncf/tensorflow/callbacks/statistics_callback.py

* keep compression controller state in clipped version of the checkpoint. This allow us to do model export properly in case of RB sparsity algo

Save compression controller state together with model

---

tests/torch/sota_checkpoints_eval.json

Resulting targets are still within 99% of FP32.

Update thresholds and targets for e2e

---

examples/tensorflow/segmentation/evaluation.py
nncf/config/extractors.py
nncf/tensorflow/quantization/algorithm.py
tests/tensorflow/data/configs/mask_rcnn_coco2017_magnitude_sparsity_int8.json
tests/tensorflow/test_sanity_sample.py

When I tried to evaluate Maskrcnn I found
1) evaluation.py initialize model even if checkpoint is present
2) QuantizationBuilder._range_init_params attribute passed to MinMaxInitializer init even if this attribute is None, which isn't handled properly

Fix quantization init

---

examples/torch/semantic_segmentation/configs/unet_camvid_int8.json
nncf/common/graph/layer_attributes.py
nncf/torch/quantization/algo.py
nncf/torch/quantization/init_range.py
nncf/torch/quantization/layers.py
nncf/torch/quantization/quantizer_propagation.py
nncf/torch/quantization/quantizer_setup.py
nncf/torch/utils.py
tests/torch/helpers.py
tests/torch/quantization/test_onnx_export.py
tests/torch/quantization/test_unified_scales.py

In particular, this fixes the issue with ConvTranspose2d's being
per-channel quantized on a wrong dimension.

Add target compression idx to layer attributes

---

docs/compression_algorithms/Pruning.md
docs/compression_algorithms/Quantization.md
docs/compression_algorithms/Sparsity.md
examples/tensorflow/classification/configs/quantization/inception_v3_imagenet_int8.json
examples/tensorflow/classification/configs/quantization/mobilenet_v2_imagenet_int8.json
examples/tensorflow/classification/configs/quantization/mobilenet_v3_large_imagenet_int8.json
examples/tensorflow/classification/configs/quantization/mobilenet_v3_small_imagenet_int8.json
examples/tensorflow/classification/configs/quantization/resnet50_imagenet_int8.json
nncf/common/initialization/batchnorm_adaptation.py
nncf/config/extractors.py
nncf/config/schema.py
nncf/tensorflow/batchnorm_adaptation.py
nncf/tensorflow/quantization/algorithm.py
nncf/torch/batchnorm_adaptation.py
nncf/torch/initialization.py
tests/tensorflow/test_bn_adaptation.py
tests/torch/data/configs/hawq/icnet_camvid_mixed_int.json
tests/torch/data/configs/hawq/inception_v3_cifar10_mixed_int.json
tests/torch/data/configs/hawq/resnet18_cifar10_mixed_int.json
tests/torch/data/configs/hawq/resnet18_cifar10_mixed_int_manual.json
tests/torch/data/configs/hawq/ssd300_vgg_voc_mixed_int.json
tests/torch/data/configs/hawq/unet_camvid_mixed_int.json
tests/torch/quantization/test_autoq_precision_init.py
tests/torch/quantization/test_hawq_precision_init.py
tests/torch/quantization/test_manual_precision_init.py
tests/torch/test_api_behavior.py
tests/torch/test_sanity_sample.py
tests/torch/test_utils.py

- Remove the BN statistics forgetting step from the BN adaptation algo
- Make BN adaptation default for quantization in TF
| model | orig. metric  | init. w/o BN adapt | init. w/ BN adapt (develop) | init. w/ BN adapt (this branch)
|:-------------:|:-------------:|:-----:|:-----:|:-----:|
| YOLOv4/COCO INT8 (TF, no 7bit fix) | 47.029 | 46.113 | 45.971 | 46.141 |
| RetinaNet-R50/COCO INT8 (TF, no 7 bit fix)      | 33.44 | 33.24 | 32.95 | 33.28 |
| MobileNetV2 INT8 (PT) | 71.8 | 69.351 | 70.946 | 70.459 (71.032 at 5k samples) |
| Squeezenet1.1 INT8 (PT), 5k samples | 58.178 | 57.929 | 57.963 | 58.005 |

Remove BN statistics forgetting step in BN adaptation

---

examples/tensorflow/classification/main.py
examples/tensorflow/object_detection/main.py
examples/tensorflow/segmentation/train.py
nncf/common/pruning/statistics.py
nncf/tensorflow/callbacks/statistics_callback.py
nncf/tensorflow/pruning/base_algorithm.py
nncf/tensorflow/pruning/callbacks.py
nncf/torch/pruning/filter_pruning/algo.py

Two main changes:
1. Some statistics are removed from printing to console. 
from 
to 
2. Filter pruning level in PyTorch is now calculated using a layer mask.
\+ added to TF statistics printing after initialization

Remove redundant pruning statistics. Align statistics report

---

examples/tensorflow/classification/main.py
examples/tensorflow/common/utils.py
examples/tensorflow/object_detection/main.py
examples/tensorflow/segmentation/evaluation.py
examples/tensorflow/segmentation/train.py

After these changes, the values of the command line arguments are printed in the TF samples, as in the PT samples.
Example of classification sample output 
```bash
INFO:example:Command line arguments
batch_size                 : 256
checkpoint_save_dir        : ../../results/quantization/tmp/MobileNetV2_imagenet2012_int8/2021-07-06__09-30-09
ckpt_path                  : None
compression                : {'algorithm': 'quantization', 'initializer': {'batchnorm_adaptation': {'num_bn_adaptation_samples': 2048}}, 'log_dir': '../../results/quantization/tmp/MobileNetV2_imagenet2012_int8/2021-07-06__09-30-09'}
config                     : configs/quantization/mobilenet_v2_imagenet_int8.json
cpu_only                   : False
dataset                    : imagenet2012
dataset_dir                : …
```

Print command line arguments

---

examples/torch/classification/main.py
examples/torch/semantic_segmentation/main.py

Previously, last data point in all DataLoaders were dropped to prevent issue with BN (#379)
But it's actual for training only, on eval it shouldn't happen.

Accuracy validation doesn't depend on batch size and number of GPU

---

setup.py

For now setup.py has two option --tf and --torch
Both intended to install tensorflow and pytorch parts of the product separately
But EXTRAS_REQUIRE also has 'all' label that suppose to install both tensorflow and torch at the same time.
The option '--all' covers using of this label.

To add --all install option to setup.

---

nncf/common/quantization/collectors.py
nncf/common/quantization/statistics.py
nncf/tensorflow/quantization/algorithm.py
nncf/tensorflow/quantization/collectors.py
nncf/tensorflow/quantization/layers.py
nncf/tensorflow/quantization/quantizers.py
nncf/tensorflow/quantization/utils.py
nncf/torch/quantization/algo.py
nncf/torch/quantization/metrics.py
nncf/torch/quantization/precision_init/autoq_init.py
nncf/torch/quantization/statistics.py
tests/tensorflow/quantization/test_statistics.py
tests/torch/quantization/test_manual_precision_init.py
tests/torch/quantization/test_quantization_metric.py

Prior to these changes, we were printing the following statistics:
- statistics of the memory consumption
- statistics of the quantization share
- statistics of the bitwidth distribution
- statistics of the quantization configuration
- ratio of enabled quantizations.
After this PR we print the following statistics:
- statistics of the quantization share
- statistics of the bitwidth distribution
- ratio of enabled quantizations
The statistics of the memory consumption and the statistics of the quantization configuration are printed only for NNCF PT in debug mode.
**Before my changes:**
**After my changes:**

Common collectors of quantization statistics

---

examples/tensorflow/common/argparser.py
examples/tensorflow/common/prepare_checkpoint.py
tests/tensorflow/data/configs/resnet50_cifar10_magnitude_sparsity_int8.json
tests/tensorflow/data/configs/retinanet_coco2017_magnitude_sparsity_int8.json
tests/tensorflow/data/configs/sequential_model_cifar10_magnitude_sparsity_int8.json
tests/tensorflow/data/configs/sequential_model_no_input_cifar10_magnitude_sparsity_int8.json
tests/tensorflow/test_sanity_sample.py

* Required checkpoint path in `prepare_checkpoints.py`
* Refactored test to load real checkpoints from sanity test_model_train to properly test  `prepare_checkpoints.py`, which required checkpoint path. (It was impossible to make new small model to pass it into prepare checkpoint because prepare checkpoint can build only yolo, retinanet and maskrcnn models.) 
Local check shows new version of the test small time consuming (~30 sec ~= not refactored test running time).

Refactor test_prepare_checkpoints

---

examples/tensorflow/requirements.txt
tests/tensorflow/conftest.py
tests/tensorflow/test_install.py

Freeze `protobuf==3.17.3` to avoid problems with old pip versions

Add TF test install with examples and tests requirements

---

nncf/tensorflow/quantization/algorithm.py

Looks like in #836 new implementation of `_get_qunatizable_weighted_layer_nodes` was added but previous wasn't removed

Remove _get_qunatizable_weighted_layer_nodes duplicated definition

---

tests/torch/test_sota_checkpoints.py

On last E2E test we have error, when installing AC:
`error: packaging 20.3 is installed but packaging>=20.9 is required by {'huggingface-hub'}`
This PR must fix this.

Added WA in AC install step for E2E test

---

examples/torch/classification/main.py

This will allow to make results with mock datasets more stable

Remove random transformations from mock datasets in PT classification

---

nncf/torch/nncf_network.py
tests/torch/test_nncf_network.py

Add a capability to change the bound functions of a wrapped module by passing NNCFNetwork instance as a first argument

Fix bug in __getattr__ of NNCFNetwork

---

nncf/common/pruning/statistics.py
nncf/tensorflow/pruning/filter_pruning/algorithm.py
nncf/torch/pruning/filter_pruning/algo.py

Add three new pruning statistics:
* Pruned layers count / prunable layers count (means number of layers which have prunable type)
* GFLOPS minimum possible after pruning / full (means number of flops for pruned
model with pruning rate = 1.)
* MParams minimum possible after pruning / full (means number of params for pruned
model with pruning rate = 1.)
This statistics useful in case maximum possible flops removal is really small thus pruning won't give any significant speedup after compression (ex mobilent-v3 with 2 stride)

Add maximum pruning rate statistics

---

nncf/torch/graph/pattern_operations.py
nncf/torch/hardware/fused_patterns.py
tests/torch/data/reference_graphs/quantized/synthetic_model/MatMulDivConv.dot
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py

The patterns were added for fusing matmul and elementwise operations for PT quantization
BERT exhibits this type of operations and currently an extra FQ is being inserted between matmul and add etc., which is unnecessary.
-
Examination of the resulting BERT-SQuAD model obtained with the transformers repo. SOTA PT eval build 539.

Add matmul patterns for fusing

---

tests/torch/data/configs/weekly/classification/cifar100/mobilenet_v2_learned_ranking.json
tests/torch/test_compression_training.py

Fixed test for compression training for LeGR algorithm. Ticket - 62532.
The number of training epochs and potential accuracy diff has been increased.
@ljaljushkin @vshampor

Test compression training fix 

---

README.md
third_party_integration/huggingface_transformers/0001-Modifications-for-NNCF-usage.patch
third_party_integration/huggingface_transformers/README.md

The third-party integration patch for NNCF was extended with results of applying NNCF quantization for BERT on MRPC.
Extending the scope of NLP application showcasing.
-
The MRPC is part of the GLUE training pipeline, which is already covered by an existing third-party sanity test.

Add BERT-MRPC config, command line and result

---

tests/torch/test_compression_training.py

LEGR training takes more than the current 2 hours to reach target accuracy (it takes 60 epochs of training).
62532
Existing test_compression_training cases should pass on CI now.

Increase timeout for compression training test cases for 3 hours

---

tests/tensorflow/sota_checkpoints_eval.json

Increased thresholds for Yolo models
In last E2E test thresholds for yolo_v4_int8_w_sym_ch_half_a_asym_t was violated
None
No needed

Increased thresholds for Yolo models

---

nncf/common/graph/graph_matching.py
nncf/common/graph/patterns.py
nncf/tensorflow/graph/patterns.py
nncf/torch/graph/patterns.py
tests/common/graph/test_graph_matching.py
tests/common/graph/test_graph_pattern.py

Introduced ANY_PATTERN_NODE_TYPE and NON_PATTERN_NODE_TYPE. ANY_PATTERN_NODE_TYPE  is a node inside the pattern, that matches on any node type, while NON_PATTERN_NODE_TYPE is outside the pattern node. NON_PATTERN_NODE_TYPE is used to reflect some outgoing edges inside the pattern
These changes allow adding the L2Norm pattern.
67283
The current tests were updated with new logic.

Introduce ANY_PATTERN_NODE_TYPE and NON_PATTERN_NODE_TYPE

---

tests/tensorflow/test_nncf_keras_graph_equality.py

Turned off downloading weights for models from the nncf_keras_model_graph_equality tests
Speeding up the nncf_keras_model_graph_equality tests
N/A
N/A

Speeding up the nncf_keras_model_graph_equality tests

---

tests/torch/conftest.py
tests/torch/test_sota_checkpoints.py

Added option for --dist-url for parallel execution test_train
To allow execution train several models simultaneously
CVS-71283
TBD

Added option for --dist-url for parallel execution train tests

---

tests/tensorflow/test_sanity_sample.py

Add fixture to enable mock datasets only for test_sanity_sample
Enabling weekly TF tests
71292
Locally tested

Make mocking datasets only for test_sanity_sample

---

nncf/tensorflow/graph/converter.py

Fixed getting layer dtype for Functional, Sequential layers
The _get_layer_dtype function for Functional, Sequential layers failes with runtime error.
N/A
N/A

Fixed getting layer dtype for Functional, Sequential layers

---

nncf/torch/graph/graph_builder.py

Check layer_attributes before check subtypes.
Incorrect works with custom modules like
```Python
class CustomMoudule(nn.Module):
def __init__(self, in_features, out_features):
...
self.in_features = in_features
self.out_features = out_features
self.weight = nn.Parameter(torch.Tensor(out_features, in_features))
...
def forward(self, x):
weight = normalize(self.weight, dim=1, p=2).view(self.out_features, self.in_features, 1, 1)
out = F.conv2d(x, weight)
return out
```
In with case layer_attributes is `GenericWeightedLayerAttributes` and `operator_name` is `conv2d` as result 
```
File "nncf/torch/graph/operator_metatypes.py", line 87, in determine_subtype
functions_kwargs):
File "nncf/torch/graph/operator_metatypes.py", line 166, in matches
if layer_attributes.groups == …
```

Fix error in determine_subtype for custom module

---

nncf/tensorflow/graph/metatypes/common.py
nncf/tensorflow/graph/metatypes/tf_ops.py
nncf/tensorflow/graph/pattern_operations.py

New metatypes was added
These changes are required for Keras Lambda layer support
N/A
N/A

Extend the metatypes for TF OPS

---

docs/compression_algorithms/Quantization.md
nncf/common/graph/utils.py
nncf/common/pruning/node_selector.py
nncf/common/pruning/utils.py
nncf/config/schema.py
nncf/tensorflow/quantization/algorithm.py
nncf/tensorflow/quantization/quantizers.py
nncf/tensorflow/quantization/utils.py
nncf/torch/quantization/algo.py
tests/tensorflow/quantization/test_algorithm_quantization.py
tests/tensorflow/quantization/test_builder_state.py
tests/tensorflow/quantization/test_overflow_issue.py
tests/torch/pruning/test_utils.py
tests/torch/quantization/test_overflow_issue_export.py
tests/torch/quantization/test_saturation_issue_export.py
tests/torch/test_utils.py

New config option "saturation_fix" was introduced. Which have choices for SF mode: `disable`, `enable`, `enable_for_first_conv_layer`. `enable` is the default option.
In order to short the tuning time and at the same time partially compensate for the saturation issue by using `enable_for_first_conv_layer` option.
71400
Tests are updated to validate all three options.

New "saturation_fix" config option

---

nncf/common/quantization/quantizer_propagation/graph.py
nncf/torch/graph/operator_metatypes.py
tests/torch/quantization/test_quantizer_propagation_graph.py
tests/torch/test_nncf_network.py

Change merging qunatizers logic for pre_hooks. 
```python
File "nncf/common/quantization/quantizer_propagation/solver.py", line 355, in run_on_ip_graph
quantizer_setup = quant_prop_graph.create_quantizer_setup(self._weight_quantizable_node_names_vs_qconfigs)
File "nncf/common/quantization/quantizer_propagation/graph.py", line 1115, in create_quantizer_setup
setup.register_unified_scale_group_with_types([pqid_vs_qpid[pq.id] for pq in pq_set],
File "nncf/common/quantization/quantizer_propagation/graph.py", line 1115, in <listcomp>
setup.register_unified_scale_group_with_types([pqid_vs_qpid[pq.id] for pq in pq_set],
KeyError: 1193
```
For subgraph with split/chunk node that does not have POST_HOOK.  
```
(add)
|
(split)
/         \
(conv)   (conv/concat)
```
It happened because …

Fix merging quantaizers

---

nncf/torch/layers.py
tests/torch/data/reference_graphs/quantized/synthetic_model/GroupNorm.dot
tests/torch/test_compressed_graph.py

Fix wrapping `nn.GroupNorm`
```bash
"nncf/torch/layers.py", line 148, in from_module
nncf_bn = NNCFGroupNorm(module.num_features)
File "torch/nn/modules/module.py", line 947, in __getattr__
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GroupNorm' object has no attribute 'num_features'
```
Add test GroupNorm in `test_synthetic_model_quantization`

Fix wrapping group_norm

---

nncf/tensorflow/graph/patterns.py
nncf/torch/graph/patterns.py
tests/torch/data/reference_graphs/quantized/synthetic_model/ConvRelu6HSwish.dot
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py

Certain MobileNetV3 variations in PyTorch use an explicit custom HSwish module instead of the `hardswish` function from torch.nn.functional, and this custom module uses ReLU6 internally.
74044
Extended tests.torch.test_compressed_graph.test_synthetic_model_quantization, created ticket 74092 for the TF implementation of synthetic tests in bulk.

Add ReLU6-based HSwish to fused patterns

---

nncf/torch/layers.py
nncf/torch/quantization/layers.py

`is_enabled_quantization`, `signed_tensor` and other ops that get a constant value from a buffer now execute outside ONNX JIT trace, if currently tracing.
Allows to suppress warnings frequently seen during export:
```
/home/alexsu/work/projects/algo/nncf_tf/source/nncf-tf/github/nncf/nncf/torch/quantization/layers.py:148: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
if not self.is_enabled_quantization():
```
, improving UX.
N/A
Manual export runs using samples.

Execute buffer-examining operations without ONNX tracing

---

.github/workflows/python-publish.yml
setup.py

Now any version of the NNCF package set up in an editable mode will have "dev-editable" appended to its version; otherwise, if the package is built/installed via setup.py without passing a "--release" argument, the "dev-_hash of the current repo_" commit will be appended to the package version.
This allows for more accountability as to which NNCF version is used where.
74164
test_install (to be run)

Add NNCF repo commit hash to developer versions of the package

---

README.md

README changes, as stated in the title.
Latest pip version brings troubles to regular installation process using older Git clients.
69243
N/A

Add info on pip installs from Github

---

examples/torch/object_detection/configs/ssd300_mobilenet_voc.json
examples/torch/object_detection/configs/ssd300_mobilenet_voc_magnitude_int8.json
examples/torch/object_detection/configs/ssd300_mobilenet_voc_rb_sparsity_int8.json
examples/torch/object_detection/configs/ssd300_vgg_voc.json
examples/torch/object_detection/configs/ssd300_vgg_voc_int8.json
examples/torch/object_detection/configs/ssd300_vgg_voc_int8_accuracy_aware.json
examples/torch/object_detection/configs/ssd300_vgg_voc_magnitude_sparsity_int8.json
examples/torch/object_detection/configs/ssd300_vgg_voc_pruning_geometric_median.json
examples/torch/object_detection/configs/ssd512_vgg_voc.json
examples/torch/object_detection/configs/ssd512_vgg_voc_int8.json
examples/torch/object_detection/configs/ssd512_vgg_voc_magnitude_sparsity_int8.json
examples/torch/object_detection/main.py

The config values in PyTorch object detection samples are modified to use epochs instead of iterations; `iter_size` parameter is removed. 
The current object detection sample configs mix up epoch-based and iteration-based specifications for test/save intervals and sparsity application. This leads to confusion and in fact we currently cannot tell if the configs are even correct w.r.t. the scheduling and training length.
71329
test_sanity_sample

Formulate PT OD configs in terms of epochs only

---

setup.py
tests/common/helpers.py
tests/tensorflow/test_install.py
tests/torch/test_install.py

The '-' in dev versions containing commit hash was changed to '+'.
Previous version format was not conforming to PEP 440, and the `pip install git+` path of installation failed to install from a wheel. This was not fatal, but a nasty warning was being spawned and a deprecated installation path had to be involved.
N/A
Extended test_install with the `pip install git+` scenarios.

Make dev versions conform to PEP 440

---

examples/torch/classification/README.md
examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_hawq_old_eval.json
examples/torch/classification/configs/mixed_precision/squeezenet1_1_imagenet_mixed_int_hawq_old_eval.json
nncf/torch/quantization/precision_init/manual_init.py
tests/torch/sota_checkpoints_eval.json

Updated mixed precision checkpoints, reference numbers in test_sota_checkpoints and README
Previous checkpoints were trained with ZP not for VPU, which is not optimal
42046
custom build number if sota_eval_pytorch will be reported later

Updated  Mixed-Precision models 

---

nncf/torch/layers.py
tests/torch/test_nncf_network.py

Upon construction (i.e. during module wrapping process), NNCF* modules now reapply the torch.nn.utils.weight_norm.WeightNorm pre-hook if it has been applied to the non-NNCF wrapped module.
The WeightNorm hook replaces the existing "weight" torch.nn.Parameter of the wrapped module with a raw Tensor of the same name and instead creates two internal torch.nn.Parameters from which the original "weight" attribute is then recomputed. In order for these changes to be propagated into the NNCF-wrapped module, the hook application must be done explicitly.
N/A
Added tests.torch.test_nncf_network.test_weight_normed_modules_are_replaced_correctly

Fix weight norm applied to modules

---

nncf/torch/algo_selector.py
nncf/torch/binarization/algo.py
nncf/torch/dynamic_graph/graph_tracer.py
nncf/torch/dynamic_graph/io_handling.py
nncf/torch/initialization.py
nncf/torch/nncf_network.py
nncf/torch/pruning/base_algo.py
nncf/torch/quantization/algo.py
nncf/torch/quantization/hessian_trace.py
nncf/torch/quantization/layers.py
nncf/torch/quantization/precision_init/hawq_init.py
nncf/torch/sparsity/base_algo.py
nncf/torch/sparsity/rb/algo.py
nncf/torch/utils.py
tests/torch/modules/test_rnn.py
tests/torch/quantization/test_algo_quantization.py
tests/torch/quantization/test_hawq_precision_init.py
tests/torch/quantization/test_unified_scales.py
tests/torch/test_compressed_graph.py
tests/torch/test_knowledge_distillation.py
tests/torch/test_models/synthetic.py

Refactored the code for determining the model's device based on its parameters and unified it across the codebase.
Previously the parameter-less models would fail to be processed by NNCF; such models aren't exactly practical, but are convenient to have in tests. The new behaviour also increases NNCF generality somewhat.
N/A
Existing tests that work with paramless models, such as tests.torch.test_compressed_graph.test_synthetic_model_quantization

Presume CPU device for parameter-less models

---

setup.py

pip pulls the latest RC version (1.4.0rc0) which, surprisingly, does not even appear on pypi. The version actually breaks the installation - pandas cannot find the numpy module.
75354
Install tests should be working now.

Freeze pandas version to exclude the broken 1.4.0rc0 and higher

---

docs/compression_algorithms/Pruning.md

Also, there is an error when I try to use this config (v2.1.0):
```
jsonschema.exceptions.ValidationError: For algorithm: 'filter_pruning'
Additional properties are not allowed ('zero_grad' was unexpected)
```

Add missed comma in example pruning config

---

nncf/common/hardware/configs/cpu.json
nncf/common/hardware/opset.py
nncf/torch/graph/operator_metatypes.py
nncf/torch/graph/pattern_operations.py
tests/torch/data/reference_graphs/quantized/synthetic_model/MMDivConv.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/normalize.dot
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py

As stated in the title. Enables models that utilize `torch.mm` to have the `torch.mm` inputs quantized.
Generalization of NNCF PT applicability.
76378
tests.torch.test_compressed_graph.test_synthetic_model_quantization

Register torch.mm as a matmul operation

---

nncf/common/compression.py
nncf/config/extractors.py
nncf/tensorflow/quantization/algorithm.py
nncf/torch/quantization/algo.py
tests/tensorflow/quantization/test_builder_state.py
tests/tensorflow/test_bn_adaptation.py
tests/torch/quantization/test_algo_quantization.py

NNCFConfig will no longer require to have a BN adaptation data loader registered if the number of BN adaptation samples is set to 0 in the quantization algorithm (and if the only required compression is quantization).
This makes for easier debug/reproducer runs of quantization algo in a scratch file or a temporary Python console.
N/A
tests.torch.quantization.test_algo_quantization.test_quantization_can_be_run_with_no_data_loaders_if_zero_init_samples

Launch BN adaptation for quantization only for non-zero sample values

---

nncf/torch/quantization/quantize_functions.py
nncf/torch/utils.py
tests/torch/quantization/test_onnx_export.py
tests/torch/quantization/test_unified_scales.py

A bug was fixed wherein the quantizers that apply to different branches in the model were exported as chained one after the other, instead of each affecting only its own branch.
Bugfix
76733
tests.torch.quantization.test_onnx_export.test_branching_fqs_are_not_chained

Fix ONNX export for quantizers on branches

---

nncf/common/pruning/operations.py
nncf/common/pruning/utils.py
nncf/torch/pruning/utils.py

Removed adding `input_masks` attribute to node.data for mask propagation algorithm
**Still keep it for deprecated export utils** - the attribute pops up in the `input_prune` methods.
Mask propagation doesn't actually use `input_masks` anymore, It keeps `output_mask` only and calculate input masks based on output masks of previous nodes. It was done to avoid duplication and errors related to inconsistent input and output masks.
Without this change mask propagation algorithm may look misleading in terms of using input_masks
just should be no regression in current test scope, new tests are not needed

Completely removed input masks for mask propagation

---

nncf/torch/quantization/quantize_functions.py

In the asymmetric quantizer execution, add a safety cast of the intermediate calculations to the precision of the tensors that are input into the quantizer.
Due to unknown reason the intermediate calculations with FP16 torch values result in FP32 outputs, which breaks downstream code that expects that all values involved have one and the same dtype.
70246
Cannot be reproduced in laboratory conditions even if the same tensor values are used.

Cast scale to the input_low/input_range dtype

---

examples/tensorflow/classification/README.md
examples/tensorflow/common/argparser.py
examples/tensorflow/common/sample_config.py
examples/tensorflow/object_detection/README.md
examples/tensorflow/segmentation/README.md

Simplify scenario of evaluation pre-trained model.  I suggest using the `disable-compression` option instead of removing the compression section from the config file.
Customer request
N/A
N/A

`disable-compression` command line option

---

examples/torch/classification/main.py

Changed mean/std values for pre-processing input images from CIFAR10 dataset
It helps to reuse models pretrained on CIFAR10 from:
https://github.com/huyvnphan/PyTorch_CIFAR10/blob/master/data.py#L16
This models are used for e2e validation of BootstrapNAS feature #1079 
It affects backward compatibility tests that compare actual test accuracy with 'best_acc1' value in the checkpoint.
The `best_acc1` value was overridden to correspond to the introduced pre-processing.

Changed normalization parameters for CIFAR-10 images

---

tests/tensorflow/test_compressed_graph.py

Corrected typo in a TF test to fix degradation in the TF precommit with new version of pytest.
Seems like previous runs was with old version of pytest (6.2.5) and it ignored this typo.
Currently, CI uses newer version - 7.0.0 and it's failing.
to fix degradation in the TF precommit
tf precommit should be green

Corrected typo to fix broken TF pre-commit

---

tests/torch/pruning/filter_pruning/test_algo.py
tests/torch/pruning/filter_pruning/test_layers.py
tests/torch/pruning/helpers.py
tests/torch/pruning/test_model_pruning_analysis.py
tests/torch/pruning/test_onnx_export.py
tests/torch/pruning/test_utils.py
tests/torch/pytest.ini
tests/torch/quantization/test_manual_precision_init.py
tests/torch/quantization/test_quantization_metric.py
tests/torch/sparsity/magnitude/test_modules.py
tests/torch/sparsity/rb/test_components.py
tests/torch/sparsity/test_common.py
tests/torch/test_algo_common.py
tests/torch/test_distributed_data_parallel_mode.py
tests/torch/test_frozen_layers.py
tests/torch/test_nncf_network.py
tests/torch/test_resume_from_checkpoint.py
tests/torch/test_sanity_sample.py

When collecting tests, pytest checks for entities called Test* and considers these to be namespaces for test cases. There were many entities which in fact do not serve that purpose, and therefore have been renamed.
The collection failure warnings take up several console screens and make it harder to understand the pytest output.
N/A
PT precommit test scope launch

Fix pytest collection warnings

---

nncf/torch/dynamic_graph/context.py
nncf/torch/dynamic_graph/graph_tracer.py
nncf/torch/nncf_network.py
nncf/torch/utils.py
tests/torch/test_graph_building.py
tests/torch/test_nncf_network.py

Fixed a return value for the internal NNCFNetwork function that populates one of the fields, and made the threading-related fields of `TracingContext` only instantiate when the context is entered.
The NNCFNetwork object is not deepcopy-able otherwise.
76848
test_deepcopy_nncf_network

Make NNCFNetwork deepcopy-able

---

nncf/common/tensor.py
nncf/tensorflow/tensor_statistics/collectors.py
nncf/torch/tensor_statistics/collectors.py
tests/tensorflow/tensor_statistics/test_tensor_statistics.py
tests/torch/tensor_statistics/test_tensor_statistics.py

As in the title.
79156
Added test for the unstack op of NNCFCollectorTensorProcessor

Handle dimensionless tensor unstack in NNCFCollectorTensorProcessor

---

README.md

Replaced the link to the HF repo by the HF patch documentation
It's more logical to refer to our documentation about the patch to HF.
Asked several times about this doc.
none
na

Link to the HF path documentation

---

nncf/common/hardware/opset.py
nncf/torch/graph/operator_metatypes.py
tests/torch/data/reference_graphs/quantized/synthetic_model/ConvGeluGetItem.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/GELU.dot
tests/torch/quantization/test_hw_config.py
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py

Add `hw_config_name` for `PTGeluMetatype`. As a result Gelu doesn`t spawn a FQ.
Fix bug for wec2vec model
78186
`tests/torch/test_compressed_graph.py`

Add IR name for GELU. 

---

nncf/common/accuracy_aware_training/runner.py
nncf/common/accuracy_aware_training/training_loop.py
nncf/tensorflow/accuracy_aware_training/runner.py
nncf/torch/accuracy_aware_training/runner.py
tests/torch/accuracy_aware_training/test_training_loop.py

BugFixes:
- Using the correct accuracy value for updating the learning rate of the Plato scheduler.
- Using the correct accuracy value to determine the best checkpoint.
- The compression stage is considered when saving the best checkpoint.
N/A
N/A

BugFixes for EarlyExitCompressionTrainingLoop

---

nncf/torch/accuracy_aware_training/runner.py

Add a check that tensorboard was initialized
`PTAdaptiveCompressionLevelTrainingRunner` fails if tensorboard is not available. Affects sc.
-
-

check in aa that tensorboard is available

---

nncf/torch/exporter.py
tests/torch/test_onnx_export.py

Add option to change onnx opset version by `save_format` argument.
Example: 
- `onnx_11` to export with opset 11
- `onnx` to export with default opset version (10)
Reopened https://github.com/openvinotoolkit/nncf/pull/1131

Add option to set onnx opeset version 

---

.pylintrc
examples/torch/object_detection/layers/extensions/__init__.py
nncf/torch/binarization/extensions.py
nncf/torch/extensions/__init__.py
nncf/torch/quantization/extensions.py
tests/torch/test_extensions_build.py

NNCF uses JIT to build its extensions upon first usage; these are binary-locked to the current CUDA and torch versions. If the torch version changes, the built extension shared object files become incompatible with the new torch and a cryptic error is spawned. Using per-torch version folders to build extensions will solve the problem, since if a torch version changes, then the target directory for the extension also changes and triggers a rebuild of the extensions automatically.
80323

Build NNCF extensions in separate folders per torch version

---

nncf/common/graph/layer_attributes.py
nncf/torch/layers.py
tests/torch/test_layer_attributes.py

BatchNorm layer parameters are correctly parsed and set to node as `LAYER_ATTRIBUTES`
Recently (#1094), new NNCFBatchNorm layers were added with new operations names that led to degradation with setting BatchNorm layer attributes, they were equal to None. But these parameters are needed for BootstrapNAS feature (#1079)
#1094 
#1079
test_can_set_valid_layer_attributes

Fixed layer_attributes for BatchNorm ops

---

README.md
tests/torch/sota_checkpoints_eval.json

Path to config for `resnet34_imagenet_filter_pruning_geomean` was changed. 
E2E test fails.
Please see sota_eval_pytorch build 839

Fix path to config in sota for ResNet34

---

nncf/tensorflow/graph/metatypes/tf_ops.py
nncf/tensorflow/quantization/default_quantization.py

The meta type for `BatchMatMulV2` operation was added.
Look at the picture. The FQs, which are marked red, weren't inserted without these changes. But we expect them in these points.
The model to reproduce is presented below
```python
class CustomModelAttention(tf.keras.Model):
def __init__(self):
super().__init__()
self.query = tf.keras.layers.Dense(units=10, name='query')
self.key = tf.keras.layers.Dense(units=10, name='key')
def transpose_for_scores(self, tensor: tf.Tensor, batch_size: int) -> tf.Tensor:
tensor = tf.reshape(tensor=tensor, shape=(batch_size, -1, 2, 5))
return tf.transpose(tensor, perm=[0, 2, 1, 3])
def call(self, inputs, training=None, mask=None):
mixed_query_layer = self.query(inputs=inputs)
query_layer = self.transpose_for_scores(mixed_query_layer, 5)
key_layer = …
```

Metatype for BatchMatMulV2

---

nncf/experimental/tensorflow/patch_tf.py
nncf/experimental/tensorflow/scope.py

- The `get_op_name()` method was updated.
- The additional TF module was wrapped.
Some FQs from the quantizer setup were not inserted to the graph. Look at the picture. The FQs, which are marked red, weren't inserted without these changes (but this FQs are presented in quantizer setup). 
The model to reproduce is presented below
```python
class CustomModelGELU(tf.keras.Model):
def __init__(self):
super().__init__()
self._dense = tf.keras.layers.Dense(units=10)
def call(self, inputs, training=None, mask=None):
x = tf.keras.activations.gelu(inputs, approximate=False)
x = self._dense(x)
x = tf.keras.activations.gelu(x, approximate=False)
return x
```
N/A
Changes were tested manually using the model which is provided above.

Fix FQs insertion for experimental quantization

---

examples/torch/object_detection/layers/extensions/nms/nms_kernel.cu
nncf/torch/extensions/include/common_cuda_defs.cuh

As stated in the title. torch 1.11 removed some of the headers we relied on and moved their functionality to other headers and objects.
Forward compatibility with torch 1.11.
N/A
Any tests checking CUDA-powered quantization and/or object detection samples.

Adjust kernels to switch from deprecated torch TH/THC namespaces

---

setup.py

- Set networkx>=2.5, <2.8.1rc1
- networkx 2.8.1rc1 incurs ImportError in Python3.7
- ImportError: cannot import name 'cached_property' from 'functools' (/usr/lib/python3.7/functools.py)

Set networkx>=2.5, <2.8.1rc1

---

setup.py

Fix version issue when installing NNCF in Python3.6 environment.
`pillow>=9.0.0` is not supported in Python3.6.
```
+ python3 -m pip install -e .
Obtaining file:///opt/nncf_ws
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting addict>=2.4.0
Downloading addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting jsonschema==3.2.0
Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting jstyleson>=0.0.2
Downloading jstyleson-0.0.2.tar.gz (2.0 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting natsort>=7.1.0
Downloading natsort-8.1.0-py3-none-any.whl (37 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.6/dist-packages (from …
```

Fix version issue for Python3.6

---

nncf/common/accuracy_aware_training/training_loop.py
nncf/torch/accuracy_aware_training/runner.py
tests/torch/accuracy_aware_training/test_training_loop.py

Before training, set best checkpoint path to real path.
Best checkpoint path remains None when the model is not improved during training, so final checkpoint cannot be loaded.
[CVS-84176](https://jira.devtools.intel.com/browse/CVS-84176)
Set a validation function that returns gradually reduced accuracy and check if best checkpoint path is not None

add setting the best checkpoint before training

---

.dockerignore
.gitignore
docker/onnx/openvinoep/Dockerfile
docker/onnx/openvinoep/build.sh
examples/experimental/onnx/README.md
examples/experimental/onnx/classification/ac_configs/resnet50.yml
examples/experimental/onnx/classification/onnx_models_configs/bvlcalexnet-12.yml
examples/experimental/onnx/classification/onnx_models_configs/caffenet-12.yml
examples/experimental/onnx/classification/onnx_models_configs/densenet-12.yml
examples/experimental/onnx/classification/onnx_models_configs/efficientnet-lite4-11.yml
examples/experimental/onnx/classification/onnx_models_configs/googlenet-12.yml
examples/experimental/onnx/classification/onnx_models_configs/inception-v1-12.yml
examples/experimental/onnx/classification/onnx_models_configs/inception-v2-9.yml
examples/experimental/onnx/classification/onnx_models_configs/mobilenetv2-12.yml
examples/experimental/onnx/classification/onnx_models_configs/resnet50-v1-12.yml
examples/experimental/onnx/classification/onnx_models_configs/resnet50-v2-7.yml
examples/experimental/onnx/classification/onnx_models_configs/shufflenet-9.yml
examples/experimental/onnx/classification/onnx_models_configs/shufflenet-v2-12.yml
examples/experimental/onnx/classification/onnx_models_configs/squeezenet1.0-12.yml
examples/experimental/onnx/classification/onnx_models_configs/vgg16-12.yml
examples/experimental/onnx/classification/onnx_models_configs/zfnet512-12.yml
examples/experimental/onnx/classification/onnx_ptq_classification.py
examples/experimental/onnx/requirements.txt
examples/experimental/onnx/run_ptq.py
examples/experimental/onnx/run_ptq_onnx_models.sh
nncf/experimental/onnx/datasets/imagenet_dataset.py
nncf/experimental/onnx/engine.py
nncf/experimental/onnx/model_normalizer.py
tests/onnx/sanity_tests/test_classification_sanity_sample.py

- Add `Dockerfile` for ONNXRuntime-OpenVINO EP runtime environment.
- Add runnable scripts for PTQ API benchmarks on ONNX Model ZOO - Vision - Classification model.
- Add `README.md` to report the benchmark results.
- Make ONNXRuntime PTQ engine to use `CPUExecutionProvider` rather than `OpenVINOExecutionProvider` (`OpenVINOExecutionProvider` incurs many errors, we need to investigate it).
Provide reproducible process for PTQ API benchmarks on ONNX Model ZOO - Vision - Classification model.
https://jira.devtools.intel.com/browse/CVS-85505
None

Exp public ptq api

---

tests/torch/test_api_behavior.py

Remove redundant Cuda device from test_model_is_inited_with_own_device_by_default test
Broken test

Fix wrong device in test_model_is_inited_with_own_device_by_default

---

tests/tensorflow/conftest.py
tests/torch/conftest.py

Tensor Float 32 precision was disabled in both TF and Torch tests
Precision of TF32 is not enough for NNCF tests. It's possible to use TF32 precision, but additional disscussion is needed
Checked locally on machine with TF32 support (RTX 3090)

Disable TF32 presicison in tests

---

Makefile
README.md
docker/onnx/openvinoep/Dockerfile.dev
docker/onnx/openvinoep/build.sh
examples/experimental/onnx/requirements.txt
nncf/experimental/onnx/algorithms/quantization/utils.py
nncf/experimental/onnx/requirements.txt
tests/onnx/quantization/test_classification_models_graph.py
tests/onnx/requirements.txt
tests/onnx/sanity_tests/test_classification_sanity_sample.py

- Revise installation steps of ONNXRuntime-OpenVINO
- `torchvision!=0.10.1` makes NNCFGraph of `mobilenet_v2` different with the reference.
- PIP installation order is important because `numpy` dependency makes conflict. So, I decided to make Makefile for installation.
https://jira.devtools.intel.com/browse/CVS-86349
https://jira.devtools.intel.com/browse/CVS-86350
- Passed all locally without xfail markers (`shufflenet_v2_x1_0`)
- `shufflenet_v2_x1_0` raises an error after quantization. It doesn't happen when using `CPUExecutionProvider`, but only when using `OpenVINOExecutionProvider`. I think the reason we haven't found this so far is because we've been using CPUExecutionProvider. If `onnxruntime-openvino` is not installed properly, `ONNXRuntime` operates as `CPUExecutionProvider` by …

[CVS-86349, CVS-86350] Revise installation steps of ONNXRuntime-OpenVINO

---

setup.py

When installing NNCF with TF the following error pop up
`error: protobuf 4.21.1 is installed but protobuf<3.20,>=3.9.2 is required by {'tensorboard'}`
Steps to reproduce:
```
pip install -U pip
python setup.py install --tf
```
Temporary patch proposed (upper limit of protobuf version). Not sure if adding this additional explicit requirement is safe.
Protobuf releases new version, which is getting installed by TensorFlow but not supported by TensorBoard. For reference please see https://github.com/tensorflow/tensorflow/issues/56077.
Update is needed be able to install NNCF with TF.
[CVS-86310]

Limit the protobuf version - tensorflow requirement

---

tests/torch/test_compression_training.py

Small relaxation on the training test criteria for the mobilenet_v2 model quantization.
CI tests to be passed. Prob. related to https://github.com/openvinotoolkit/nncf/pull/1195

Update threshold for train test

---

tests/torch/nas/test_search.py

Fix missing import in `tests/torch/nas/test_search.py`
The current develop fails pylint.
Please see  `NNCF/job/precommit/job/ubuntu20_precommit_pytorch/9/`

Fix pylint for tests/torch/nas/test_search.py

---

examples/experimental/onnx/README.md
examples/experimental/onnx/yolov5/0001-Add-NNCF-ONNX-PTQ-example-notebook.patch

- Added a Git patch file to support ONNXRuntime PTQ for Yolov5 third-party.
- Updated `README.md` to guide users on how to use it.
- To enable Yolov5s through ONNX Post-Training quantization POC
72747
This PR would be merged without test because there is no code change.

Enable Yolov5s through ONNX Post-Training quantization POC

---

nncf/common/pruning/utils.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/multi_elasticity_handler.py
nncf/tensorflow/pruning/filter_pruning/algorithm.py
nncf/torch/pruning/filter_pruning/algo.py
nncf/torch/pruning/utils.py
tests/tensorflow/pruning/test_flops_pruning.py
tests/torch/pruning/filter_pruning/test_algo.py

Redundant input shape param was removed from `count_flops_and_weights_per_node` function.
`count_filters_num` now always takes into account pruned linear layers.
`collect_input_shapes` function isn't protected from case when input edges don't exist (unlike `collect_output_shapes`, which process nodes without output edges correctly). Turns out that output of `collect_input_shaped` used only in `count_flops_and_weights_per_node` function and could be easily replaced by linear layers `in_features` and `out_features` attributes
86889
No need

[Pruning] Input shapes param removal

---

nncf/torch/pruning/operations.py
tests/torch/nas/models/synthetic.py
tests/torch/nas/test_elastic_width.py

Co-authored-by: Zheng, Yi <yi.zheng@intel.com>
Add input_reorder and output_reorder for linear layer
Enable weights reordering for linear layer. Please see how other layers already have enabled weight reordering. This is used by BootstrapNAS for its [filter reordering algorithm](https://github.com/openvinotoolkit/nncf/blob/d5e9edf8f335fc6d97825ddc07cfbd03594defd2/nncf/experimental/torch/nas/bootstrapNAS/elasticity/filter_reorder.py#L50): 
Added test in BootstrapNAS tests

Add reorder weights for Linear layer

---

examples/experimental/onnx/classification/onnx_ptq_classification.py
examples/experimental/onnx/performance_checker.py
examples/experimental/onnx/run_ptq.py
examples/experimental/onnx/semantic_segmentation/onnx_ptq_segmentation.py
nncf/common/tensor.py
nncf/experimental/onnx/datasets/imagenet_dataset.py
nncf/experimental/onnx/datasets/segmentation_dataset.py
nncf/experimental/onnx/engine.py
nncf/experimental/onnx/samplers.py
nncf/experimental/onnx/statistics/collectors.py
nncf/experimental/post_training/api/dataset.py
nncf/experimental/post_training/api/engine.py
nncf/experimental/post_training/api/metric.py
nncf/experimental/post_training/api/sampler.py
nncf/experimental/post_training/samplers.py
tests/onnx/quantization/common.py
tests/onnx/sanity_tests/test_classification_sanity_sample.py
tests/onnx/sanity_tests/test_segmentation_sanity_sample.py
tests/onnx/test_samplers.py
tests/onnx/test_statistics_aggregator.py

- Add `NNCFData` data type which is a dictionary with string key and tensor values.
- Revise ONNX PTQ pipeline to handle `NNCFData` as inputs and outputs.
- ONNX PTQAPI fails for `yolov3-12` and `tiny-yolov3-11` models. This is because those models require to put `input_shape` tensor as their inputs. However, the current input pipeline cannot handle this case.
86465

Revise ONNX PTQ pipeline

---

examples/experimental/onnx/README.md
examples/experimental/onnx/det_and_seg/onnx_models_configs/tiny-yolov3-11.yml
examples/experimental/onnx/det_and_seg/onnx_models_configs/yolov3-12.yml
examples/experimental/onnx/run_ptq.py
nncf/experimental/onnx/graph/nncf_graph_builder.py

Please merge this after https://github.com/openvinotoolkit/nncf/pull/1214.
- Give `GraphConverter.DEFAULT_TENSOR_SHAPE` to input and output nodes when it cannot infer shape as same as https://github.com/openvinotoolkit/nncf/blob/d5e9edf8f335fc6d97825ddc07cfbd03594defd2/nncf/experimental/onnx/graph/nncf_graph_builder.py#L66-L75
- Fix `run_ptq.py` to accept `ignored_scopes` parameter from the config file.
- Update model accuracy and performance in `README.md`
- To support ONNX PTQ API for `yolov3-12` and `tiny-yolov3-11` models
86465

Fix ONNX PTQ API for yolov3-12 and tiny-yolov3-11 models

---

examples/experimental/onnx/README.md
examples/experimental/onnx/det_and_seg/onnx_models_configs/yolov4.yml
nncf/experimental/onnx/algorithms/quantization/min_max_quantization.py
tests/onnx/quantization/common.py
tests/onnx/quantization/test_graphs.py

Please merge this after https://github.com/openvinotoolkit/nncf/pull/1216.
- Prevent PTQ API from adding the duplicate weight quantizers.
- Update yolov4 `ignore_scopes`.
- Update `README.md` with the latest benchmark results.
- If there are many operators sharing the identical weight tensor, ONNX PTQ API failed.
86465

[ONNX PTQ API] Fix retinanet-9

---

examples/experimental/onnx/README.md
examples/experimental/onnx/run_ptq.py
nncf/experimental/onnx/algorithms/quantization/min_max_quantization.py
nncf/experimental/onnx/model_normalizer.py
nncf/experimental/post_training/compression_builder.py
tests/onnx/quantization/common.py
tests/onnx/quantization/test_graphs.py

- Support `opset` version < 13
- Block per channel quantization for `opset` version < 13 models
- Add `convert_opset_version` flag to `CompressionBuilder`
- Add test cases for `opset` version < 13
- Update ssd-12 benchmark results
Support PTQ API for ssd-12 model which cannot be converted to `opset_version=13`
87359

[ONNX PTQ API] Fix ssd-12

---

examples/experimental/torch/classification/bootstrap_nas_search.py
nncf/config/experimental_schema.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_width.py
nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_controller.py
nncf/experimental/torch/nas/bootstrapNAS/training/stage_descriptor.py
tests/torch/nas/test_all_elasticity.py

Co-authored-by: Zheng, Yi <yi.zheng@intel.com>
- Add sample rate for subnet sampling in BootstrapNAS.
- The PR also fixes an import in BootstrapNAS subnet search example and adds a call to the visualization of the search. 
This PR enables the adjustment of the subnet sampling rate to improve training efficiency significantly while maintaining the original accuracy. This improvement is motivated by the paper ***Does Interference Exist When Training a Once-For-All Network?*** by Jordan Shipard et al., 2022. 
N/A
Modified elasticity test to include sample rate.

Add sample rate for subnet sampling in BootstrapNAS and fix search example

---

docs/compression_algorithms/Pruning.md
nncf/common/pruning/schedulers.py
nncf/common/pruning/statistics.py
nncf/common/pruning/utils.py
nncf/config/schema.py
nncf/tensorflow/pruning/filter_pruning/algorithm.py

Rebase of #1028 
Added new section to documentation that describes filter pruning algorithm statistics
To provide a better understanding of algorithm logs.
https://github.com/openvinotoolkit/nncf/issues/1011
73888

Add pruning stats docs

---

third_party_integration/huggingface_transformers/0001-Modifications-for-NNCF-usage.patch

Based on HF patch, models used to be exported before QAT. Model exporting is moved further to export the model after QAT.
Previously, if the option "--to_onnx" is used with "--do_train", the model was exported before the training. So, we have to train the model, save the checkpoint, and export the model after when evaluating the model from the saved checkpoint. The reason of this changes is to enable using "--to_onnx" while training as well. So, with this change, the model model will not be exported right after it is compressed. It will be exported when the training is completed.
Tested on question answering. Other scripts should be validated as well. I am not confident if the change break anything and it would be better if this can be tested by someone else who is more experienced with …

Updated placement of exporting model

---

examples/torch/classification/main.py
examples/torch/requirements.txt
setup.py
tests/torch/requirements.txt

- Fix PyTorch examples' pip dependency.
- Fix PyTorch classification examples' Tensorboard logging.
While I have been working on https://github.com/openvinotoolkit/nncf/pull/1238, I found some buggy things.
- It failed when I made a new virtual environment for PyTorch examples and ran example code as follows.
1. Install NNCF
2. Install `pip install examples/torch/requirements.txt`
3. Run `examples/torch/classification/main.py`
- This is because `efficientnet_pytorch` dependency exists in `tests/torch/requirements.txt`, but not in `examples/torch/requirements.txt`.
- We log average statistics, not online statistics to Tensorboard. This is not a common practice when using Tensorboard. It makes this strange cascading pattern for losses which should be continuously smooth across epochs. …

Fix PyTorch examples

---

nncf/config/experimental_schema.py
nncf/experimental/torch/nas/bootstrapNAS/search/search.py
nncf/experimental/torch/nas/bootstrapNAS/training/stage_descriptor.py

Enable BootstrapNAS search component to use its own parameters for BN adaptation 
User might want to use a different BN adaptation parameters for training the super-network and searching for sub-networks. 
N/A

Search BN Adapt

---

nncf/tensorflow/graph/utils.py
nncf/tensorflow/helpers/model_creation.py
tests/experimental/tensorflow/test_keras_layer_model.py
tests/tensorflow/requirements.txt

We get an exception if we try to run tensorflow experimental quantization algorithm with model that contains `tensorflow_hub.KerasLayer`.
The tensorflow experimental quantization has not supported models with `tensorflow_hub.KerasLayer` layer yet. This layer contains already compiled subgraphs so we cannot wrap operations inside them. When we try to run the algorithm on such model we get strange error. Please look at this GitHub [issue](https://github.com/openvinotoolkit/nncf/issues/1161). Current changes resolves this problem. Now we get the message which explains the reason.
Ref: 88614
N/A

Handle KerasLayer in the experimental_quantization algorithm

---

docs/compression_algorithms/Binarization.md
docs/compression_algorithms/KnowledgeDistillation.md
docs/compression_algorithms/Pruning.md
docs/compression_algorithms/Quantization.md
docs/compression_algorithms/Sparsity.md

mathematical equations in "compression_algorithms" have been changed from png to text, using LaTex formatting, which is rendered by GitHub natively and can be processed by Sphinx using Mathjax.
images are not visible in darkmode and are not searchable
81822

Math png to text

---

tests/torch/conftest.py
tests/torch/test_sanity_third_party.py

Introduced --torch-with-cuda11 option for 3rd party sanity tests to install torch compatible with GTX3090.
There's issue with torch installation inside a 3rd party test.
The 3rd party sanity test creates a virtual python environment by itself. Particularly, it installs default pytorch 1.9.1 with CUDA 10 support.
```python
BKC_TORCH_VERSION=1.9.1
pip_runner.run_pip("install torch=={}".format(BKC_TORCH_VERSION))
```
The target hardware might have RTX-3090 cards, which requires torch with CUDA 11 support.
It can be installed as follows:
```bash
pip install torch==1.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html 
```
Currently, the corresponding CI job has RTX3090 card now. As results, test fails with the following error:
```
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 …
```

Introduced --torch-with-cuda11 option for 3rd party sanity tests

---

tests/tensorflow/requirements.txt
tests/torch/requirements.txt

The `virtualenv` was added to the `tests/tensorflow/requirements.txt` file.
The `install_tf` job from the nightly jobs has not been passed.
Ref: 89150

test_install was fixed for TF, PT backends

---

tests/torch/test_sanity_third_party.py

Updated datasets dependency to solve some bugs in transformers' code.
Also use `pip install -e .` to install editable nncf. 
CI uses python3.7 that is fine with invoking setup.py for installing nncf. But for python3.8 it pulls some incompatible package versions (numpy, scipy) and tests fail.
A recommendation from [spec](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#working-in-development-mode)
`pip install -e .`  solves the issue.
Also, there were 3 tests failing:
`test_ner_train` failed with
```python
FileNotFoundError: Couldn't find file at https://github.com/davidsbatista/NER-datasets/raw/master/CONLL2003/train.txt
```
The link to the file was corrected in the new version of datasets: 
https://github.com/davidsbatista/NER-datasets/issues/8 …

Fix third-party sanity tests

---

nncf/common/graph/graph.py

Add output_port_id, input_port_id to the NNCFGraph visualization.
To be able to see the ports connection between nodes in the graph visualization. To speed up graph debugging.
The request from the comments in PR #1263 
No tests

Add output_port_id, input_port_id to the NNCFGraph visualization

---

tests/torch/pruning/helpers.py

Amount of channels and initialization of conv layers of HRNetBlock in pruning tests was updated to make is possible to actually prune and export this block. It's needed to start Ngraph pruning transformation experimenting
88441

Minor: make HRNetBlock actually prunable

---

docs/styleguide/PyGuide.md

Removed a couple of recommended docstring locations from class documentation style guide.
These particular documentation locations seem to be superfluous. 
N/A
N/A

Remove excessive docstring locations

---

tests/torch/data/search_building_block/BERT
tests/torch/data/search_building_block/ViT
tests/torch/data/search_building_block/wave2vec 2.0

Updated reference graph for block search tests
https://github.com/openvinotoolkit/nncf/pull/1273 introduced new layer - NNCFLayerNorm, but block search tests weren't updated correspondingly
n/a
test_transformer_building_blocks

Fixed degradation in block search tests with LayerNorm

---

nncf/tensorflow/graph/metatypes/matcher.py

Fixed typo in the docstring of the get_keras_layer_metatype function
Incorrect docstring
N/A
N/A

Fixed typo in the docstring of the get_keras_layer_metatype function

---

tests/torch/test_sanity_third_party.py
third_party_integration/huggingface_transformers/0001-Modifications-for-NNCF-usage.patch
third_party_integration/huggingface_transformers/README.md

Updated patch for NNCF integration to the latest transformers release (v4.23.1)
for smoother integration of JPQD #1319
94449
3rd party sanity

Updated patch for NNCF integration to the latest transformers release

---

nncf/tensorflow/quantization/algorithm.py
tests/tensorflow/quantization/test_algorithm_quantization.py

Fixed the issue with num_bn_adaptation_samples=0
The quantization algorithm for Tensorflow backend fails if num_bn_adaptation_samples=0 with the following error message:
```
def _run_batchnorm_adaptation(self, model: tf.keras.Model) -> None:
if self._bn_adaptation is None:
>           self._bn_adaptation = BatchnormAdaptationAlgorithm(self._bn_adapt_params['data_loader'],
self._bn_adapt_params['num_bn_adaptation_samples'],
self._bn_adapt_params['device'])
E           TypeError: 'NoneType' object is not subscriptable
```  
N/A
test_quantization_with_bn_adaptation_disable

Fixed the issue with num_bn_adaptation_samples=0

---

nncf/__init__.py
nncf/openvino/quantization/helpers.py
nncf/parameters.py
nncf/quantization/__init__.py
nncf/quantization/helpers.py
tests/openvino/__init__.py
tests/openvino/quantization/__init__.py
tests/openvino/quantization/test_helpers.py
tests/tensorflow/README.md
tests/tensorflow/conftest.py
tests/torch/conftest.py

Added the ignored scope parameter to the quantize function signature. Support the ignored scope in the OpenVINO backend.
Feature alignment with POT OpenVINO
N/A
[test_helpers.py](https://github.com/openvinotoolkit/nncf/blob/1f09ad3b4cb5c3b6805bece2abb3a4e29f564cc5/tests/openvino/quantization/test_helpers.py)

Added the ignored scope parameter to the quantize function signature

---

setup.py

Should fix the following error on test_force_cuda_build[venv-develop-GPU]:
`RuntimeError: Ninja is required to load C++ extensions`
Restricted ninja version to be not higher than 1.11
`RuntimeError: Ninja is required to load C++ extensions`
n/a
test_force_cuda_build

Restricted ninja version to be not higher than 1.11

---

nncf/torch/binarization/binarize_functions.py
nncf/torch/quantization/quantize_functions.py

Warning-level outputs here are unnecessary and clog the output. The user cannot do anything about this kind of warning anyway.
N/A
Manual runs of unet_camvid_int8 training in PT

Remove contiguous grad_output warning

---

README.md
setup.py

The lowest supported python version was increased to 3.7.0
OpenVINO will deprecate support for the 3.6 version.
N/A
N/A

Support for Python 3.6 was removed

---

examples/torch/classification/main.py
examples/torch/common/utils.py
tests/torch/conftest.py
tests/torch/test_compression_training.py
tests/torch/test_sota_checkpoints.py

Support of mixed precision training in NNCF PT classification sample by torch.cuda.amp autocasting. Mixed precision mode is being enabled by `--mixed-precision` key. Default behavior - FP32 training.
Weekly test with mixed precision is introduced.
To test FP16 kernels by the NNCF weekly test
79587

[Torch] Weekly test with mixed precision

---

nncf/experimental/torch/nas/bootstrapNAS/elasticity/base_handler.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_depth.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_width.py
tests/torch/nas/test_all_elasticity.py

(1) Add depth_indicator in ctrl_state.
(2) Add width_num_params_indicator in ctrl state.
The current version of the training controller state does not save 'depth_indicator' and 'width_num_params_indicator'.
When we load 'last_elasticity.pth' in 'bootstrap_nas_search.py', 'depth_indicator' and 'width_num_params_indicator' will use default values (1 and -1 respectively) instead of values in the config.
This means that in some cases(e.g. 'depth_indicator' > 1 in config), when we use 'bootstrap_nas_search.py' to search the best subnet, the search space is different from what we designed due to different values of 'depth_indicator' and 'width_num_params_indicator'.
N/A
Fixed test_all_elasticity

BNAS: State for depth and width indicators

---

docs/compression_algorithms/Quantization.md

Provided examples of compression ratio for uniform quantization with different bitwidth
clarifications for the users
https://github.com/openvinotoolkit/nncf/discussions/1380
n/a

Added small clarifications about compression ratio in HAWQ

---

nncf/experimental/torch/nas/bootstrapNAS/elasticity/elasticity_controller.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/onnx_export.py
nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_controller.py
nncf/torch/exporter.py
nncf/torch/quantization/layers.py
nncf/torch/quantization/quantize_functions.py
tests/torch/helpers.py
tests/torch/nas/models/synthetic.py
tests/torch/nas/test_all_elasticity.py
tests/torch/nas/test_elastic_depth.py
tests/torch/nas/test_onnx_export.py
tests/torch/quantization/test_onnx_export.py
tests/torch/quantization/test_overflow_issue_export.py

- export to ONNX in EVAL mode by default
- export to ONNX in TRAINING mode for NAS in order to avoid hang. Most probably it happens because of incompatibility of skipped layer in Elastic Depth with optimizations/fusings on export in EVAL mode.
- remove error for per-channel Q-DQ export
The behavior of exporting in training mode had been changed, and it started producing invalid graph for evaluation, as result e2e validation started to fail on accuracy validation
96710
e2e torch

Fix export of SOTA checkpoints for e2e validation

---

nncf/common/utils/progress_bar.py
tests/common/test_progress_bar.py

In the examples below whitespaces got squashed. Couldn't find a way to format it properly here. In reality, all "|" symbols are below each other.
**Before:**
INFO:nncf:Collecting tensor statistics █                 | 1 / 16
INFO:nncf:Collecting tensor statistics ██                | 2 / 16
INFO:nncf:Collecting tensor statistics ███               | 3 / 16
INFO:nncf:Collecting tensor statistics ████              | 4 / 16
INFO:nncf:Collecting tensor statistics █████             | 5 / 16
INFO:nncf:Collecting tensor statistics ██████            | 6 / 16
INFO:nncf:Collecting tensor statistics ███████           | 7 / 16
INFO:nncf:Collecting tensor statistics ████████          | 8 / 16
INFO:nncf:Collecting tensor statistics █████████         | 9 / 16
INFO:nncf:Collecting tensor statistics …

ProgressBar formatting improvement

---

nncf/experimental/torch/nas/bootstrapNAS/search/search.py
nncf/experimental/torch/nas/bootstrapNAS/training/lr_scheduler.py
nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_builder.py
nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_controller.py
nncf/experimental/torch/nas/bootstrapNAS/training/scheduler.py
tests/torch/nas/creators.py
tests/torch/nas/test_all_elasticity.py
tests/torch/nas/test_ps_controller.py
tests/torch/nas/test_scheduler.py
tests/torch/nas/test_search.py

(1) When num_bn_adaptation_samples = 0, batchnorm adaptation will be skipped
(2) Add function "get_last_lr". This function will be used in Hugging Face patch.
(3) Add property for lr_scheduler. This will be used in Hugging Face patch.
Substep to implement a patch for HF Transformers for BootstrapNAS
N/A
N/A

BNAS: Allow disabling BN Adaptation

---

nncf/torch/binarization/binarize_functions.py
nncf/torch/exporter.py
tests/torch/quantization/test_adjust_padding.py
tests/torch/test_onnx_export.py

Bumped onnx opset version on export to support Q-DQ format for per-channel quantization
One commit on top of https://github.com/openvinotoolkit/nncf/pull/1384, which should be merged soon.
e2e tests fail for Q-DQ mode
96710
e2e torch

Use ONNX opset 13 on torch export

---

tests/torch/experimental/search_building_blocks/test_transformer_blocks.py
tests/torch/requirements.txt

Use randomly initialized models from configs without downloading and loading pre-trained weights
Also pinned a specific transformers version == 4.23.1
- Reduce dependency from stable internet connection. 
There's a PR https://github.com/openvinotoolkit/nncf/pull/1249 that sporadically failed with error on downloading weights:
`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)`
- Saves ~1.5 minutes of Pytorch precommit by not downloading weights
n/a
test_transformer_building_blocks

Removed weights downloading in tests for searching blocks in transformers

---

README.md

CUDA version was changed from `11.7` to `11.6` in the readme
According to official documentation torch1.12.1 works only with CUDA versions `10.2`, `11.3`, `11.6` and not working with `11.7`
https://pytorch.org/get-started/previous-versions/

Fix CUDA version in the README.md

---

README.md
setup.py
tests/cross_fw/install/install_checks_torch.py
tests/cross_fw/install/test_install.py
tests/shared/helpers.py

READMEs and tests are adjusted to use the `pip install` approach instead of the `python setup.py` approach.
`python setup.py` direct calls are deprecated in the community.
N/A
cross_fw/install/test_install

Remove direct setup.py installation

---

tests/onnx/test_e2e_ptq.py

Adjusted indentation on HTML report dumping code.
Multi-line strings are output with indents. The original implementers really should have used HTML-as-code approach that we have in the rest of the E2E report generating tests.
N/A
e2e_onnx

Fix HTML rendering for E2E ONNX

---

tests/cross_fw/install/test_install.py
tests/shared/helpers.py

Fixed leftovers from #1390 to enable correct testing for the PT GPU installation
Install tests fail otherwise.
N/A
tests/cross_fw_install

Fix torch install

---

examples/tensorflow/requirements.txt

Originally the versions were fixed as a workaround for direct setup.py installation issues. Now that we deprecate this installation approach, the hacks are not required.
N/A
cross_fw/install

Remove fixed protobuf versions from requirements

---

nncf/torch/pruning/utils.py
tests/torch/pruning/filter_pruning/test_algo.py
tests/torch/pruning/helpers.py

Output shape calculation for linear layers in case of the output edge is absent was added.
`DisconectedGraphModel` in tests was fixed to be actually disconnected
Pruning isn't working in DOR due to latest linear layer has no output edge because of output node absence
Tests was updated

Linear output shape collection fix

---

nncf/torch/quantization/layers.py
nncf/torch/quantization/quantize_functions.py

Added detection of the per-channel axis in Q-DQ export in PT and proper setting of the `axis_i` attribute for the ONNX ops
mobilenet_v2_imagenet_int8 fails to be converted by MO in Q-DQ export mode due to presence of per-channel activation quantized eltwise convs which had `axis` erroneously set to 0 in Q-DQ ops
N/A
e2e_pt, unit tests TBA

Export Q-DQ for correct axis in torch

---

nncf/telemetry/wrapper.py
tests/common/test_telemetry.py

When launched in a pytest context, NNCF won't be sending telemetry. This applies even to usages of NNCF in pytest runs other than our own (i.e. in dependent tools' testing pipelines).
Keeping test runs out of telemetry.
78624
test_telemetry

Do not send telemetry if in pytest

---

nncf/torch/pruning/filter_pruning/layers.py
nncf/torch/sparsity/layers.py
tests/torch/pruning/filter_pruning/test_layers.py
tests/torch/test_algo_common.py

Export sparsity models with non-in-place (`mul` instead of `mul_`) multiply operation.
User doesn't expect that export to onnx would do something with parameters. 
It could break convergence if user wants export on each epoch (e.g. saving checkpoint in Optimum requires export to ONNX and conversion to IR).
n/a

No weights override on sparsity model's export

---

tests/torch/sota_checkpoints_eval.json

Threshold for mobilenet_v2_int4_int8 is increased
Quantized model has validation metric close to the threshold (-0.97%), any small deviation makes this model fall.
Model should be retrain in future to gain better validation metric
99626

[Torch][SOTA eval] Threshold for mobilenet_int4_int8 is updated

---

setup.py

Fixed OpenVINO version "openvino-dev~=2022.2.0"
Workaround for the OpenVINO pre-commit CI issue.
N/A
N/A

Fixed OpenVINO version

---

examples/torch/README.md
examples/torch/requirements.txt
nncf/torch/binarization/binarize_functions.py
setup.py
tests/torch/data/reference_graphs/quantized/synthetic_model/ConvRelu6HSwishHSigmoid.dot
tests/torch/experimental/search_building_blocks/test_transformer_blocks.py
tests/torch/nas/test_elastic_depth.py
tests/torch/nas/test_sanity_sample.py
tests/torch/sparsity/movement/test_model_saving.py
tests/torch/sparsity/movement/test_structured_mask.py
tests/torch/sparsity/movement/test_training.py
tests/torch/test_graph_building.py
tests/torch/test_models/synthetic.py
tests/torch/test_sanity_sample.py

Loosened requirements for torch and torchvision:
```
0.9.2<=torchvision<0.15
1.8.2<=torch<1.14
```
Fixed failures in pre-commit tests. 
Some of them were conditionally skipped, some were adapted for different torch versions.
Some modification were made in NNCF as well (e.g. fix binarize functions for torch 1.8.2).
Support of PyTorch versions <1.12 has been broken in #1323. It should be recovered. 
It's proposed to manually validate 1.8.2 as Geti uses it. Then recover it for 1.9.1.
99051
Besides pre-commit scope on torch 1.13.1, manual test for torch 1.8.2, torch 1.9.1 and torch 1.12.1

Recover pytorch version < 1.12

---

examples/tensorflow/requirements.txt
tests/tensorflow/requirements.txt

Bump tensorflow_addons version
Fix user warning:
```
Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.4.0 and strictly below 2.7.0 (nightly versions are not supported). 
The versions of TensorFlow you are currently using is 2.8.4 and is not supported.
```
N/A
e2e 197

tensorflow_addons~=0.16.1

---

nncf/torch/nncf_network.py
tests/torch/test_nncf_network.py

Type checking fixed in insertion type translation inside `PTInsertionPoint`
In case `PTInsertionType` is passed to `PTInsertionPoint` and its id will match `InsertionType` id, it will be translated in a wrong way

[Torch][Microfix] PTTarget point translation fix

---

nncf/common/logging/logger.py
nncf/common/utils/logger/__init__.py
tests/torch/test_backward_compat.py
tests/torch/test_load_model_state.py

Some code seems to rely on the old import paths.
N/A
Manual (`from nncf.common.utils.logger import logger`, `from nncf.common.utils.logger import set_log_level` etc.)

Restore logging imports and mark legacy import as deprecated

---

nncf/torch/quantization/metrics.py

Torch quantization statistic collector moved to use metatypes
To escape `get_all_aliases` usage in quantization algo

Torch quantization statistic collector moved to metatypes

---

examples/torch/object_detection/configs/ssd300_vgg_voc_pruning_geometric_median.json

Remove incorrect ignored_scopes for `ssd300_vgg_voc_pruning_geometric_median` model because conv2d layers ignored by `Prunable: False; Reasons: [<PruningAnalysisReason.MODEL_ANALYSIS: 'of model analysis'>]`
CVS-100105

Fix config ssd300_vgg_voc_pruning_geometric_median

---

docs/compression_algorithms/Pruning.md
nncf/common/pruning/shape_pruning_processor.py
nncf/tensorflow/pruning/filter_pruning/algorithm.py
nncf/torch/pruning/filter_pruning/algo.py
tests/tensorflow/pruning/test_algorithm.py
tests/torch/pruning/filter_pruning/test_flops_pruning.py
tests/torch/pruning/filter_pruning/test_set_pruning_rate.py

Renamed `pruning_rate` to `pruning_level` for TF pruning controller
Everywhere in the codebase `pruning_level` is used for compression rate of pruning controller except multiple places in TF implementation of pruning controller

Renamed pruning_rate to pruning_level for TF pruning controller

---

Makefile
examples/experimental/openvino/bert/requirements.txt
examples/experimental/openvino/yolo_v5/requirements.txt
tests/experimental/tensorflow/__init__.py

Extending makefile for OpenVINO, TensorFlow and PyTorch backends
Simplify validation process
N/A
N/A

Extending makefile for OpenVINO, TensorFlow and PyTorch backends

---

nncf/openvino/quantization/quantize.py

- fix model_type config providing for pot configuration
- allow to run with openvino 2022.3 where algo already registred
inability to successfully run quantization for openvino notebooks

[OV]: fixes for quantize_with_accuracy_control

---

nncf/openvino/quantization/quantize.py
nncf/quantization/quantize.py

Type hints were fixed for the `quantize_with_accuracy_control` method.
Type hints were wrong.
N/A
N/A

Type hints were fixed

---

tests/torch/data/configs/unet_camvid_int8.json
tests/torch/data/configs/unet_camvid_rb_sparsity.json
tests/torch/test_sanity_sample.py

Workaround for the hang on CPU: https://discuss.pytorch.org/t/backward-hangs-on-torch-for-cpu/169282
Set number of threads = 1 to avoid hang for backward on UNet.
Presumably, it might happen when OpenMP is used before fork.
Sanity test was simplified in order to compensate slowdown on a single CPU thread. It takes 10 seconds more than without the workaround, but still 7 seconds faster than it was on develop branch.
permanent hang of tests on hosts with `Intel(R) Core™ i9-10980XE CPU @ 3.00GHz`
100106

Workaround for the hang in sanity tests with --cpu-only option

---

nncf/telemetry/__init__.py
nncf/telemetry/decorator.py
nncf/telemetry/wrapper.py
tests/common/test_telemetry.py
tests/shared/helpers.py

Better UX - the telemetry calls are not essential and failures therein must be ignored.
100503
test_telemetry

Wrap telemetry object to ignore exceptions triggered in the telemetry backend

---

setup.py

Update some dependencies in preparation for upcoming Python 3.11 support. In theory `networkx` and `pyparsing` versions do not support Python 3.11, but installing them locally works. They were not updated as there are tickets related to them.
Old versions do not support Python 3.11 according to their corresponding PyPI pages.
98870

Update requirements in preparation for Python 3.11

---

setup.py

Better compatibility of dependencies
Fixes: #1482 
Existing `*schema` tests in torch scope

Relax jsonschema requirements

---

nncf/common/utils/decorators.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/elasticity_controller.py
nncf/experimental/torch/nas/bootstrapNAS/search/search.py
nncf/torch/quantization/precision_init/hawq_debug.py
setup.py

matplotlib dependency has been moved under dev extra.
OpenVINO notebooks have compatibility issues with matplotlib dependency.
Custom request
N/A

Removing matplotlib from the mandatory requirements

---

nncf/common/accuracy_aware_training/runner.py
nncf/common/accuracy_aware_training/training_loop.py
nncf/common/quantization/quantizer_propagation/solver.py
nncf/experimental/torch/sparsity/movement/algo.py
nncf/experimental/torch/sparsity/movement/scheduler.py
nncf/experimental/torch/sparsity/movement/structured_mask_handler.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/torch/debug.py
nncf/torch/dynamic_graph/io_handling.py
nncf/torch/dynamic_graph/patch_pytorch.py
nncf/torch/dynamic_graph/wrappers.py
nncf/torch/extensions/__init__.py
nncf/torch/pruning/base_algo.py
nncf/torch/pruning/filter_pruning/algo.py
nncf/torch/quantization/precision_init/autoq_init.py
tests/onnx/opset_converter.py

Forgot to set a proper log level at nncf/torch/pruning/base_algo.py:117 so that a message was printed for every weight pruned in INFO level, while it should have been printed to DEBUG. Also made the rest of the non-f-string-constructed parametrized log strings actually use f-strings.
Follow-up for the things that slipped away in the previous log-related PR.
N/A
N/A

Fix the rest of the log string creation

---

nncf/torch/composite_compression.py
tests/torch/composite/test_sparsity_quantization.py

- Fixed implementation of `compression_rate` property for `PTCompositeCompressionAlgorithmController`: it did not work correctly when some of the child controllers didn't implement the property
- Added a corresponding test
PR #1437 introduced a wrong implementation of the property
101212
Added a simple test based on quantization + sparsity composite controller

Fix for compression_rate property of PTCompositeCompressionAlgorithmController

---

examples/torch/common/execution.py

A single-line change to reflect the new API in PyTorch.
The old way has been deprecated since 1.8. The newly re-enabled compression training tests caught this.
N/A
tests/torch/test_compression_training.py

Use new version of requesting deterministic algorithms in PyTorch

---

nncf/openvino/engine.py
tests/openvino/tools/calibrate.py

`DatasetWrapper` was improved. It is a temporary class. It will be removed when we will switch on native implementation. 
The `nncf.quantize()` method is slower than POT.
**Before Fix:**
Elapsed Time: 00:04:01
**After Fix:**
Elapsed Time: 00:00:31
Ref: 100984
N/A

Time for the dataset's length estimation was improved

---

setup.py

Add synonyms for the `tf` and `torch` in context of extra dependency installation, i.e. now can run `pip install .[tensorflow]` to do the same thing as `pip install .[tf]`.
Consistency with `openvino-dev` extras syntax makes for better UX.
N/A
N/A

Add aliases for backend extra installation

---

nncf/torch/model_creation.py
tests/torch/data/configs/weekly/classification/cifar100/mobilenet_v2_rb_sparsity_int8.json

Ignored scope was assigned incorrectly in the config used in a case in test_compression_training. Also restored dumps of `original_graph.dot` at model creation in PT.
Tests failing.
N/A
PT test_compression_train[mobilenet_v2_rb_sparsity_int8_cifar100_multiprocessing-distributed]

Fix ignored scope setting in compression training test

---

tests/openvino/tools/calibrate.py

The `transform_fn()` was fixed.
I got the following error:
```
File "openvino/tools/pot/engines/ie_engine.py", line 242, in process_input
is_loader_batchfied = input_dim(input_blob) == input_data[0].ndim
AttributeError: 'list' object has no attribute 'ndim'
```
N/A
N/A

Fix calibrate tool

---

tests/torch/data/configs/weekly/classification/cifar10/mobilenet_v2_nas_SMALL.json
tests/torch/test_compression_training.py

1) Restricted the maximum number of nodes in block for mobilenet-v2 in order to match previous setup in weekly test.
2) Decreased expected accuracy for vgg, since after #1281 B-NAS skip 1 block. Previously, it skipped nothing and consequently accuracy was higher.
2 failures in the test_compression_training.py (build 3)
n/a
local run of test_compression_training.py

Fixed weekly NAS tests

---

nncf/experimental/openvino_native/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/bias_correction/backend.py
nncf/quantization/algorithms/bias_correction/onnx_backend.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/backend.py
nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/min_max/backend.py
nncf/quantization/algorithms/min_max/onnx_backend.py

Redundant model_transformer property was removed from the algorithm's backends.
- `ModelTransformerFactory` is not used.
N/A
N/A

Redundant model_transformer property was removed from algo backends

---

examples/torch/object_detection/datasets/voc0712.py

Fixes some of the issues in PT compat E2E tests for 1.8.2 and 1.9.1
N/A
e2e compat PT tests

Use parse_voc_xml in a backwards-compatible way with old torchvision

---

examples/tensorflow/requirements.txt
nncf/common/hardware/config.py
nncf/openvino/quantization/accuracy_aware.py
setup.py
tests/experimental/tensorflow/test_compressed_graph.py
tests/experimental/tensorflow/test_context_independence.py
tests/openvino/pot/test_engine.py
tests/openvino/requirements.txt
tests/tensorflow/pruning/helpers.py
tests/tensorflow/quantization/utils.py
tests/tensorflow/sparsity/magnitude/test_algorithm.py
tests/tensorflow/sparsity/magnitude/test_scheduler.py
tests/tensorflow/sparsity/rb/test_components.py
tests/tensorflow/sparsity/test_common.py
tests/tensorflow/test_bn_adaptation.py
tests/tensorflow/test_compressed_graph.py
tests/tensorflow/test_ignored_scopes.py

Removed `addict` and `wheel` from NNCF package dependencies and moved `pillow` dependency to the `[dev]` extra.
These dependencies are not strictly necessary for NNCF to function across the supported frameworks.
N/A
Precommit scope

Remove unnecessary dependencies

---

examples/torch/object_detection/layers/extensions/__init__.py
nncf/common/logging/logger.py
nncf/torch/binarization/binarize_functions.py
nncf/torch/binarization/extensions.py
nncf/torch/binarization/reference.py
nncf/torch/extensions/__init__.py
nncf/torch/quantization/extensions.py
nncf/torch/quantization/quantize_functions.py
nncf/torch/quantization/reference.py
tests/cross_fw/install/install_checks_torch.py
tests/shared/isolation_runner.py
tests/torch/binarization/test_functions.py
tests/torch/quantization/extensions/__init__.py
tests/torch/quantization/extensions/isolated_cases.py
tests/torch/quantization/extensions/test_extension_unavailable.py
tests/torch/quantization/test_algo_quantization.py
tests/torch/quantization/test_functions.py

As stated in the title. Also changed the way of loading extensions to the lazy approach, so that the extensions are only loaded if associated quantization or binarization functionality is invoked, meaning that non-INT8 workflows will have less points of failure for the user.
UX improvement due to not failing where we may keep working functionally.
94348
test_extension_unavailable

Use reference quantization on CPU if compiled extensions are unavailable

---

third_party_integration/huggingface_transformers/0001-Modifications-for-NNCF-usage.patch

The scopes didn't actually match to anything, and now that we have the runtime checking of such situations the `third_party_sanity` tests have been failing for a while. Some of the ignored scopes referred to GELU activations that were blown up in previous transformers versions, but starting from some point in time they were replaced with proper `gelu` operator calls, so there was no need to work around that with ignored_scopes anymore. Other ignored scopes were written in an old style when  they could be matched partially without regex, which means that they have been invalid for quite a while and it is unknown whether the config with or without them actually produces the claimed quantizer setup and accuracy.
N/A
third_party_sanity

Remove unmatched ignored scopes from HF configs

---

nncf/experimental/openvino_native/quantization/quantize.py
tests/openvino/native/quantization/test_quantization_pipeline.py

* Compressed `ov.Model` quantized weights
* To align NNCF OV PTQ with POT
* 102077
* Added test_compress_weights

[OV] Compress quantized weights

---

nncf/experimental/openvino_native/graph/transformations/command_creation.py
nncf/experimental/openvino_native/hardware/fused_patterns.py
nncf/experimental/openvino_native/quantization/algorithms/min_max/openvino_backend.py

Fixed pylint errors were found by the following command: `make pylint-openvino`
pylint errors
N/A
N/A

Pylint happy

---

tests/onnx/quantization/common.py
tests/onnx/test_nncf_graph_builder.py
tests/openvino/native/common.py
tests/shared/nx_graph.py
tests/tensorflow/test_compressed_graph.py
tests/tensorflow/test_transformations.py
tests/torch/automl/test_ddpg.py
tests/torch/binarization/test_functions.py
tests/torch/conftest.py
tests/torch/modules/test_rnn.py
tests/torch/nas/test_all_elasticity.py
tests/torch/nas/test_elastic_width.py
tests/torch/quantization/test_autoq_precision_init.py
tests/torch/quantization/test_functions.py
tests/torch/quantization/test_hawq_precision_init.py
tests/torch/test_compressed_graph.py
tests/torch/test_utils.py

As stated in the title. Also had to move the `_seed` fixture because it was imported implicitly by a package that I moved in this PR.
Code reuse and some improvement of the common code
N/A
.dot-checking tests

Align graph checks in OV code with common code

---

nncf/experimental/openvino_native/graph/metatypes/openvino_metatypes.py
nncf/experimental/openvino_native/graph/nncf_graph_builder.py
nncf/experimental/openvino_native/hardware/pattern_operations.py
nncf/experimental/openvino_native/quantization/default_quantization.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_ptq_params.py
tests/openvino/native/quantization/test_quantizer_config.py
tests/openvino/native/test_metatypes.py

* Add `OVDepthwiseConvolutionMetatype` as a subtype of `OVGroupConvolutionMetatype`
* To correctly quantize depthwise and group convolutions.
* 101928
* Added `DepthwiseConvModel` synthetic model for tests

[PTQ][OV] Support Depthwise, Group convolutions

---

nncf/torch/dynamic_graph/patch_pytorch.py
tests/torch/data/reference_graphs/quantized/synthetic_model/__matmul__.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/__rmatmul__.dot
tests/torch/test_compressed_graph.py

To support tracing of matmul expressed in the following way: a @ b
It's used in official implementation of SwinTransformer by Microsoft. 
NNCFGraph is disjointed without it.
n/a
graph tests

Added __matmul__ magic functions to the list of patched ops

---

examples/post_training_quantization/openvino/quantize_with_accuracy_control/README.md
examples/post_training_quantization/openvino/quantize_with_accuracy_control/main.py
examples/post_training_quantization/openvino/quantize_with_accuracy_control/requirements.txt

The example of quantization with accuracy control for OpenVINO backend
Demonstrate how to use Post-Training Quantization with accuracy control API.
`nncf.quantize_with_accuracy_control()` 
ref: 98687
TBD

The example of quantization with accuracy control for OpenVINO backend

---

tests/shared/nx_graph.py

Drop incorrect node after reading the dot graph
Bug of NetworkX - https://github.com/networkx/networkx/issues/5686
No
No

Fix issue with IO dot file

---

nncf/torch/dynamic_graph/patch_pytorch.py
tests/torch/pytorch_patch_isolated.py
tests/torch/test_pytorch_patch.py

The fact of importing of `nncf.torch` can lead to `torch.onnx.export` failing if the model being exported internally relies on [torch.jit.script_if_tracing](https://pytorch.org/docs/stable/generated/torch.jit.script_if_tracing.html). This is due to patching issues.
- Added patching of torch.jit._script_if_tracing
- Added a couple of tests

Added patching of torch.jit.script_if_tracing

---

nncf/telemetry/decorator.py
nncf/telemetry/wrapper.py
nncf/torch/dynamic_graph/wrappers.py

Makes NNCF-wrapped functions preserve original names and attributes, which will make NNCF patching less noticeable to external entities.
N/A
Existing PT precommit scope

Use functools.wraps on NNCF wrappers

---

examples/post_training_quantization/openvino/quantize_with_accuracy_control/main.py

Convert str to float.
The `max_frop` parameter in the `nncf.quantize_with_accuracy_control()` method should be float.
N/A
N/A

Incorrect type for max_frop parameter

---

nncf/torch/quantization/layers.py
tests/torch/quantization/test_algo_quantization.py

1. Add post_hook on `load_state_dict` to update `level_low` and `level_hight` for `SymmetrciQuantizer`.
2. Setter for signed got boolean value and cast to `int` inside function. To work with same type for getter and setter. (now type hint is actual.
3.  Add in setter of `signed` and `num_bits` parameters call `set_level_range` function. To have actual values of levels in all time.
```python
qspec = PTQuantizerSpec(
num_bits=4,
mode=QuantizationMode.SYMMETRIC,
signedness_to_force=None,
scale_shape=(1, ),
narrow_range=False,
half_range=False,
logarithm_scale=False
)
sq = SymmetricQuantizer(qspec)
sq.apply_minmax_init(torch.Tensor([-11]), torch.Tensor([11]))
loaded_sq = SymmetricQuantizer(qspec)
loaded_sq.load_state_dict(sq.state_dict())
```
This does not affect the behaviour of the models, …

Fix: out of sync level_ranges and signed parameter

---

nncf/experimental/openvino_native/statistics/aggregator.py
nncf/onnx/statistics/aggregator.py

Statistic collector registers constant statistics only ones
Constants don't change during inference, so registering them one is enough

[PTQ] Constant statistics aggregation optimization

---

nncf/experimental/tensorflow/quantization/algorithm.py
nncf/tensorflow/quantization/algorithm.py
nncf/torch/quantization/algo.py

Overflow fix for a first layer check should consider `conv3d` besides `conv2d`.
In general, all weighted ops should be considered, but this requires some refactoring, see ticket [104645]

Added conv3d to first layer overflow fix check

---

nncf/tensorflow/pruning/operations.py
nncf/torch/pruning/operations.py

`PTAvgPool2dMetatype` and `PTMaxPool2dMetatype` were in `PTIdentityMaskForwardPruningOp` but `PTAvgPool3dMetatype` and `PTMaxPool3dMetatype` not. Added.
Similarly for TF.

Added average pool 3d -like ops to pruning mask forwarding ops

---

nncf/torch/pruning/base_algo.py

For PT filter pruning, before `compression_ctrl.export_model()` call the pruned layer statistics are printed. They however are currently empty and do not reflect the actual pruned state of the model.
This is due the fact that `pruning_level_for_filters()` method used to retrieve statistics returns incorrect values. This in turn is due the fact that it relies on the number of zeros in the model weights. But weights are zeroed (pruned) only during model export and actual model weights are not zeroed during runtime.
Removed `pruning_level_for_weight()` and `pruning_level_for_filters()` altogether. Now `pruning_level_for_mask()` is the only method to compute the statistic.

[Pruning] Fixed statistics computation for pruned layers

---

tests/torch/quantization/test_functions.py

`test_function` is stabilized:
* min scale and min range level was increased to make quant length lager than min fp16 value
* input vs quantized output was made less strict for FP16 and was made more strict for FP32
For some inputs FP16 FQ maps middle quants with significant arithmetic error (input=x, exact quant placement=-173.5, output=x (exact x as input)) when quant level is divided by scale. 
For FP32: input vs quantized output differ no more than 0.5 + EPS of correspondent quant lengtg

[Torch] test_function stabilization

---

nncf/experimental/openvino_native/hardware/pattern_operations.py

Add OVClmapMetatype to ATOMIC_ACTIVATIONS_OPERATIONS
Fix bug with quantization scheme for mobilenetv2_050
No
No

[OV] Add Clamp to ATOMIC_ACTIVATIONS_OPERATIONS

---

nncf/experimental/openvino_native/graph/model_transformer.py
nncf/experimental/openvino_native/quantization/quantizer_parameters.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_fq_params_calculation.py
tests/openvino/native/test_model_transformer.py

For models coming from a framework in FP16 precision, FakeQuantize parameters should be in FP16.
For models coming from a framework in FP32 precision and converted to FP16 via MO, FakeQuantize parameters should be in FP32.
FQ parameters precision aligned with model input precision.
Input FP32
Input FP16
* To align NNCF PTQ with POT
* 103926, 101738

[OV] Align FQ params data type with target node  precision

---

nncf/openvino/quantization/accuracy_aware.py

Saving intermediate model was disabled.
nncf.quantize_with_accuracy_control() dumps accuracy_aware_intermediate by default. It looks like it should not be done by default.
Ref: 102887
N/A

Saving intermediate model was disabled

---

tests/openvino/tools/calibrate.py

Ignored scope for some models now is being calculated by model architecture and not depend on IR names
To make NNCF ignored scopes independent of MO names changes in OV convert test
105384

Calculated ignored scope for calibrate.py

---

nncf/torch/quantization/prepare_for_inference.py
tests/torch/quantization/test_prepare_for_inference.py

Add support ad tests for convert 4bit fakequantizer.
https://github.com/openvinotoolkit/nncf/pull/1526

Add support int4 for convert_to_torch_fakequantizer

---

tests/tensorflow/test_sota_checkpoints.py

Removed an autouse fixture that led to a scikit-images pre-installation step before TF E2E tests were being run.
The scikit-images now pulls with itself an incompatible numpy version and TF E2E are failing. The workaround might be no longer relevant for the latest OV anyway.
N/A
TF E2E + compat

Remove scikit pre-install step

---

nncf/experimental/openvino_native/graph/node_utils.py
tests/openvino/native/test_node_utils.py

The typo was fixed in the `get_weight_value()` method.
TypeError: get_input_edges() missing 1 required positional argument: 'node'
N/A
tests/openvino/native/test_node_utils.py

Typo was fixed

---

nncf/torch/quantization/adjust_padding.py
tests/torch/autograd_functions/test_autograd_functions.py
tests/torch/binarization/test_functions.py
tests/torch/conftest.py
tests/torch/modules/test_rnn.py
tests/torch/quantization/test_functions.py
tests/torch/quantization/test_onnx_export.py
tests/torch/quantization/test_prepare_for_inference.py
tests/torch/quantization/test_range_init.py
tests/torch/sparsity/movement/test_components.py

Extend list of fixtures which are often used to remove code duplicate and improve test names.
```
is_per_channel
is_signed
is_weights
use_cuda
is_half_range
quantization_mode
```
https://github.com/openvinotoolkit/nncf/pull/1526#discussion_r1108322175
104706

Extend fixtures in tests/torch/conftest.py

---

nncf/torch/dynamic_graph/patch_pytorch.py
nncf/torch/dynamic_graph/wrappers.py
tests/torch/test_pytorch_patch.py

Generally `torch.jit.script` is applied to methods, but in some cases it may be applied to classes, for example in `kornia` package. In such case NNCF patching of `torch.jit.script` is incorrect and leads to an error during import of the scripted class. 
The problem arises because patching inserts and additional item to call stack and `torch.jit.script` relies on it when retrieving `ResourceResolutionCallback` object representing the scopes for the trace methods of the class. All this results in the need for providing a custom `ResourceResolutionCallback` during patching.
Also, `ORIGINAL_OPERATORS` list was increasing in size after each unpatch-patch iteration resulting in duplication up to 10x. This is because it wasn't cleared before yet another patching operation. This issue was fixed …

Fix for torch.jit.script patching applied to classes

---

nncf/experimental/openvino_native/graph/node_utils.py
tests/openvino/native/test_node_utils.py

* Implemented `get_const_value()` function for OpenVINO Native backend.
* Fixed bug with constant data_type for FP16 models.

[OV] Add get_const_value function

---

tests/torch/data/ac_configs/googlenet_imagenet_pruning_geometric_median.yml
tests/torch/data/ac_configs/resnet18_imagenet_pruning_geometric_median.yml
tests/torch/data/ac_configs/resnet18_imagenet_pruning_magnitude.yml
tests/torch/data/ac_configs/resnet34_imagenet_pruning_geometric_median_kd.yml
tests/torch/data/ac_configs/resnet34_imagenet_pruning_magnitude.yml
tests/torch/data/ac_configs/resnet50_imagenet_pruning_geometric_median.yml
tests/torch/data/ac_configs/resnet50_imagenet_pruning_magnitude.yml

Names in AC configs for PT E2E models were aligned with canonical names.
E2E test pipeline relies on AC config model names being the same as the model IDs in `sota_checkpoints_eval.json`, otherwise it can't find proper OV metrics to be displayed in the test report.
N/A
E2E PT

Align PT model names in AC configs

---

nncf/experimental/netron.py

The `save_for_netron()` method was added. It takes the `NNCFGraph` object and `save_path` (path to the `.xml` file where the graph should be saved).
There is an ability to show the arbitrary number of the node attributes. For example, I added the metatype attribute
- You can see the NNCF graph object in the Netron app now.
N/A
N/A

Export of the NNCF graph for the Netron app was added

---

nncf/torch/dynamic_graph/patch_pytorch.py
nncf/torch/dynamic_graph/trace_tensor.py
tests/torch/test_graph_building.py

Modified the `trace_tensors` function in order for it not to fail if it cannot find tensors to trace in the operator output. Also added a `torch.Tensor.get_device` function to the list of non-patched functions because it is irrelevant for DNN control flow.
Increased robustness of NNCF PT.
N/A
tests.torch.test_graph_building.test_trace_output_with_no_tensors

Do not fail outright if cannot trace tensors

---

tests/cross_fw/install/test_install.py
tests/shared/helpers.py

Installation tests was designed to run only on unix platforms (for example: `{venv_path}/bin/activate`), and was never tested on Win32 platform
We want to run tests on Windows platform
10585
pytest tests/cross_fw/install/ -s --backend {backend.name} {backend.params}

Windows installation tests

---

nncf/common/logging/logger.py
tests/common/test_logging.py
tests/openvino/tools/calibrate.py

- `set_log_file()` method was added for nncf logger.
Calibrate tool should save logs to analyze
N/A
- tests/common/test_logging.py

Log file for calibrate tool

---

nncf/torch/compression_method_api.py
nncf/torch/model_creation.py
nncf/torch/nncf_network.py
tests/torch/test_algo_common.py

NNCFNetwork objects leaving `create_compressed_model` now have a controller reference available in them.
Much ore convenient to access the controller through the model object in certain cases.
N/A
tests.torch.test_algo_common.test_compressed_model_has_controller_references

Register controller in NNCFNetwork at create_compressed_model

---

nncf/torch/quantization/algo.py
tests/torch/quantization/test_algo_quantization.py
tests/torch/quantization/test_prepare_for_inference.py

* Fix narrow_range for weighted symmetric quantizers in case of num_bits != 8
* Fix torch sota eval
* 106861
Build: 279

[Torch] Set narrow_range=False for bits != 8

---

nncf/quantization/algorithms/bias_correction/onnx_backend.py
nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py

Use `get_input_edges` that return sorted edges by port_id instead of `get_previous_nodes`
`get_previous_nodes` returns unsorted nodes, in result `is_quantized_weights` can return false negative result.

Fix incorrect work of `is_quantized_weights` in ONNX backend of PTQ

---

tests/post_training/model_scope.py

- Excluded models with zero accuracies on POT & NNCF
- Speed up the conformance test

[PTQ] Drop zero-accuracy models from conformance

---

nncf/torch/graph/operator_metatypes.py
nncf/torch/graph/pattern_operations.py
nncf/torch/hardware/fused_patterns.py
tests/torch/data/reference_graphs/quantized/synthetic_model/Baddbmm.dot
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py

`torch.baddbmm` has been added as an alias for the matmul metatype for quantization purposes.
Wouldn't be quantized otherwise.
N/A
test_synthetic_model_quantization

Add baddbmm as a matmul alias for PT

---

tests/openvino/tools/calibrate.py

The initialization of the model evaluator was fixed.
Some models failed.
N/A
N/A

Minor fix for calibrate tool

---

setup.py

tensorflow-metadata<=1.13.0
tensorflow-metadata==1.13.1 requires incompatible with TensorFlow 2.8.4 version of protobuf.
N/A
pre-commit

Fixed version of tensorflow-metadata

---

nncf/scopes.py
tests/openvino/tools/calibrate.py

- Support for peration types in calibrate.py
- Refactor IgnoredScope class to the datatclass.
This caused operation types from the ignored scope to be skipped.
ref: 105079
N/A

Support for ignored operation types in calibrate.py

---

nncf/torch/debug.py
nncf/torch/nncf_network.py

The `@debuggable_forward` decorator was removed from the `NNCFNetwork.forward` function and applied elsewhere.
Removing extra layers of decoration from the original method.
N/A
`tests.torch.quantization.test_algo_quantization.test_debug_mode`

Remove debuggable forward decorator

---

nncf/common/compression.py
nncf/config/extractors.py
nncf/tensorflow/sparsity/magnitude/algorithm.py
tests/tensorflow/pruning/test_strip.py
tests/tensorflow/quantization/test_strip.py
tests/tensorflow/test_ignored_scopes.py
tests/torch/test_algo_common.py
tests/torch/test_compression_lr_multiplier.py

Now `create_compressed_model` won't fail no BN adaptation data loader is given, but there was nothing in the NNCFConfig about BN adaptation anyway. If we skip BN adaptation in this way, log a corresponding message at `INFO` level.
This allows using shorter configs such as `"compression": { "quantization" }` without calling `register_default_init_args`. Examples would be test cases where we don't need BN adaptation mostly, but need a model with quantizers at proper places and do not want to define a dummy dataloader or to explicitly specify 0 BN adaptation samples in config. Also might make it easier for the user to quickly evaluate NNCF even if they missed the `register_default_init_args` call. 
N/A
tests.torch.test_algo_common.test_can_apply_algo_with_single_line, also some tests that …

Skip BN adaptation in some cases to enable shorter compression configs

---

nncf/experimental/common/pruning/block_hierarchy.py
nncf/experimental/common/pruning/operations.py

`PropagationGroup` is imported directly
degradation in ONNX install tests
n/a
install_tests
nightly onnx install build 87 - ✅

Corrected incorrect import to restore nightly tests

---

nncf/experimental/openvino_native/graph/node_utils.py
nncf/experimental/openvino_native/statistics/collectors.py
tests/openvino/native/models.py
tests/openvino/native/test_model_transformer.py
tests/post_training/test_quantize_conformance.py

Nodes with zero output ranks raised runtime error because empty `np.array` has `np.float` type and openvino reduction operations require `np.int64`. Now case `rank==0` works as expected.
To fix runtime error during statistic collection for models with nodes with target quantize nodes that have `rank==0` output.
108784
New test in openvino `test_model_transformer.py` that checks corner case with a target point node that has `rank==0` output.

[PTQ][OV] Fix rank zero output tensor for inplace statistics

---

setup.py

Allow for `pandas<=2.0`
Current pandas version is causing conflicts in OpenVINO CI jobs on https://github.com/openvinotoolkit/openvino/pull/17117
NA

Bump pandas 

---

examples/tensorflow/common/utils.py

Tenserflow: use set_hard_limit_num_open_files() only on Linux platform
There is no "resource" package for Win32
107218
Windows and Linux precommits

Tenserflow: use set_hard_limit_num_open_files() only on Linux platform

---

docs/styleguide/PyGuide.md

Update PyGuide.md
- added `Automating Code Formatting` paragraph 
- removed paragraphs about code style that will be auto-formatted by 'black' and 'isort'
https://github.com/openvinotoolkit/nncf/pull/1692
CVS-74733

Automating Code Formatting in PyGuide.md

---

nncf/quantization/algorithms/post_training/algorithm.py

Remove warning "You are using experimental OpenVINO backend for the Post-training quantization."
OpenVINO backend was removed from experimental
N/A
N/A

Remove redundant warning

---

nncf/quantization/algorithms/post_training/algorithm.py

Remove warning "You are using experimental OpenVINO backend for the Post-training quantization."
OpenVINO backend was removed from experimental
https://github.com/openvinotoolkit/nncf/pull/1761
N/A

[ReleaseV250] Remove redundant warning

---

nncf/torch/model_creation.py
tests/torch/test_api_behavior.py

When running `nncf.torch.create_compressed_model` on one and the same object more than once (deliberately or not), raise an exception with an informative explanation of the situation.
Jupyter notebook users who re-run cells out of order may end up compressing models twice without knowing it. This functionality will prevent that outcome.
109958
tests.torch.test_api_behavior.test_repeat_compression_fails

Fail informatively when compressing Torch models twice

---

nncf/tensorflow/quantization/quantizers.py
tests/tensorflow/quantization/test_range_init.py

Included 0 in quantization ranges computation for TF.
MobileNets had accuracy degradation to 0 after quantization initialization. The issue was with the range initialization for outputs of HardSigmoid function which always returned 1 for samples from initializing dataset. This resulted in `input_low=0.95` and `input_range=0.1`, and then TF quantization turns these into `input_low=0`, `input_range=0.1` which doesn't include 1.
The fix forces initializer to include 0 in the range, as it should've done. This in the end results in `input_low=0` and `input_range=1` which allows for proper quantization of HardSigmoid outputs and resolves the accuracy issue.
56945
Added a test for `apply_range_initialization` method.

[TF] Range initialization fix

---

tests/post_training/conftest.py
tests/post_training/model_scope.json
tests/post_training/model_scope.py
tests/post_training/test_quantize_conformance.py

- Add `model_scope.json` that will be used in CI to parallel jobs by models. 
- Add `--skip_bench` to skip collect performances metrics (for manual use).
- Add `--eval_fp32` arguments. By defaults evaluation of fp32 models will be skipped and get `top 1` metric from  `model_scope.json`. The `top 1` metric of fp32 model is not changed by update quantization algorithms. 
And it's the slowest model. It' should save 20-30% of time for full tests. And 60% of manual test only 1 backend (example: mobilnetv2: fp32 - 20 mins, torch_ptq - 10min).
- Set `CPU_THREADS_NUM` for OpenVINO inference by env variable. To control number of threads, need to optimize inference in Docker with `cpu_limit`.
- Use `None` instead of `-1` for failed metrics. And replace all `None` to  `N/A` in results.csv.
` …

[ReleaseV250] Speedup test_quantize_conformance.py

---

nncf/tensorflow/quantization/quantizers.py
tests/tensorflow/quantization/test_range_init.py

This is a copy of #1774 to release branch. This PR fixes TensorFlow MobileNets quantization initialization.
Included 0 in quantization ranges computation for TF.
MobileNets had accuracy degradation to 0 after quantization initialization. The issue was with the range initialization for outputs of HardSigmoid function which always returned 1 for samples from initializing dataset. This resulted in `input_low=0.95` and `input_range=0.1`, and then TF quantization turns these into `input_low=0`, `input_range=0.1` which doesn't include 1.
The fix forces initializer to include 0 in the range, as it should've done. This in the end results in `input_low=0` and `input_range=1` which allows for proper quantization of HardSigmoid outputs and resolves the accuracy issue.
56945
Added a test for …

[ReleaseV250] Range initialization fix (#1774)

---

Makefile
nncf/__init__.py
nncf/openvino/quantization/quantize_model.py
setup.py
tests/cross_fw/install/install_checks_openvino.py

Replaced openvino-dev to openvino in required dependencies of nncf[openvino]
The OpenVINO backend migrated to the NGraph implementation that requires only openvino as dependency.
N/A
install_ov: 140

Replaced openvino-dev to openvino in required dependencies of nncf[openvino]

---

nncf/openvino/graph/node_utils.py
tests/openvino/tools/calibrate.py

Copy of #1763 
`allow_reshape_input` Accuracy checker param now emulated in calibrate.py
To enable models that require reshape or dynamic shapes before inference on a calibration dataset
108977

[ReleaseV250][PTQ][Tests] Add model reshape to calibrate.py

---

nncf/openvino/graph/node_utils.py
tests/openvino/tools/calibrate.py

`allow_reshape_input` Accuracy checker param now emulated in `calibrate.py`
To enable models that require reshape or dynamic shapes before inference on a calibration  dataset
108977
Checked locally on bert-base-cased, fbcnn and human-pose-estimation
TODO

[PTQ][Tests] Add model reshape to calibrate.py

---

nncf/common/tensor_statistics/aggregator.py
nncf/experimental/common/tensor_statistics/collectors.py
tests/common/test_statistics_aggregator.py
tests/onnx/test_statistics_aggregator.py
tests/torch/test_statistics_aggregator.py

If `tensor_collector.num_samples is None` skip it. None in tensor_collector.num_samples means that there is no limitation for registering numbers of tensors.
Fix Failure when `tensor_collector.num_samples is None`
109341
Add test on `register_statistic_points()`

[PTQ] Add check number_samples on None in StatisticsAggregator

---

tests/torch/test_sota_checkpoints.py

Replace an outdated MO parameter with a new version.
Tests on newer OV package versions fail otherwise.
N/A
PT E2E run TBA

Fix torch E2E

---

nncf/torch/nncf_network.py
tests/torch/test_nncf_network.py

Backward compatibility with existing code
N/A
tests.torch.test_nncf_network.test_warns_on_old_style_calls

Restore get_nncf_wrapped_model with deprecation warning

---

nncf/openvino/pot/engine.py

The `_fill_input()` method was overridden. It returns the value that was given from tranform_fn.
The following code does not work, but the transformation function is valid
```python
import nncf
from nncf.openvino.quantization.backend_parameters import BackendParameters
from nncf.quantization.advanced_parameters import AdvancedQuantizationParameters
import torch
from torch import nn
import numpy as np
from openvino.tools import mo
import openvino.runtime as ov
class ModelWithMultipleInputs(nn.Module):
def __init__(self):
super().__init__()
self._conv2d_0 = nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1)
self._conv2d_1 = nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1)
def forward(self, input_0, input_1):
output_0 = self._conv2d_0(input_0)
output_1 = self._conv2d_1(input_1)
return …
```

Support for models with multiple inputs was added

---

nncf/onnx/graph/transformations/commands.py
nncf/openvino/graph/model_transformer.py
nncf/openvino/graph/model_utils.py
nncf/openvino/graph/transformations/command_creation.py
nncf/openvino/graph/transformations/commands.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/bias_correction/backend.py
nncf/quantization/algorithms/bias_correction/onnx_backend.py
nncf/quantization/algorithms/bias_correction/openvino_backend.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/backend.py
nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
tests/openvino/native/test_model_transformer.py

- Added `insert_null_biases` pass into the BiasCorrection algorithm.
- This pass allows us to correct the bias in the layers that could have it.
104117
conformance run - 123
ONNX ticket - 110696
PT ticket - 110697

[PTQ][OV] Insert null biases pass for BC

---

nncf/torch/nncf_network.py
tests/torch/test_nncf_network.py

Preserve NNCFNetwork.get_nncf_wrapped_model() and deprecate it

---

.github/workflows/pre-commit.yml
Makefile

Running `make pre-commit` locally currently tries to install `pre-commit` from pip even if it is already present, taking up some seconds of time. The new state makes the process of getting a pre-commit-ready state locally faster.
N/A
pre-commit action check

Install pre-commit in separate step from make pre-commit

---

tests/tensorflow/sota_checkpoints_eval.json

- Updated reference metric for `mobilenet_v3_small_imagenet_rb_sparsity_int8` according to the newly trained checkpoint (see nightly e2e TF build 322)
- Removed relaxed thresholds overrides

Updated reference metric for MobileNetV3Small Quantization + Sparsity

---

nncf/experimental/common/tensor_statistics/collectors.py
nncf/openvino/graph/node_utils.py
nncf/openvino/statistics/collectors.py
tests/common/test_statistics_aggregator.py
tests/experimental/common/test_reducers_and_aggregators.py
tests/onnx/test_statistics_aggregator.py
tests/openvino/native/quantization/test_reducers_and_aggregators.py
tests/openvino/native/test_model_transformer.py
tests/openvino/native/test_statistics_aggregator.py
tests/post_training/test_ptq_params.py
tests/torch/test_statistics_aggregator.py

* Names of reducers is used instead of types of reducers to name statistic subnet operations
* Reducer names now differs one from another if they have different attributes and aren't merged
* Hash of reducer now take into account `reduction_shape`
To fix problem when two different statistics that are instances of one class and share target point have equal name
109989
TODO:

[PTQ][OV] Fix inplace statistic reducers names and hashes

---

nncf/torch/quantization/layers.py

If running on Torch < 1.12, do not use `register_load_state_dict_post_hook` and do level range updates on each forward instead.
E2E tests for torch 1.9.1 failing, because `torch.nn.Module.register_load_state_dict_post_hook` has only been added in 1.12.
N/A
E2E PT 1.9.1 run TBA

Restore compatibility with PT 1.9.1

---

tests/openvino/data/ov_dataset_definitions.yml
tests/openvino/datasets_helpers.py
tests/openvino/native/quantization/test_sanity.py

Place AC dataset format of imagenette in a separate directory, not removing the original format.
Dataset processing prepares the dataset for test_sanity rewriting the original format. This adds conflicts in running ONNX and OV tests on one machine.
No
Tested locally.

Fix OV sanity test - make dataset processing in separate directory

---

nncf/torch/initialization.py
nncf/torch/quantization/algo.py
tests/torch/quantization/test_range_init.py

Force range initialization to be applied in eval mode.
If model in train mode is given to `create_compressed_model()`, the graph is built for the model in eval mode, but range initialization statistics are collected in train mode. This may result in wrong statistics collection if model behaves differently in train and eval modes.
Added a test failing before the fix.

Force range initialization to be applied in eval mode

---

tests/post_training/test_quantize_conformance.py

- Fixed conformance test for OV (POT) backend
- Wrong results
- Build 26

[PTQ] Update conformance for POT backend

---

nncf/onnx/graph/metatypes/onnx_metatypes.py
nncf/openvino/graph/metatypes/openvino_metatypes.py
nncf/quantization/algorithms/bias_correction/algorithm.py

- Fixed BiasCorrection `subset_size` usage.
- Removed BackpropData types from the OPERATIONS_WITH_BIAS_METATYPES
- Bug
- Alignment with [POT logic](https://github.com/openvinotoolkit/openvino/blob/master/tools/pot/openvino/tools/pot/graph/special_operations.py#L28)
- 110908
- 110914

[PTQ] Fix BC subset_size usage & operations with bias list

---

nncf/experimental/openvino/quantization/quantize_model.py
nncf/openvino/pot/quantization/quantize_model.py
nncf/openvino/quantization/quantize_model.py
nncf/quantization/advanced_parameters.py
tests/openvino/tools/calibrate.py

- The `convert_to_mixed_preset`  parameter was removed from the `AdvancedAccuracyRestorerParameters`.
- As we decided we will convert a model to a mixed preset as part of the tune hyperparameters algorithm. So we don't need this parameter anymore.
N/A
N/A

Remove convert_to_mixed_preset parameter

---

tests/post_training/conftest.py
tests/post_training/test_quantize_conformance.py

Disable run `benchmark_app` by default. It's not stable can not be used for analysis.

Not run benchmark by default for PTQ tests

---

nncf/common/quantization/quantizer_propagation/solver.py
tests/common/quantization/test_ignore_post_processing.py

The algorithm for automatically adding post-processing nodes to ignored scope has been redesigned.
Starting from the output nodes all the nodes are added to path, until the quantizable nodes with weights are faced.
If the path with the nodes has the post-processing marker node, all the nodes in this path (except outputs and nodes with weights) will be added into ignored scope.
* To fix loading cascade_rcnn_resnet101_fpn_1x_coco, pointrend-resnet50-fpn to OpenVINO runtime
* 104185
* Added test cases to tests/common/quantization/test_ignore_post_processing.py

Disable quantization for post-processing ops

---

nncf/torch/dynamic_graph/patch_pytorch.py
nncf/torch/nncf_network.py
tests/torch/ptq/test_calculation_quantizer_params.py
tests/torch/quantization/test_algo_quantization.py
tests/torch/test_nncf_network.py
tests/torch/test_onnx_export.py

#1584 seems to have broken down the use case where the original model object has forward or backward hooks set up via `torch.nn.Module.register_forward_hook` etc. This PR restores the corresponding functionality.
Although the use case is not common, leaving things as-is means that a limitation is introduced by NNCF in regards to the fundamental torch behaviour, which is not something we want.
N/A
tests.torch.test_nncf_network.test_forward_hooks_are_preserved

Fix setting forward/backward hooks on NNCFNetwork

---

examples/torch/common/models/segmentation/icnet.py
examples/torch/common/models/segmentation/unet.py
nncf/common/deprecation.py
nncf/tensorflow/__init__.py
nncf/torch/__init__.py
nncf/torch/quantization/layers.py
setup.py
tests/tensorflow/test_compressed_graph.py
tests/tensorflow/test_transformations.py
tests/torch/nas/test_elastic_depth.py
tests/torch/quantization/test_algo_quantization.py
tests/torch/sparsity/movement/test_model_saving.py
tests/torch/sparsity/movement/test_structured_mask.py
tests/torch/sparsity/movement/test_training.py
tests/torch/test_sanity_sample.py
tests/torch/test_tracing_context.py

- Use `packaging` instead pkg_resources to parse package version
- Add `packaging` to INSTALL_REQUIRES, because it installs as dependency of `pymoo`
- Setup.py still uses pkg_resources, because `packaging` is not installed on initialization of virtualenv
```
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
declare_namespace(pkg)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Use packaging instead pkg_resources

---

nncf/common/graph/operator_metatypes.py
nncf/common/quantization/quantizer_propagation/solver.py
nncf/torch/graph/operator_metatypes.py
tests/torch/data/reference_graphs/quantized/synthetic_model/Baddbmm.dot

Add a field to `OperatorMetatype` that specifies input ports to be ignored and use it to disable quantization on the 0-th input port of the `torch.baddbmm` operation.
The 0-th input for baddbmm is a bias addition in essence, and if the input tensor is a constant, then adding a quantizer there breaks down a hardware-fused pattern and reduces performance. It is still possible that the 0-th input may be a runtime-dynamic activation tensor, in which case the quantization of this input would probably still be relevant, but right now there is no way in NNCF PT to discern activation and constant inputs.
110848
test_synthetic_model_quantization

Ignore 0-th port of baddbmm in quantization

---

tests/openvino/tools/calibrate.py

* Fixed `quantize_with_accuracy_control` in calibrate.py test for OV (POT) backend

Fix "use_pot" option in calibrate.py

---

nncf/quantization/algorithms/accuracy_control/algorithm.py
tests/common/accuracy_control/test_calculate_drop.py

Incorrect calculation of the drop when the `drop_type` is `DropType.RELATIVE`.
Reproducer:
```python
initial_metric = -0.2923
quantized_metric = -0.3185
accuracy_drop = 1 - quantized_metric / initial_metric <= max_drop 
```
Ref: 110824
- tests/common/accuracy_control/test_calculate_drop.py

Fix calculation of the accuracy drop when the drop_type is DropType.RELATIVE

---

nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/min_max/torch_backend.py

`Divide`, `Sqrt` operations are part of LayerNorm. We shouldn't insert FQs inside LayerNorm pattern, because it is fused at runtime.
* To improve accuracy and performance of transformers
* 111764

Add Divide and Sqrt to ignored scope for ModelType.TRANSFORMER

---

nncf/torch/nncf_network.py
tests/torch/test_nncf_network.py

`get_nncf_modules` return copy of the scopes.
`get_modules_in_nncf_modules_by_type` chages original scope of the modules by `nncf_module_scope.pop()`

Return copy of scope from get_nncf_modules

---

examples/torch/classification/main.py
examples/torch/common/example_logger.py
nncf/common/hardware/config.py
nncf/common/quantization/quantizers.py
nncf/quantization/fake_quantize.py
nncf/torch/quantization/layers.py
nncf/torch/quantization/strip.py
tests/torch/quantization/test_strip.py
tests/torch/test_compression_training.py

LeGR compression training threshold for comparing checkpoint's saved eval metric value with the currently measured one was increased. Levels in `BaseQuantizer`s have been made into torch buffers.
#1578 removed the level updating code on forward and sadly this broke down the DDP training because the levels, which were not torch buffers but instead simple Python attributes, were not synchronized across DDP processes and no calls to level-updating property setters (`num_bits` or `signed`) have been made, so while the model in the 0-th (main) DDP process started out the training OK, the other DDP replicas started from pretty much 0 accuracy.
N/A
PT compression training weekly tests

Fix compression training tests

---

examples/experimental/torch/classification/bootstrap_nas.py
examples/experimental/torch/classification/bootstrap_nas_search.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/multi_elasticity_handler.py
nncf/experimental/torch/nas/bootstrapNAS/search/supernet.py

Adds super-network abstraction to simplify third-party search. 
Simple interface for users that are implementing their own search algorithms 
[Example of how this wrapper is used by third-party search solutions](https://github.com/IntelLabs/Hardware-Aware-Automated-Machine-Learning/blob/main/examples/bootstrapNAS/external_search_resnet50_supernet.ipynb)
N/A - Class wraps multi elasticity handler.

BootstrapNAS - Add super-network abstraction to simplify third-party search

---

tests/post_training/test_quantize_conformance.py

1. Add separate string for tests
```
------------------------------------------------------------
Model: {model_name} Backend: {backend}
------------------------------------------------------------
```
2. Add `tqdm` progress bar to validation function, but that disable for Jenkins and prunt "Validataion...". On Jenkins progressbar prints only after last finish loop and each update prints on new lines. 
3. Fix bug with modified `model_quantization_params` if OV backend runs before others.
```
torch_quantized_model = quantize_torch_ptq(model, calibration_dataset, **model_quantization_params)
TypeError: quantize_torch_ptq() got an unexpected keyword argument 'advanced_parameters'
```

Improve logs of test_ptq_timm

---

nncf/experimental/torch/replace_custom_modules/timm_custom_modules.py
tests/post_training/model_scope.json
tests/post_training/requirements.txt
tests/torch/experimental/replace_custom_modules/test_replace_timm_custom_modules.py
tests/torch/requirements.txt
tests/torch/test_models/swin.py

- Update `timm` to 0.9.2
- Set `torch` to `1.13.1`
- Add tests for `replace_timm_custom_modules_with_torch_native`
111127
TODO: 
| model_name | new 'FP32 top 1' | old  'FP32 top 1' |
|---|---|---|
| darknet53 | 0.79858 | 0.7645 |
| dla34 | 0.74416 | 0.68424 |
| dpn68 | 0.75964 | 0.71478 |
| efficientnet_b0 | 0.77292 | 0.72912 |
| efficientnet_lite0 | 0.7496 | 0.69878 |
| hrnet_w18 | 0.77504 | 0.70656 |
| inception_resnet_v2 | 0.80102 | 0.78894 |
| mobilenetv2_050 | 0.64568 | 0.59498 |
| mobilenetv3_small_050 | 0.56338 | 0.51764 |
| regnetx_002 | 0.67826 | 0.63078 |
| resnest14d | 0.74862 | 0.70102 |
| resnet18 | 0.70104 | 0.62734 |
| tf_inception_v3 | 0.77728 | 0.75948 |
| vgg11 | 0.68344 | 0.61246 |
| wide_resnet50_2 | 0.81414 | 0.7664 |
| xception | 0.78506 | 0.77522 |

Update versions of packages in requirements for post_training tests

---

tests/openvino/native/quantization/test_fq_params_calculation.py

Fixed typo in the test_omz_models_fq_scales test
Avoid saving gold values on every test.
N/A
N/A

Fixed typo

---

nncf/quantization/advanced_parameters.py

Fixed type hints in the advanced_parameters.py
Type hints incompatible with python 3.7
N/A
N/A

Fixed type hints

---

examples/torch/common/export.py

- As in the title
- Bug with PyTorch 1.9.9:
`11:51:05  observer = torch.ao.quantization.observer.MinMaxObserver`
`11:51:05  AttributeError: module 'torch' has no attribute 'ao'`
- `torch.ao.quantization.observer.MinMaxObserver` was introduced only in the 1.10 version

[PyTorch] Fix lower PR version for strip

---

nncf/common/hardware/configs/cpu.json
nncf/common/hardware/configs/gpu.json

Added quantization config for ReduceSum operation
OpenVINO supports int8 precision for ReduceSum operation
https://github.com/openvinotoolkit/openvino/issues/17389
N/A

Added quantization config for ReduceSum operation

---

tests/post_training/requirements.txt
tests/torch/requirements.txt

Fix version of `onnx==1.13.1` and `onnxruntime==1.14.1` for torch and post_training tests.
112492
TODO:

Fix onnx-1.13.1 onnxruntime-1.14.1 for torch and ptq tests

---

nncf/quantization/advanced_parameters.py
nncf/tensorflow/quantization/quantize_model.py
nncf/torch/quantization/quantize_model.py
tests/tensorflow/quantization/test_ptq_params.py
tests/torch/ptq/test_ptq_params.py

Replaceconvert_advanced_parameters_to_dict to apply_advanced_parameters_to_config to avoid missing parameters on config.update().
```python
a = {"a": 1, "b": {"b1": 1, "b2": 2}} 
b = {"b": {"b1": "b1"}} 
a.update(b)  # {"a": 1, "b": {"b1": "b1"}},  missed "b2": 2
```
As result of dict.update batchnorm_adaptation is missed after update config with result of convert_advanced_parameters_to_dict.
Incorrect converting advanced parameters to NNCFConfig.
test_create_nncf_config

Fix convert_advanced_parameters_to_dict

---

tests/post_training/model_scope.json
tests/post_training/test_quantize_conformance.py

1) Skip by backend approach is implemented in test conformance
2) crossvit_9_240 is skipped for TORCH backend
To make conformance test results consistent
109655

Skip crossvit_9_240 TORCH backend in conformance test

---

tests/post_training/requirements.txt
tests/post_training/test_quantize_conformance.py

- Update torch to 2.0.1 
- Disable used fused attention operation `aten::scaled_dot_product_attention` 
112589

Update torch to 2.0.1 for ptq tests

---

nncf/common/graph/patterns/patterns.py
nncf/openvino/hardware/fused_patterns.py
tests/onnx/test_pattern_manager.py
tests/torch/test_pattern_manager.py

Add LINEAR_ACTIVATIONS_UNSQUEEZE_BN_SQUEEZE fused pattern
- These nodes are fused to Convolution/GroupConvolution in the execution graph.
Ref: 112991
N/A

Add LINEAR_ACTIVATIONS_UNSQUEEZE_BN_SQUEEZE fused pattern

---

tests/post_training/model_scope.json

Remove `xception` model from ptq test scope - zero accuracy for OV backend, so can not be used to compare results.
Model | FP32 top 1 | Torch INT8 top 1 | Torch PTQ INT8 top 1 | ONNX INT8 top 1 | OV Native INT8 top 1 | Openvino INT8 top
-- | -- | -- | -- | -- | -- | --
xception | 0.7851 | 0.75048 | 0.7824 | 0.7832 | 0.7826 | 0.0107

Remove xception from ptq tests

---

tests/torch/sparsity/movement/test_training_with_third_party.py
tests/torch/test_sanity_third_party.py

TPS installation tests cannot find the torch version with the CUDA-specific index URL. Also removed the associated test parameter since we don't need this kind of disambiguation for supported torch versions anymore.
N/A
third_party_sanity run

Remove CUDA spec from torch installation in tests

---

nncf/common/graph/graph.py
nncf/common/insertion_point_graph.py
nncf/torch/dynamic_graph/graph.py
nncf/torch/graph/graph.py
nncf/torch/graph/graph_builder.py
nncf/torch/nncf_network.py
tests/common/pruning/test_pruning_operations.py
tests/cross_fw/examples/test_examples.py
tests/torch/test_graph_analysis.py
tests/torch/test_graph_building.py

Fixes the torch graph tracing to correctly handle parallel edge scenario in case when the tensors belonging to parallel edges do are interleaved in the order of the tensor arguments to a given traced torch op.
Bugfix
113539
precommit, E2E TBR

Use explicit port IDs for parallel edge case instead of the parallel edge count

---

nncf/common/graph/patterns/patterns.py
nncf/openvino/hardware/fused_patterns.py
nncf/openvino/quantization/ignored_patterns.py
tests/onnx/test_pattern_manager.py
tests/torch/test_pattern_manager.py

Move the `FC_BN_HSWISH_ACTIVATION` pattern from fused patterns to ignored patterns.
This is an incorrect fused pattern because we cannot fuse batch normalization in `Unsqueeze` operation. The correct fused pattern is
Convolution + Bias + Activation + Unsqueeze + BatchNormalization + Squeeze
Ref: 112991
N/A

Move the FC_BN_HSWISH_ACTIVATION pattern from fused to ignored

---

README.md

Resolves TypeError - default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.Image.Image'>
Usage guide in README.md
Resolves TypeError when quantizing
Non-applicable
By running the quantize script, the model is be quantized successfully.

Update Usage Guide

---

.github/action_configs/labeler.yml

Add label `NNCF PTQ`
If changes files for post training quantization it's not set label, as result CI can be skipped (in case when set only `documentation` label)

Add label `NNCF PTQ`

---

nncf/quantization/advanced_parameters.py

- Fix implementation of the `convert_to_dict_recursively function()` function
Incorrect implementation
```python
from dataclasses import dataclass
@dataclass
class A:
param_a: int
@dataclass
class B:
param_b: int
@dataclass
class C:
a: A
b: B
obj = C(A(0), B(1))
{'a': {'param_a': 0}, 'b': {'param_b': 1}}
{'a': A(param_a=0), 'b': B(param_b=1)}
```
N/A
N/A

Fix convert_to_dict_recursively function

---

nncf/common/graph/graph.py
nncf/common/graph/graph_matching.py
nncf/quantization/algorithms/min_max/algorithm.py

Add strict with default value True parameter to find_matching_subgraphs.
IgnoredPatterns shouldn't be checked on strict matches. This is specific only for HWFusedPatterns.
N/A
N/A

Add strict parameter for find_matching_subgraphs

---

nncf/torch/layer_utils.py
tests/torch/test_nncf_network.py

Redefined __class__ in ProxyModule
If wrapped (user defined module added with "nncf.torch.register_module") module call super() in forward method then this change fix problem "super(type, obj): obj must be an instance or subtype of type".
For example: https://github.com/mosaicml/llm-foundry/blob/ef350d9e64d13cb1db35ab7941bf9039b1b499fd/llmfoundry/models/layers/custom_embedding.py#L15
No tests.

Added redefined __class__ method for ProxyModule.

---

tests/tensorflow/sota_checkpoints_eval.json

Increased `diff_target_max` from default `0.1` to `0.15`.
TF nightly test fail

Increased threshold for TF retinanet_coco 

---

tests/torch/test_nncf_network.py

Fix warning:
```
W0237: Parameter 'input' has been renamed to 'x' in overridden 'EmbeddingWithSharedWeights.forward' method (arguments-renamed)
```
Pylint is red
N/A
N/A

Fix pylint

---

nncf/common/factory.py
nncf/common/graph/layer_attributes.py
nncf/experimental/torch/sparsity/movement/layers.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/backend.py
nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
nncf/quantization/algorithms/fast_bias_correction/torch_backend.py
nncf/tensorflow/graph/converter.py
nncf/torch/dynamic_graph/layer_attributes_handlers.py
nncf/torch/graph/operator_metatypes.py
nncf/torch/model_analyzer.py
nncf/torch/model_transformer.py
nncf/torch/quantization/quantize_functions.py
tests/torch/ptq/test_fast_bias_correction.py
tests/torch/sparsity/movement/helpers/utils.py
tests/torch/test_layer_attributes.py

- Use compressed graph for torch backend
- Add `with_bias` for `WeightedLayerAttributes` what means that layer contain bias inside module (will true only for torch and tf)
- Removed `bias` from `LinearLayerAttributes`, use `with_bias`.
- Remove `model` from functions backend of `fast_bias_correction`
111576

Use nncf_graph for FBC

---

nncf/common/tensor_statistics/statistic_point.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/channel_alignment/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/smooth_quant/algorithm.py
tests/post_training/test_templates/test_channel_alignment.py
tests/post_training/test_templates/test_ptq_params.py

Use the unique key for statistic points per algorithm's instance.
The following code does not work with current approach
```python
quant_algo_performance = PostTrainingQuantization(preset=QuantizationPreset.PERFORMANCE)
quant_algo_mixed = PostTrainingQuantization(preset=QuantizationPreset.MIXED)
stats_aggregator = OVStatisticsAggregator(calibration_dataset)
stats_aggregator.register_statistic_points(quant_algo_performance.get_statistic_points(ov_model))
stats_aggregator.register_statistic_points(quant_algo_mixed.get_statistic_points(ov_model))
stats_aggregator.collect_statistics(ov_model)
quantized_model_performance = quant_algo_performance.apply(ov_model, stats_aggregator.statistic_points)
quantized_model_mixed = quant_algo_mixed.apply(ov_model, stats_aggregator.statistic_points)
```
N/A …

Use unique key for statistics points

---

tests/torch/modules/test_rnn.py

Replace deprecated `torch.testing.assert_allclose` with `torch.testing.assert_close`
```
FutureWarning: `torch.testing.assert_allclose()` is deprecated since 1.12 and will be removed in a future release. Please use `torch.testing.assert_close()` instead.
```

Fix torch deprecation warning

---

examples/post_training_quantization/torch/mobilenet_v2/main.py
nncf/torch/quantization/layers.py
nncf/torch/quantization/quantize_functions.py
tests/torch/quantization/test_tracing.py

Trace FQ nodes by torch.jit.trace to convert model by model_optimizer, without calling `strip` function.
Add experimental convertor of model_optimizer for torch model without export to onnx.
```python
mo.convert_model(torch_quantized_model, example_input=dummy_input)
```
115483
- test_trace_symmetric_quantizer
- test_trace_asymmetric_quantizer

Trace for FQ nodes by torch.jit.trace

---

tests/post_training/pipelines/base.py
tests/post_training/test_quantize_conformance.py

Set number of thread for torch backends for `torch.set_num_threads(int(cpu_threads_num))` by set `CPU_THREADS_NUM` env variable.
Example of reducing quantization time for TORCH backend:
Model | Before | After  
--- | --- | --- 
deit3_small_patch16_224 | 2:34:09  | 0:00:46
dla34 | 0:16:38  | 0:00:38
Build: manual/post_training_quantization/122
Renamed tests to `test_ptq_quantization`
Quantization time is dramatically slow for TORCH backends on CI.

Add torch.set_num_threads for ptq tests

---

nncf/common/graph/patterns/patterns.py
nncf/onnx/hardware/fused_patterns.py
nncf/openvino/hardware/fused_patterns.py
nncf/torch/hardware/fused_patterns.py
tests/torch/data/reference_graphs/quantized/synthetic_model/ShiftScale__multi_input_branch.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/ShiftScale__normalize__multi_input_branch.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/ShiftScale__normalize__single_input_branch.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/ShiftScale__single_input_branch.dot
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py
tests/torch/test_pattern_manager.py

Introduced Shift + Scale fused pattern and Input+Shift+Scale pattern to insert Fake Quantize operations optimally for CPU.
Customer has a model that is quantized not optimally:
FakeQuantize between subtraction and division is redundant and introduces additional cost in runtime.
FakeQuantize between input and pre-processing is not needed in case of single edge from input, because pre-processing can be fused to the FQ after pre-processing.
When there are multiple edges from input and one edge is going to pre-processing, it's optimal to have a common fake quantize for all edges. 
If pre-processing represented via normalize op from torchvision (e.g. like here https://github.com/PeterL1n/RobustVideoMatting/blob/master/model/mobilenetv3.py#L37), NNCF doesn't insert FQ between subtraction and …

Shift+Scale and Input+Shift+Scale pattern for PT

---

nncf/torch/dynamic_graph/graph.py
nncf/torch/dynamic_graph/scope.py
tests/torch/data/reference_graphs/quantized/synthetic_model/OrdinaryModelWithRecurrentInName.dot
tests/torch/modules/test_rnn.py
tests/torch/test_compressed_graph.py
tests/torch/test_models/synthetic.py

The node is considered within iteration scope if the correspondent module name fully matches the registered names of registered recurrent modules (LSTM, GRU cells). 
Previously, there was a less strict rule: the name of the iteration module should include the name of the considered module.
The problem appeared with `RecurrentDecoder` with a customer model: 
https://github.com/PeterL1n/RobustVideoMatting/blob/master/model/model.py#L26C28-L26C44
FQ should be propagated up through `concat` and `strided slice`, but it was mistakenly considered within iteration scope and added to ignored scope for quantization.
The concat's scope is `205 MattingNetwork/RecurrentDecoder[decoder2]/OutputBlock[decode0]/cat_0`
It matched with one of the registered iteration scopes – `Recurrent`. With a corrected …

Corrected condition for matching recurrent nodes

---

nncf/torch/layers.py

Changed default NNCFEmbedding target dim for compression.
Keep better accuracy for compressed LLMs.

Changed NNCFEmbedding target dim for compression.

---

nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
tests/post_training/test_templates/test_quantizer_config.py

Make num_samples=1 for weights statistics collection for all backends
Speed up statistics collection for ONNX, Torch.
Generalize logic.
N/A
Update `test_get_stat_collector`

 [PTQ] Extend num_samples=1 for weights statistics collection for all backends

---

nncf/telemetry/wrapper.py
setup.py
tests/common/test_telemetry.py

Use a new measurement ID for `openvino_telemetry` instead of the old one. Fixed the `skip_if_raises` wrapper which silently broke down the telemetry measurements all this time since #1493.
The old property has been deprecated by the provider and will no longer work. 
N/A
test_telemetry, test_skip_if_raises

Use new property for telemetry and fix to actually send events

---

nncf/torch/binarization/reference.py
nncf/torch/extensions/include/dispatch.h
nncf/torch/quantization/reference.py
tests/cross_fw/install/install_checks_torch.py

Apply a workaround for __VA_ARGS__ expansion on Windows for the DISPATCH_TENSOR_DATA_TYPES macro and apply some minor fixes to the reference quantization functions.
MSVC expands variadic args in macros incorrectly. This may have been fixed in the MSVC, but only very recently.
N/A
windows/install_torch_cpu, windows/precommit_torch_cpu

Fix variadic macros for Windows

---

nncf/common/accuracy_aware_training/runner.py
nncf/common/plotting.py
nncf/experimental/torch/nas/bootstrapNAS/search/search.py

Windows pre-commits fail because they cannot find tk during the sanity tests. The plotting in sanity tests doesn't actually need interactivity, so agg can be used instead of tk as a backend which does not pose cross-platform problems.
N/A
windows/precommit_torch_cpu

Plot NAS search progression non-interactively

---

tests/torch/test_compression_training.py

failed weekly tests due to latest adjustments in NAS:
https://github.com/openvinotoolkit/nncf/pull/1916
https://github.com/openvinotoolkit/nncf/pull/1903
cc: @jpablomch, @yzheng124
117724
weekly

Corrected references for weekly nas tests

---

nncf/openvino/graph/node_utils.py
tests/openvino/native/test_model_transformer.py

Dims are always casted to `np.int` type during creation of an inplace operation, because empty tuple is casted to float type by default and leads to runtime error.
To support empty dims inplace reduction operations
117500
* test_model_transformer.py is updated

[OV][PTQ][Inplace statistics] Always cast dims to np.int to support empty dims case

---

.github/workflows/build_html_doc.yml
.github/workflows/build_schema_page.yml

Now doing `pip install .` instead of `pip install -e .` in GH Actions workflow files.
Ubuntu 22 and pip/setuptools have a lot of bugs when installing editable packages with the new build isolation flow (e.g. when the pyproject.toml is present). We don't have pyproject.toml yet, but should we need to switch, better to have less failures in the unrelated tests and workflows - we don't really need editability in GH actions we have now.
N/A
Can only test changes in these workflows post-factum.

Do not install editable NNCF in workflows

---

nncf/__init__.py

This seems to be a better, more modern way to detect the installed package in the user environment.
117951
precommit should be enough

Use find_spec instead of try-import-except to detect backends

---

codecov.yml

Only the ONNX precommit coverage results are currently uploaded, so there is no sense checking and failing on patch coverage being always 0 on non-ONNX PRs.
N/A
coverage/patch check

Enable codecov/patch status check for onnx code only

---

.github/workflows/precommit.yml
.github/workflows/upload_coverage_for_develop.yml

Fixed workflow script to correctly use passed input parameters
Current version does not send out coverage reports at all.
N/A
post-merge action run, can't be tested before merging

Fix parameters in coverage workflows

---

.github/workflows/upload_coverage_for_develop.yml

Otherwise the `CODECOV_TOKEN` is not available from the `upload_coverage_for_develop.yml` workflow and the upload cannot proceed.
N/A
post-merge

Inherit secrets in upload_coverage reusable workflow

---

codecov.yml

Makes Codecov wait for 2 reports being uploaded before printing a comment, since we have both onnx and common precommits submitting coverage reports now via GH action runs.
Currently the common precommit finishes much faster than the ONNX, and Codecov posts coverage based off that run before waiting for the ONNX precommit to finish, which is necessarily lower and confusing.
N/A
N/A

Adjust codecov.yml

---

nncf/__init__.py
tests/common/conftest.py
tests/common/test_framework_detection.py

Fixed a bug with backend detection where NNCF would report every package detected.
`importlib.utils.find_spec` turns out to find the local subpackages instead of global packages if the global package is not present. Since we have every backend as a local subpackage (e.g. at `nncf.torch`, `nncf.tensorflow` etc.), the previous code would report every backend as available, regardless of actual `torch` or `tensorflow` packages being installed or not.
N/A
test_framework_detection

Work around find_spec finding local subpackages

---

nncf/torch/__init__.py
nncf/torch/dynamic_graph/patch_pytorch.py
tests/torch/pytorch_patch_isolated.py
tests/torch/test_pytorch_patch.py

`torch.jit.script` wrapper fixed to catch exceptions in the original `torch.jit.script` call in order to keep torch state patched if an exception from the user's `torch.jit.script` invocation was expected to fail (by handling the original exception) and the process should have continued.
If the user has the following code:
```python
_, nncf_model = create_compressed_model(...)
try:
_ = torch.jit.script(nncf_model)
except:
pass
```
then, since `torch.jit.script` will fail for NNCF models and the wrapper had to unpatch torch ops in the meanwhile, we end up in a state where the script continues, but torch ops are unpatched, and further interaction with `nncf_model` will fail.
118468
tests.torch.test_pytorch_patch.test_jit_script_exception_preserves_patching

Fix torch.jit.script wrapper

---

examples/torch/common/export.py
nncf/experimental/torch/sparsity/movement/structured_mask_handler.py
nncf/torch/nncf_network.py
tests/torch/pruning/experimental/test_nodes_grouping.py
tests/torch/test_nncf_network.py

Some methods were left for backward compatibility after #1584 and are due for deletion before NNCF 2.6 release.

Deprecate some methods for NNCF 2.6 release

---

nncf/common/quantization/quantizer_propagation/graph.py
nncf/common/quantization/quantizer_propagation/solver.py
tests/common/quantization/test_ignore_post_processing.py

- Fixed PostprocessingNodeLocator algorithm to ignore `Input -> ... -> TopK/NMS -> ... -> Output` pattern (without Conv/MatMul).
- Accuracy degradation
- 117437
- Updated `tests/common/quantization/test_ignore_post_processing.py`

Fix PostprocessingNodeLocator

---

examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt

tensorflow>=2.7.0,<2.12 => tensorflow~=2.12.0
Installation errors:
ERROR: google-auth 2.22.0 has requirement urllib3<2.0, but you'll have urllib3 2.0.4 which is incompatible.
ERROR: tensorflow-metadata 1.14.0 has requirement protobuf<4.21,>=3.20.3, but you'll have protobuf 3.19.6 which is incompatible.
ERROR: tensorflow-datasets 4.9.2 has requirement protobuf>=3.20, but you'll have protobuf 3.19.6 which is incompatible.
N/A
example tests (build 73)

Updated requirements of the ptq tensorflow mobilenet_v2 example

---

nncf/quantization/algorithms/accuracy_control/algorithm.py

Use num_ranking_processes = 1 for Windows
num_ranking_processes > 1 leads to the error of nncf.qunatize_with_accuracy_control(...) on Windows:
ref:118321
N/A

Use num_ranking_processes = 1 for Windows

---

tests/tensorflow/requirements.txt

Add package constraint `filelock<3.12.3`.
Installing tensorflow test environment produces the error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.1 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.7.1 which is incompatible.
```
Starting from `filelock==3.12.3`, it requires `typing-extensions>=4.7.1` so downgrading to `filelock==3.12.2` resolves the issue.
This is temporary measure unless we upgrade to TF 2.13 which does not have `typing-extensions<4.6.0` constraint.

Constrain filelock package version

---

nncf/__init__.py
tests/common/test_framework_detection.py

Fixed the package detection to account for cases where backend's `ModuleSpec` origin path can validly contain 'nncf'
NNCF would report incorrect package availability when the virtual environment has `nncf` in its path, which can actually happen commonplace.
119563
test_frameworks_detected_if_origin_in_nncf

Fix package detection

---

nncf/quantization/algorithms/post_training/algorithm.py
nncf/quantization/algorithms/smooth_quant/algorithm.py

Don't create Smooth Quant algorithm if alpha parameter is negative.
When running AA with `tune_hyperparams=True` and `smooth_quant_alpha<0`, it fails here https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/post_training/algorithm.py#L168 because SQ had been created. This fix makes it so SQ is not created if it won't be used.

Skip SmoothQuant creation if alpha is negative

---

tests/tensorflow/test_compressed_graph.py

Disable MaskRCNN and RetinaNet graph tests until ticket 119664 is resolved.
The following tests are now excluded:
test_compressed_graph.py::TestModelsGraph::test_quantize_network[w_sym_t_a_sym_t-retinanet]
test_compressed_graph.py::TestModelsGraph::test_quantize_network[w_sym_t_a_sym_t-mask_rcnn]
test_compressed_graph.py::TestModelsGraph::test_quantize_network[w_sym_ch_a_asym_t-retinanet]
test_compressed_graph.py::TestModelsGraph::test_quantize_network[w_sym_ch_a_asym_t-mask_rcnn]
test_compressed_graph.py::TestModelsGraph::test_magnitude_sparsity_network[retinanet]
test_compressed_graph.py::TestModelsGraph::test_magnitude_sparsity_network[mask_rcnn]
test_compressed_graph.py::TestModelsGraph::test_rb_sparsity_network[retinanet]
test_compressed_graph.py::TestModelsGraph::test_rb_sparsity_net …

[TF] Disable MaskRCNN and RetinaNet graph tests

---

nncf/config/schemata/algo/quantization.py
nncf/torch/quantization/algo.py

Add message about deprecation of  `export_to_onnx_standard_ops`  option in NNCFConfig
Recommended way to export to onnx with QuantizeLinear-DequantizeLinear node pairs is `nncf.strip(quantized_model)`.

Add message about deprecation `export_to_onnx_standard_ops` 

---

Makefile
tests/shared/command.py
tests/torch/nas/test_sanity_sample.py
tests/torch/pytest.ini
tests/torch/quantization/test_functions.py
tests/torch/quantization/test_sanity_sample.py
tests/torch/test_sanity_sample.py

- Add marks `nightly` and `weakly` for tests.
- Mark sanity tests as `nightly`
- Split `test_functions.TestParametrized` to fast for precommit and long for nightly
- Time of torch precommit reduced from 60 to 40 mins
- Set `xfail` for sanity tests with `--mode train` in case of segment fault.
Sporadic segment fault reproduced on torch>=2.0.0 on call `backward` function.
119128

Add marks nightly and weakly for torch tests

---

nncf/openvino/quantization/quantize_model.py
nncf/quantization/advanced_parameters.py
tests/openvino/tools/calibrate.py

- Add support for the `dump_intermediate_model` parameter to save fully quantized model in the AAQ pipeline
- Alignment with POT
N/A
N/A

Add support for the dump_intermediate_model parameter

---

nncf/common/tensor_statistics/aggregator.py
nncf/data/dataset.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/channel_alignment/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/smooth_quant/algorithm.py
tests/common/test_dataset.py
tests/openvino/datasets_helpers.py

1. Fixed an issue with wrong `tqdm` bar length in the case when calibration dataset length is less than `subset_size`.
Reproducer: https://github.com/nikita-savelyevv/nncf/commit/f0951c14ab6c831fe2f6c389a605593846adeeab
**Before:**
`Statistics collection:  34%|██████            | 101/300 [00:03<00:06, 28.66it/s]`
**After:**
When dataset has `__len__`:
`Statistics collection: 100%|██████████████████| 101/101 [00:03<00:00, 28.20it/s]`
When dataset doesn't have `__len__`:
`Statistics collection:  34%|██████            | 101/300 [00:03<00:06, 29.45it/s]`
2. Improved progress bar GUI when ran from notebooks.
**Before:**
or (in some browsers progress bar takes up multiple lines):
**After:**
In console the progress bar is the same.
User experience improvement.
112627

tqdm progress bar improvements

---

examples/post_training_quantization/openvino/yolov8/main.py
examples/post_training_quantization/openvino/yolov8/requirements.txt
examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt

Upgrade ultralytics to 8.0.170
For some reason yolo samples started to fail. Upgrading ultralytics solves this issue because the later version contains these changes: https://github.com/ultralytics/ultralytics/commit/a7419617a6f2f74849161f3faa5b65d2cef92bd5
120311
Build 82 passed

Upgrade ultralytics to 8.0.170

---

tests/openvino/tools/calibrate.py

- Fixed behaviour in the `calibrate.py` for algos without options
- Bugfix
- 120295

[PTQ] Fix non-optional algos in calibrate.py

---

tests/tensorflow/test_compressed_graph.py

This reverts #2119
It seems that the problem is only reproduced on a single machine. This machine is excluded from test scope.
119664

Revert "[TF] Disable MaskRCNN and RetinaNet graph tests (#2119)"

---

nncf/common/logging/track_progress.py
nncf/common/tensor_statistics/aggregator.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/channel_alignment/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/smooth_quant/algorithm.py
setup.py

Added `nncf.common.logging.track_progress.track()` method to replace `tqdm` for quantization algorithms bars.
This method is an almost exact copy of `rich.progress.track()` method, but with an addition of an iteration counter. This is kind of a hack, but `rich` does not provide a way to add custom `Column` objects to the `track()` method.
By default `rich.progress.track()` renders progress bar as 
With an addition of customizations this becomes
With this change the quantization pipeline looks like
For iterables without length the progress bar displays as 
How it looks in a notebook:
- User experience improvement
- Avoiding multi-line logs in CI produced by `tqdm`, for example:
Statistics collection:   0%|          | 0/300 [00:00<?, ?it/s]
Statistics collection:   0%|          | 1/300 …

Added rich-based progress bar

---

nncf/experimental/torch/nas/bootstrapNAS/search/search.py
setup.py

- Fixed `pymoo` version.
- Added patch for the `IntegerRandomSampling` to avoid errors.
- Bugfix

Update pymoo version

---

nncf/common/graph/patterns/patterns.py
nncf/onnx/graph/metatypes/groups.py
nncf/onnx/graph/metatypes/onnx_metatypes.py
nncf/onnx/hardware/fused_patterns.py
nncf/openvino/hardware/fused_patterns.py
tests/torch/test_pattern_manager.py

- Added LINEAR_SQUEEZE_ARITHMETIC_ACTIVATIONS pattern
- Added ONNXGlobalMaxPoolMetatype metatype for ONNX backend
Fixed FakeQuantize operations placement
ref: 113396
N/A

linear_squeeze_arithmetical_activations pattern

---

examples/torch/classification/main.py
tests/torch/test_compression_training.py

In torch classification sample: `write_metrics` and `mlflow` accuracy logging is called only in main process
Torch test_compression_training (build 106) failed due to metric collected by `write_metrics` and metric saved in checkpoint with key "best_acc1" were different
Torch test_compression_training build ~~109~~ 111

[Torch] Fix classification sample metric dumps not in main process

---

nncf/openvino/quantization/quantize_model.py
nncf/quantization/advanced_parameters.py
nncf/quantization/algorithms/accuracy_control/algorithm.py
nncf/quantization/algorithms/accuracy_control/backend.py
nncf/quantization/algorithms/accuracy_control/openvino_backend.py
nncf/quantization/algorithms/accuracy_control/ranker.py

- Use multithreading instead of multiprocessing to calculate quantizer ranking score
- Rename num_ranking_process to num_ranking_workers
- Support parallel calculations of quantizer ranking score for Windows
- Introducing more general name of parameter of number parallel workers.
ref: 119274
N/A

Move the ranker to a multi-threaded approach

---

nncf/torch/quantization/hessian_trace.py

Use absolute value of avg_total_trace in denominator, as done in [PyHessian:](https://github.com/amirgholami/PyHessian/blob/master/pyhessian/hessian.py#L186C22-L186C22)
more robust mixed precision algo
resolves #2155 
hawq-related tests

More correct hessian trace calculation

---

docs/api/requirements.txt

- Fixed the `astroid` version (`shpinx-autoapi` dependence)
- The 3.0.0 version breaks our pipeline

Fix docs deps version

---

nncf/torch/checkpoint_loading.py
nncf/torch/nncf_network.py
tests/torch/test_backward_compat.py
tests/torch/test_load_model_state.py

Legacy quantizer storage names in checkpoints were removed
The format had changed after the NNCFNetwork rework, and the deprecation warning has been in place for two releases now.
121535
test_load_model_state

Remove legacy external quantizer storage names

---

examples/post_training_quantization/openvino/mobilenet_v2/main.py
nncf/common/logging/track_progress.py

- Progress bar now extends to screen width
- Iteration count, time spent and time remaining text components are now Intel blue (RGB [0,104,181])
How it looks in terminal (Windows Terminal):
How it looks in Jupyter:
Please see how it looked before at #2132
Note: I've tried changing color for progress percent too, but couldn't, most probably due to a bug in rich https://github.com/Textualize/rich/issues/3133
- Improving user experience
Special thanks to @AlexanderDokuchaev and @kshpv for suggesting these changes.

Progress bar visuals enhancement 

---

tests/post_training/pipelines/base.py

Add missed `input_shape` to `convert_model` for PT backend.
IR of quantized models have dynamic shape.

Fix: missed input_shape to `convert_model` for PT backend.

---

tests/post_training/pipelines/base.py

Add `cleanup_torchscript_cache` function to test_quantize_conformance.py
After run torch.jit.trace in convert_model, PyTorch does not clear the trace cache automatically.
Same function in torch test and openvino notebok:
https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/jit_utils.py#L59
https://github.com/openvinotoolkit/openvino_notebooks/blob/1932d4b4e99116bdedaa620c9dc92069fbb1f05e/notebooks/236-stable-diffusion-v2/implementation/conversion_helper_utils.py#L8

Add `cleanup_torchscript_cache` to test_quantize_conformance.py

---

tools/extract_ov_subgraph.py
tools/ir_subgraph.py

There recently have been cases of very large model IRs, for example for LLMs which can't be opened by Netron. This makes it difficult to examine model graph in general and Fake Quantize node placement in particular.
The added helper script allows to select a node from a graph and extract some subgraph around it. To control how many surrounding nodes to include, `distance` parameter is used.
```
python ir_subgraph.py openvino.xml "Constant_1116858"
```
The result will be saved at `./openvino_Constant_1116858_10.xml`. An additional symbolic link will be created at `./openvino_Constant_1116858_10.bin` leading to original `.bin` file so that weights for the subgraph IR are visible through Netron.
- Parameter `--distance` can be used to control the subgraph size (10 by default)
```
python …
```

Added a helper script for extracting an IR subgraph

---

nncf/openvino/quantization/quantize_ifmodel.py

Apply output transformation first to correctly take the tensor names.
This allows to use of these names to collect data from If inputs
122100
Manually model from the ticket was tested.

[OV] Apply output insertion transformation first for model with If node 

---

README.md
nncf/telemetry/wrapper.py
setup.py

Updated the telemetry lib to use the opt-out approach.
Manual testing for the `opt_in_out` entrypoint

Use opt-out telemetry

---

tests/torch/ptq/test_fast_bias_correction.py
tests/torch/test_tensor.py

Add check `torch.cuda.is_available` to `TestTorchCudaFBCAlgorithm` test.
122537

Skipping CUDA tests for CPU setup

---

tests/post_training/conftest.py
tests/post_training/pipelines/base.py
tests/post_training/test_quantize_conformance.py

Add `--no-eval` argument to debug

Add --no-eval arg to test_quantize_conformance.py

---

nncf/quantization/algorithms/accuracy_control/ranker.py

The `_multithreading_calculation_ranking_score` does not work when len(groups_to_rank) < self._num_workers
IndexError: pop from empty list
N/A
N/A

Fix multithreading

---

nncf/quantization/algorithms/hyperparameter_tuner/algorithm.py
nncf/quantization/algorithms/hyperparameter_tuner/param_grid.py
nncf/quantization/algorithms/pipeline.py
nncf/quantization/algorithms/post_training/algorithm.py
nncf/quantization/algorithms/post_training/pipeline.py
nncf/quantization/quantize_model.py
tests/onnx/quantization/common.py
tests/onnx/quantization/test_ptq_params.py
tests/openvino/native/quantization/test_ptq_params.py
tests/post_training/test_templates/test_ptq_params.py
tests/post_training/test_templates/test_quantizer_config.py
tests/torch/ptq/test_fq_params_calculation.py
tests/torch/ptq/test_ptq_params.py

- Add the `Pipeline` class. To use the algorithm with the `HyperparameterTuner`, it should be wrapped within a `Pipeline` object.
- Add the SmoothQuant and ChannelAlignment algorithms to the parameter optimization process.
Ref: 117471

Add SmoothQuant and ChannelAlignment to HyperparameterTuner

---

setup.py

Bump `numpy` version.
Current version causes issues in OpenVINO CI: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/2803
122802

Bump `numpy` version upper bound

---

tests/cross_fw/examples/conftest.py
tests/cross_fw/examples/test_examples.py
tests/cross_fw/install/conftest.py
tests/cross_fw/install/test_install.py

- Added `ov_version` variable for the pytest in `test_examples`;
- Added `ov_version` variable for the pytest in the `test_install_*`;
- More flexible tests
- 122860
- Updated

Added ov_version parameter to the env tests

---

Makefile

Common code has an own target now which is run using GH actions, no reason to run these tests additionally in the backend-specific targets.
TBA
Existing precommit scope

Do not test common code in backend-specific test targets

---

nncf/quantization/algorithms/algorithm.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/bias_correction/backend.py
nncf/quantization/algorithms/bias_correction/onnx_backend.py
nncf/quantization/algorithms/bias_correction/openvino_backend.py
nncf/quantization/algorithms/channel_alignment/algorithm.py
nncf/quantization/algorithms/channel_alignment/backend.py
nncf/quantization/algorithms/channel_alignment/openvino_backend.py
nncf/quantization/algorithms/fast_bias_correction/algorithm.py
nncf/quantization/algorithms/fast_bias_correction/backend.py
nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py
nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
nncf/quantization/algorithms/fast_bias_correction/torch_backend.py
nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/min_max/backend.py
nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/min_max/torch_backend.py
nncf/quantization/algorithms/pipeline.py
nncf/quantization/algorithms/post_training/algorithm.py
nncf/quantization/algorithms/smooth_quant/algorithm.py
nncf/quantization/algorithms/smooth_quant/backend.py
nncf/quantization/algorithms/smooth_quant/openvino_backend.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/backend.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py

Run the SmoothQuant and ChannelAlignment algorithms only for the OpenVINO backend.
Only the OpenVINO backend supports SmoothQuant and ChannelAlignment algorithms.
N/A
N/A

Enable SmoothQuant only for OV backend

---

nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/min_max/torch_backend.py

[PTQ] Avg pool is added as ignored metatype for TRANSFORMER model_type in TORCH/OV/ONNX backends
* To align PTQ backends as for example TORCH avg_pool is mapping to reduce_mean in OV, for timm/visformer_small in particular
110985
119910

[PTQ] Avg pool is added as ignored metatype for TRANSFORMER model_type

---

nncf/common/graph/graph.py
nncf/common/quantization/quantizer_propagation/graph.py

Visualization of debug graph is fixed by replacing : to ^
To fix graph visualization for OV backend

[Graph visualization] Reserved dot symbols are replaced for each graph visualization

---

.pre-commit-config.yaml

Fixes the following message (spawned when ruff finds an error):
```
panicked at 'byte index 1024 is not a char boundary; it is inside '█' (bytes 1023..1026) of `# Copyright (c) 2023 Intel Corporation
Backtrace:    0: <unknown>
1: <unknown>
2: <unknown>
```
N/A
pre-commit linters

Update ruff to v0.1.3

---

tests/torch/test_compression_training.py

Acceptable range for mobilenet_v2 models in compression training tests is increased
After migration to CUDA-11.8 in NNCF Torch, some torch training_compression tests started to fail due to the fact that difference between validation metrics calculated after training and metrics calculated after --resume is exceeded expected boundaries (0.2 in most cases). Different cases with mobilenet_v2 model were failed due to this problem.
124083

[TORCH] Increase acceptable range for mobilenet_v2 models in compression training tests

---

nncf/common/tensor_statistics/collectors.py
nncf/experimental/common/tensor_statistics/collectors.py
nncf/onnx/statistics/collectors.py
nncf/openvino/statistics/collectors.py
nncf/tensorflow/tensor_statistics/collectors.py
nncf/torch/tensor_statistics/collectors.py
tests/common/experimental/test_reducers_and_aggregators.py
tests/openvino/native/quantization/test_reducers_and_aggregators.py

Lucky PR 🍀🍀🍀
MAD and Percentile aggregators accepts tensors that have different axes along aggregation axes
To align behaviour of the experimental tensor collectors with common tensor collectors
123519
* test_mad_percentile_aggregators_different_sizes

[PTQ][Experimental stats] MAD and Percentile aggregators accept dynamic tensors

---

nncf/common/tensor_statistics/aggregator.py
nncf/quantization/quantize_model.py
tests/common/test_statistics_aggregator.py
tests/openvino/native/quantization/test_quantize_api.py

Added raising an exception when an empty calibration dataset is provided.
Now if empty calibration dataset is passed to `nncf.quantize()` the following exception will be thrown:
```
Calibration dataset must not be empty. Please provide calibration dataset with at least one sample.
```
Also added a check for non-positive `subset_size` provided to `nncf.quantize()`. Otherwise, it would error with the same statistics not collected error.
Without an explicit exception it will error out later with a message like:
```
File "/home/nsavel/workspace/openvino_notebooks/nncf/nncf/quantization/algorithms/min_max/algorithm.py", line 673, in apply
raise RuntimeError(f"Statistics were not collected for the node {target_node_name}")
RuntimeError: Statistics were not collected for the node …
```

Added raising an exception when empty calibration dataset is provided

---

nncf/torch/tensor_statistics/collectors.py
tests/torch/ptq/test_reducers_and_aggregators.py

torch quantile is always using numpy realization
Bug https://github.com/pytorch/pytorch/issues/64947
third party test 237 has failed
```
RuntimeError: quantile() input tensor is too large
```
Build test third party 239 is finished successfully

[Torch] Workaroud for torch.quantile function

---

tests/torch/ptq/test_reducers_and_aggregators.py

Skip cuda test if cuda is not available
To fix CPU pre-commit
precommit_torch_cpu/169/ is finished successfully

[Torch] Skip cuda test if cuda is not available

---

nncf/onnx/quantization/ignored_patterns.py
nncf/openvino/quantization/ignored_patterns.py
nncf/torch/quantization/ignored_patterns.py

Added `Concat` to `MULTIHEAD_ATTENTION_OUTPUT` ignored pattern for OV, ONNX, Torch backends
To improve accuracy of https://huggingface.co/EleutherAI/gpt-neo-1.3B model
* 117617

Add Concat to _add_softmax_matmul ignored pattern

---

nncf/torch/dynamic_graph/io_handling.py
tests/torch/test_graph_building.py

PTQ PT CUDA test cases fail
124679
test_input_infos_respect_device_setting

Correct device assignment for ExactInputsInfo

---

examples/torch/common/export.py
examples/torch/object_detection/main.py
nncf/torch/exporter.py
tests/torch/quantization/test_sanity_sample.py
tests/torch/requirements.txt

Fixed a regression introduced in #2196 for the object detection samples and bumped the `datasets` version for the movement sparsity tests to fix a `Loading a dataset cached in a LocalFileSystem is not supported` error in the associated test cases.
Torch nightly tests fail otherwise.
N/A
torch_nightly

Fix object detection sample and bump datasets version

---

nncf/config/schemata/experimental_schema.py
nncf/experimental/torch/nas/bootstrapNAS/elasticity/elastic_width.py
nncf/experimental/torch/nas/bootstrapNAS/training/progressive_shrinking_builder.py
tests/torch/nas/models/synthetic.py
tests/torch/nas/test_all_elasticity.py
tests/torch/nas/test_elastic_width.py

Allow the use of an external weight importance information for reordering weights of the super-network. 
Adds missing info in experimental schema for previously committed KD. 
Several advanced algorithms can produce weight importance information that outperform L1/L2 weight reordering strategies. This PR allows the use of external weight importance information to reorder the weights in the super-network. 
N/A
Tests have been included.

BootstrapNAS External Weight Reorg.

---

examples/post_training_quantization/torch/mobilenet_v2/main.py
examples/post_training_quantization/torch/mobilenet_v2/requirements.txt
examples/post_training_quantization/torch/ssd300_vgg16/main.py
examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/passes.py
nncf/torch/engine.py
nncf/torch/quantization/quantize_model.py
tests/common/data/reference_graphs/passes/test_constant_filtering_model_after.dot
tests/common/data/reference_graphs/passes/test_constant_filtering_model_before.dot
tests/common/quantization/test_passes.py
tests/cross_fw/examples/example_scope.json
tests/cross_fw/examples/test_examples.py
tests/post_training/test_templates/models.py
tests/torch/test_transform_fn.py

Cherry-pick of 1493149ae35987442a13a60de151e7842159955f
- Do not filter constant nodes for torch backend in the inference graph
- Fix version in requarements.txt for examples of post_training_quantization
- for ssd300_vgg16 is not available to use torch 2.1.0 (failed on export to onnx Unsupported: ONNX export of operator get_pool_ceil_padding, tracing is not supporting too)
- Update metrics
- Add to PTEngine convert inputs to model's device to sync behavior with `create_compress_model` 
- Mobilenet_v2 example converting PyTorch model to IR by tracing (without onnx).
- nncf.quantize for PyTorch works with copy of the target model
To make PTQ work properly with disconnected graphs (like in  [example](https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/tor …

[Release][Torch][PTQ] Examples are updated for the new PTQ TORCH backend

---

examples/torch/requirements.txt

Allow torchvision 0.16 in the examples
Otherwise the installation of the requirements for the torch examples tries to install torchvision 0.16, which pulls the torch 2.0.1 which is different from the BKC torch v2.1
N/A
torch_nightly, torch E2E

Fix torchvision version in the examples

---

nncf/common/graph/layer_attributes.py
nncf/common/graph/operator_metatypes.py
nncf/common/pruning/tensor_processor.py
nncf/common/tensor_statistics/collectors.py
nncf/onnx/graph/node_utils.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/quantization/test_weights_compression.py

Exclude from weight compression nodes that has more than one reduction axes
There's only one model that has multiple reduction axes.
It's `chatglm` with one embedding layer having [8132,32,2] shape. It was decided to not quantize this layer, since it would save just 6Mb in 4Gb model in case of int8 quantization with risk to reduce accuracy, and it can't be quantized group-wise.
The idea is to switch to multiple reduction axes when it will be really needed.
n/a
Tested on 104 models from share with IR's for llm models. In all cases except chatglm there's a single reduction axis.

Compress weights with a single reduction axis only

---

examples/post_training_quantization/torch/ssd300_vgg16/main.py
nncf/torch/engine.py
tests/torch/test_transform_fn.py

Remove logic to set device in `PTEngine`, to support multi-device model https://github.com/openvinotoolkit/nncf/pull/2253

Remove to_device from PTEngine

---

nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py

renamed name to node_name in the warning
chatglm model support
125045
test_not_quantize_with_multiple_reduction_axes

Fixed typo in the warning from compress_weights

---

tests/post_training/pipelines/image_classification_timm.py
tests/post_training/reference_data.yaml

Do constant folding while exporting to ONNX from Torch
Conformance test regressgion of ONNX after updating torch to 2.1
Model graphs are updated and contain BatchNorm. Therefore bias locates no more as Conv attribute but in BatchNorm layer. It leads to not applying FBC and BC algorithms to these biases.
125203
N/A

Update Torch to ONNX export in conformance 

---

nncf/openvino/quantization/quantize_model.py
nncf/openvino/rt_info.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py

Hyperparameters of weight compression are dumped to IR
Useful in cases when different configurations are considered (validation, research experiments, etc)

Dump weight compression params to IR

---

tests/openvino/native/quantization/test_weights_compression.py

as stated in title
new version of OpenVINO contains nf4 type, therefore no need to xfail nf4 tests
nf4 tests

Enabled nf4 tests after switching to openvino==2023.2

---

nncf/experimental/torch/pruning/operations.py
nncf/torch/graph/operator_metatypes.py
nncf/torch/pruning/operations.py
tests/torch/data/reference_graphs/quantized/synthetic_model/Conv_AdaptiveMaxPool1d_Conv.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/Conv_AdaptiveMaxPool2d_Conv.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/Conv_AdaptiveMaxPool3d_Conv.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/Conv_MaxPool1d_Conv.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/Conv_MaxPool2d_Conv.dot
tests/torch/data/reference_graphs/quantized/synthetic_model/Conv_MaxPool3d_Conv.dot
tests/torch/test_compressed_graph.py

According to https://docs.openvino.ai/2023.1/openvino_docs_OV_UG_lpt.html
Placement FQ nodes like in OV backend.
124839

Not quantize AdaptiveMaxPool

---

nncf/torch/dynamic_graph/context.py
nncf/torch/dynamic_graph/io_handling.py
nncf/torch/dynamic_graph/trace_tensor.py
nncf/torch/nncf_network.py
tests/torch/ptq/test_wrap_model.py
tests/torch/test_nncf_network.py
tests/torch/test_tracing_context.py

Strip traced tensors when exit from the tracing context
`nncf_model_input` patched `torch.Tensor` with `TracedTensor` which does not support deepcopy.
125357
test_wrap_model_with_example_input
e2e 506
test_examples 154

[Fix] Patching nncf_model_inputs

---

nncf/torch/nncf_network.py
tests/torch/ptq/test_strip.py
tests/torch/quantization/test_strip.py

Fix `do_copy` option for `strip` function
Does not make a copy of the quantized model by PTQ in `strip` function.

Fix do_copy in strip function

---

nncf/common/utils/dot_file_rw.py
tests/common/graph/test_graph_pattern.py

Replace node name only if node id is string (it can also be `int` like in patterns)
```python
for original_name in nx_graph.nodes():
>           dot_name = original_name.replace(__CHARACTER_REPLACE_FROM, __CHARACTER_REPLACE_TO)
E           AttributeError: 'int' object has no attribute 'replace'
nncf/common/utils/dot_file_rw.py:104: AttributeError
```
tests/common/graph/test_graph_pattern.py::test_dump

Fix dump of patterns

---

tests/onnx/quantization/test_ptq_regression.py

Update links to ONNX models
`HTTP Error 404: Not Found` after changes in  https://github.com/onnx/models
tests/onnx/quantization/test_ptq_regression.py::test_compression

Update links to ONNX models

---

tests/torch/conftest.py
tests/torch/quantization/test_sanity_sample.py
tests/torch/requirements.txt
tests/torch/test_sanity_sample.py
tests/torch/test_sota_checkpoints.py

- Update argument name in tests 
- accelerate==0.24.1, 0.25.0 raises exception 
```
NotImplementedError: Using RTX 3090 or 4000 series doesn't support faster communication broadband via P2P or IB. Please set `NCCL_P2P_DISABLE="1"` and `NCCL_IB_DISABLE="1" or use `accelerate launch` which will do this automatically.
```
- Path type in addoption

Fix pt sanity tests

---

nncf/torch/graph/operator_metatypes.py

`num_edges_expected` filled for each Torch metatype
To fix `filter_constant_nodes` for cases when node with not filled yet metatype should be considered as an input node
Build test_examples 169 is finished successfully

[Torch] `num_edges_expected` filled for each Torch metatype

---

nncf/openvino/graph/model_transformer.py
nncf/openvino/graph/node_utils.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_quantize_api.py
tests/openvino/native/test_layer_attributes.py
tests/openvino/native/test_model_transformer.py
tests/openvino/native/test_node_utils.py
tests/openvino/native/test_statistics_aggregator.py
tests/openvino/test_telemetry.py

Default OV opset has been changed to `opset13`
125777

[PTQ] Bump OV opset from 9 to 13

---

nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/backend.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/quantize_model.py
tests/openvino/native/quantization/test_weights_compression.py

some models, e.g. Qwen, may benefit from quantization of the first and last layers to 4-bit
but by default, they were always quantized to 8-bit
test_compress_first_and_last
test_mixed_precision

Added option for compressing first and last layers

---

.github/workflows/post_pr_merge.yml
.github/workflows/precommit.yml
Makefile
tests/openvino/native/quantization/test_sanity.py
tests/openvino/pot/quantization/test_sanity.py

- Fixed instruction set for openvino precommit.
- Moved openvino precommit to the GitHub Actions (mainly from #2188).
- CI improvements.
- 123702
- Manual

[PTQ][OV] Move OV precommit to GitHub Actions

---

nncf/common/quantization/quantizer_removal.py
nncf/openvino/quantization/quantize_model.py
nncf/quantization/advanced_parameters.py
nncf/quantization/algorithms/accuracy_control/algorithm.py
nncf/quantization/algorithms/accuracy_control/backend.py
nncf/quantization/algorithms/accuracy_control/openvino_backend.py
nncf/quantization/algorithms/accuracy_control/ranker.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_quantizer_removal.py

- Add a backup precision option that allows for preserving FQs on weights during the accuracy-aware algorithm.
See description in Ref: 123999
Ref: 123999
tests/openvino/native/quantization/test_quantizer_removal.py

Add backup precision option

---

nncf/torch/pruning/filter_pruning/algo.py
tests/torch/pruning/filter_pruning/test_algo.py

#1149 reopened with tests
Filter pruning algorithm now uses proper calculation of current pruning level to determine compression stage.
Affects SC.
Compression stage of the model pruned by flops was calculated incorrectly.
Affects Adaptive Compression training as best checkpoints were not saved.
103420
test_compression_stage

Fix pruning compression stage check

---

docs/compression_algorithms/CompressWeights.md
nncf/parameters.py
nncf/quantization/algorithms/bias_correction/algorithm.py
nncf/quantization/algorithms/bias_correction/backend.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/backend.py
nncf/quantization/algorithms/weight_compression/compression_info.py
nncf/quantization/algorithms/weight_compression/mixed_precision.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/quantize.py
nncf/quantization/quantize_model.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py
tests/torch/ptq/test_weights_compression.py

Introduced 4 new criteria (HAWQ_IN, MEAN_VAR, MEAN_MAX, MAX_VAR) for assigning different quantization precision based on the given dataset
determine more accurate configuration by taking into account activations
126378
test_data_based_criterion
test_mixed_precision
the MAX_ACTIVATION_VARIANCE metric shows improvement on wikitext and who-what-benchmark for the 4 considered models.
Manual validation on llama-2 shows that output is without German words.
MEAN_VAR
MAX_VAR
HAWQ_IN
INT8_ERROR

Data-based mixed-precision for weight compression

---

README.md
third_party_integration/huggingface_transformers/README.md

Added a deprecation note for the git patch to Transformers
optimum-intel is recommended way to apply NNCF optimizations for HF Transformers
na
na

Deprecation note for the git patch to Transformers

---

tests/post_training/requirements.txt
tests/torch/data/reference_graphs/pruning_groups/1_layer_BERT.dot
tests/torch/data/reference_graphs/pruning_groups/1_layer_BERT_.dot
tests/torch/data/reference_graphs/pruning_groups/CLIP.dot
tests/torch/data/reference_graphs/pruning_groups/MobileBERT.dot
tests/torch/data/reference_graphs/pruning_groups/RoBERTa.dot
tests/torch/data/reference_graphs/pruning_groups/larger_BERT.dot
tests/torch/data/search_building_block/bert.json
tests/torch/models_hub_test/requirements.txt
tests/torch/pruning/experimental/test_nodes_grouping.py
tests/torch/requirements.txt
tests/torch/sparsity/movement/test_model_saving.py
third_party_integration/huggingface_transformers/0001-Modifications-for-NNCF-usage.patch

- Remove `attention_mask` from `input_info` to disable tracing. The placement of the FQ has not changed.
- Bump version of transformers and optimum
After changes in the graph trace, `attention_mask` branch was added in NNCFgraph as result added FQ for mask. 
But since the mask is used values 0 and finfo(float32).min, inf and nan appear at backpropagation, as result parameters xof FQ are set nan.
127936
test_sanity_third_party.TestTransformers.test_glue_train

Update patch for roberta-large-mnli in third_party_integration

---

tests/post_training/pipelines/image_classification_timm.py
tests/post_training/reference_data.yaml

Use transformers from timm.
Use incorrect transformers to validate models from timm.
128005
tests/post_training/test_quantize_conformance.py

Use transforms from timm

---

tests/openvino/pot/quantization/test_helpers.py
tests/openvino/pot/quantization/test_parameters.py
tests/openvino/pot/quantization/test_sanity.py
tests/openvino/pot/test_engine.py
tests/openvino/pot/utils.py
tests/openvino/tools/calibrate.py
tests/openvino/tools/config.py

* All POT imports from the `calibrate.py` are wrapped by try-catch
* `tests/openvino/pot` tests are skipped in case POT is not available
POT is not available on openvino master branch after the PR  https://github.com/openvinotoolkit/openvino/pull/21805
128463
* calibration2_int8 build 10865
* I've built lates OV manually and checked one default quantization case and one AA case in the calibrate.py.
* tests/openvino/pot are tested in an environment without POT

[OV][Calibrate tool] Try to import POT instead of unconditional POT import

---

tests/torch/sparsity/movement/test_training.py

Update name of expected output file. 
Since [4.35.0](https://github.com/huggingface/transformers/tree/v4.35.0) used safetensors serialization by default.
tests/torch/sparsity/movement/test_training.py

Fix test_compression_movement_short_train after update transformers to 4.36

---

tests/torch/sota_checkpoints_eval.json

Metrics for resnet18_imagenet_binarization_xnor are updated
Green e2e_pytorch
e2e_pytorch_2.0.1/18/

[Torch] Update metrics for resnet18_imagenet_binarization_xnor

---

tests/openvino/tools/calibrate.py

Fix TypeError: Object of type RestoreMode is not JSON serializable
TypeError: Object of type RestoreMode is not JSON serializable
N/A
N/A

[release_v280] Fix TypeError: Object of type RestoreMode is not JSON serializable

---

nncf/__init__.py
nncf/parameters.py
tests/openvino/native/quantization/test_weights_compression.py
tests/torch/ptq/test_weights_compression.py

as stated in title
`nncf.parameters.SensitivityMetric` is an argument for `compress_weights` API 
it should be accessible in the folllowing way:
```python
from nncf import SensitivityMetric
#or 
nncf.SensitivityMetric.HESSIAN_INPUT_ACTIVATION
```

Added a SensitivityMetric enum to API

---

nncf/parameters.py
tests/openvino/native/quantization/test_weights_compression.py
tests/torch/ptq/test_weights_compression.py

#2385 to release branch
Added a SensitivityMetric enum to API 
`nncf.parameters.SensitivityMetric` is an argument for `compress_weights` API
it should be accessible in the folllowing way:
```python
from nncf import SensitivityMetric
#or 
nncf.SensitivityMetric.HESSIAN_INPUT_ACTIVATION
```

Added a SensitivityMetric enum to API (#2385)

---

nncf/experimental/common/tensor_statistics/collectors.py
nncf/torch/tensor_statistics/collectors.py
tests/common/experimental/test_reducers_and_aggregators.py

Support for tensors with different sizes on aggregation axes in `TensorCollector`
Previous implementation of tensor collectors was able to aggregate tensors with different batch size in the `per_sample` mode.
As this functional was not tested, this feature was missed in new implementation
125669
Tests with different sizes for online and offline tensor aggregators in `tests/common/experimental/test_reducers_and_aggregators.py`
MaskRCNN-EfficientNetB2B PTQ is checked locally

[Experimental tensor statistics] Tensors with different sizes on aggregation axes support

---

nncf/quantization/algorithms/min_max/torch_backend.py
nncf/torch/quantization/quantize_functions.py
nncf/torch/quantization/reference.py
tests/post_training/reference_data.yaml
tests/torch/quantization/test_functions.py
tests/torch/sota_checkpoints_eval.json

Scale in the torch `tune_range` operation uses `(levels - 1)` instead of `levels` in the numerator
According to the formula from the [docs ](https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Quantization.md#asymmetric-quantization) and my understanding of formula: scale := 1 / len of one quant, levels -1  in the nominator of the scale formula should be used in the `tune_range` function.
128005
`test_functions` is updated accordingly 
e2e_pytorch_2.0.1/17/ (Green after #2365 )
post_training_quantization/244 (Metrics for problematic models timm/mobilenetv3_small_050 and timm/crossvit_9_240 for OV and TORCH backends became close)
NNCF/job/nightly/job/TriggerBetta/559

[Torch] Scale calculation is fixed in the `tune_range` function

---

nncf/openvino/graph/node_utils.py
nncf/openvino/statistics/collectors.py
tests/common/experimental/test_reducers_and_aggregators.py
tests/common/test_statistics_aggregator.py
tests/openvino/native/test_model_transformer.py

* Mean per channel reducer inplace==True mode is enabled
* special_zero reshape parameter is used inside mean per channel inplace implementation to make
* Micro bug in `OVMeanPerChanelReducer.get_inplace_fn` is fixed
* To use mean_per_channel reducer inplace thus to reduce memory consumption for BiasCorrection algorithm
113335
All related tests are updated with new reference values

[OV] `mean_per_channel` inplace==True mode is enabled by default

---

Makefile
tests/cross_fw/sdl/fuzz/quantize_api.py
tests/cross_fw/sdl/fuzz/requirements.txt

Added a fuzz target for `nncf.quantize` API using `atheris` and the idea by @jszczepa. Added a `make` target `test-fuzz` for this and future fuzz run cases.
Fuzzing is a necessary testing technique.
126163, 129621
tests/cross_fw/sdl/fuzz/quantize_api.py

Add first version of fuzzing tests

---

tests/post_training/reference_data.yaml

timm/crossvit_9_240_backend_TORCH metrics are adjusted
*Validation timeline
4.01.24 Tune range fix https://github.com/openvinotoolkit/nncf/pull/2364 validation is green ✅
6.01.24 Weekly post training quantization test is green ✅
9.01.24 Matmul to symmetric mode for transformer https://github.com/openvinotoolkit/nncf/pull/2375 validation is green ✅
11.01.24 Matmul to symmetric mode for transformer https://github.com/openvinotoolkit/nncf/pull/2375 is merged
12.01.24 Tune range fix https://github.com/openvinotoolkit/nncf/pull/2364 is merged
20.01.24 Weekly post training quantization test is red ❌
* timm/crossvit_9_240_backend_TORCH is affected by both PRs  (tune range is calculated differently, some MatMuls were quantized in a wrong mode (asymmetric instead of symmetric) and was never tested …

Adjust timm/crossvit_9_240_backend_TORCH metrics

---

nncf/experimental/tensor/functions/__init__.py
nncf/experimental/tensor/functions/numeric.py
nncf/experimental/tensor/functions/numpy_numeric.py
nncf/experimental/tensor/functions/torch_numeric.py
tests/common/test_tensor.py
tests/shared/test_templates/template_test_nncf_tensor.py
tests/torch/test_tensor.py

Numeric.quantile is introduced
To make it possible to calculate quantile on `nncf.experimental.tensor.Tensor`
test_fn_quantile

[Experimental tensor] numeric.quantile is introduced

---

examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/README.md
examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
tests/cross_fw/examples/example_scope.json

Relax the default accuracy drop to 0.005
test_examples fix
ref: 130462
test_examples 216

Update anomaly_stfpm_quantize_with_accuracy_control example

---

nncf/quantization/algorithms/weight_compression/mixed_precision.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py

Using FP32 precision to calculate compressed weights
Time Optimization of weight compression.
Models | Weight precision | Task | 0fdac3dc131facb7353e61a9282454253c82ae6e | PR | Speed up
-- | -- | -- | -- | -- | --
  |   |   | Time (sec) | Time (sec) |  
llama-2-7b-chat-hf | FP16 | int8_asym | 239,36 | 59,98 | 3,990713571
llama-2-7b-chat-hf | FP16 | int4_sym_g128_r80 | 633,45 | 279,41 | 2,267103064
llama-2-7b-chat-hf | FP32 | int8_asym | 74,22 | 44,81 | 1,656215131
llama-2-7b-chat-hf | FP32 | int4_sym_g128_r80 | 315,83 | 243,76 | 1,295663768
130239
N/A

Using FP32 precision to calculate compressed weights

---

nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/config.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
tests/openvino/native/quantization/test_weights_compression.py

To further reduce the model footprint
124822
test_quantize_Gather_with_multiple_reduction_axes_in_8bit
test_not_quantize_Gather_with_multiple_reduction_axes_if_all_layers

Compress Embeddings with multiple axes to 8 bit

---

nncf/torch/nncf_network.py

Fix missed new arguments `replace_modules`  and `trace_parameters`  on get_clean_shallow_copy

Fix missed new arguments on get_clean_shallow_copy

---

docs/compression_algorithms/CompressWeights.md
nncf/common/tensor_statistics/collectors.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/awq.py
nncf/quantization/algorithms/weight_compression/backend.py
nncf/quantization/algorithms/weight_compression/config.py
nncf/quantization/algorithms/weight_compression/mixed_precision.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
nncf/quantization/quantize_model.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py
tests/torch/ptq/test_weights_compression.py

To further reduce the model footprint and handle situations when Linear layers are expressed by Convolution operation, we should add Conv layers to the scope of weight compression.
124822
Added tests to tests/openvino/native/quantization/test_weights_compression.py

Compress weights of Conv layers to 8 bit

---

nncf/openvino/graph/layout.py
tests/openvino/native/test_layer_attributes.py

- Updated `get_conv_weights_layout` to prevent linked list incrementation;
- Failed tests;
- 131207
- Should be tested with the newest `pytest` version;

[PTQ] Update get_conv_weights_layout method

---

nncf/quantization/algorithms/weight_compression/config.py
tests/openvino/native/quantization/test_weights_compression.py

Explicitly use unsigned 64-bit integer for number of weight in weight compression.
The overflow is happening on Windows, when 32-bit integers are summed up: 
it leads to incorrect mixed precision selection.
bug with chatglm3 on Windows - 130819

Avoiding overflow on summing 32-bit int on Windows

---

nncf/quantization/algorithms/weight_compression/torch_backend.py
tests/torch/ptq/test_weights_compression.py

Fixed bug with `channel_idx` for Torch Conv metatypes
Fixed bug in `get_module_by_name()` if base model has weights as a `torch.nn.Parameter`
124822
Added `test_compress_weights_functional_model`

[PT][WC] Add WC tests for functional models

---

nncf/openvino/quantization/quantize_model.py
nncf/quantization/quantize_model.py

Minor fixes
nncf.quantize_with_accuracy_control fails with tune_hyperparams=True
Ref: 131814
Current tests

nncf.quantize_with_accuracy_control fails with tune_hyperparams=True

---

tests/tensorflow/sota_checkpoints_eval.json
tests/tensorflow/test_sota_checkpoints.py

- Increase threshold for test int8 model on GPU
- Increase max threshold for metric on OV for yolo_v4_coco_int8 (that depends from TF version)
132089

[TF] Increase thresholds for e2e

---

tests/post_training/data/wc_reference_data.yaml
tests/post_training/pipelines/lm_weight_compression.py
tests/post_training/test_quantize_conformance.py

Introduced a more strict criterion for passing conformance tests for weight compression: similarity should match at least to the fifth decimal place.
Also use a specific dataset revision to avoid issues with different accuracy
in order to catch regressions - e.g., https://github.com/openvinotoolkit/nncf/pull/2420
n/a

More strict threshold for accuracy and minor corrections

---

nncf/quantization/quantize_model.py

`subset_size` and `awq` were made keyword-only arguments in `nncf.compress_weights`
Maintaining backward compatibility for `nncf.compress_weights`
N/A
TBD

subset_size and awq are keyword-only arguments in nncf.compress_weights

---

nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py

- Changed `multiply` node `scale` creation to `opset.constant` with unique name;
-  Robustness of the `compress_weights` pipeline;
- 132595
- Updated `tests/openvino/native/quantization/test_weights_compression.py`;

[PTQ][OV] Added scale constant creation

---

tests/onnx/benchmarking/accuracy_checker.py
tests/onnx/benchmarking/run_ptq.py
tests/openvino/datasets_helpers.py
tests/openvino/tools/calibrate.py
tests/openvino/tools/config.py

- Added try-catch for OMZ imports;
- [OV PR #22683](https://github.com/openvinotoolkit/openvino/pull/22683)
- 132634
- Locally tested with 24.0 OV
- Test run with OV nightly - ubuntu20_precommit_openvino/48 (upd. useless run due to the latest drop a week ago)

[PTQ][v2.9.0] Added try-catch for the OMZ imports

---

nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py

- Changed `multiply` node `scale` creation to `opset.constant` with unique name;
-  Robustness of the `compress_weights` pipeline;
- 132595
- Updated `tests/openvino/native/quantization/test_weights_compression.py`;
(cherry picked from commit 59a6a40118037471f09b3cb7f1142180c0da2824)

[PTQ][OV][v2.9.0] Added scale constant creation (#2475)

---

nncf/torch/dynamic_graph/context.py
nncf/torch/dynamic_graph/trace_tensor.py
nncf/torch/graph/graph_builder.py
nncf/torch/graph/operator_metatypes.py
nncf/torch/model_analyzer.py
nncf/torch/nncf_network.py
tests/torch/helpers.py
tests/torch/nas/helpers.py
tests/torch/ptq/test_wrap_model.py

- If model traced with trace_parameters=True, detect shared constant nodes by number of output nodes and propagate this attribute to next nodes.
- Rename OP_NAMES_QUANTIZE_NODE to QUANTIZE_NODE_TYPES
Incorrect set `is_shared` attributes. 
test_shared_nodes_in_wrapped_model_with_trace_parameters

[PT] Propagate is_shared attribute from constant node

---

nncf/quantization/algorithms/accuracy_control/ranker.py

Fix typo
TypeError: revert_operations_to_floating_point_precision() missing 2 required positional arguments: 'is_node_with_weight_fn' and 'get_weight_tensor_port_ids_fn'
N/A
Current scope

Fix TypeError: revert_operations_to_floating_point_precision() missing 2 required positional arguments

---

nncf/quantization/fake_quantize.py
tests/post_training/test_tune_range.py

When `tune_range()` is called with a `left_border` being equal to 0. This leads to the following warning
```
/home/nsavel/workspace/nncf/nncf/experimental/tensor/tensor.py:84: RuntimeWarning: invalid value encountered in multiply
return Tensor(self.data * unwrap_tensor_data(other))
```
at this line:
```
rb = fns.where(qval > 0.0, (qval - level_high) / qval * left_border, right_border)
```
When we divide by `qval` which equals 0, this results in a NaN during computation. At the same time if `qval` is zero then `where` condition does not hold and `rb==right_border`. Seems like numpy computes both results nevertheless of the condition.
Do not show the unnecessary warning because it is confusing.
Improving UX
Added a test for `tune_range`. Not sure about the location, feel free to suggest a …

Hide an irrelevant warning during tune_range call

---

nncf/quantization/algorithms/min_max/algorithm.py

- Fix **ModeBasedDefaults** creation with **fields**;
- Bug with Python 3.11;
- N/A
- N/A

[PTQ] Fix ModeBasedDefaults

---

nncf/torch/__init__.py
nncf/torch/dynamic_graph/patch_pytorch.py
nncf/torch/dynamic_graph/structs.py
nncf/torch/dynamic_graph/trace_tensor.py
tests/torch/ptq/test_weights_compression.py

Correct dtype handling for compressed torch.nn.Parameter
Weight compression for `CompVis/ldm-super-resolution-4x-openimages`
PR: https://github.com/openvinotoolkit/openvino.genai/pull/232
test_get_dtype_attribute_of_parameter

Correct dtype handling for compressed torch.nn.Parameter

---

examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/README.md
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/deploy.py
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
tests/cross_fw/examples/example_scope.json
tests/cross_fw/examples/run_example.py

- Add quantize_with_accuracy_control example for ONNX backend
Add example for ONNX backend.
An example is needed to demonstrate how to use quantize_with_accuracy_control for the ONNX backend.
Ref: 127606
test_examples build

Add quantize_with_accuracy_control example for ONNX backend

---

tests/cross_fw/examples/run_example.py

Skip `llm_tune_params` test due to different in output for the same sentence (Runtime ticket 133681)
To fix nightly job
132631

Skip llm_tune_params test

---

tests/cross_fw/examples/run_example.py
tests/cross_fw/examples/test_examples.py

pytest dependency is removed from run_example.py
Test example fails due to missing pytest dependency 
Found in test_examples/261/
test_examples/262/

Remove pytest dependency from run_example.py

---

nncf/torch/model_analyzer.py
nncf/torch/model_transformer.py
tests/post_training/test_templates/helpers.py
tests/torch/test_model_analyzer.py

Return bias value after fusing layer, only for conv+bn (other layers does not supported by PT FBC). 
It's temporal fix, working with bias and extracted model will be reworked in 129581.
Incorrect calculation bias shift magnitude

[PT] Return bias value after fusing layer for FBC

---

nncf/torch/dynamic_graph/wrappers.py
nncf/torch/external_hook.py
tests/torch/test_nncf_graph.py
tests/torch/test_tracing_context.py

Do not trace parameters for modules inserted by NNCF
Reduce number of nodes in NNCFGraph, this parameters will not used to anilazine graph or insert points. 
test_not_trace_parameters_in_nncf_modules

[PT] Do not trace parameters for modules inserted by NNCF

---

tests/cross_fw/examples/run_example.py
tests/cross_fw/examples/test_examples.py

- Cherry-picked change from https://github.com/openvinotoolkit/nncf/pull/2513
- Cherry-picked change from https://github.com/openvinotoolkit/nncf/pull/2520
- Failed test_examples run 271 with 
`FAILED tests/cross_fw/examples/test_examples.py::test_examples[llm_tune_params] - assert 1.0 == 0.9 ± 2.0e-03`
- 132634
- N/A

[v2.9.0] Disable broken test in examples

---

examples/llm_compression/openvino/tiny_llama_find_hyperparams/main.py
tests/cross_fw/examples/example_scope.json
tests/cross_fw/examples/test_examples.py

Fix problem with inputs in `tiny_llama_find_hyperparams` example and remove xfail for `llm_tune_params` test
test_examples job: 274
Enable test in nightly validation
132631
Enable `llm_tune_params` test

Enable llm_tune_params test

---

nncf/torch/pruning/filter_pruning/algo.py

Add logs for user guiding better

---

examples/torch/requirements.txt

tabulate is removed from torch examples requirements
Redundant requirements is removed

[Torch] tabulate is removed from torch examples requirements

---

nncf/quantization/algorithms/accuracy_control/ranker.py
nncf/quantization/passes.py
tests/common/accuracy_control/backend.py

The `remove_shapeof_subgraphs()` function removes some operations whose weights are quantized.
Ref: 131843
Current scope

Fix remove_shapeof_subgraphs

---

Makefile
tests/tensorflow/pytest.ini
tests/tensorflow/test_compressed_graph.py
tests/tensorflow/test_sota_checkpoints.py

- TF tests: Add nightly mark for mask_rcnn model.
- Reduced time of TF precommit from ~65min to ~30min.
Skip long-running tests in precommit

[CI] Move mask_rcnn model to nightly TF tests

---

nncf/__init__.py
nncf/scopes.py
tests/common/test_ignored_scope.py

Introduce an ability to define subgraph in ignored scope
The models get more complicated in terms of structure. Noticed many times, that it's impossible to exclude some parts of the model from quantization using the existing ignore scope functionality.
Ref: 100999
tests/common/test_ignored_scope.py

Introduce an ignored subgraph

---

examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
tests/cross_fw/examples/run_example.py

Please see https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection
anomaly_stfpm_quantize_with_accuracy_control example fails on Windows
Ref: 131932
test_exampels

Fix anomaly_stfpm_quantize_with_accuracy_control for Win

---

nncf/quantization/advanced_parameters.py
tests/tensorflow/quantization/test_ptq_params.py

Add a check on None for OverflowFix parameter.
Fix bug
N/A
Add test on a failed before scenario

Add check on None

---

examples/quantization_aware_training/torch/resnet18/requirements.txt
tests/cross_fw/examples/example_scope.json

- Fix requirements.txt to actual version
- Set int8_top reference to mean from 10 runs ( min: 56.527 max: 56.913) = 56.7721
Failed nightly test

Fix test examples qat resnet18

---

nncf/experimental/common/graph/netron.py
tests/common/experimental/test_netron.py

This PR solves #2552 by fixing the Netron visualization. The function `save_for_netron` now produces an XML file that can be correctly opened by Netron. To achieve this, a dummy `dtype` conversion has been introduced, as discussed in #2552. This conversion maps the nncf dtype `Dtype.FLOAT` to `f32` and `DType.INTEGER` to `i32`.
The `precision` parameter of the class `PortDesc` now is no longer optional as it's always available and it's necessary to produce a working XML file.
In addition, I added a docstring for all the functions/classes and implemented tests for the following methods:
- `get_graph_desc()`
- `PortDesc.as_xml_element()`
- `NodeDesc.as_xml_element()`
- `EdgeDesc.as_xml_element()`
It was not possible to open XML files produced by the function `save_for_netron` due to the …

Fixed netron visualization

---

docs/compression_algorithms/CompressWeights.md

Link for LLM inference moved to other url
Fix pre-commit links check

Fix broken link

---

nncf/torch/utils.py
tests/torch/helpers.py
tests/torch/test_utils.py

This PR addresses #2579.
- Add tests for torch device utils. The tests consider the case in which the model has no parameters, has all parameters on CPU, has all parameters on CUDA, and has parameters placed on different devices. In the latter, the parameters are moved on different devices randomly. 
- Add tests for torch `dtype` utils. The case in which the model has no parameters is also considered.
- Created a test torch helper class `EmptyModel` to take into account the case in which the model has no parameters at all.
- Add docstrings in utils.
I compared all the results manually checking for their correctness. The code is also compliant with the coding style having been verified with `pre-commit run`

Tests for torch device and dtype utils

---

examples/quantization_aware_training/torch/resnet18/main.py
licensing/third-party-programs.txt
nncf/common/utils/helpers.py
nncf/torch/pruning/base_algo.py
nncf/torch/pruning/filter_pruning/algo.py
setup.py

Using tabulate instead of texttable package to create tables.
Avoid installation two packages to same task.
Tabulate is optional dependencies of pandas package, that used in NNCF. https://github.com/openvinotoolkit/nncf/pull/2542
134603

Use tabulate instead of texttable

---

nncf/openvino/graph/metatypes/groups.py
nncf/openvino/graph/node_utils.py
nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
nncf/quantization/quantize_model.py
tests/post_training/data/ptq_reference_data.yaml
tests/post_training/model_scope.py

- Extended OPERATIONS_WITH_BIAS for BiasCorrection algorithm;
- Extended conformance test scope with the `mobilenetv3` + BiasCorrection;
- List extension would allow us to restore accuracy for the specific models;
- To observe differences between BiasCorrection algorithms;
- 133198
- manual/post_training_quantization/326/ - passed

[PTQ] Extend layers list for BiasCorrection

---

tests/post_training/pipelines/causal_language_model.py
tests/post_training/requirements.txt

use the latest release of optimum-intel==1.15.2
The previously used version of optimum had a call of deprecated API that was removed in 2024 release of OpenVINO.
https://github.com/openvinotoolkit/openvino/issues/21979
```
outputs = self.request(inputs, shared_memory=True)
```
Latest optimum migrated to the actual API.
n/a

Use latest optimum to not call deprecated shared_memory API

---

tests/cross_fw/examples/example_scope.json

Update accuracy drop reference value. 
In #2246 reference accuracy values for original and quantized models were updated, but the corresponding accuracy drop reference value was not updated.
136123

Update accuracy drop reference value for SSD example

---

nncf/onnx/graph/metatypes/groups.py
nncf/onnx/graph/metatypes/onnx_metatypes.py
nncf/openvino/graph/metatypes/groups.py
nncf/torch/graph/operator_metatypes.py
tests/openvino/native/quantization/test_sanity.py
tests/post_training/data/ptq_reference_data.yaml

- Reduced metatypes in `OPERATIONS_WITH_BIAS` list for ONNX;
- Reduced metatypes in `OPERATIONS_WITH_BIAS` list for PyTorch;
- Separated GroupConvolution from the Convolutions on ONNX;
- Alignment for algorithms between backends;
- 133198
- 104166
- 106469
- post_training_quantization/323 - failed with regressions for ONNX (as expected)
- post_training_quantization/324 - passed (updated references)

[PTQ] Metatypes with bias list alignment

---

tests/openvino/native/data/2024.1/reference_scales/yolo-v3-tiny-onnx_mixed.json
tests/openvino/native/data/2024.1/reference_scales/yolo-v3-tiny-onnx_performance.json

- Update references for OV 2024.1;
- Bugfix for `openvino-nightly`;
- N/A
- openvino-nightly/windows_precommit_openvino/23 - failed (with the issue from CVS-135890, expected to fix on the OpenVINO side)
- openvino-nightly/ubuntu20_precommit_openvino/57 - failed (with the issue from CVS-135890, expected to fix on the OpenVINO side)

Update references for 2024.1

---

nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/torch/quantization/layers.py
tests/torch/ptq/test_weights_compression.py

- Store compression scale if FP16
- Add type conversion to original data type after decompression
Below are the compression subgraphs for the first conv2d in mobilenet_v2 after conversion to OV, this is similar to the table presented in #2537 .
Compared to OV case, there is an additional Multiply node after the scale Multiply node. It seems to come from Batch Norm applied to the convolution. In case of PT weight compression it does not get merged into the weight as it does in OV case.
Weight compression for PT backend fails when applied to model in half precision. The reason is that the scale is always in FP32, and hence decompression result is also in FP32, which conflicts with input type of FP16.
134063
Added test for half/full precision cases. Also added cases for different devices as …

[WC, PT] Store compression scale in f16

---

nncf/common/tensor_statistics/aggregator.py

Restore total number of iterations for StatisticsAggregator after https://github.com/openvinotoolkit/nncf/pull/2197
N/A
136892
Manually tested on yolov8 sample for OV.
Before:
After:

Restore total of status bar

---

tests/cross_fw/examples/example_scope.json
tests/cross_fw/examples/run_example.py
tests/cross_fw/examples/test_examples.py

Deterministic mode is enabled for resnet18 qat example
To make test_examples stable
136387
test_examples/314/ PASSED
test_examples/317/ PASSED

[Test][Examples] Make resnet18 qat test deterministic

---

README.md
examples/post_training_quantization/onnx/mobilenet_v2/requirements.txt
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
examples/post_training_quantization/torch/ssd300_vgg16/requirements.txt
setup.py
tests/post_training/requirements.txt
tests/torch/requirements.txt

Bump up onnx, onnxruntime versions for torch tests
Update version of onnx at Readme
Many
N/A
N/A

Update onnx and onnxruntime for torch tests

---

nncf/quantization/algorithms/min_max/torch_backend.py
nncf/torch/external_hook.py
nncf/torch/graph/transformations/command_creation.py
nncf/torch/graph/transformations/commands.py
nncf/torch/model_graph_manager.py
nncf/torch/model_transformer.py
nncf/torch/nncf_network.py
nncf/torch/quantization/algo.py
nncf/torch/quantization/debug_interface.py
nncf/torch/quantization/external_quantizer.py
nncf/torch/quantization/precision_init/base_init.py
nncf/torch/quantization/precision_init/hawq_debug.py
nncf/torch/quantization/strip.py
tests/torch/ptq/test_smooth_quant.py
tests/torch/quantization/test_algo_quantization.py
tests/torch/quantization/test_strip.py
tests/torch/test_extractor.py
tests/torch/test_model_graph_manager.py
tests/torch/test_model_transformer.py
tests/torch/test_nncf_network.py
tests/torch/test_tracing_context.py

Preparation for #2531
1) `PTQuantizerInsertionCommand` is removed and replaced with create_quantizer_insertion_command function
2) `SharedFNInsertionCommand` updates with one new attribute: compression_module_type
3) `ExtraOpCallHook` doesn't require context in constructor anymore
4) Multidevice support is moved from `apply_quantizers_insertion_commands_transformation` to `apply_insertion_transformation`
1) To make it easier to store and restore commands: less commands - less amount of adapters are needed
2) To make it possible to express  `PTQuantizerInsertionCommand` by  `SharedFNInsertionCommand`
3) To make it possible to create `ExtraOpCallHook` outside of the `PTModelTransformer`
4) To unify multidevice support for all insertion operations
2531 …

[Torch] Drop `PTQuantizerInsertionCommand` 

---

nncf/__init__.py
nncf/common/quantization/structs.py
nncf/quantization/advanced_parameters.py

- Inherit `OverflowFix` and `QuantizationPreset` from `StrEnum` instead of `Enum` to make them serializable.
- Expose `OverflowFix` as `nncf.OverflowFix`
Came up during optimum-intel integration.

Inherit OverfloFix and QuantizationPreset from StrEnum

---

tests/openvino/native/data/2024.1/reference_scales/yolo-v3-tiny-onnx_mixed.json
tests/openvino/native/data/2024.1/reference_scales/yolo-v3-tiny-onnx_performance.json

- Updated references for OV 24.1;
- Stable tests;
- N/A;
- Updated;
- openvino-nightly/windows_precommit_openvino/27/ - passed
- openvino-nightly/ubuntu20_precommit_openvino/63/ - failed due to issue CVS-137763 (fix https://github.com/openvinotoolkit/openvino/pull/23849)

Update refs for OV 24.1

---

nncf/common/graph/operator_metatypes.py
nncf/onnx/graph/metatypes/onnx_metatypes.py
nncf/openvino/graph/metatypes/openvino_metatypes.py
nncf/tensorflow/graph/metatypes/keras_layers.py
nncf/torch/graph/operator_metatypes.py

Add `is_subtype` argument for meta type register 
Registering a nonlinear hierarchy of sub meta types.

Add is_subtype argument for metatype register 

---

nncf/__init__.py
nncf/common/quantization/structs.py
nncf/quantization/advanced_parameters.py

Copy of #2624 to release branch.

[Release] Expose some advanced quantization parameters to be available as nncf.*

---

nncf/torch/graph/transformations/commands.py

Check input_port_id in __eq__ of PTTargetPoins
To correctly check PTTargetPoints

[Torch] Check input_port_id in __eq__ of PTTargetPoint

---

tests/openvino/requirements.txt

- Bumped missed **openvino-dev** package version;
- Missed package version;
- N/A
- post_training_quantization/359/ - passed

Fix missed openvino-dev version package

---

tests/post_training/requirements.txt
tests/torch/models_hub_test/requirements.txt
tests/torch/requirements.txt

- Bumped **transformers** package version to 4.38.2;
- Updating to 4.39.3 is not possible due to **optimum** incompatibility;
- Bumped **accelerate** package due to issue in **transformers** package;
- Package security issues;
- N/A
- post_training_quantization/355/ - passed
- additional post_training_quantization/358/ - passed

Bump transformers version

---

tests/cross_fw/examples/example_scope.json

Increase INT8 metrics after [2610](https://github.com/openvinotoolkit/nncf/pull/2610)
Two extra quantizers were removed -> int8 metrics improved
N/A
test job is run

[OpenVINO] Update reference for YOLOV8 after PR#2610

---

examples/quantization_aware_training/torch/anomalib/README.md
examples/quantization_aware_training/torch/anomalib/main.py
examples/quantization_aware_training/torch/anomalib/requirements.txt
tests/cross_fw/examples/example_scope.json
tests/cross_fw/examples/run_example.py
tests/cross_fw/examples/test_examples.py

Added the example: Quantization-Aware Training of STFPM PyTorch model from Anomalib
This example demonstrates how to quantize [Student-Teacher Feature Pyramid Matching (STFPM)](https://anomalib.readthedocs.io/en/latest/markdown/guides/reference/models/image/stfpm.html) PyTorch model from [Anomalib](https://github.com/openvinotoolkit/anomalib) using Quantization API from Neural Network Compression Framework (NNCF).
N/A
test_examples 323

QAT anomaly example

---

.github/workflows/precommit.yml
Makefile
tests/openvino/native/test_model_transformer.py
tests/openvino/requirements.txt

Use `ubuntu-20.04-8-cores` runner 
Run tests in parallel by xdist (12 vs 37 mins)
Add summary `-ra` to show list of not passed tests (skip, xfail, fail)

[OV] Speedup precommit tests

---

nncf/torch/model_creation.py

Added model type check in nncf.torch.wrap_model
Improve UX
https://github.com/openvinotoolkit/nncf/pull/2636#discussion_r1576234452
N/A

Checking model type in nncf.torch.wrap_model

---

tests/post_training/conftest.py
tests/post_training/data/ptq_reference_data.yaml
tests/post_training/model_scope.py
tests/post_training/test_quantize_conformance.py

Add default batch_size for calibration dataset for every model.
If model has no "batch_size" parameter meaning that it doesn't support batch_size > 1
Speed up quantization
N/A
N/A

[PTQ] Add default batch sizes for PTQ conformance test

---

nncf/torch/graph/graph.py
nncf/torch/graph/transformations/command_creation.py
nncf/torch/graph/transformations/commands.py
nncf/torch/nncf_network.py
tests/torch/helpers.py
tests/torch/nncf_network/helpers.py
tests/torch/nncf_network/test_get_applied_modifications.py
tests/torch/nncf_network/test_hook_handlers.py
tests/torch/nncf_network/test_nncf_network.py
tests/torch/test_api_behavior.py
tests/torch/test_nncf_network.py

On top of #2584 
`NNCFNetwork.transformation_layout` method is introduced
To make it possible to collect applied transformation commands from a modified `NNCFNetwork`
129586
TestGetAppliedModificationCommands

[Torch] NNCFNetwork.transformation_layout

---

tests/tensorflow/sota_checkpoints_eval.json
tests/torch/sota_checkpoints_eval.json

Update metrics for e2e
- PT, Update metrics, ov models start collect parameters for FQ in float32, was float16
- TF, increase threshold for unstable measured metrics on cuda.
138550, 138552

Update targets metrics for e2e (#2633)

---

tests/torch/quantization/test_algo_quantization.py

Model moved to cuda before the quantization in `test_works_when_wrapped_with_dataparallel`
To build CUDA extensions in main process as pytorch could not build extensions in dataparallell mode
https://github.com/pytorch/pytorch/issues/125403
torch_nightly/204/ - Passed
Test started to fail because the order of the tests were changed:
torch_nightly/197:
```
tests/torch/nas/test_sanity_sample.py ........                           [  0%]
[2024-04-25T00:01:42.305Z] tests/torch/quantization/test_functions.py ............sss...sss........ [  2%]
...
```
torch_nightly/198
```
[2024-04-26T00:03:47.228Z] tests/torch/nas/test_sanity_sample.py ........                           [  0%]
[2024-04-26T00:03:47.804Z] tests/torch/nncf_network/test_nncf_network.py .                          [  0%] …
```

[Torch][Tests] Build cuda qantizer extentions before the DataParallel

---

nncf/experimental/tensor/functions/__init__.py
nncf/experimental/tensor/functions/linalg.py
nncf/experimental/tensor/functions/numeric.py
nncf/experimental/tensor/functions/numpy_linalg.py
nncf/experimental/tensor/functions/numpy_numeric.py
nncf/experimental/tensor/functions/torch_linalg.py
nncf/experimental/tensor/functions/torch_numeric.py
tests/shared/test_templates/template_test_nncf_tensor.py

The following functions were added:
- numeric.py: diag
- linalg.py: cholesky, cholesky_inverse, inv
Part of GPTQ implementation.
126887
tests/shared/test_templates/template_test_nncf_tensor.py

Extending functions by diag, cholesky, cholesky_inverse, inv

---

nncf/torch/layer_utils.py
nncf/torch/sparsity/rb/layers.py
tests/torch/test_serialization.py

`_compression_lr_multiplier`  attribute introduced in  #2531 is removed from the `CompressionParameter`
`_compression_lr_multiplier` makes the `CompressionParameter` a stateful parameter which for some reason does not work properly in distributed/dataparallel mode
torch_nightly/213/ - finished successfully

[Torch] Do not change state of the compression parameter

---

tests/tensorflow/sparsity/rb/test_integration.py

Deterministic execution is enabled for rb sparsity integration test 
To prevent sporadic test failure
138817
I've run test several times and differences between reference were bit exact

[TF] RB sparsity integration test is made deterministic

---

nncf/torch/__init__.py
nncf/torch/model_creation.py
nncf/torch/nncf_network.py
tests/torch/test_serialization.py

`model.nncf.get_config` method and `nncf.torch.load_from_config` function are presented
To enable saving/loading NNCFNetwork transformations
129586
`tests/torch/test_serialization.py` is updated

[API][Torch] Save/Load transformations

---

examples/tensorflow/requirements.txt
tests/tensorflow/requirements.txt

tensorflow-metadata 1.13.0
```
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 3.19.6 which is incompatible.
```
140478

[TF] Fix dependency conflict

---

nncf/torch/dynamic_graph/io_handling.py
tests/torch/helpers.py
tests/torch/test_input_management.py

* NNCF wrapping for Tensor input parameters is skipped when actual parameter is not a tensor
* To support models which could accept different types as an input
(example: [YolovV8](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/tasks.py#L77-L89) 
```
def forward(self, x, *args, **kwargs):
if isinstance(x, dict):  # for cases of training and validating while training.
return self.loss(x, *args, **kwargs)
return self.predict(x, *args, **kwargs)
```
138682
* tests/torch/test_input_management.py is extended

[Torch] Do not wrap not tensor inputs

---

nncf/experimental/tensor/definitions.py
nncf/experimental/tensor/functions/torch_numeric.py
nncf/openvino/graph/nncf_graph_builder.py
nncf/openvino/graph/node_utils.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py
tests/openvino/native/test_nncf_graph_builder.py

Added support for bf16 in `nncf.compress_weights`
Support models with bf16 weights and fp32 or fp16 inference precision.
ref: 141582
tests/openvino/native/quantization/test_weights_compression.py:test_compression_for_different_dtypes

[OV] Compress bf16 weights

---

nncf/common/accuracy_aware_training/training_loop.py
setup.py

Remove dependency from typing_extensions 
Fail with `ImportError` on python>=3.9.
nncf.common depends from typing_extensions packages
https://github.com/openvinotoolkit/nncf/blob/47187e5bbaef678508fdfdc980b258fc4e32d3db/nncf/common/accuracy_aware_training/training_loop.py#L22-L23
With python3.8 typing_extensions installs as depends of rich module, but it works only on `python<3.9`
```
Collecting typing-extensions<5.0,>=4.0.0 (from rich>=13.5.2->nncf==2.11.0.dev0+1406e7f)
```
https://github.com/Textualize/rich/blob/349042fd8912ab5f0714ff9a46a70ef8a4be4700/pyproject.toml#L31
tests/cross_fw/install (python 3.10)

Remove dependency from typing_extensions 

---

nncf/quantization/algorithms/smooth_quant/algorithm.py

- Fixed SmoothQuant algorithm to work with Split ports correctly;
- Bugfix
- 140351

Fix SQ algorithm ports usage

---

tests/cross_fw/examples/example_scope.json

Fix name of backend
```
>   packages = [item for b in backends for item in MAP_BACKEND_PACKAGES[b]]
E   KeyError: 'tensorflow'
```
tests.cross_fw.examples.test_examples.test_examples[post_training_quantization_tensorflow_mobilenet_v2]

Fix test examples

---

tests/cross_fw/install/test_install.py

Removal install package with extra from tests
```
WARNING: nncf 2.11.0.dev0+unknown.version does not provide the extra 'torch'
```

Removal install package with extra from tests

---

.github/workflows/api_changes_check.yml
.github/workflows/assign_issue.yml
.github/workflows/build_and_publish_doc.yml
.github/workflows/build_html_doc.yml
.github/workflows/build_schema_page.yml
.github/workflows/labeler.yml
.github/workflows/model_hub.yml
.github/workflows/mypy.yml
.github/workflows/nightly.yml
.github/workflows/post_pr_merge.yml
.github/workflows/pre-commit-linters.yml
.github/workflows/precommit.yml
.github/workflows/python-publish.yml
.github/workflows/upload_coverage_for_develop.yml

Token permissions docs: https://github.com/ossf/scorecard/blob/98ec491a888a8a0db9d83a3c7d379ae1f46321de/docs/checks.md#token-permissions
Actions by hash docs: https://github.com/ossf/scorecard/blob/98ec491a888a8a0db9d83a3c7d379ae1f46321de/docs/checks.md#pinned-dependencies
143130

[CI] Set actions references to specific commit hash, provide explicit top level token permissions for jobs

---

nncf/torch/dynamic_graph/patch_pytorch.py
nncf/torch/dynamic_graph/patch_pytorch_state.py
nncf/torch/dynamic_graph/wrappers.py
tests/torch/pytorch_patch_isolated.py
tests/torch/test_pytorch_patch.py

- Add condition to skip operator wrapping if torch is in unpatched state
- Fix test from a previous PR #2665 (remove dependency of the test on `nncf.torch`)
Fix inference of compiled torch models when `nncf.torch` is imported
140265
Added `test_operator_unpatching`

Fix torch operator unpatching

---

tests/post_training/data/wc_reference_data.yaml
tests/post_training/pipelines/base.py

Fail test pipeline in case of improvement if target metric improves
To catch unexpected changes.

[CI] Fail pipeline on improvement metric

---

nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/min_max/torch_backend.py

Excluded comparison operations from quantizable operations for transformer models
Quantization of comparison operations is lead to the runtime error:
```
RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:223:
Exception from src/plugins/intel_cpu/src/node.cpp:559:
Multiply node with name 'self_attn/aten::mul/Multiply' Exception from src/plugins/intel_cpu/src/shape_inference/custom/eltwise.cpp:45:
Eltwise shape infer input shapes dim index: 1 mismatch
```
ref 143448
N/A

Excluded comprasion operations from quantizable operations

---

tests/openvino/native/common.py

Remove raising an error in the test when a graph does not exist.
To return the feature with re/generating reference graphs using `NNCF_TEST_REGEN_DOT`
N/A
N/A

[Tests] Remove raising error when graph is not existed

---

.github/workflows/precommit.yml

[CI] install missed requirements for torch-cuda action

---

tests/torch/test_pytorch_patch.py

xfail for test_torch_compile in windows
Torch not support compile on windows

xfail for test_torch_compile in windows

---

Makefile

Add `--dist loadscope` for OV tests.
Try to fix sporadically issue `EOFError: Compressed file ended before the end-of-stream marker was reached` for  tests/openvino/native/quantization/test_sanity.py::test_compression
Possible reason is downloading dataset in several process at the same time.
Example: https://github.com/openvinotoolkit/nncf/actions/runs/9610990503/job/26508643899

[OV] Parallel tests by scope

---

tests/openvino/tools/calibrate.py

Change None to []
Incorrect API usage
144809
Manually tested on failed scenario

Fix default value for ignored scope in calibrate.py

---

.github/workflows/post_pr_merge.yml

Add `paths-ignore` to post post_pr_merge.yml, like in pre-commit
Failed job for pull request that not run pre-commit and not generate coverage reports.

[CI] Add paths-ignore like in pre-commit

---

nncf/tensor/README.md
nncf/tensor/functions/__init__.py
nncf/tensor/functions/linalg.py
nncf/tensor/functions/numeric.py
nncf/tensor/functions/numpy_linalg.py
nncf/tensor/functions/numpy_numeric.py
nncf/tensor/functions/torch_linalg.py
nncf/tensor/functions/torch_numeric.py
tests/shared/test_templates/template_test_nncf_tensor.py

The following functions were added:
- numeric.py: eye
- linalg.py: lstsq, svd
Part of int4 with LoRA adaptation implementation.
CVS-135863
tests/shared/test_templates/template_test_nncf_tensor.py

Extending functions by lstsq, svd, eye

---

Makefile

Removed `tensorflow` from test environment.
After https://github.com/openvinotoolkit/nncf/pull/2663 module is not required in tests. It was need for yolov4.

[OV] Clean test environment

---

nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
tests/openvino/native/quantization/test_weights_compression.py

Fixed bug with clamp ranges in scale estimation.
bug
Unit test.

1) Fixed bug with clamp range in scale estimation.

---

examples/post_training_quantization/onnx/mobilenet_v2/main.py
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/deploy.py
examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
examples/post_training_quantization/openvino/mobilenet_v2/main.py
examples/post_training_quantization/openvino/yolov8/main.py
examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
examples/post_training_quantization/torch/mobilenet_v2/main.py
nncf/openvino/engine.py
nncf/quantization/algorithms/accuracy_control/openvino_backend.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/onnx/quantization/test_ptq_regression.py
tests/openvino/native/quantization/test_sanity.py
tests/openvino/native/test_model_transformer.py
tests/openvino/test_transform_fn.py
tests/openvino/tools/calibrate.py
tests/post_training/pipelines/image_classification_timm.py

- Set the `CPU` device for `compile_model`.
- Unstable results with the `AUTO` device.
- 144747
- nightly/test_examples/441/ - **passed**
- nightly/windows/test-examples/100/ - **passed**
- openvino-nightly/test_examples/50/ - **failed** (as expected due to 145701)
- manual/post_training_weight_compression/86/ - **passed**
- manual/post_training_quantization/420/ - **passed**

Compile model only for CPU

---

examples/llm_compression/openvino/tiny_llama/main.py
examples/llm_compression/openvino/tiny_llama_find_hyperparams/main.py

Explicit enabling of dynamic quantization of activations and updating metrics in the weight compression examples. 
It's possible to adapt compression examples for new openvino-nightly by explicitly turning off the dynamic quantization of activations via 
```
OVModelForCausalLM.from_pretrained(OUTPUT_DIR, ov_config={"DYNAMIC_QUANTIZATION_GROUP_SIZE": "0"})
```
The successful 45th run of `test examples` is proving that. 
But examples with dynamic quantization should make validation faster, that's why this PR enables it and updates the metrics. 
OpenVINO 2023.2 has a dynamic quantization of activation enabled by default. (https://github.com/openvinotoolkit/openvino/pull/25054) and that's affects accuracy/metrics in the weight compression examples/tests, since before it was disabled by …

Fix for llm examples with openvino-nightly

---

nncf/tensor/tensor.py
tests/shared/test_templates/template_test_nncf_tensor.py

Support `__iadd__`, `__isub__`, `__imul__`, `__ipow__`, `__itruediv__`, `__ifloordiv__`, `__matmul__` operators for Tensor

Add assignment operators and matmul

---

nncf/tensor/functions/linalg.py
nncf/tensor/functions/numpy_linalg.py
nncf/tensor/functions/torch_linalg.py
tests/shared/test_templates/template_test_nncf_tensor.py

The following functions were added:
- linalg.py: pinv
Part of int4 with LoRA adaptation implementation.
CVS-135863
tests/shared/test_templates/template_test_nncf_tensor.py

Add a linalg.pinv wrapper to common tensor

---

nncf/quantization/algorithms/weight_compression/algorithm.py

Sort weights for compression:
```
all_weight_params = sorted(all_weight_params, key=lambda wp: wp.num_weights, reverse=True)
```
During weights compression, memory footprint gradually increases when new low-bit constants are created. At the same time there are temporary spikes in memory footprint which happen during compressed weight computation. For example, here:
```
if invert_scale:
scale = fns.power(scale, -1)
compressed_weights = weight * scale
else:
compressed_weights = weight / scale
if zero_point is not None:
compressed_weights += zero_point.astype(weight.dtype)
compressed_weights = fns.round(compressed_weights)
compressed_weights = fns.clip(compressed_weights, level_low, level_high).astype(dtype)
```
Multiple temporary full precision arrays are needed to be created here. After …

Lower weight compression memory footprint by sorting weights according to their size

---

docs/usage/post_training_compression/weights_compression/Usage.md
nncf/quantization/algorithms/weight_compression/gptq.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
nncf/quantization/quantize_model.py
tests/openvino/native/quantization/test_weights_compression.py
tests/post_training/data/wc_reference_data.yaml
tests/post_training/model_scope.py

* Support `group_size=-1` in AWQ, GPTQ and Scale Estimation algorithms 
* To enable more accurate per-channel quantization for devices that do not support group quantization
* 145725
tests/openvino/native/quantization/test_weights_compression.py

Support per-channel mode in AWQ, GPTQ and Scale Estimation algos

---

tests/post_training/data/wc_reference_data_2024.3.yaml
tests/post_training/test_quantize_conformance.py

Introduced opportunity to override metrics in the conformance test for different OpenVINO versions
There are some known differences in accuracy between OV 2024.2 and OV nightly, but tests for OV nightly are constantly failing
until migration to 2024.3. 
This PR helps to keep track of changes in accuracy during release preparation.
CVS-146143
16 build of weekly/openvino-nightly/post_training_weight_compression
Thanks to @AlexanderDokuchaev for the implementation

Introduced versioning of reference for conformance tests

---

tests/common/accuracy_control/test_calculate_drop.py
tests/common/graph/test_dot_file_rw.py
tests/common/quantization/test_minmax.py
tests/common/quantization/test_passes.py
tests/common/quantization/test_quantizer_removal.py
tests/common/requirements.txt
tests/onnx/pytest.ini
tests/onnx/quantization/test_classification_models_graph.py
tests/onnx/quantization/test_opset_versions.py
tests/onnx/test_nncf_graph_builder.py
tests/onnx/test_weightless_model.py
tests/post_training/test_templates/test_quantizer_config.py
tests/tensorflow/pytest.ini
tests/torch/nas/test_state.py
tests/torch/nncf_network/test_hook_handlers.py
tests/torch/nncf_network/test_nncf_network.py
tests/torch/pruning/experimental/test_nodes_grouping.py
tests/torch/quantization/test_tracing.py
tests/torch/test_algo_common.py
tests/torch/test_no_nncf_trace_patching.py

Fix warnings in tests:
- PytestCollectionWarning: cannot collect test class 'Test' because it has a __init_ constructor 
- UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
- UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future.
- Add `pytest-dependency` to requirements for common tests
- Remove xfail for expected exception in `tests/common/quantization/test_minmax.py::test_mode_against_default_map`
- Fix marks for onnx tests
Reduce output log.
138690

Fix pytest warnings

---

nncf/common/graph/graph.py
nncf/onnx/graph/node_utils.py
nncf/openvino/graph/node_utils.py
nncf/quantization/algorithms/bias_correction/openvino_backend.py
nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py
nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/smooth_quant/algorithm.py
nncf/quantization/algorithms/smooth_quant/openvino_backend.py
nncf/quantization/algorithms/weight_compression/algorithm.py
tests/openvino/native/data/2024.1/reference_scales/LSTMSequenceModel_mixed.json
tests/openvino/native/data/2024.1/reference_scales/LSTMSequenceModel_performance.json
tests/openvino/native/models.py
tests/post_training/test_templates/test_quantizer_config.py

Before the changes in the PR, it was possible to insert the quantize operation after some layer only on its first output (`output port_id = 0`). The PR adds changes that allow the insertion of the quantize operation for operations with multiple outputs (they have different output port IDs), but only when one is used.
The selected FQ operations are not inserted unless changes are made.
- 146088
pre-commit scope

Use a graph to find the output port id for the activation quantization target point

---

tests/torch/sparsity/movement/test_model_saving.py

Increase abs from 1e-2 to 3e-2
Size of pruned and not prunned IR models can changes by openvino version.
it's not first time when reference size required to be change, so increase threshold to be more tolerance.
```
2024.2
desc0 pruned_file_bytes=596  not_pruned_file_bytes=932
desc1 pruned_file_bytes=1004  not_pruned_file_bytes=1340
desc2 pruned_file_bytes=2552  not_pruned_file_bytes=2756
desc3 pruned_file_bytes=584  not_pruned_file_bytes=872
desc4 pruned_file_bytes=748  not_pruned_file_bytes=940
desc5 pruned_file_bytes=1156  not_pruned_file_bytes=1900
desc6 pruned_file_bytes=1240  not_pruned_file_bytes=1900
desc7 pruned_file_bytes=620  not_pruned_file_bytes=956
2024.3
desc0 pruned_file_bytes=604  not_pruned_file_bytes=940
desc1 pruned_file_bytes=1004  not_pruned_file_bytes=1340
desc2 …
```

Increase approx abs 

---

tests/openvino/native/common.py
tests/post_training/data/wc_reference_data_2024.4.yaml
tests/post_training/test_quantize_conformance.py

Consistent apply of correction files until OV version is greater that version of correction file.
A new file needs to be added for the any new versions of OV.

[CI] Correction files for conformance tests

---

setup.py

Set upper limit for pydot version 3.0.0
Pydot 3.0.0 broke saving and loading with special characters

Set upper limit for pydot version 3.0.0 (#2814)

---

tests/torch/sparsity/movement/test_model_saving.py

Increase abs from 1e-2 to 3e-2
Size of pruned and not prunned IR models can changes by openvino version.
it's not first time when reference size required to be change, so increase threshold to be more tolerance.
```
2024.2
desc0 pruned_file_bytes=596  not_pruned_file_bytes=932
desc1 pruned_file_bytes=1004  not_pruned_file_bytes=1340
desc2 pruned_file_bytes=2552  not_pruned_file_bytes=2756
desc3 pruned_file_bytes=584  not_pruned_file_bytes=872
desc4 pruned_file_bytes=748  not_pruned_file_bytes=940
desc5 pruned_file_bytes=1156  not_pruned_file_bytes=1900
desc6 pruned_file_bytes=1240  not_pruned_file_bytes=1900
desc7 pruned_file_bytes=620  not_pruned_file_bytes=956
2024.3
desc0 pruned_file_bytes=604  not_pruned_file_bytes=940
desc1 pruned_file_bytes=1004  not_pruned_file_bytes=1340
desc2 …
```

Increase approx abs  (#2826)

---

tests/torch/sota_checkpoints_eval.json

Update reference from 58.07 to 58.09
Changed in maxpoll layer:
-  `opset8` -> `opset14`
- `rounding_type="ceil"` ->  `rounding_type="ceil_torch"`
```
<layer id="18" name="__module.features.2/aten::max_pool2d/MaxPool" type="MaxPool" version="opset14">
<data strides="2, 2" dilations="1, 1" pads_begin="0, 0" pads_end="0, 0" kernel="3, 3" rounding_type="ceil_torch" auto_pad="explicit" index_element_type="i64" axis="2" />
<layer id="18" name="__module.features.2/aten::max_pool2d/MaxPool" type="MaxPool" version="opset8">
<data strides="2, 2" dilations="1, 1" pads_begin="0, 0" pads_end="0, 0" kernel="3, 3" rounding_type="ceil" auto_pad="explicit" index_element_type="i64" axis="2" />
```

[PT] Update reference for squeezenet1_1_imagenet_int8_per_tensor

---

.github/action_configs/labeler.yml
.github/workflows/labeler.yml

- Bump action/laber v5
- Update laber.yml to be compatible new version
- New rule to add `release target` label for pull requests to `release_v*` branch

Bump laber action to v5

---

nncf/experimental/torch/fx/transformations.py
nncf/torch/graph/operator_metatypes.py
tests/torch/fx/helpers.py
tests/torch/fx/test_fast_bias_correction.py

Add Fast BC test in tests/torch/fx. 
#2809 
The implemented test class inherits from the template for Fast bias correction.

[TorchFX]: Test Fast Bias Correction algorithm

---

tests/openvino/native/common.py
tests/post_training/test_quantize_conformance.py
tests/shared/openvino_version.py
tests/tensorflow/sota_checkpoints_eval.json
tests/tensorflow/test_sota_checkpoints.py

Skip inception_v3_imagenet_rb_sparsity_int8 test from Tensorflow backend for OpenVINO 2024.3
Known issue of OpenVINO 2024.3
147730
OpenVINO 2024.2: e2e_tf_full 726
OpenVINO 2024.3: e2e_tf_full 725

Skip inception_v3_imagenet_rb_sparsity_int8 test from Tensorflow backend

---

Makefile

Junit argument to torch cpu/gpu makefile tasks
Jenkins jobs uses junit to generate report

Add junit report to torch cpu/gpu makefile tasks

---

tests/torch/fx/test_statistics_aggregator.py

New test file for the statistics aggregator for the TorchFX backend has been added in tests/torch/fx.
Closes Issue #2777

[Torch Fx] Statistics Aggregator test

---

nncf/common/hardware/configs/cpu.json
nncf/common/hardware/configs/gpu.json
nncf/common/hardware/configs/npu.json
nncf/common/hardware/opset.py
nncf/openvino/graph/metatypes/groups.py
nncf/openvino/graph/metatypes/openvino_metatypes.py

Adds Slice operation - https://docs.openvino.ai/2022.3/openvino_docs_ops_movement_Slice_8.html
As a result the performance for modnet_webcam_portrait_matting from DLB was improved (local measurement)
from 44 FPS till 72 FPS.
Fix incorrect quantization scheme due to unknown metatype
144218
Manually

[OpenVINO] Add Slice metatype

---

tests/torch/sota_checkpoints_eval.json

Update reference from 58.07 to 58.09
Changed in maxpoll layer:
-  `opset8` -> `opset14`
- `rounding_type="ceil"` ->  `rounding_type="ceil_torch"`
```
<layer id="18" name="__module.features.2/aten::max_pool2d/MaxPool" type="MaxPool" version="opset14">
<data strides="2, 2" dilations="1, 1" pads_begin="0, 0" pads_end="0, 0" kernel="3, 3" rounding_type="ceil_torch" auto_pad="explicit" index_element_type="i64" axis="2" />
<layer id="18" name="__module.features.2/aten::max_pool2d/MaxPool" type="MaxPool" version="opset8">
<data strides="2, 2" dilations="1, 1" pads_begin="0, 0" pads_end="0, 0" kernel="3, 3" rounding_type="ceil" auto_pad="explicit" index_element_type="i64" axis="2" />
```

[PT] Update reference for squeezenet1_1_imagenet_int8_per_tensor (#2831)

---

tests/post_training/data/ptq_reference_data.yaml
tests/post_training/model_scope.py
tests/post_training/pipelines/base.py
tests/post_training/pipelines/image_classification_base.py
tests/post_training/pipelines/image_classification_timm.py
tests/post_training/pipelines/image_classification_torchvision.py
tests/post_training/test_quantize_conformance.py

Conformance test for resnet18
To extend testing scope for the TorchFX backend
https://github.com/openvinotoolkit/nncf/issues/2766
post_training_quantization/442 is successfull

[TorchFX] Conformance test init

---

nncf/experimental/torch/fx/commands.py
nncf/experimental/torch/fx/model_transformer.py
nncf/experimental/torch/fx/transformations.py
nncf/quantization/algorithms/min_max/torch_fx_backend.py
nncf/torch/graph/transformations/serialization.py
tests/post_training/data/ptq_reference_data.yaml
tests/post_training/model_scope.py
tests/post_training/pipelines/image_classification_torchvision.py
tests/torch/data/reference_graphs/fx/extracted/ConstantModelExtractionModel.dot
tests/torch/data/reference_graphs/fx/extracted/ModelExtractionModel.dot
tests/torch/fx/test_model_transformer.py
tests/torch/fx/test_models.py
tests/torch/test_models/synthetic.py

Constant linear layers support
To support swint_v2_s FBC
#2766 
Build post_training_quantization/444/ is finished successfully
Unit test `test_model_transformer.test_model_extraction` is presented

[TorchFX][FBC] Constant linear layers support

---

.github/workflows/api_changes_check.yml

Remove "Add release label" step
The condition `${{ contains(github.event.pull_request.base.ref, 'release_v') }}` will never be `True`, because this action triggered only for a pull request to develop branch.
```
on:
pull_request:
branches:
- develop
```
Label `release target` should be added by https://github.com/openvinotoolkit/nncf/pull/2836

[GA] Remove unreached step

---

tests/tools/requirements.txt
tools/memory_monitor.py

Stop addition of new memory values as soon as possible in order to correctly represent the tracked task.
When running memory monitor as a CLI tool, sometimes it may happen that the last value is recorded in the main process, i.e. when the child process has already died. This is represented as a drop in memory, because the child process memory is deallocated. This PR tries to avoid such behavior.

Add early stopping for memory monitoring

---

.github/workflows/api_changes_check.yml
.github/workflows/api_set_label.yml

Add "Set api label" action
Workflow to update API label:
1) `api_changes_check.yml` runs (build docs, compare with develop) and saves artifacts with status of check 'add, remove or none` (for external contributor only after approval)
2) After finished job will be triggered `api_set_label.yml` with write permission to update label from `api_changes_check.yml`, that downloads artifact and updates API label in pull request 
To follow [Good practices for mitigating script injection attacks](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks) pull_request_target is not allow to use for api_changes_check.yml.
But pull_request provide only read permission in result not …

[GA] Add `Set api label` action

---

nncf/common/logging/track_progress.py
nncf/quantization/algorithms/weight_compression/algorithm.py

During nncf weight compression, `rich` progress bar is used to display the progress. In this PR, progress bar is changed to be weighted according to model weights. With these changes, each weight contributes proportional amount of percent to the progress bar.
Iteration number was removed from weight compression progress bar to avoid confusion between different speeds in percent and iteration coordinates. For example now a single weight might contribute 5-10% to the whole progress.
The time it takes to compress a weight is roughly proportional to its size, so incrementing the progress by 1 for each weight is not ideal.
Especially after #2803 when weight sorting was added. Now, the largest weights come first and the smallest ones are at the end of the compression. This leads to misleading …

Add weighted progress tracking for weight compression

---

nncf/common/logging/track_progress.py
tests/common/utils/test_progress_tracking.py

Fix `track` usage as a context manager. This is a regression after #2892.

Fix track context manager

---

tests/post_training/data/ptq_reference_data.yaml
tests/post_training/model_scope.py
tests/post_training/pipelines/causal_language_model.py

Added statefull GPTNeox for PTQ conformance tests
There was a WA for the bug ref-135375 that used stateless instead of stateful model type.
https://github.com/openvinotoolkit/nncf/pull/2569/files#diff-99cb9f0934f8c3ee6a920ad98a7de38df18ebb07acd15b97a6e32dc318c17168R29 
Both modes should be tested with new OpenVINO release. 
ref-137079

Added statefull GPTNeox for PTQ conformance tests

---

nncf/quantization/algorithms/accuracy_control/ranker.py
nncf/quantization/algorithms/layerwise/scheduler.py
nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/min_max/backend.py
nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/min_max/torch_backend.py
nncf/quantization/algorithms/min_max/torch_fx_backend.py
nncf/quantization/algorithms/weight_compression/awq.py
nncf/quantization/passes.py
tests/common/quantization/test_passes.py
tests/common/quantization/test_quantizer_removal.py
tests/cross_fw/test_templates/test_ptq_params.py
tests/cross_fw/test_templates/test_quantizer_config.py

Removing the ShapeOf subgraph may lead to the removal of some input edges of operations, and QPS doesn't place FQ on these edges. In this case, the operations are quantized incorrectly because not all required inputs are quantized. These operations don't change their runtime precision in the execution graph, which means we do not have a fully quantized model.
To resolve the described problem, this PR introduces the following algorithm:
- **Step 1:** Find all nodes belonging to the ShapeOf subgraphs in the graph. Let's denote the found nodes as $S$. At this step, we don't remove the found subgraphs; we only store the nodes they consist of. See `find_shapeof_subgraphs()` method.
- **Step 2:** Check the producers for the specified nodes (currently, we are considering only nodes of the …

Preserve the constant subgraph

---

tests/common/quantization/mock_graphs.py

```
if not isinstance(population, _Sequence):
>           raise TypeError("Population must be a sequence.  "
"For dicts or sets, use sorted(d).")
E           TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

Fix random.sample for python312

---

README.md
ReleaseNotes.md

- Minor update in Readme to have links on one line
- Remove numpy2.0 from release notes to avoid any confusion

Update readme and release notes

---

nncf/torch/dynamic_graph/wrappers.py
tests/torch/pytorch_patch_isolated.py
tests/torch/test_pytorch_patch.py

Check whether model is compiled based on `"_torchdynamo_orig_callable"` property of the model forward.
`torch.compile` can be applied not only to the model itself, but to `forward()` method only. For example:
```
model.forward = torch.compile(model.forward)
```
In this case the model itself doesn't change and it won't be an instance of `torch._dynamo.OptimizedModule`.
143796
Added test when `torch.compile` is applied this way. It does not fail without the fix though, because the issue is sporadic.
#2665, #2719

Fix torch compile applied to model forward

---

nncf/quantization/algorithms/layerwise/scheduler.py
nncf/quantization/algorithms/weight_compression/activation_stats.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/gptq.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
nncf/quantization/quantize_model.py
tests/openvino/native/quantization/test_gptq.py
tests/openvino/native/quantization/test_weights_compression.py

- The scale estimation algorithm is used to calculate quantization parameters inside GPTQ.
- Combination GPTQ and AWQ algorithm is supported.
- The layer-wise scheduler is deterministic.
Improve model compression accuracy for low bits.
ref: 143637
job/manual/job/post_training_weight_compression/152/

Support the scale estimation inside GPTQ

---

nncf/quantization/advanced_parameters.py

AdvancedSmoothQuantParameters -> nncf.quantization.advanced_parameters.AdvancedSmoothQuantParameters
smooth_quant_alpha is not clickable. https://openvinotoolkit.github.io/nncf/autoapi/nncf/quantization/advanced_parameters/index.html#nncf.quantization.advanced_parameters.QuantizationParameters
N/A
N/A

[Docs] smooth_quant_alpha parameter

---

nncf/openvino/graph/nncf_graph_builder.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/backend.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
tests/openvino/native/quantization/test_min_max.py
tests/openvino/native/quantization/test_quantizer_config.py
tests/openvino/native/test_layer_attributes.py
tests/openvino/native/test_node_utils.py

Avoid retrieving weight data if not necessary.
For llama-3-8b with BF16 weights there is about 1.5x time and 1.26x peak memory improvement. Please see the figure below.
| Before         | After   |
|-------------------|-------|
| ![system_memory_usage_from-zero](https://github.com/user-attachments/assets/910e5525-c1c0-4f18-a379-2ae87a2648ba) |  ![system_memory_usage_from-zero](https://github.com/user-attachments/assets/589c0e46-acd0-4a33-91ed-843e631d5a8d) |
For BF16 dtype when constant data is fetched, it is loaded into memory resulting in additional time and memory overhead.

Improve weight compression time and memory for BF16 OV models

---

tests/post_training/data/wc_reference_data_2024.5.yaml

This PR introduced changes in accuracy:
https://github.com/openvinotoolkit/openvino/pull/26147, but it's coming from float error:
As result validation with openvino nightly failed:
150613
151260

Added metrics for 2024.5 nightly (#2954)

---

tests/common/graph/test_dot_file_rw.py

Compare content of files instead of `filecmp.cmp`
```
>       assert filecmp.cmp(tmp_path_to_graph, REF_DOT_REPRESENTATION_GRAPH_PATH)
E       AssertionError: assert False
```
Files is differ because used differ line separators for WIN in UNIX.
nightly/job/windows/job/precommit_common/40/

Fix file comparison on windows

---

nncf/openvino/quantization/quantize_model.py
nncf/quantization/quantize_model.py

- Align type hints for the `quantize_with_accuracy_control()` method
Issue: https://github.com/openvinotoolkit/nncf/issues/2957

Type mismatch in onnx quantize_with_accuracy_control validation_fn

---

nncf/common/graph/graph.py
nncf/scopes.py
tests/common/test_ignored_scope.py

Make correct ignored subgraph in which start and end nodes are the same 
Change behavior of nx.all_simple_paths in networkx==3.3.
```python
nx.all_simple_paths(graph, "A", "A" )  # [] 
nx.all_simple_paths(graph, "A", "A" )  # ["A"] 
```
tests/common/test_ignored_scope.py::test_ignored_scopes
tests/common/test_ignored_scope.py::test_wrong_ignored_scopes

Alignment behavior of get_ignored_node_names_from_ignored_scope

---

tests/post_training/requirements.txt

Set version of datasets package
```
Failed: BuilderConfig ParquetConfig(name='sst2', version=0.0.0, data_dir=None, data_files={'train': ['sst2/train-*'], 'validation': ['sst2/validation-*'], 'test': ['sst2/test-*']}, description=None, batch_size=None, columns=None, features=None) doesn't have a 'use_auth_token' key.
```

Fix version of datasets for conformance test

---

nncf/common/insertion_point_graph.py
nncf/tensorflow/quantization/algorithm.py
nncf/torch/nncf_network.py
tests/common/quantization/mock_graphs.py
tests/common/quantization/test_quantizer_propagation_graph.py
tests/common/quantization/test_quantizer_propagation_solver.py

- Remove unused weight_modifiable_node_names property
- Code quality

Remove unused weight_modifiable_node_names property

---

nncf/quantization/algorithms/min_max/openvino_backend.py

Add `OVGroupNormalizationMetatype` to the list of op types ignored with `ModelType.TRANSFORMER`.
For PT backend it is already present. For ONNX backend there is no such metatype.
It was observed that with update to OV 2024.4 some models are converted in such a way that in places where there was an MVN node before, now is a GroupNorm node. Since GroupNorm is not ignored, it leads to FQs being placed for them.
152427

Add GroupNorm to the OV list of ignored ops for ModelType.TRANSFORMER

---

nncf/openvino/graph/metatypes/groups.py
nncf/openvino/graph/metatypes/openvino_metatypes.py

Add https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/pooling/adaptive-max-pool-8.html and https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/pooling/adaptive-avg-pool-8.html
Based on the description of the operations I make their treatments for quantization the same as for AvgPool and MaxPool. I checked the correct quantization scheme with this PR for litehernet from ticket 150502

[OV] Add adaptive poolings metatypes

---

nncf/quantization/algorithms/min_max/algorithm.py
nncf/quantization/algorithms/min_max/backend.py
nncf/quantization/algorithms/min_max/onnx_backend.py
nncf/quantization/algorithms/min_max/openvino_backend.py
nncf/quantization/algorithms/min_max/torch_backend.py
nncf/quantization/algorithms/min_max/torch_fx_backend.py
tests/cross_fw/test_templates/models.py
tests/cross_fw/test_templates/test_quantizer_config.py
tests/onnx/quantization/test_quantizer_config.py
tests/openvino/native/quantization/test_quantizer_config.py
tests/post_training/data/ptq_reference_data.yaml
tests/torch/fx/test_quantizer_config.py
tests/torch/ptq/test_quantizer_config.py

* Weights nodes collection is updated for PT/FX backends
* Constant matmul check is updated for PT/FX/ONNX backends
To unify self attention quantization across all backends and align with the OV quantization
#2766 
* test_model_type_transformer_quantization_config
* post_training_quantization/485/ + post_training_quantization/486/ is finished successfully

[FX/PT/ONNX][MinMax] Weights nodes/ constant matmuls collection fix

---

nncf/experimental/torch/fx/nncf_graph_builder.py
tests/post_training/data/ptq_reference_data.yaml
tests/post_training/pipelines/image_classification_torchvision.py

* tests/post_training/pipelines/image_classification_torchvision.py supports both `capture_pre_autograd_model` and `torch.export.export(...).module()` export paths
* Micro fix in NNCFGraph
* capture_pre_autograd_graph introduces accuracy drop for the swin_v2_s model (Improvement: Metric value is better than reference 0.836 > 0.8296)
* Incorrect constant collection fails on models exported via `torch.export.export(...).module()`
#2766 
post_training_quantization/490/

[TorchFX][Conformance test] Migration to `torch.export.export`

---

nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
tests/post_training/data/wc_reference_data.yaml
tests/post_training/data/wc_reference_data_2024.4.yaml
tests/post_training/data/wc_reference_data_2024.5.yaml

* Accuracy bug with LLMs across different CPUs was fixed
* The problem was in execution of models from `get_compress_pipeline` and `get_compress_decompress_pipeline`
* TODO: add ticket link
* 148819, 152627

Fix metric for tinyllama_scale_estimation_per_channel

---

nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/quantization/algorithms/weight_compression/torch_fx_backend.py

PTMeanReducer is removed
To fix pre-commit

PTMeanReducer is removed

---

.github/workflows/examples.yml

- Use `if: ${{ !cancelled() }}` to upload artifact for failed job
- Make possible manually run workflow on branch
`continue-on-error: true` is make failed job green.

[GA] fail status for example workflow

---

nncf/common/tensor_statistics/statistics.py
nncf/quantization/algorithms/weight_compression/gptq.py
nncf/quantization/algorithms/weight_compression/mixed_precision.py
tests/openvino/native/quantization/test_weights_compression.py

Fixes after #3003 .
1. Convert raw activations to WC statistics for GPTQ + SE scenario.
2. Allow 2D tensor inputs for data-aware mixed precision. 2D activations arise in `opt`-like models, e.g. `opt-125m`. There, LayerNorm reshapes activations from [B, L, D] to [B*L, D].
1. Added a unit test for GPTQ + SE.
2. Modified a test for 2D activations and mixed precision.
3. Compressed tiny-llama to int4_asym with SQ + GPTQ before #3003 and for this PR. Got the same PPL value of 15.739704794594019 .

Data-aware compression fixes

---

nncf/openvino/quantization/quantize_model.py
nncf/quantization/telemetry_extractors.py
nncf/telemetry/extractors.py
nncf/telemetry/wrapper.py
nncf/torch/quantization/quantize_model.py

- Added telemetry for the `nncf.compress_weights` backend-specific `impl`;
- Added missed wrapper for the `nncf.qantize` PyTorch `impl`;
- Fixed reported event for `nncf.quantize_with_accuracy_control` OpenVINO `impl`.
- Added missed `app_name`, `app_version` fields for each event.
- Telemetry update.
- 154833
- TBD

compress_weights telemetry update

---

examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/openvino/anomaly_stfpm_quantize_with_accuracy_control/main.py
examples/post_training_quantization/openvino/yolov8/main.py
examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/torch/ssd300_vgg16/main.py

Add `subset_size` to PTQ samples after merging https://github.com/openvinotoolkit/nncf/pull/2995 to remove the warning message
CI: https://github.com/openvinotoolkit/nncf/actions/runs/11436915496

Remove warning from examples

---

examples/torch/common/restricted_pickle_module.py
pyproject.toml
tests/cross_fw/shared/paths.py
tests/torch/requirements.txt

- setup pythonpath for pytests
- support numpy2 for unplicker
- bump datasets to support numpy2 
- fix ROOT_PYTHONPATH_ENV that was always None

set pythonpath for pytest

---

tests/torch/sota_checkpoints_eval.json

Correct metric after migrate to numpy2
After migrate tests to numpy2 final metric changed on 0.02

Fix metric pt_e2e

---

nncf/quantization/algorithms/weight_compression/awq.py

Cast `fns.quantile()` result to float32 inside AWQ algorithm.
`fns.quantile()` for numpy backend returns `np.float64` value. In AWQ it is used as a clip lower bound, resulting in float64 result. Then via chain reaction it leads to weights and activations being converted to float64. 
As I understand, processing in float64 is not necessary. At the same time it leads to increased running time. Below are measurements for compression time with AWQ enabled before and after the changes.
| Model           | develop (sec.) | branch (sec.) |
|-----------------|----------------|---------------|
| tiny-llama-1.1b | 123            | 109 (-11%)    |
| phi3_mini-3.7b  | 487            | 419 (-14%)    |
| llama3-8b       | 1091           | 912 (-16%)    |

[AWQ] Cast `fns.quantile()` result to float32

---

tests/post_training/data/wc_reference_data.yaml

After moving PTWC tests to Xeon Gold (ticket 153844), we should update the `tinyllama_scale_estimation_per_channel_backend_OV` metric due to unstable accuracy deviations across different CPUs (ticket 152627)
CI job: 233

[WC][Tests] Update Scale Estimation metric

---

examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/deploy.py
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/onnx/yolov8_quantize_with_accuracy_control/requirements.txt
examples/post_training_quantization/openvino/yolov8/main.py
examples/post_training_quantization/openvino/yolov8/requirements.txt
examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py
examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt
tests/cross_fw/examples/test_examples.py

- Update ultralytics 8.3.22
- Update ultralytics 8.3.22
- Ref: 151072
test_examples

Update ultralytics 8.3.22

---

tests/post_training/data/ptq_reference_data_2024.5.yaml

- As stated in the title.
- OV started to produce more correct SE graphs.
- NNCF SE pattern started to match with the model. The number of FQ layers was reduced from 79 to 61.
- N/A
- openvino-nightly post_training_quantization/68/ - success
Pattern wasn't applied for a model with OV 24.4 because of the Reshape layer:
There is no Reshape with OV 24.5:

Update PTQ reference for 24.5

---

nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
tests/openvino/native/quantization/test_weights_compression.py

1. Made Scale Estimation return zero points besides scales.
2. Minor fixes to `do_int_quantization` function, made its signature more strict.
1. Currently zero points need to be re-computed for the weights for which SE computed scales.
2. Avoid unnecessary computations inside `do_int_quantization`. Avoid wrong usage of the function.
Added a test to verify correctness of feeding precomputed quantization parameters to `do_int_quantization`.
Prerequisite to 139047.

Make SE algorithm also return zero points

---

nncf/openvino/quantization/quantize_model.py
nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/quantization/algorithms/weight_compression/mixed_precision.py
nncf/quantization/statistics_caching.py
tests/openvino/native/quantization/test_weights_compression.py

Set a subset size for collecting statistics
`subset size` option is ignored and the whole dataset is used
n/a

Collect statistics from subset in weight compression

---

nncf/quantization/algorithms/weight_compression/backend.py

Use raw string for docstring with `\`
```
nncf/quantization/algorithms/weight_compression/backend.py:165
/home/runner/work/nncf/nncf/nncf/quantization/algorithms/weight_compression/backend.py:165: DeprecationWarning: invalid escape sequence '\ '
"""
```

Fix deprecation warning

---

tests/post_training/data/wc_reference_data_2024.5.yaml

Revert of https://github.com/openvinotoolkit/nncf/pull/2954
Use [references for the OV 2024.3](https://github.com/ljaljushkin/nncf_pytorch/blob/873fbb80ab07bd41a3b1a2e21f68bc1a7a394810/tests/post_training/data/wc_reference_data.yaml) when run conformance tests with OV 2024.5. 
According to the CPU team: 
> 1) In 24.4 time frame, RMS impl has been enabled (https://github.com/openvinotoolkit/openvino/pull/26147), which introduce some accuracy change due to vrsqrtss which is done by approximation. 
> 2) In 24.5 time frame, fix has been applied (https://github.com/openvinotoolkit/openvino/pull/26817) to use vsqrtss instead. With that we can see the result can be covered to that prior to https://github.com/openvinotoolkit/openvino/pull/26147
> With that (in 24.5), the accuracy result is …

Returned OV 2024.3 references for OV 2024.5 in Weight Compression tests

---

tests/post_training/data/wc_reference_data.yaml

After moving PTWC tests to Xeon Gold (ticket 153844), we should update the metrics due to unstable accuracy deviations across different CPUs (ticket 152627).
https://github.com/openvinotoolkit/nncf/pull/3048 updated only `tinyllama_scale_estimation_per_channel_backend_OV`, but 
`tinyllama_awq_backup_mode_none` and `tinyllama_NF4_scale_estimation_stateful_per_channel` were also affected.

Left-overs after moving PTWC tests to Xeon Gold

---

nncf/experimental/common/tensor_statistics/collectors.py
nncf/openvino/statistics/collectors.py
nncf/quantization/algorithms/weight_compression/mixed_precision.py
tests/cross_fw/test_templates/test_weights_compression_backends.py
tests/openvino/native/quantization/test_weights_compression.py
tests/openvino/native/quantization/test_weights_compression_backends.py

https://github.com/openvinotoolkit/nncf/pull/3072

[RELEASE] Fix hessian criteria statistics collector (#3072)

---

examples/post_training_quantization/torch_fx/resnet18/main.py

Migrate torch.export.export in examples to torch.export.export_for_training

[Torch Fx] Migrate example to torch.export.export_for_training

---

examples/post_training_quantization/torch_fx/resnet18/main.py

Moving PR #3086 to release branch
Migrate torch.export.export in examples to torch.export.export_for_training

[Release][TorchFX] Migrate example to torch.export.export_for_training

---

README.md
docs/Algorithms.md
docs/usage/post_training_compression/post_training_quantization/Usage.md

* Main README.md, Usage.md and post training quantization docs are updated with info about the TorchFX
* To reflect new experimental features of TorchFX in the docs
#2766

[TorchFX] Documetation update

---

docs/api/source/conf.py
nncf/common/utils/api_marker.py

- Rework api decorator to pass annotation of object
- Remove unused 'is_api' function
Broken annotation of object

Fix annotation for api marker

---

examples/llm_compression/openvino/tiny_llama/main.py
examples/llm_compression/openvino/tiny_llama_find_hyperparams/main.py
tests/post_training/pipelines/lm_weight_compression.py

explicitly disable kv cache compression to u8, f16 precision is used instead.
PTWC nightly has a different metrics (ticket 157594). 
It happens, because since https://github.com/openvinotoolkit/openvino/pull/27454 KV Cache compressed to u8 by default and it affects accuracy of fp32 models (ticket 157571). 
Propose using kv cache in the f16 in order to handle issues in nncf rather than in ov (there's still an open issue with kv cache compression, and it can be modified in the nearest future)
157571
157594

set kv cache in f16

---

tests/post_training/pipelines/image_classification_torchvision.py

All `capture_pre_autograd_graph` calls in the conformance test were replaced by `torch.export.export_for_training`.
To remove deprecated `capture_pre_autograd_graph` from the conformance test.
#2766 
post_training_quantization/555/ have finished succesfully

[TorchFX][Conformance] Move all models to export_for_training

---

nncf/experimental/torch/fx/constant_folding.py
tests/torch/fx/test_model_transformer.py

Folded constants do not require gradient
* To unify all model constant/buffers
* To make compressed model deepcopy-able
#2766 
`test_constant_folding` is updated

[TorchFX][MicroFix] Folded constants do not require grad

---

.github/workflows/nightly.yml
Makefile
tests/tensorflow/requirements.txt

Add tensorflow nightly test scope

[GHA] tf nighlty

---

examples/quantization_aware_training/torch/anomalib/requirements.txt

Limit version of matplot for quantization_aware_training_torch_anomalib example
```
File "/tmp/pytest-of-runner/pytest-0/test_examples_quantization_awa0/venv/lib/python3.10/site-packages/anomalib/utils/visualization/image.py", line 172, in _visualize_batch
yield GeneratorResult(image=self.visualize_image(image_result), file_name=file_name)
File "/tmp/pytest-of-runner/pytest-0/test_examples_quantization_awa0/venv/lib/python3.10/site-packages/anomalib/utils/visualization/image.py", line 184, in visualize_image
return self._visualize_full(image_result)
File "/tmp/pytest-of-runner/pytest-0/test_examples_quantization_awa0/venv/lib/python3.10/site-packages/anomalib/utils/visualization/image.py", line 239, in _visualize_full
return image_grid.generate()
File …
```

limit version of matplot

---

nncf/common/utils/backend.py

- Added `try-catch` blocks for `isinstance` during backend calculation.
- Corrupted frameworks may lead to exceptions even if these frameworks were not intended to be used.
- 158806
- Manual

Added try for backends

---

examples/quantization_aware_training/torch/anomalib/requirements.txt

Limit version of matplot for quantization_aware_training_torch_anomalib example
```
File "/tmp/pytest-of-runner/pytest-0/test_examples_quantization_awa0/venv/lib/python3.10/site-packages/anomalib/utils/visualization/image.py", line 172, in _visualize_batch
yield GeneratorResult(image=self.visualize_image(image_result), file_name=file_name)
File "/tmp/pytest-of-runner/pytest-0/test_examples_quantization_awa0/venv/lib/python3.10/site-packages/anomalib/utils/visualization/image.py", line 184, in visualize_image
return self._visualize_full(image_result)
File "/tmp/pytest-of-runner/pytest-0/test_examples_quantization_awa0/venv/lib/python3.10/site-packages/anomalib/utils/visualization/image.py", line 239, in _visualize_full
return image_grid.generate()
File …
```

limit version of matplot (#3147)

---

docs/styleguide/PyGuide.md

Add to pyguide.md point about checking symbolic links

Add to pyguide.md point about checking symbolic links

---

nncf/telemetry/decorator.py
nncf/telemetry/events.py
nncf/telemetry/extractors.py
nncf/telemetry/wrapper.py
pyproject.toml

- Fix suggestion in editor for function under tracked_function
- Add nncf/telemtry to mypy check
Broken annotation of function that decorated by tracked_function

Fix annotation for tracked_function

---

constraints.txt
docs/PyPiPublishing.md
examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt

- remove `tensorflow==2.12.1; python_version < '3.9'`, according with drop support python 3.8 https://github.com/openvinotoolkit/nncf/pull/2919
- align PyPiPublishing.md with https://github.com/openvinotoolkit/nncf/pull/3111

Some fixes

---

examples/post_training_quantization/torch/mobilenet_v2/main.py
nncf/torch/extensions/__init__.py

TORCH_CUDA_ARCH_LIST warning is suppressed using `torch.cuda.get_arch_list()`. 
Please let me know, if any changes are required.
Solves issue #3141

Suppressed UserWarning: TORCH_CUDA_ARCH_LIST

---

.github/workflows/api_changes_check.yml
.github/workflows/build_and_publish_doc.yml
.github/workflows/build_html_doc.yml
.github/workflows/build_schema_page.yml

Use `actions/upload-artifact` and `actions/download-artifact` instead of `alehechka/upload-tartifact` and `alehechka/download-tartifact`
```
[Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/openvinotoolkit/nncf/actions/runs/12696443147/workflow)
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "html_doc_artifact". Please update your workflow to use v4 of the artifact actions. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
```
Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or …
```

[GHA] Replacement tartifact actions

---

examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
examples/quantization_aware_training/tensorflow/mobilenet_v2/README.md
examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
examples/quantization_aware_training/tensorflow/mobilenet_v2/requirements.txt
nncf/common/strip.py
nncf/tensorflow/quantization/quantize_model.py
nncf/tensorflow/strip.py
tests/tensorflow/pruning/test_strip.py
tests/tensorflow/quantization/test_strip.py
tests/tensorflow/sparsity/test_strip.py

Add simple QAT example for TF backend
Ref: 158980
Ref: 158980
- tests/tensorflow/quantization/test_strip.py
- tests/tensorflow/sparsity/test_strip.py
- tests/tensorflow/pruning/test_strip.py

 QAT example for TF backend

---

tests/post_training/data/ptq_reference_data.yaml
tests/post_training/model_scope.py
tests/post_training/test_quantize_conformance.py

- Remove levit model_128 
- Fix: no catching exception without message
```
File "/home/jenkins/agent/workspace/NNCF/manual/Daemons/PTQ/ptq_single_model/venv/lib/python3.10/site-packages/timm/models/_builder.py", line 393, in build_model_with_cfg
load_pretrained(
File "/home/jenkins/agent/workspace/NNCF/manual/Daemons/PTQ/ptq_single_model/venv/lib/python3.10/site-packages/timm/models/_builder.py", line 193, in load_pretrained
state_dict = filter_fn(state_dict, model)
File "/home/jenkins/agent/workspace/NNCF/manual/Daemons/PTQ/ptq_single_model/venv/lib/python3.10/site-packages/timm/models/levit.py", line 707, in checkpoint_filter_fn
assert 'head' in ka or 'stem.conv1.linear' in ka
AssertionError
```

Remove levit model from ptq conformance tests

---

.markdownlint.yaml
.pre-commit-config.yaml
nncf/common/logging/track_progress.py
tests/torch/ptq/test_wrap_model.py
tests/torch/test_serialization.py
tests/torch2/function_hook/test_function_hook_mode.py

black - 24.10.0
isort - 5.13.0
ruff - v0.9.2
markdownlint - 0.43.0

Bump version of linters in pre-commit 

---

.github/workflows/call_precommit_windows.yml
.github/workflows/nightly.yml
.github/workflows/precommit.yml
nncf/experimental/torch2/function_hook/graph/build_graph_mode.py
tests/common/utils/test_timer.py
tests/onnx/quantization/test_classification_models_graph.py
tests/onnx/test_nncf_graph_builder.py
tests/onnx/test_weightless_model.py
tests/torch/test_pytorch_patch.py

Run test from precommit test scope in nightly trigger
- pt2: use fixed parameters for .T, _saved_dim0/1 depends from os, but actual value always -1, -2
- onnx: build model only inside test function, not in collect parameters, to more effective use memory 
- common: use `1.2` s for test timer, to be sure that will be catch 00:00:01
NOTE: pt test falls in case of parallel run on build quantization extension.
https://github.com/openvinotoolkit/nncf/actions/runs/12835288745/job/35794407928?pr=3194

[GHA] windows precommit

---

nncf/api/compression.py
nncf/common/accuracy_aware_training/runner.py
nncf/common/accuracy_aware_training/runner_factory.py
nncf/common/composite_compression.py
nncf/common/compression.py
nncf/common/quantization/config_assignment.py
nncf/common/quantization/quantizer_propagation/graph.py
nncf/common/quantization/quantizer_removal.py
nncf/common/quantization/quantizer_setup.py
nncf/common/utils/backend.py
pyproject.toml

Enable mypy for nncf/common directory

[mypy] nncf/common

---

tests/post_training/pipelines/base.py

TorchFX model in the conformance test are being reshaped explicitly before the serialization
To work around dynamic shapes export OpenVINO bug 161495
161495
job/weekly/job/Daemons/job/PTQ/job/ptq_single_model/7198 -passed

[release_v2150][WA][conformance][TorchFX] reshape model explicitly

---

nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/torch/model_graph_manager.py
tests/torch/test_model_graph_manager.py

Return detached tensor from `get_const_data` function
Memory leak

[PT] detach tensor in get_const_data

---

tests/post_training/pipelines/base.py

Copy of the #3228 to the develop branch
TorchFX model in the conformance test are being reshaped explicitly before the serialization
To work around dynamic shapes export OpenVINO bug 161495
161495
job/weekly/job/Daemons/job/PTQ/job/ptq_single_model/7198 - passed

[WA][conformance][TorchFX] reshape model explicitly

---

nncf/common/quantization/quantizers.py
nncf/quantization/fake_quantize.py
tests/cross_fw/shared/json.py
tests/cross_fw/test_templates/fq_params/fq_params.json
tests/cross_fw/test_templates/test_calculate_quantizer_parameters.py

* `symmetric_range` and  `asymmetric_range` functions were refactored to avoid dependency on quantization group
* input configs of `test_calculate_quantizer_parameters` were updated to align with real cases computed by the solver with `cpu.json` HW config (all symmetric weights configs have `signedness_to_force=True` in actual code)
`symmetric_range` and  `asymmetric_range` functions are using prior knowledge about HW config (if symmetric and weights -> input_low = -input_high) but could just use the qconfig attributes (signed == True and narrow_range == True -> input_low = -input_high) . New quantizers from the #3231 does not obey hardcoded OpenVINO HW config rules (X86 quantizer require narrow_range false for symmetric weights, for example), thus support of the new quantizers requires …

[PTQ] Remove HWConfig hardcode from calculate_quantizer_parameters

---

nncf/common/utils/backend.py
nncf/common/utils/cpu_info.py
nncf/common/utils/helpers.py
nncf/openvino/optimized_functions/models.py
nncf/version.py
pyproject.toml
tests/common/utils/test_helpers.py

Set `export DNNL_MAX_CPU_ISA=AVX2_VNNI` during weights compression on LNL CPUs.
Fix compression on LNL CPUs.
161336
- https://github.com/openvinotoolkit/nncf/actions/runs/13075940656 ✅ 
- https://github.com/openvinotoolkit/nncf/actions/runs/13075938396 ✅ 
- NNCF/job/nightly/job/sdl/job/nightly_trigger/426/ ✅

[Release] Set environment variable on LNL CPUs before compression model compilation

---

.github/workflows/examples.yml
nncf/tensor/functions/numeric.py
nncf/tensor/functions/torch_numeric.py
tests/cross_fw/shared/json.py
tests/cross_fw/test_templates/fq_params/fq_params.json
tests/cross_fw/test_templates/template_test_nncf_tensor.py
tests/cross_fw/test_templates/test_calculate_quantizer_parameters.py

- Remove import nncf in tests/cross_fw/shared/json.py
- Remove install nncf in test_examples on windows
- Add as_numpy_tensor for TORCH backend
https://github.com/openvinotoolkit/nncf/actions/runs/13103780497
https://github.com/openvinotoolkit/nncf/actions/runs/13121758899

Avoid import nncf in tests/cross_fw/shared/json.py 

---

README.md
docs/usage/training_time_compression/quantization_aware_training/Usage.md
examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
nncf/tensorflow/__init__.py
nncf/tensorflow/helpers/model_creation.py
nncf/tensorflow/quantization/algorithm.py
nncf/tensorflow/quantization/quantize_model.py
nncf/tensorflow/utils/state.py
nncf/torch/model_creation.py

- Update TF QAT docs
- Deprecate the create_compressed_model() method for the TF backend.
Ref: 158980
Ref: 158980
N/A

Update TF QAT docs. Deprecate TF create_compressed_model method

---

tests/post_training/test_quantize_conformance.py

TorchFX CUDA tests require --cuda argument to run
to prevent conformance test to run CUDA tests by default, as by default there is no CUDA installed on CI machines

[Conformance][TorchFX] Run CUDA test only with --cuda argument enabled

---

examples/tensorflow/common/object_detection/architecture/fpn.py
nncf/common/quantization/quantizer_setup.py
nncf/quantization/algorithms/bias_correction/torch_fx_backend.py
nncf/tensorflow/quantization/init_range.py
nncf/torch/model_creation.py
pyproject.toml
tests/openvino/tools/calibrate.py

https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc

[ruff] Enable ISC rule

---

nncf/experimental/torch/fx/quantization/quantizer/openvino_quantizer.py

Mode return is added to `annotate` method of the OpenVINOQuantizer
To align with the signature

[OpenVINOQuantizer] return annotated model

---

nncf/torch/extractor.py
tests/torch/test_extractor.py

Disable gradient for extracted modules
Possible memory leaks
manual/job/post_training_quantization/606

[PT] disable grad for extracted module

---

nncf/experimental/torch/fx/quantization/quantize_pt2e.py
nncf/experimental/torch/fx/quantization/quantizer/openvino_adapter.py
nncf/experimental/torch/fx/quantization/quantizer/openvino_quantizer.py

Refines for ExecuTorch OpenVINO backend integration
To enable the OpenVINOQuantizer and quantize_pt2e exectutorch integration

[TorchFX] Refines for ExecuTorch OpenVINO backend integration

---

nncf/quantization/algorithms/min_max/algorithm.py
tests/cross_fw/test_templates/test_min_max.py

`set_ignored_scope` method in the MinMax algorithm is introduced
To allow later ignored scope settings (requires for the executorch implementation)
tests/cross_fw/test_templates/test_min_max.py: test_set_ignored_scope

[MinMax] set_ignored_scope method

---

.pre-commit-config.yaml
pyproject.toml

Enable auto fix for ruff 
Place ruff hook before black and isort, as recommended in https://github.com/astral-sh/ruff-pre-commit
Bump version to 0.9.6
Removed deprecated option `ignore-init-module-imports`
To automatically fix founded error if it possible.

[ruff] Enable auto fix for ruff

---

nncf/quantization/algorithms/weight_compression/gptq.py
tests/openvino/native/quantization/test_weights_compression.py

Use `block_compression_config` as input for the scale estimation algorithm.
GPTQ fails with per-channel int4 compression.
ref: 159891
test_call_gptq_with_dataset_scale_estimation_neg_group_size

Fix: GPTQ fails with per-channel int4 compression.

---

.github/workflows/api_changes_check.yml
.github/workflows/api_set_label.yml
.github/workflows/build_and_publish_doc.yml
.github/workflows/build_html_doc.yml
.github/workflows/build_schema_page.yml
.github/workflows/call_precommit.yml
.github/workflows/call_precommit_windows.yml
.github/workflows/conformance_weight_compression.yml
.github/workflows/examples.yml
.github/workflows/install.yml
.github/workflows/macos.yml
.github/workflows/model_hub.yml
.github/workflows/mypy.yml
.github/workflows/nightly.yml
.github/workflows/pre-commit-linters.yml
.github/workflows/python-publish.yml
.github/workflows/sdl.yml

- actions/checkout@v4.2.2
- actions/setup-python@v5.4.0
- github/codeql-action@v3.24.5
- actions/upload-artifact@v4.5.0
- ilammy/msvc-dev-cmd@v1.13.0
- dawidd6/action-download-artifact@v8
- JamesIves/github-pages-deploy-action@v4.7.2
Prepare to allow dependabot to update dependencies in NNCF

[GHA] Bump actions

---

README.md
docs/PyPiPublishing.md
nncf/experimental/torch/sparsity/movement/MovementSparsity.md

Remove paragraphs with link to `https://github.com/huggingface/optimum-intel/tree/main/examples/openvino` 
https://github.com/huggingface/optimum-intel/pull/1167

Remove dead link to examples in optimum-intel 

---

docs/api/source/conf.py
nncf/experimental/torch/fx/__init__.py
nncf/experimental/torch/fx/quantization/quantize_pt2e.py
nncf/experimental/torch/fx/quantization/quantizer/openvino_quantizer.py

Mark quantizer and quantize_pt2e as API
To introduce `OpenVINOQuantizer` and `quantize_pt2e` in the api docs: https://openvinotoolkit.github.io/nncf/index.html
https://github.com/daniil-lyakhov/executorch/pull/2

[OpenVINOQuantizer] Mark quantizer and quantize_pt2e as API

---

.github/workflows/precommit.yml
tests/torch/sparsity/movement/test_model_saving.py

Use atol=1e-5 in test_same_outputs_in_torch_and_exported_onnx 
https://github.com/openvinotoolkit/nncf/actions/runs/13510568468/job/37749802966
https://github.com/openvinotoolkit/nncf/actions/runs/13533343712/job/37820218205?pr=3311

[PT] less atol on windows for test_same_outputs_in_torch_and_exported_onnx

---

nncf/quantization/algorithms/layerwise/scheduler.py

`add_additional_outputs = True` is set in `LayerwiseScheduler` by default. It's mean that additional output nodes will be added that were visited to remove inputs to target nodes.
Memory and speed optimization. 
More details:
Calibration dataset: wikitext-2-raw-v1
```
compressed_model = nncf.compress_weights(
model,
dataset=quantization_dataset,
mode=nncf.CompressWeightsMode.INT4_SYM,
gptq=True,
subset_size=128,
ratio=1,
)
```
1. sequence length > 128
- Reduce memory footprint in 2.71 times.
- 1.16x compression time speed up. 
Model | Accuracy (lambada_openai) Develop | Accuracy (lambada_openai) Branch | Compression time Develop (sec.) | Compression time Branch (sec.) | Compression time speed up | Peak Memory Develop (MiB) | Peak Memory Branch (MiB) | Memory reduction
-- | -- | -- | -- | …

Update default LayerwiseScheduler behavior

---

nncf/experimental/torch2/function_hook/wrapper.py
tests/torch2/function_hook/test_train.py

Move check on overridden forward to _replicate_for_data_parallel, because it's actual only for case with using DataParallel.
For other cases overridden forward can correctly works, depends from user implementation

[PT2] check overridden forward in _replicate_for_data_parallel

---

nncf/quantization/algorithms/min_max/algorithm.py
tests/common/quantization/test_minmax.py
tests/onnx/quantization/test_ptq_params.py
tests/openvino/native/quantization/test_ptq_params.py
tests/torch/fx/test_ptq_params.py
tests/torch/ptq/test_ptq_params.py

- Fixed `_override_device` function https://github.com/openvinotoolkit/nncf/blob/5c75e22c2888ebde2a87534c8cb204497899b0b7/nncf/quantization/algorithms/min_max/algorithm.py#L253 
- Apply overflow fix only for 8-bit quantization by default https://github.com/openvinotoolkit/nncf/blob/5c75e22c2888ebde2a87534c8cb204497899b0b7/nncf/quantization/advanced_parameters.py#L36
The overflow fix should only be applied for 8 bit quantization
None
test_target_device
test_npu_target_device
test_overflow_fix

Refactoring of minmax algorithm parameter setup and checking

---

nncf/quantization/algorithms/weight_compression/awq.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
tests/torch/ptq/test_weights_compression.py

Adapted AWQ and Scale Estimation algorithm for the case when weights and activations are float16 and bfloat16.
Otherwise, compression fails with errors like that:
`
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != float
`
n/a
- tests/torch/ptq/test_weights_compression.py::test_half_precision_models
- PTWC https://github.com/openvinotoolkit/nncf/actions/runs/13680175191
- PTWC Performance 
| 51 build on develop |  52 build on PR |
:-------------------------:|:-------------------------:

Fixed weight compression for float16/bfloat16 Torch models

---

examples/llm_compression/openvino/tiny_llama_find_hyperparams/main.py

Use wikitext-2-raw-v1 in the examples
Minimize number downloads.
N/A
https://github.com/openvinotoolkit/nncf/actions/runs/13715504451

Use wikitext-2-raw-v1 in the examples

---

nncf/quantization/algorithms/weight_compression/openvino_backend.py
tests/openvino/native/models.py
tests/openvino/native/quantization/test_weights_compression.py

Assign the weight to the constant operation, rather than the first operation following the matrix multiplication.
In the past, the weights were assigned to the first operation after the Matmul, and this approach functioned properly when the weights were in float32 format. However, with the introduction of the ability to use float16/bfloat16 weights in AWQ, as described in the pull request #3330, the set_weights function no longer operates correctly. The first operation in the process is a `Convert`, which is replaced by a constant, and this causes an error:
```
RuntimeError: Check 'element::Type::merge(result_et, get_input_element_type(0), get_input_element_type(1))' failed at src\core\src\op\matmul.cpp:113:
While validating node 'opset1::MatMul MatMul_1657124 (opset1::Multiply …
```

Set weight without overriding convert node

---

tests/cross_fw/examples/test_examples.py

`whowhatbench` tool depends on `openvino-genai` module, but it takes it from PyPI by default, so it depends on released OpenVINO version, so it install it and we're getting this in validation cycles:
```
ImportError: libopenvino.so.2500: cannot open shared object file: No such file or directory
```
This PR hacks `test_examples.py` (`llm_tune_params` test to be exact) to install nightly versions of `openvino-genai` and `whowhatbench`

[test_examples] Install WWB version compatible with nightly openvino-genai

---

nncf/torch/quantization/reference.py

- Added `torch.compile` for `forward` & `backward` in reference implementation.
- Training speed-up from 7 minutes to 5 minutes for 1 epoch of phi3.5 qat-lora tuning
- 163973
- TBD

[QAT Lora 6/N] torch.compile for reference implementation

---

nncf/openvino/cpu_info.py
nncf/openvino/optimized_functions/models.py
pyproject.toml

Use openvino instead of cpuinfo to get CPU full name. Using cpuinfo can result in issues.
Related to https://github.com/openvinotoolkit/openvino_notebooks/issues/2810

Use openvino instead of cpuinfo to get CPU full name

---

nncf/quantization/algorithms/weight_compression/algorithm.py
nncf/torch/quantization/layers.py
tests/torch/ptq/test_fq_lora.py
tests/torch/ptq/test_weights_compression.py
tests/torch/quantization/test_layers.py
tests/torch/test_models/synthetic.py

Added test for loading/saving compression checkpoint. Fixed revealed errors with different device and invalid lora rank.
Compression module and the corresponding layer may have a different device in multi-device setup (e.g. when HF model was loaded with device_map='auto'). Need to align devices. 
154907
- test_checkpoint_loading
- test_invalid_lora_rank

[QAT Lora 5/N] Fixes for loading/saving compression checkpoint 

---

nncf/torch/graph/graph.py
tests/torch2/function_hook/nncf_graph/test_nncf_graph.py

For new tracing detect missed inputs based on count of TensorMeta instance in op inputs.
Failed on detection missed input for concat nodes.

[PT2] Detect missed inputs for noed based on TensorMeta in arguments

---

nncf/__init__.py
nncf/api/compression.py
nncf/common/composite_compression.py
nncf/common/strip.py
nncf/experimental/tensorflow/quantization/algorithm.py
nncf/parameters.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/tensorflow/algorithm_selector.py
nncf/tensorflow/pruning/base_algorithm.py
nncf/tensorflow/quantization/algorithm.py
nncf/tensorflow/sparsity/base_algorithm.py
nncf/tensorflow/strip.py
nncf/torch/algo_selector.py
nncf/torch/nncf_network.py
nncf/torch/pruning/filter_pruning/algo.py
nncf/torch/quantization/algo.py
nncf/torch/quantization/strip.py
nncf/torch/sparsity/base_algo.py
nncf/torch/strip.py
tests/torch/helpers.py
tests/torch/ptq/test_fq_lora.py
tests/torch/quantization/test_strip.py
tests/torch/requirements.txt

- Introduced strip method for LoRA modules as a new strip format = `StripFormat.DQ`. The old format named `StripFormat.NATIVE`. 
- Continuation of https://github.com/openvinotoolkit/nncf/pull/3331
- To able IR model conversion
- 159708
- test_fq_lora_tuning
- test_nncf_strip_lora_model

[QAT Lora 4/N] Strip for LoRA modules

---

nncf/experimental/torch2/function_hook/graph/build_graph_mode.py
nncf/experimental/torch2/function_hook/hook_executor_mode.py
nncf/experimental/torch2/function_hook/wrapper.py
tests/torch2/function_hook/test_train.py
tests/torch2/function_hook/test_wrapper.py

Rework ForwardWithHooks to be more flexible to patching forward function. 
Now model collects inside ForwardWithHooks and not used original forward to find model.
Add `_has_compatible_shallow_copy_type` and `_parse_to` to ignored function names.
Fix tests on cuda.
```python 
model = AutoModelForCausalLM.from_pretrained("hf-internal-testing/tiny-random-GPTNeoXForCausalLM", torch_dtype=torch.bfloat16, device_map="auto")
model = wrap_model(model)
```

[PT2] rework ForwardWithHooks

---

README.md
docs/usage/training_time_compression/quantization_aware_training/Usage.md
examples/quantization_aware_training/torch/resnet18/main.py
nncf/torch/__init__.py
nncf/torch/model_creation.py
tests/torch2/function_hook/test_serialization.py

Add `get_config` to `nncf/torch/__init__.py`
Use function `get_config` and `load_from_config` for new and old tracing as `from nncf.torch import get_config, load_from_config`
https://github.com/openvinotoolkit/nncf/actions/runs/13974357105

[PT] change api for get_config and load_from_config

---

nncf/openvino/cpu_info.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
tests/openvino/native/quantization/test_weights_compression.py

- Disabled optimized compression on ARM CPUs until the next OV 2025.2 release. The fix https://github.com/openvinotoolkit/openvino/pull/29577 won't be merged in time.
- Added `NNCF_DISABLE_OPTIMIZED_COMPRESSION` environment variable flag to disable optimized compression if needed.
Enable weights compression on ARM CPUs.
164135

Disable optimized compression on ARM CPUs until the next release

---

tests/torch/fx/test_compress_weights.py
tests/torch/ptq/test_fq_lora.py
tests/torch/ptq/test_weights_compression.py
tests/torch2/function_hook/quantization/test_weights_compression.py

Currently, tests are launched on CUDA or CPU based on the marker `cuda`: https://github.com/openvinotoolkit/nncf/blob/develop/Makefile#L146-L150
Check `torch.cuda.is_available()` is not valid anymore. 
n/a
pre-commit

Proper handling cuda/cpu tests for weight compression

---

nncf/__init__.py
nncf/errors.py
nncf/quantization/algorithms/weight_compression/handle_errors.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
tests/cross_fw/test_templates/template_test_weights_compression.py
tests/openvino/native/quantization/test_weights_compression.py
tests/torch/ptq/test_weights_compression.py
tests/torch2/function_hook/quantization/test_weights_compression.py

If the number of weight channels is not dividable by group size, the compression will fail with the following message:
previous message wasn't informative
n/a
- test_raise_error_with_unsupported_params_for_int8

More helpful error message in case of invalid group size

---

tests/torch/experimental/sparsify_activations/test_algo.py

As in the title.
A bug in OV CPU plugin prevents a model from being compiled. Reproduces on OV 2025.1 RC.
165186
- NNCF/job/precommit/job/ubuntu20_precommit_pytorch/6687/
- NNCF/job/nightly/job/windows/job/precommit_torch_cpu/621/

Add xfail to activation sparsity OV export test

---

tests/torch/experimental/sparsify_activations/test_algo.py

Copy of #3390 to release branch.
- NNCF/job/precommit/job/ubuntu20_precommit_pytorch/6687/
- NNCF/job/nightly/job/windows/job/precommit_torch_cpu/621/

[Release] Add xfail to activation sparsity OV export test

---

.github/workflows/api_set_label.yml
.github/workflows/build_and_publish_doc.yml
.github/workflows/build_schema_page.yml
.github/workflows/examples.yml
.github/workflows/install.yml
.github/workflows/labeler.yml
.github/workflows/model_hub.yml
.github/workflows/mypy.yml
.github/workflows/pre-commit-linters.yml
.github/workflows/python-publish.yml

Set a timeout for all jobs to prevent slow or stacked jobs from running indefinitely.
Add a condition for the update_labels job to avoid failure when the API changes check job is canceled or fails.
1. To catch slow or stacked jobs
2. To prevent the `update_labels` job from failing with `Error: no artifacts found` when the `API changes check` job is canceled (e.g., due to a new commit push or PR closure).

[gha] set timeout

---

tests/torch/fx/test_compress_weights.py
tests/torch/ptq/test_fq_lora.py
tests/torch/ptq/test_weights_compression.py
tests/torch2/function_hook/quantization/test_weights_compression.py

Cherry-pick of #3389
Currently, tests are launched on CUDA or CPU based on the marker `cuda`: https://github.com/openvinotoolkit/nncf/blob/develop/Makefile#L146-L150 
Check `torch.cuda.is_available()` is not valid anymore. 
n/a
pre-commit

Proper handling cuda/cpu tests for weight compression (#3389)

---

nncf/__init__.py
nncf/errors.py
nncf/quantization/algorithms/weight_compression/handle_errors.py
nncf/quantization/algorithms/weight_compression/openvino_backend.py
nncf/quantization/algorithms/weight_compression/scale_estimation.py
nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/quantization/algorithms/weight_compression/weight_lowering.py
tests/cross_fw/test_templates/template_test_weights_compression.py
tests/openvino/native/quantization/test_weights_compression.py
tests/torch/ptq/test_weights_compression.py
tests/torch2/function_hook/quantization/test_weights_compression.py

Cherry-pick of #3391
If the number of weight channels is not dividable by group size, the compression will fail with the following message:
previous message wasn't informative
n/a
- test_raise_error_with_unsupported_params_for_int8

More helpful error message in case of invalid group size (#3391)

---

nncf/quantization/algorithms/weight_compression/torch_backend.py
nncf/torch/quantization/strip.py
tests/cross_fw/shared/nx_graph.py
tests/torch/data/reference_graphs/compress_weights/fq_lora/shared_weights_all_layers_False.dot
tests/torch/data/reference_graphs/compress_weights/fq_lora/shared_weights_all_layers_True.dot
tests/torch/ptq/test_fq_lora.py

Cherry-pick of #3397
Insert FQ_LORA as post_hook, instead of pre_hook. 
Models with shared weights had incorrect quantizer setup.
| before fix | after fix |
|--------|-------|
| ![Screenshot 2025-03-31191411](https://github.com/user-attachments/assets/b104c542-df96-4a6a-a65f-c458246b00b2)| ![Screenshot 2025-03-31191313](https://github.com/user-attachments/assets/edb94470-5637-49f9-9380-84bcde38a443)|
n/a
- test_compress_shared_weights

Fixed bug with FQ_LORA for shared weights (#3397)

---

.github/workflows/examples.yml

Set mark 'not cuda' for windows runner
https://github.com/openvinotoolkit/nncf/pull/3386
No gpu on windows hosts
https://github.com/openvinotoolkit/nncf/actions/runs/14298014723/job/40067736711

[gha] skip cuda examples on windows

---

nncf/common/utils/caching.py
tests/common/utils/test_cache_results_decorator.py

Enable caching back in case an exception is raised after disabling.
Added a corresponding test (fails on develop).

Fix disable_caching context manager

---

tests/openvino/native/quantization/test_weights_compression.py

Remove xfail for tests/openvino/native/quantization/test_weights_compression.py::test_mixed_precision_e2m1
```
XPASS tests/openvino/native/quantization/test_weights_compression.py::test_mixed_precision_e2m1[weight_quantization_error-True-1-ref_ids0]
XPASS tests/openvino/native/quantization/test_weights_compression.py::test_mixed_precision_e2m1[weight_quantization_error-True-0.8-ref_ids1]
...
```

Remove xfail for test_mixed_precision_e2m1

---

README.md
examples/post_training_quantization/torch_fx/resnet18/main.py
tests/post_training/pipelines/image_classification_torchvision.py

No need after https://github.com/openvinotoolkit/nncf/pull/3338
###
https://github.com/openvinotoolkit/nncf/actions/runs/14470409240
manual/job/post_training_quantization/648

Remove disable patching for fx examples and docs

---

.github/actions/add_job_link/action.yml
.github/workflows/conformance_weight_compression.yml
.github/workflows/examples.yml
.github/workflows/install.yml
.github/workflows/macos.yml

Add action `add_job_link` to add job link in the end of PR description
Update workflow that can be run manually for PR 
Laziness

[gha] Automatically add job link to PR description

---

.ci/cspell_dict.txt
nncf/onnx/engine.py
nncf/onnx/graph/metatypes/onnx_metatypes.py
nncf/onnx/graph/model_metadata.py
nncf/onnx/graph/model_transformer.py
nncf/onnx/graph/model_utils.py
nncf/onnx/graph/onnx_helper.py
nncf/onnx/quantization/backend_parameters.py
nncf/onnx/quantization/quantize_model.py
nncf/quantization/advanced_parameters.py
nncf/quantization/algorithms/accuracy_control/onnx_backend.py
nncf/quantization/algorithms/weight_compression/onnx_backend.py
tests/onnx/models.py
tests/onnx/quantization/test_backend_parameters.py
tests/onnx/test_engine.py
tests/onnx/test_external_data.py
tests/onnx/test_model_metadata.py
tests/onnx/test_onnx_helper.py

- Added the `BackendParameters.EXTERNAL_DATA_DIR` parameter for the ONNX backend. This parameter specifies the absolute path to the directory where the model’s external data files are stored. All external data files must be located in the same directory. It should be used when the model is loaded without external data using `onnx.load("model.onnx", load_external_data=False)`, and the external data files are not in the current working directory of the process. This parameter can be omitted if the external data files are located in the current working directory of the process.
- Added `check_model_protobuf_size()` and `check_external_data_location()` validation checks. After this PR, calling `nncf.quantize()` on an ONNX model with a protobuf size exceeding 2GB will raise an …

[ONNX] Add external_data_dir backend parameter

---

tests/torch/test_utils.py

- As stated in the title. It is likely that Python side-effects like printing a message would not be compiled with `torch.compile` and would trigger `is_compiling`.
- Fix for Torch 2.7.0.
- 166894
- N/A

Added logging for compilation trigger

---

tests/post_training/data/wc_reference_data.yaml
tests/post_training/requirements.txt

Use Optimum Commit with PR https://github.com/huggingface/optimum/pull/2237 in conformance test.
This change is necessary because PT WC conformance test in NNCF uses `optimum.exporters.openvino.convert.export_from_model` which corrupts the PT namespace due to patching leading to errors in using torch.export. This issue is resolved in the exact commit used to run the Conformance test resolving the issue with FX backend conformance tests.
Issue 165013
Category | Job | Status | Job Number | Notes
-- | -- | -- | -- | --
GH WC | WC test on GHA | Pass | <a href="https://github.com/openvinotoolkit/nncf/actions/runs/14705449313">72</a> |
Manual | job/manual/job/post_training_quantization/664/ | Pass | 664 |

[Conformance] Use Nightly Commit for Optimum in Conformance Test

---

tests/onnx/test_engine.py

Skip test for old onnxruntime in weekly scope on python3.9
https://github.com/openvinotoolkit/nncf/actions/runs/14815781819

[onnx] Skip test for old onnxruntime in weekly scope

---

README.md
docs/usage/training_time_compression/quantization_aware_training/Usage.md
examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py

- Calling `nncf.strip()` is no longer required for the TF backend, as this function is now integrated into the `ov.convert_model()` method. Therefore, the model can be converted directly using `ov.convert_model()`.

remove strip

---

examples/llm_compression/torch/qat_with_lora/README.md
nncf/torch/quantization/quantize_functions.py
tests/cross_fw/examples/example_scope.json
tests/torch2/function_hook/quantization/strip/test_strip_dequantize.py
tests/torch2/function_hook/quantization/test_fq_lora.py

Always cast input to float32 inside FQ + LoRA.
Benchmark results with new schema on the https://github.com/ljaljushkin/nncf_pytorch/tree/nl/ref_benchmark with small modifications from @nikita-malininn's branch https://github.com/nikita-malininn/nncf/tree/nm/ref_benchmark:  
device | dtype | exec_type | tensor_type | granularity | symmetric | narrow_range | timing_mode | num_runs | input_size
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
cuda | bfloat16 | ExecutionType.REGULAR | TensorType.WEIGHTS | GranularityType.PER_CHANNEL | TRUE | FALSE | TimingMode.KERNEL | 1000 | [2048, 128256]
name | Mode | forward_avg, ms | backward_avg, ms | memory, Gb
-- | -- | -- | -- | --
compile (PR) | sym | 6.5 | 10.7 | 3.9
compile (PR) | asym | 6.8 | 10.7 | 3.9
compile (before) | sym | 1.6 | 9.5 | 4.2 …

Aligned bf16 tuning vs f32 inference for 4bit compression

---

nncf/quantization/algorithms/weight_compression/algorithm.py

Before:
After:
Statistics are not calculated for ignored weights.
N/A
Manual

[Fix] Calculation of statistics for ignored weights

---

nncf/data/generators.py
tests/torch/test_dataset_generators.py

During data generation, check that the model is an instance of `transformers.GenerationMixin` instead one of `PreTrainedModel.__bases__`. Because of the fact that during generation, we require the model to have `model.device`, `model.config` and `model.generate()` properties available, `transformers.GenerationMixin` satisfies these requirements. 
Starting from transformers 4.52, `PreTrainedModel` does not inherit from `GenerationMixin` no more. Because of this the current isinstance check fails for `OVModelForCausalLM` which inherits from `GenerationMixin` but not `PreTrainedModel`.
Extended `tests.torch.test_dataset_generators::test_generate_text_data_functional`.

Data generation: check inheritance from `GenerationMixin` instead of `PreTrainedModel.__bases__`

---

.github/workflows/conformance_weight_compression.yml

parallel on 4 hosts for wc tests
increase timeout
To avoid fails by timeout on adding new testcases
https://github.com/openvinotoolkit/nncf/actions/runs/15249451258/job/42882568423?pr=3510

[gha] parallel on 4 hosts for wc tests

---

examples/llm_compression/onnx/tiny_llama/README.md
examples/llm_compression/onnx/tiny_llama/main.py

- Use OVModelForCausalLM for ONNX weight compression example
- Better performance
Ref: 168070
Current scope

Use OVModelForCausalLM for ONNX weight compression example

---

tests/torch/sparsity/movement/test_model_saving.py

set xfail for tests/torch/sparsity/movement/test_model_saving.py::TestONNXExport::test_ngraph_pruning[desc3]
```
E       RuntimeError: Check 'backward_compatible_check || in_out_elements_equal' failed at src/core/shape_inference/include/reshape_shape_inference.hpp:370:
E       While validating node 'opset1::Reshape /swin/encoder/layers.0/blocks.0/Reshape_9 (opset1::Reshape /swin/encoder/layers.0/blocks.0/Reshape_8[0]:f32[4,4,4,4], opset1::Constant /swin/encoder/layers.0/blocks.0/Constant_43[0]:i64[3]) -> (f32[1,16,4])' with friendly_name '/swin/encoder/layers.0/blocks.0/Reshape_9':
E       Shape inference input shapes {[4,4,4,4],[3]}
E       Requested output shape [1,16,4] is incompatible with input shape
```
168947

[release 2.17.0] xfail 168947

---

tests/tensorflow/test_compressed_graph.py

Add xfail for sporadic `403: Forbidden` error on downloading from `https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/classification/4`
https://github.com/openvinotoolkit/nncf/actions/runs/15720727872/job/44300948459

xfail for sporadic fail

---

tests/post_training/pipelines/base.py

Due to missing `aot_autograd` option, the torch compile call was not working as expected.
The torch.compile() call was silently falling back to eager execution due to using improper tracing mechanism(make_fx instead of aot_autograd) 
Category | Job | Status | Job Number | Notes
-- | -- | -- | -- | --
Manual | job/manual/job/post_training_quantization/664/ | Failed | 677 | Swin model fails due to graph break which is fixed in PR https://github.com/openvinotoolkit/openvino/pull/30895

[Torch FX][Conformance] Fix FX PTQ Conformance Test Issue with Torch Compile Call

---

pyproject.toml

Update license field 
```
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: Apache Software License
See …
```

Update license field in pyproject.toml

---

nncf/common/quantization/quantizer_propagation/graph.py
nncf/common/quantization/quantizer_propagation/solver.py
nncf/common/quantization/structs.py

Most QuantizerConfig logic is moved to the QuantizerConfig class
To separate logic of QuantizerConfig from the Solver to make it easier to process new QuantizerConfigs in future

[Solver] Move most of quantizer_config into the QuantizerConfig itself

---

.github/workflows/conformance_weight_compression.yml

Set `set -e` to dont fail on pytest command, and run script forward to suppress `no_test_found` return code if action runs with `pytest_args` 
Disable "no file found" warning in upload step
https://github.com/openvinotoolkit/nncf/actions/runs/15164300318/job/42637948116
168252
https://github.com/openvinotoolkit/nncf/actions/runs/16051113240/job/45293751022?pr=3572

[ci] fix fail on no tests found if run with pytest_args

---

src/nncf/experimental/torch/fx/transformations.py
src/nncf/quantization/algorithms/weight_compression/algorithm.py

1. Add method to set ignored scope in Weight Compression algorithm. 
1. This is to allow the user of OpenVINO quantizer to set the ignored scope from the instance without passing it in the quantizer initialization.

[Torch FX] Changes to Support OpenVINO Quantizer

---

examples/llm_compression/torch/distillation_qat_with_lora/README.md
examples/llm_compression/torch/distillation_qat_with_lora/main.py
examples/llm_compression/torch/downstream_qat_with_nls/main.py
src/nncf/quantization/algorithms/smooth_quant/torch_backend.py
src/nncf/quantization/algorithms/weight_compression/torch_backend.py
src/nncf/torch/quantization/layers.py
tests/cross_fw/examples/example_scope.json
tests/cross_fw/examples/run_example.py

- Fixed support for more advanced compression methods (AWQ+Scale Estimation) as initialization for QAT with absorbable LoRA. 
Previously RTN baseline was used, but now with data-aware AWQ + Scale Estimation tuning starts with more accurate model and achieves superior accuracy: 
- Removed selection of the best checkpoint based on validation set. It significantly reduces overall tuning time and max allocated memory. The best results are slightly worse on wikitext, but it should provide more fair and faster tuning pipeline (from 32 min to 25 min for SmoLM-1.7B). 
Improvements in QAT + absorbable LoRA.
ticket - 169140
test_examples - https://github.com/openvinotoolkit/nncf/actions/runs/16223789950

FQLoRA: use last checkpoint with AWQ+SE as initialization

---

.github/workflows/sdl.yml

Set version of stevedore==5.4.1 
https://github.com/openvinotoolkit/nncf/actions/runs/17211295443/job/48824963052 stevedore==5.5.0 
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.14/x64/bin/bandit", line 3, in <module>
from bandit.cli.main import main
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/bandit/__init__.py", line 5, in <module>
import pbr.version
ModuleNotFoundError: No module named 'pbr'
```

[release_v2180] [ci] Fix bandit workflow (#3638)

---

src/nncf/quantization/algorithms/weight_compression/algorithm.py

Re-worked the `apply` method in WC algorithm to use an extra method to return weights compression params such that the apply method is more concise and only contains algorithm, quantization logic etc.
This is done so that OpenVINO quantizer can obtain the final collection of weights compression parameters for all the nodes so that are to be compressed.

[Weight Compression] Rework WC Algorithm to Return WC Params

---

examples/post_training_quantization/onnx/mobilenet_v2/main.py
src/nncf/onnx/graph/onnx_helper.py
src/nncf/onnx/graph/passes.py
src/nncf/onnx/quantization/backend_parameters.py
src/nncf/onnx/quantization/quantize_model.py
tests/cross_fw/examples/example_scope.json
tests/onnx/test_passes.py
tests/post_training/pipelines/base.py
tests/post_training/pipelines/image_classification_timm.py
tests/post_training/pipelines/image_classification_torchvision.py

Added the `compress_quantize_weights_transformation()` method that transforms the model by folding `QuantizeLinear` nodes with constant inputs into precomputed, quantized initializers.
- Models after NNCF PTQ should be saved with INT8 weights for the ONNX backend.
Ref: 101733
-  tests/cross_fw/examples/test_examples.py[post_training_quantization_onnx_mobilenet_v2]
- tests/onnx/test_passes.py

[ONNX] Compress quantize weights transformation

---

tests/post_training/pipelines/base.py
tests/post_training/pipelines/image_classification_timm.py
tests/post_training/pipelines/image_classification_torchvision.py

Revert the temporary test changes that were introduced in PR https://github.com/openvinotoolkit/nncf/pull/3662

[ONNX] Revert the temporary test changes
